### ISSUE TITLE
Verifier unable to download National Moth Night records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1010]
Steve Palmer has a verification filter for NMN records (for moth family Gelechiidae).

NMN records are linked to website ID 16.

The website has an agreement to share records for verification and for dataflow, but not for reporting.

Steve can see the records in his verification view.

However, if he tries to download the records, by setting "Records to access" for his verification role, the resulting file is empty.

Is there some interaction between the download page and the website agreements that is behaving unexpectedly?

This may also relate to a recent problem that Surrey Wildlife Trust have have with the new downloads not matching the old ones (as discussed with @burkmarr - I am trying to find out more about the background to that one).

Marking as a priority because this will cause continuity problems for anyone trying to download an updated set of records on the new page as opposed to the old.

**Comment by burkmarr** [comment]
@johnvanbreda - I pointed the new ES download page to the es-irecord-reporting ES endpoint.  Is that right or should it be es-irecord-data-flow?

**Comment by johnvanbreda** [comment]
Hmm, I wonder if it needs to switch end-point according to the task you are doing?
BTW, in Drupal 8 I've added extra authentication options so that it will be possible to just authenticate as a website for reporting/verification/data flow etc and the warehouse will work out the correct filter. Then we can stop setting up aliases for each use case.

**Comment by burkmarr** [comment]
@kitenetter @johnvanbreda. If I understand this correctly, the root of Steve's problem is that the records he's after cannot be seen in iRecord reporting (becasue of website agreement) and are therefore not available from the download page which is using the ES reporting endpoint.

Doesn't the nature of the website agreements mean that the endpoint for the download form should be data-flow rather than reporting? Should records shared only for reporting even be available for download?

For verifiers, we could provide a separate download page that points to the ES verification endpoint and only has the `[permissionsFilter]` control available, using existing options on that control to limit the displayed filters to verification filters. (That would enable Steve to get his records.)

For the existing form, we could configure the `[permissionsFilter]` control so that only data-flow filters are available.

**Comment by kitenetter** [comment]
My expectations would be:
- Any iRecord user can download their own records, regardless of which website was used to enter them (I don't know if this has been the case for the old download page - were users able to download their own records from websites that did not have any of the data-sharing agreements in place?)
- Any iRecord verifier can download any records that they can verify, which ought to relate to those websites that share for verification
- Any LERC download ought to include all records within their remit that are from websites that share for data-flow
- Our exports to NBN Atlas ought to include all records that share for data-flow
- We have some miscellaneous download roles (e.g. for conservation organisations and a few local groups) and I'm not sure what has applied to them in the past, but I would have thought that these too ought be to confined to websites that share for data-flow

My understanding of the website agreement for "reporting" was that it only influenced whether or not the data could be viewed via the iRecord website, and did not influence downloading.

**Comment by burkmarr** [comment]
@johnvanbreda @kitenetter - I think a short zoom meeting would be good to understand what's going on here and plot a way forward. Could we tack it on to the next review meeting which must be due soon?

**Comment by johnvanbreda** [comment]
@kitenetter I've implemented a raft of changes in the permissions code now. Please can you test this version of the download form, which is cloned from the original but uses a new website-based automated authentication mode that automatically applies the correct list of websites: https://www.brc.ac.uk/irecord/node/8272

If that's OK it's a simple task to copy the permissions config across and this test download page can be deleted. The changes should also be passed to @BirenRathod to keep the D9 version updated.

**Comment by kitenetter** [comment]
@johnvanbreda I've just been trying to do a test download using my moth verification role, and setting a date filter for all records since 1 Jan 2020. On both the new test download page, and the page that is currently public, the taxonomic filtering is being ignored, and I'm getting a very large file of over 1.5 million records for all taxa.

I haven't yet checked to see if this applies to other taxon-based filters.

**Comment by johnvanbreda** [comment]
@kitenetter I've applied a temporary fix and I'm just going to patch it properly. A small mistake in a regular expression.

**Comment by johnvanbreda** [comment]
Now fixed.

**Comment by kitenetter** [comment]
@johnvanbreda I've just re-run the Surrey download and it is behaving correctly (or at least it is in accord with my expectations of which datasets whould be included or excluded). So if you can transfer this over to the main download page and then remove the test page that would be great.

**Comment by johnvanbreda** [comment]
That's done @kitenetter - if you are happy can you remove the warning message from the original download page?

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - closing.
