### ISSUE TITLE
No access directly to iNaturalist system from within iRecord record.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#1012]
I notice that there has been a couple of changes to records imported from iNaturalist imported into iRecord.

1) We now have a big green "share" symbol occupying another line within the record display without any indication of what this means - no mouse over text etc.  In my opinion this is redundant, if some sort of "shared across / imported" indicator is needed than it should show within the record details block, not cause fewer records to be displayed on the grid at one time.  I would request this be removed.

2) More importantly, the direct link to the actual record on iNaturalist that used to be present on the "Actions" line of the Record Details is no longer present, meaning we cannot go directly from the record in iRecord to the original on iNaturalist.  I found this very useful, allowing me to quickly access iNats records to add comments or look at additional photos or re-det them at the point of origin.  Can we please have this facility added back to the actions bar.

Thanks.

**Comment by kitenetter** [comment]
Hi @MNSmith we haven't re-started the iNaturalist import from our end. However, some iNaturalist users have developed a way of exporting records from iNat and importing them into iRecord, see:
https://forum.inaturalist.org/t/tool-for-exporting-inaturalist-data-to-irecord/19160

I suspect the records you are seeing result from that process. We weren't informed that it was being done and haven't had any communication from the people involved. I can see some positive things about the process, but as you say it doesn't link the observations together.

There are due to be some more discussions between us, NBN and iNaturalist later this year to try and find a way forward for the iNat records, and we'll look into this further as part of that.

**Comment by MNSmith** [comment]
Next time I come across one of these records I'll take a closer look and see who uploaded it.
