### ISSUE TITLE
Import is unpredicatable if 'intermediate' columns are left in the CSV

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1025]
I recommend advising importers in the Guidance Document (currently 3.2) to delete all temporary/intermediate columns from their CSV before importing it. My experience is that these columns confuse the automatic column-to-field matching and, instead of showing the manual field-matching page, iRecord tries to do the import but fails with unexpected and misleading errors.

**Comment by kitenetter** [comment]
@DavidHepper personally I don't like the fact that iRecord will attempt to import without showing the field-matching page, if it thinks it has mapped all the fields. This is mainly because I'm worried that I may use a field name that iRecord 'knows' but my meaning may not be how iRecord understands it. So I always prefer to see the field-mapping page to double-check that the system is doing what I think it is doing.

Would it cause you problems if we were to switch off the auto-matching in this way?

**Comment by kitenetter** [comment]
moving to new issue #1091 and closing this one
