### ISSUE TITLE
New termlists preventing records being saved?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1038]
@johnvanbreda I have a report of the new terms not working on the enter a casual record page. This is from a user with firefox, who says: "It comes up with the old options, then switches to the new options and then bombs out", and he is unable to save a record. Rather fuzzy screenshot:

![image](https://user-images.githubusercontent.com/16039111/113026718-43d87500-9181-11eb-971d-ae6ffa0476de.png)

I can't reproduce this on my firefox.

P.S. I note that he is entering records via an activity form, could that make any difference? (It makes no difference for me, works okay either way.)

**Comment by kitenetter** [comment]
Just hit a similar problem myself now I'm on my home computer, also using firefox. Added a record using the list records form. The first time whn I clicked save it failed to save, and highlighted the missing stage attribute (which I had previously selected from the arthropod list). When I selected it a second time the save went through okay.

Will try to capture a HAR file next time.

**Comment by kitenetter** [comment]
Added a new record, failed to save with the arthropod termlist, subsequently offered me the default termlist, and saved okay when I chose the stage from that. HAR:

[www.brc.ac.uk_Archive [21-03-30 19-33-33].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/6231430/www.brc.ac.uk_Archive.21-03-30.19-33-33.zip)

**Comment by kitenetter** [comment]
This is definitely causing problems. I just went back into a list that I had entered and the record I thought I had saved with stage "adult" was showing as "not recorded". Once again it failed to save with the arthropod list, but this time I think it has saved when it defaulted back to the standard terms.

Also, having picked a stage in the first record in a list, that stage is not being offered as a default for the second record in the list.

If there isn't an immediate solution I think we should switch the dynamic terms off again, to avoid incorrect data being entered.

**Comment by johnvanbreda** [comment]
@kitenetter - apologies, I think caching on the warehouse meant that when I tested this I didn't see the full effect. The main problem here is that the generic Stage attribute is required - so when you submit a record with a specific stage attribute, the validation fails as the generic one is not filled in. So - for now a quick fix is that I've made the generic stage attribute not required, which won't matter much because the default is not recorded anyway.

The longer term solution is:
1. When a generic Stage (or other system function) attribute is required, if it get's replaced by a specific version of the same attribute then the required stage should be ignored.
2. When a validation error happens on the server side, then the records which reload into the grid for editing need to still reload the specific versions of the attributes. When the validation failed in your example, the grid should not have reloaded with the generic versions of the Stage attribute. It's this problem which allowed you to set a generic "adult" value for an arthropod stage value, which shouldn't have happened.
3. If reloading a record which has a generic Stage attribute value, even if replaced by a specific one, then the existing attribute value still needs to show for the edited record.

**Comment by kitenetter** [comment]
Thanks for the fix @johnvanbreda 

Not so urgent, but another oddity - this record says it is of an adult on its 'view' page:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=20142333

But if I go to edit it the stage comes up as "not recorded":

![image](https://user-images.githubusercontent.com/16039111/113052147-b277fb80-919e-11eb-9f5c-ce32a71866c3.png)

**Comment by kitenetter** [comment]
The problem with records showing as stage "not recorded" when edited (as per previous comment) seems to have gone away (it is not affecting the records I've just added).

**Comment by johnvanbreda** [comment]
I've now implemented a set of bug fixes around this area including fixing the stage attribute on the record, plus the longer term solution's 2nd and 3rd points. The first point is mitigated by removing the required state of the generic Stage attribute.

**Comment by kitenetter** [comment]
I think we can close this, but see #1039
