### ISSUE TITLE
Records being flagged as 'edited' unnecessarily

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1040]
It appears that if I add a record to an existing list, the entire list gets flagged as having been edited, and therefore requiring re-verification. I suspect this is an unforeseen consequence of the dynamic terms - does adding a new record with a dynamic stage term trigger an update of the stage for all other records in the list?

Marking as urgent due to potential impact on verifiers.

**Comment by johnvanbreda** [comment]
I think the problem here was if an pre-dynamic record had a Stage attribute value such as adult or not-recorded, when loading to edit, the code automatically swaps to the dynamic version of the attribute and maps to the term with the same text. Even though it looks the same, its in a different termlist so is a different value. Thus saving re-queues for verification. I've changed this behaviour so it only happens with non-verified records. 
The consequence of this is you can't change an old verified record to set it's Stage using the new dynamic termlists.
