### ISSUE TITLE
Make link more obvious when editing a list of records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1057]
This is from "Explore - My records", and then editing an occurrence that was entered as part of a list.

In the sentence about adding new occurrences to an existing list, the text that is a link to allow additions ("View all the records ...") is not distinguished from the text that is not a link, and users could easily overlook that a link is available:

![image](https://user-images.githubusercontent.com/16039111/118461735-e4650300-b6f5-11eb-80d1-8258e87dede3.png)

I guess this must be because the entire sentence is in bold. Is there a way of emphasising the link, or failing that can we switch off the bold emphasis for the non-link text?

**Comment by johnvanbreda** [comment]
I'd favour changing this link into a button, since it is an action, not a navigation.

**Comment by kitenetter** [comment]
We have had a request to make the warning text more prominent:
"You are editing a single record that is part of a larger sample, so any changes to the sample's information such as edits to the date or map reference will affect the whole sample."

I think that warning is a separate piece of information that should be split off from the part about adding records (which we want to change into a button as discussed above):
" View all the records in this sample or add more records."

The question is then how we can best highlight the warning text. Putting it on its own line, and emboldening it, are definitely worth doing. Maybe move it to the top of the form (if possible)? Any other way of highlighting it?

Recently we have had conflicting feedback about the coloured text boxes (the ones that are yellow on the live site, and blue on the Drupal 9 site) - some think they work well to highlight important messages, but others have said that it is difficult to read text on a coloured background, a problem that is exacerbated by the text itself also being shaded, rather than black.

**Comment by johnvanbreda** [comment]
I've updated this in the develop branch - the warning box is now above the input grid, highlighted better, font colour darkened so that it passes AAA accessibilty checker (https://webaim.org/resources/contrastchecker/) and with the link now a button on it's own line. Here's a preview of the Bootstrap version:

![image](https://user-images.githubusercontent.com/2392594/124949530-8d9aec00-e009-11eb-84cc-6483a582f10c.png)

Plus a preview of the non-Boostrap version (as currently on iRecord):

![image](https://user-images.githubusercontent.com/2392594/124948125-5415b100-e008-11eb-97ab-3178acbb7cf7.png)
