### ISSUE TITLE
Problem with map on enter records page, and record details page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1084]
Reported this morning.  Marked as urgent as a very visible bug

<img width="640" alt="int" src="https://user-images.githubusercontent.com/2699478/120599718-c3174d00-c43f-11eb-9a8c-324de4a0165c.png">

**Comment by BirenRathod** [comment]
@DavidRoy It works fine on my machine. No problem found.

**Comment by johnvanbreda** [comment]
@BirenRathod it relates to cookies - I think if you clear all the map related cookies then the problem occurs. Something to do with the changes to lazy-load the Google API I suspect, so I'll take a look now.

**Comment by johnvanbreda** [comment]
@DavidRoy ah - got it. The requests to the OS maps API are returning the following error:
```xml
<error>
  <messages>
    <message>Exceeded developer limit configuration - </message>
    <message>Is Developer Suspended - true </message>
  </messages>
</error>
```

**Comment by DavidRoy** [comment]
@johnvanbreda I think our OS license might have ended.  Can you disable this layer while I investigate?

**Comment by johnvanbreda** [comment]
I've switched the default layer to a dynamic one which switches from OSM to Google when zoomed in (rather than OSM -> OS leisure -> Google).

**Comment by DavidRoy** [comment]
Thanks.  Ideally we'd minimize the use of Google maps due to rising costs.  Do we need to switch to the newer OS Maps API as OS Maps API for Enterprise has been withdrawn - 31/03/2021
https://developer.ordnancesurvey.co.uk/os-maps-api-enterprise

**Comment by BirenRathod** [comment]
@johnvanbreda Regardless of cookies, it works fine at my end anyway.

**Comment by johnvanbreda** [comment]
@BirenRathod it probably worked for you as I'd already changed the map configuration to not load OS Leisure.

@DavidRoy there have been recent code changes to reduce the loading of the Google Maps API so it would be worth checking in a month or so to see if this has helped. That's a separate issue though. I agree we need to switch to the newer OS Maps API - can you email me an API key we can use?

**Comment by BirenRathod** [comment]
@johnvanbreda I tried before and it worked.

**Comment by DavidRoy** [comment]
@JimBacon is investigating options with OS

**Comment by johnvanbreda** [comment]
@DavidRoy @JimBacon looking at the new API, it is a WMTS which is supported by OpenLayers 2 so I hope it's not too tricky to swap the code to the new API.

**Comment by JimBacon** [comment]
This may not be the actual problem that caused things to break today but we clearly need to change our ways.

**Withdrawal Notice OS Maps API for Enterprise** 

Hello, 

We would like to notify you of our intention to withdraw OS Maps API for Enterprise on 31st March 2021. With effect from this date, the OS API Framework Agreement will be varied to remove the OS Maps – API Service.  

We have now launched a new suite of APIs, with similar and improved functionality, accessible from our new data access platform, [OS Data Hub](https://osdatahub.os.uk/).

What happens next? 

Don’t worry, you can continue using your maps and API keys until 31st March 2021 when the service will be withdrawn.   
  
We recommend that you migrate your maps before this date, so that you can continue using them in your applications, without interruption.  

There are additional benefits to signing up to the OS Data Hub:
•	Benefit from £1,000 of free Premium data every month 
•	A new simple [pricing plan](https://osdatahub.os.uk/plans) 
•	Access a suite of new APIs – including OS Vector Tile API and OS Features API 
•	Improved [online support resources](https://www.ordnancesurvey.co.uk/business-government/developers)  
Our recommended steps for migrating: 

1. Learn about the new OS Maps API on the OS Data Hub

•	[OS Maps API](https://osdatahub.os.uk/docs/wmts/overview) - very similar functionality, available in four improved cartographic styles 
•	If you use the EPSG:3857 projection and overlay your own data, it will need to be reprojected using the newer OSTN15 transformation model. [Learn more here](https://www.ordnancesurvey.co.uk/business-government/tools-support/os-net/for-developers) 

2. Work through guides and copy / paste examples to see what is possible
•	[Copy and paste code examples](https://labs.os.uk/public/os-data-hub-examples/)
•	[Tutorials to inspire your next application](https://labs.os.uk/public/os-data-hub-tutorials/)
3. Sign up for a new API endpoint and key on the OS Data Hub 

You will need to choose a plan: 
•	Sign up for a [Premium Plan](https://osdatahub.os.uk/plans) – unlimited OS OpenData plus up to £1,000 a month of free premium data, such as OS MasterMap Topography Layer and 1: 25 000 Scale Colour Raster (OS Explorer Maps)
4. Start to use your new API key in your applications 

Please don’t hesitate to contact us if you have any questions at customersuccess@os.uk, or contact your Account Manager.   

Best wishes,

OS API team
Ordnance Survey

**Comment by JimBacon** [comment]
Ordnance Survey have extended our access to the existing mapping service until 15th June.
We are reviewing the licence agreement for the new service to see if we can accept it.

If acceptable, we need to 
- set up a new account with the OS (or share an existing account which is already in use),
- obtain new API keys,
- update affected websites with new API keys (iRecord and Honey Recording Scheme) and any relevant software changes.
- restrict the use of OS maps to registered users only,
- update our terms and conditions,
- update our privacy statement.
- notify users of changes to terms.

**Comment by JimBacon** [comment]
- The account with OS has been set up.
- iRecord and Honey Recording Scheme sites have been updated to use new service.
- There is no need to restrict maps to registered users.
- There is no need to change our privacy statement.
- We may need to update our terms to incorporate any we inherit from OS. Oliver Robertson will advise.

**Comment by DavidRoy** [comment]
@JimBacon are we able to close this issue now?

**Comment by JimBacon** [comment]
Since we patched this, UKCEH have entered an agreement with NERC, allowing us to use API keys from their public-sector licence with the Ordnance Survey for projects which are NERC funded. When I have checked previously, we have been nowhere near using our free monthly mapping allowance so it is low priority, but it would be neat and more future-proof to use NERC API keys.

**Comment by kitenetter** [comment]
As far as I know this can be closed.
