### ISSUE TITLE
Plant kingdom

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#110]
We have Animalia, but I can't find the Plantae.

**Comment by kitenetter** [comment]
In table cache_taxa_taxon_lists, "Animalia" appears twice (id 106890 and 306184), both of which are marked as "true" for allow_data_entry. Preferred is id 106890.

"Plantae" appears three times (id 125442, 125443 and 341522), all of which are marked as "false" for allow_data_entry. Preferred is id 125442 and 341522.

So the questions are:

- Why did we decide to allow data entry for Animalia but not Plantae?
- Will it cause any problems if we set Plantae to be allowed (I believe Karolis's request is in connection with the New Year Plant Hunt, where we wish to allow photo upload of undetermined plant species)
- If we are going to allow Plantae, should we use id 125442 or 341522?

id 125442 has no associated authority name, while id 341522 does have an authority name. The former is marked in the UKSI as ill-formed but is used for all vascular plants on the NBN Gateway. The latter is well-formed but is only used for algae on the Gateway.

**Comment by BirenRathod** [comment]
May be this is the result of recent upgrade of UKSI.

**Comment by johnvanbreda** [comment]
I think the Animalia data look correct - there are 2 records because 1 is the vernacular Animal and one is the preferred latin Animalia.
For the Plantae, record 341522 (Plantae Haeckel, 1866, TVK NHMSYS0021059028) no longer exists in the data I pull in from UKSI. My importer has correctly left the taxon in the database though because there are some records attached to it, so it has marked it not for data entry. Remember that because it has a different preferred TVK to the new Plantae entries in UKSI and there is no audit trail, my code cannot automatically work out that these refer to the same taxa. So the old Plantae Haeckel, 1866 entry <> the new Plantae entry.
That leaves us with 2 Plantae records, in fact its 1 Plantae and 1 of Plants, which is the vernacular linked to the latin name so that's correct. However I can't see why these are not both marked as allow data entry. Its another case of the import script process getting quite complex so it could do with a review I think.
In the meanwhile, I've flagged the Plants and Plantae entries so they allow data entry. Therefore the correct preferred ID to submit against will be 125442.

**Comment by kazlauskis** [comment]
Thanks, that is all I needed.
