### ISSUE TITLE
Deleted user account to re-link

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1114]
Same problem as in #1094 and #1110 

Deleted user ID 9810 is linked to deleted person ID 9902, for the iRecord website.

The user has changed email address, and all her other websites are linked to user ID 19868 and person ID 19997.

Records for user ID 9810 need to be moved to user ID 19868, and the link to the iRecord website needs to be reinstated. I'm still unlcear about exactly what steps are involved to relink the user accounts, Drupal accounts and records, but I know that you've done it before!

**Comment by johnvanbreda** [comment]
Done. Here's the process I used. First, some queries to check the user IDs are as expected, linked to the websites I might expect and the number of records involved:

```sql
select * from users where id in (9810, 19868)

select * from users_websites where user_id in (9810, 19868)

select created_by_id, website_id, count(*) from cache_occurrences_functional where created_by_id in (9810, 19868) group by created_by_id, website_id
```

Once I've convinced myself that everything is as it should be, I run the following SQL to move the records:

```sql
update samples set created_by_id=19868 where created_by_id=9810;
update samples set updated_by_id=19868 where updated_by_id=9810;
update cache_samples_functional set created_by_id=19868 where created_by_id=9810;
update occurrences set created_by_id=19868 where created_by_id=9810;
update occurrences set updated_by_id=19868 where updated_by_id=9810;
update cache_occurrences_functional set created_by_id=19868 where created_by_id=9810;
update locations set created_by_id=19868 where created_by_id=9810;
update locations set updated_by_id=19868 where updated_by_id=9810;
```

Then for any accounts that remain connected to the wrong user ID (as found by the 2nd query above) I need to edit and resave the accounts, having blanked out the Indicia Warehouse User ID field so it gets regenerated. On Drupal 9 I actually need to edit the user form so it temporarily shows the warehouse User ID field (as otherwise I can't blank it) - this can be done at https://irecord.org.uk/admin/config/people/accounts/form-display.

Finally check the My Records page shows records that I'd expect.
