### ISSUE TITLE
Update email text for BloominAlgae

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1118]
When a user registers with the Bloomin Algae project, they get a confirmation email with this message:

> From: noreply@brc.ac.uk <noreply@brc.ac.uk>
> Subject: Welcome to iRecord
> Activate your account by visiting the following page in your web browser: ...

Laurence asks if we can make this text more relevant to Bloomin Algae, as some users may by unaware of the link to iRecord and could be put off by the confirmation email text. Suggested replacement text:

> Subject: Welcome to iRecord at the UKCEH Biological Records Centre
> Thank you for signing up to an iRecord account, which is used by UKCEH’s Biological Records Centre to manage the data submitted to our recording apps.
> To receive feedback on the records you submit through our UKCEH apps, and to be able to view your own data via the iRecord website, you need to activate your account by visiting the following page in your web browser: ...
>
> The iRecord website is at https://www.brc.ac.uk/irecord/

Question: what scope do we have for tailoring the wording of these emails - would it be possible to have a bespoke email just for Bloomin Algae (and potentially for other surveys)?

**Comment by johnvanbreda** [comment]
I've updated the variables on iRecord which define the email sent out when an app user account registration occurs. I've not been able to test though as I can't see how to register in the app without submitting a record.

@kitenetter I think it would be possible to tailor the messages to different apps, but it would require a change in the app to include the app name in the submission and some updates to the Indicia API on the Drupal sites. As this area of code is in flux due to the transition to Drupal 9 and the new app JWT API, I think it would be best to delay any updates till that area of code has settled.

@BirenRathod this will need to be applied to the D8/9 version of indicia_api on iRecord, but I don't know which branches I should update. Or should we just be using language translation?

**Comment by BirenRathod** [comment]
@johnvanbreda I'm only using V1 on iRecord, so you can use that.

**Comment by kitenetter** [comment]
@johnvanbreda Laurence reports that this is working for new registrations, so the issue can be closed unless you need to keep it open for the D9 work.
