### ISSUE TITLE
Species-details page broken link

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#1119]
broken link - https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=179383

**Comment by DavidHepper** [comment]
It's working for me. I see the Giant Hogweed page.
FF 89

**Comment by DavidRoy** [comment]
The map on the species details page is blank
https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=179383

Also, if you explore to the species-details page via an occurrence view, i.e. https://www.brc.ac.uk/irecord/record-details?occurrence_id=21068734

You end up with a different taxon_meaning_id
https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=109326

With the map populated and picking up the taxon attributes (e.g. from the plant_portal PLANTATLAS attributes).

Do the taxon_meaning_ids need some clearing up for this taxon?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
The taxon_meaning_id being different is ok I think.
I think that taxon_meaning_id would be from the Uk Master List. The external_keys are the same across species lists, so that link is made.
As long as what is display on the screen is ok that would be fine.

However.
I have looked at the code of the that map on the Species Details page (obviously only briefly so may be wrong) but I think that empty map you are seeing is a general issue with that map.
I think it only ever uses the taxon_meaning_id to find records, and isn't taking into account the taxon_meaning_ids could be different in different species lists but the external_key could be the same.

The Northern Ireland Invasive List entry was created with the same external key, but new species list entries will not have the same taxon_meaning_id when they are created.
I think it is valid for the taxon_meaning_id not to match like this, they won't always be the same accross all species lists, we could never enforce that reliably.
The external_key being the same should be enough.
For instance, the species alert system can work like this, just the external_key match is enough.

Also I think some unrelated observations from those links you sent is that the attribute display on that second summary page looks to have a problematic presentation, although that is outside the scope of this fix. Also the map is slow to draw the features (seem to only appear after 10+ seconds)

So in summary I think I observe the following issues

1. Slow map draw on
https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=109326

2. Attribute presentation appears messy on
https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=109326

3. The map on this age isn't displaying, possibly due to the limitations with the report I mentioned
https://www.brc.ac.uk/irecord/species-details?taxon_meaning_id=179383

The first 2 would probably be for John to look at if you wanted.

The 3rd could be me or John, but I don't have any budget to look at the situation in more detail, so you would need to let me know where I can get some budget to look at it.
Although, to be honest, you might want John's opinion on what I am saying anyway, as that would be the first thing I would do even if you assigned to me. So I guess assign to him if you feel this needs further investigation.

Andy

**Comment by DavidRoy** [comment]
Thanks.  Not an immediate priority as we know this page needs an overhaul.  It's good to have your findings captured here for future reference

**Comment by kitenetter** [comment]
I think this can be closed now that we have a new species mapping page.
