### ISSUE TITLE
Request to implement Period rules in iRecord

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1121]
Flight Period rules are checked in iRecord and warnings issued with a calendar icon but there appear to be no checks on Period rules - year of introduction/establishment and year of extinction. Jim confirms that these rules are currently maintained in Record Cleaner. I've put quite a bit of work into computing the Period limits for all dragonfly species and mplementing these checks in iRecord would be useful, especially as a warning to verifiers for non-resident and vagrant species. Have I missed something? There appears to be no icon defined in iRecord Help and I tried in Training Mode with a species that should fail the existing rule but there was no warning - see record of _Coenagrion armatum_ this year, ID 21096662.

**Comment by JimBacon** [comment]
Just need to clarify a point here. What I confirmed is that, if there are period rules defined, then there is code in the warehouse which should apply those rules. I wasn't sure what iRecord might do to show the results.

I've just had a look at the [current Period rules](https://github.com/BiologicalRecordsCentre/record-cleaner-rules/tree/master/rules/Dragonfly%20Recording%20Scheme/DRN%20Odonata%20Rules/DRN/period), which do no include the updates @DavidHepper is working on at present, and there is no rule for _Coenagrion armatum_ by the look of it. 

On the other hand, there is a [period rule for _Coenagrion scitulum_](https://github.com/BiologicalRecordsCentre/record-cleaner-rules/blob/master/rules/Dragonfly%20Recording%20Scheme/DRN%20Odonata%20Rules/DRN/period/coenagrion_scitulum_recording_period.txt). I have added a record for that with a date prior to its introduction and it is flagged successfully.
![image](https://user-images.githubusercontent.com/2545390/127365127-62e4fb8e-a208-4200-92bd-9697dd348dca.png)


Also, in passing, I note that the TVK in the [ period rule for _Oxygastra curtisii_](https://github.com/BiologicalRecordsCentre/record-cleaner-rules/blob/master/rules/Dragonfly%20Recording%20Scheme/DRN%20Odonata%20Rules/DRN/period/oxygastra_curtisii_recording_period.txt) is incorrect and set to the same as _Coenagrion scitulum_ which has the potential to confuse matters.

I think the issue here, then, is a difference in the rules @DavidHepper thinks we are checking against and those that we are actually using.

**Comment by DavidHepper** [comment]
Good research, thanks, Jim! The rules _are_ being applied and it's just the iRecord help doc (v5.1, section 4.3) that doesn't mention them. As shown, the icon for failing this test is a little ruler > 
![image](https://user-images.githubusercontent.com/24915271/127887757-a5e5d3e1-f522-4e14-8a70-fcb6c3d40d0a.png)
I should have tested a species from the example that you sent me: _Aeshna affinis_ so have done so just now. Success. (Training Mode; id=21369048)
