### ISSUE TITLE
Prevent use of "iRecord dragonflies" web app 

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1133]
The iRecord dragonflies web app is no longer used by British Dragonfly Society and needs to be removed as it is producing incorrect data.

The web page is here:
https://irecord.org.uk/dragonflies/#list

That page needs to be unpublished, or replaced with a message that redirects people to:
https://british-dragonflies.org.uk/recording/submit-your-records/

The web app is also listed in the Chrome web store:
https://chrome.google.com/webstore/detail/irecord-dragonflies/ajiopnflbgclbhnjhmepnkhmcacdkmap?hl=en-GB

That listing should be completely removed.

**Comment by BirenRathod** [comment]
@kitenetter I'm completely unaware of dragonflies site was exists. No recollection of using that site by people. 

I have created the redirection now , so people will stop using dragonflies webapp now.

I can't able to remove the extension as it hadn't created under brc, irecord or app account but due to redirection people won't be able to use it from now on. 
The extension might had created using Karolis own account which @kazlauskis or @DavidRoy can able to confirm it.

**Comment by kitenetter** [comment]
@BirenRathod Karolis doesn't know which account was used to set up the Chrome extension (it wasn't his account).

The extension no longer works, and does redirect people to the BDS page, so it won't be causing incorrect records to be submitted. However, if we can remove it that would keep things tidy.

The Chrome page included a link to an unpublished BRC page about the app, so I have [reinstated that page](https://www.brc.ac.uk/app/irecord-dragonflies) which now also links back to BDS.

**Comment by BirenRathod** [comment]
Thanks, @kitenetter.

I'm looking into user account to delete extension, is I can find I will delete it.

**Comment by kitenetter** [comment]
Biren has now removed the Chrome extension. Closing.

**Comment by DavidHepper** [comment]
I've confirmed that the link no longer works. Thanks, all.
