### ISSUE TITLE
Request to include accepted name TVK in downloads

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#1135]
Request from ERCCIS. Currently the iRecord download page offers 2 download format options, neither of which include the accepted name TVK, they just include the recorded name TVK which might be for a synonym or vernacular name. This is mostly OK but in some cases, where custom taxon lists are used for projects, only the accepted name TVK for the taxa in the list is correct and the recorded name TVK is actually a custom code. An example of this are the taxa in the list used by the Orthoptera Recording Scheme. Records downloaded from these data do not contain any valid TVK at all.

There are several possible fixes:
1. Extend the "easy-download" format to include the accepted name TVK. 
2. Enable downloading the default download format defined on the warehouse, which does include this field. However this option might also require a review of the default download format. 
3. Fix the data in the ORS taxon list (there might be others).

No. 1 is the easiest, is that OK with you @kitenetter?

**Comment by kitenetter** [comment]
I was under the impression that the TVK in the download was the recommended TVK, hadn't realised that it wasn't, and I agree that the recommended TVK would be a useful addition.

In fact, since the only taxon name we give is the recommended taxon name, there is an argument for using the recommended TVK **in place of** the entered TVK, rather than having both (unless we extend the downloads to include both the entered taxon name and the recommended taxon name, which might be of interest to some but adds to the already numerous set of columns that we output).

Not sure what you mean by the "easy-download" format? On the iRecord download page we have a "simple" format and a "standard" format, each of which would benefit from having the recommended TVK. Would option 1 add the recommended TVK to both of those download formats?

Not sure how option 2 relates to the two formats on the existing download page.

**Comment by johnvanbreda** [comment]
Easy-download is the internal name given to the set of columns labelled as Standard Download on the form. 

Option 2 above relates to the original download format, which was a "rough and ready" set of columns I set up when first working on the Elasticsearch downloads. Since then, Rich has worked more thoroughly on the map mate and standard download formats, but the original set of columns is still available in the code.

I agree with your suggestion, that the accepted TVK should be used in the download instead of the recorded name's TVK, so that the TVK and name in the download match. Considering whether to add the name and TVK as recorded is really a separate issue.

@kitenetter do you agree?

**Comment by kitenetter** [comment]
Agreed
