### ISSUE TITLE
Unable to Edit or Redetermine dragonfly records from UKBMS

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1143]
Some records from UKBMS have come in with only the genus entered, even though there is only one species in the UK in that genus. The CDR wishes to edit these records to the full species name but it appears UKBMS records have no form available, so clicking the Edit icon shows only 'Page load failed: the record you are trying to load does not exist'. 
I tried Redetermine at about 08:30 on record 21395310 but it has still disappeared completely as of 09:20.
I'm not sure it's worth adding a form but could Retermine be fixed, please, if this isn't just an indexer issue?
(Other records to be redetermined:  21395311, 21395247, ... )

**Comment by johnvanbreda** [comment]
@DavidHepper I've fixed the edit link.
It looks to me like the Redetermination tool had an error when you tried it, causing it to fail to update the underlying data. Due to the way it works, the system "knocks out" the redetermined record from Elasticsearch, then the change to the raw data version of the record gets copied across to Elasticsearch a few minutes later so it should re-appear. In your case this didn't happen as the underlying data weren't amended.
I've just restored the record in Elasticsearch, then masqueraded as you and successfully tested the redetermine tool using Edge. I also did record ID 21395311 using Chrome. Is there any additional information about what happened when you redetermined them that might help me spot the problem?

**Comment by DavidHepper** [comment]
This is getting complicated. Here's the Comments history for ID 21395247, with my notes alongside. (I have turned the table from iR upside down so that chronological order starts at the top and works down). There are two entries that seem unexpected. I hope this helps! Let me know if you need more info.

<html>
<body>

Comment | My Notes
-- | --
Record was determined as Cordulegaster |  
Mason, Chris 2021-08-04 14:06:05 | Original entry
Accepted as considered correct |  
Clarke, David 2021-08-05 07:54:55 | Accepted by verifier with Genus-only det.
Accepted as considered correct |  
Clarke, David 2021-08-05 07:55:16 | ? duplicate entry 20s later
Record was determined as Cordulegaster boltonii |  
Clarke, David 2021-09-06 14:04:46 | Note of the redet by DH to species level, but the comment shows the verifier’s name as the redeterminer. This is unexpected.
This record's verification status needs to be rechecked as it has been edited. |  
Hepper, David 2021-09-06 14:04:47 | Explanatory comment, 1s later with the correct user name (DH).
As requested by David Clarke: originally recorded as genus-only. |  
Hepper, David 2021-09-06 14:04:47 | Addition of the verbatim comment by DH in the redet dialog, 0s later with the correct user name (DH).
Accepted as considered correct |  
Clarke, David 2021-09-06 15:59:24 | Reacceptance by verifier (DC).

</body>
</html>

**Comment by DavidHepper** [comment]
Never mind. Not sufficiently important.
