### ISSUE TITLE
Checks for sensitive plant species on export

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#115]
Country agencies have (short) lists of sensitive plant species, for which records should be blurred to 10 km. OLP has these lists. DBR has suggested that a future iRecord enhancement could be to have an option to blur these species records on export, although the detail has not been thought through. @DavidRoy to talk to @johnvanbreda about costings.

**Comment by kitenetter** [comment]
May also need to take into account NBN's proposed lists of sensitive species (haven't yet seen any detail of this)

**Comment by sacrevert** [comment]
I don't know for sure, but I would assume the NBN list is an amalgamation of the country agency lists.

**Comment by johnvanbreda** [comment]
Would this list apply to all records, not matter the location? Perhaps supporting a sensitivity_blur flag in the species database tables would allow us to apply this blur on export, or perhaps better at the point of data entry?

**Comment by sacrevert** [comment]
No, the sensitive species (at least for plants) will be country-specific.

**Comment by kitenetter** [comment]
See also #407

**Comment by johnvanbreda** [comment]
We have a workflow module that can flag incoming records as sensitivei, blurring them. I think we should do it at the point of data entry rather than export, otherwise people can still find the unblurred versions in the explore pages. Should we enhance this feature to make the workflow rules linkable to either vice counties or countries? If we do that it would be worth asking LRCs for locally appropriate species lists to blur.

**Comment by sacrevert** [comment]
I think it would be good to have country-level workflow rules, VC level seems a bit over the top to me.

**Comment by kitenetter** [comment]
@kitenetter to document sensitive species process

**Comment by kitenetter** [comment]
Now being discussed under #407 - closing this one.
