### ISSUE TITLE
Edits to menus for verification

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1152]
As usual I'm struggling with the menu settings.

What I would ideally like is for there to be a top level menu that is called "Verify" and has two submenus: "Verify - iNaturalist" and "Verify - old format". But if I set things up like that, the top level "Verify" will not work unless you double-click on it. This appears to be a Drupal limitation that we've hit up against in the past.

So if that cannot be achieved, the next best option would be to have a top-level "Verify" menu with three sub-menus:
- Verify - main
- Verify - iNaturalist
- Verify - old format

I have set up the pages required to do this, with node 8477 as the new top-level menu item, but I have not enabled that node, because I don't know how to make it so that it only appears to users who are verifiers.

The iNat page is also currently not enabled but I will enable it once the new records start being imported.

@johnvanbreda can you set up the new "Verify" menu item, linked to node 8477, so that it is only visible to verifiers (or let me know how to do so).

**Comment by johnvanbreda** [comment]
@kitenetter Drupal doesn't have a built in per-page permissions system, though one can be added via a module. Or, an alternative would be to use the permissions system built into the iForm module's pages - rather than adding a normal Page, you can add an Indicia page, then set it to the Reporting > Reporting pages (customisable) page type. If you then empty the User Interface > Form Structure box and set View access control to ticked, and the subsequent "Permission name for view access control" box to "verification" it should create a page that only verifiers can use.

Or - an alternative would be to use the main verification page as both the top-level AND one of the child menu options. Then a verifier who knows how can double click to access, otherwise if this isn't obvious they can click on the sub-menu item. It's possible to add a second menu item for one page if you do that via the Structure > Menus section.

Let me know if you need more help.
