### ISSUE TITLE
Deleted records not being removed from ES dataset

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1255]
A user has deleted some records, and they are showing as deleted in the warehouse, but they are still appearing in the user's "My records" view.

Record ID examples:
24143233
24143232
24143231
24143314

These are marked as deleted = TRUE in table occurrences, and are not available in table cache_occurrences_functional, but they seem to have remained in the ES view of the records. The deleted records are also still visible to verifiers (again in ES view).

**Comment by johnvanbreda** [comment]
The deletion process was stuck because it uses timestamps to select records and processes up to 10000 at a time. There was a batch of 24K deleted in the same millisecond, so it could not separate them. As a temporary fix I increased the batch size to 25K so it's running again.

Do we need to do any more, or can we consider this a one off and close it?

**Comment by kitenetter** [comment]
Hopefully it is a one-off, so will close for now.
