### ISSUE TITLE
Has the iNaturalist import got switched off?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1257]
I've had a report that no iNaturalist records are coming through at the moment, and I can't see any since 25 Feb.

**Comment by johnvanbreda** [comment]
@BirenRathod do you mind taking a look at this please? When it runs the import task from the Windows Task Library it just comes back saying it failed to start the action. I've left it disabled but if you re-enable it you will see.

I've checked the warehouse logs and there are no errors generated. I've also tried running the rest_api_sync directly from a browser URL and it worked fine so it does seem the problem is at the task scheduler end, not in the warehouse code.

**Comment by BirenRathod** [comment]
@johnvanbreda It just need to amend the path of PHP which I done it. It works fine now.
@kitenetter Please close if it resolved

**Comment by kitenetter** [comment]
I'm still not seeing any iNat records after 25 Feb. But maybe it will take some time for the records to feed through to the ES layer? WIll check again this afternoon.

**Comment by kitenetter** [comment]
Now coming through okay on ES. Closing.
