### ISSUE TITLE
Verification page running slow

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1293]
Have just been verifying and the page does seem to be taking longer to load for each new record following verification of the previous one, and with the map sometimes being slow to redraw. The speed is not impossibly slow, but it does seem slower than I am used to.

HAR file from the last 20 minutes or so:
[irecord.org.uk_Archive [22-05-15 20-30-39].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/8695794/irecord.org.uk_Archive.22-05-15.20-30-39.zip)

**Comment by kitenetter** [comment]
Okay, so it is being impossibly slow from time to time! It's particularly frustrating that it sometimes shows no evidence of doing anything, e.g. after clicking a button to accept a record the page just sits there doing nothing for an appreciable number of seconds, and then changes to the egg-time symbol and shows that for some more appreciable seconds. In the gap before the egg-timer appears you are left wondering whether or not you did actually click the "accept" button, and are tempted to click it again.

**Comment by kitenetter** [comment]
HAR file after a particularly slow response:
[irecord.org.uk_Archive [22-05-15 21-18-56].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/8695920/irecord.org.uk_Archive.22-05-15.21-18-56.zip)

**Comment by DavidRoy** [comment]
@BirenRathod can you investigate options for the ES server, with IT

**Comment by BirenRathod** [comment]
@johnvanbreda Back in September last year, we have upgraded memory from 16 GB to 24 GB. After upgrading memory, server was running on high memory due to some ongoing process in the background. 
I have sent you last email.

It has increased using memory of 2GB more from 20GB but it hasn't used all of them.

Also, Is it ok to restart the elastic server now or at 12?  To see if that make any difference.

**Comment by johnvanbreda** [comment]
If you restart the server best to check with David/Martin first, also would be a good idea to check that Logstash is idle at the time. Normally at 0, 15, or 45 minutes past the hour it will be. 

When considering options, you need to look into whether it is better to scale horizontally by adding machines to a cluster rather than vertically.

**Comment by BirenRathod** [comment]
@DavidRoy  & @kitenetter Can you let me know if that is ok to do?

I had discussion last time with our IT team but they suggest, it will not make much difference because memory will divide between each processor, so we might need more memory for each processor.  I will ask again and see if they will provide any better solution.

**Comment by BirenRathod** [comment]
@johnvanbreda After restarted the server, the server is only consumed max of 10 GB memory of 24 GB. 
@kitenetter I don't find any problem but can you check verification page loading?

**Comment by kitenetter** [comment]
I haven't had a chance to do any verification since Sunday but will report back when I can.
