### ISSUE TITLE
Update request for some species in the taxon dictionary

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1313]
This will no doubt be picked up when we next get an update from UKSI, but the recording scheme concerned (Conch Soc) has asked if we can make this change as a priority, as it is causing problems for their recorders.

Currently iRecord has a taxon "Polycera faeroensis" with taxa_taxon_list_id = 38774 ([UKSI link](https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000177339)).

All existing records need to be transferred to a new aggregate taxon, "Polycera faeroensis/kernowensis" ([UKSI link](https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021494710)).

We then need to add two further new taxa:
Polycera faeroensis sensu stricto ([UKSI link](https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021494720))
Polycera kernowensis ([UKSI link](https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021494715))

**Comment by johnvanbreda** [comment]
@kitenetter can I just check. Since the new aggregate P. faeroensis/kernowensis will actually become the accepted name for the old P. faeroensis taxon (id 38774). So I don't need to actually move the records as they will inherit the new accepted name. I can mark the P. faeroensis taxon as not for data entry. Or would you prefer that the records actually get moved across to the aggregate? Normally I prefer not to actually change the representation of the data as it was input by the user.

**Comment by kitenetter** [comment]
Good point @johnvanbreda and I agree that it is best for the original name to be kept but linked to the current preferred name, which is the aggregate. No need to move the records to the new name.

**Comment by johnvanbreda** [comment]
Now done.
