### ISSUE TITLE
Precision incorrect on Birdtrack imported data

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#1316]
Records are often having 8 figure grid references assigned to the site's lat long (presumably a centroid), which does not reflect the coordinate uncertainty supplied for the record.

**Comment by johnvanbreda** [comment]
Due to the sample attribute not having the system function set correctly (ID 1645).

**Comment by DavidHepper** [comment]
This issue is causing great consternation. It also affects 4-figure monad GRs that are being demoted to (useless) 2-figure hectad resolution, e.g. record 27028167 with coord uncertainty 1000 that shows as SU29. It also makes a mess of the maps. The word is that these started off being shown correctly but were modified after import. 
Could recalculating the GRs be moved up the priorities, please?

**Comment by johnvanbreda** [comment]
The original problem here was spurious accuracy being assigned to grid refs due to the coordinate uncertainty I'd actually fixed the attribute last week and as 27028167 is a new record is actually has the correct processing applied. The raw data we have is a very precise lat/long, plus a coordinate uncertainty of 1000. This should be a radius of the smallest circle containing the site. As our current output_sref calculation doesn't currently do tetrads, rounding up to a 10km grid square is better than giving spurious accuracy.

Note that the data provided from BTO does give a grid ref for the site, but this is not necessarily correct for the record, so it's shown in the list of sample attributes as a separate thing.

@kitenetter we could support tetrads in the calculation of output grid refs if that is helpful. It's a fairly simple change, although of course will need to be applied to existing data at some point. Also, should I recalculate the output grid refs for all the BTO data?

**Comment by DavidHepper** [comment]
The 100x difference in area between monad and hectad makes these records unhelpful. CEH exclude them from their occupancy analyses, for example. 
We agreed (with @kitenetter ) not to import records that resolve to vaguer than monad. I'd much rather accept the spurious accuracy of the monad in which the detailed map ref lies than take up my verifiers' time rejecting or parking these records.

**Comment by johnvanbreda** [comment]
@kitenetter please can you confirm any changes you want here - the agreed specification from the final document sent on 29/10/21 was that we would only reject records with a grid reference size > 1000, not records with a lat long that have a coordinate uncertainty provided. The latter would instead have a warning comment attached if the uncertainty > 1000 but it is 1000 in this case so nothing was attached. Some thoughts:

1. David may be expecting that lat/long points with a coordinate uncertainty that implies a grid ref > monad should be excluded. This is different to the agreed spec I have, so should we change it?
2. Our code is based on a cut-off of 1000, but as this is a radius, it corresponds to a tetrad. Should the cut-off be 500, corresponding to a monad?
3. Are we sure that BTO are supplying the coordinate uncertainty correctly and that 1000 is not supposed to imply a monad?
4. As per comment above - should we change the code for creating output grid refs so it supports tetrads, for data going forward and possibly for data in the past?

**Comment by DavidHepper** [comment]
Yes but TG14 is completely useless. I'll take the spurious accuracy every time. Besides, if you were doctrinaire about including everywhere the 'circle of uncertainty' touches you'd have to compute to myriad TG instead of TG14.
I wish we'd kept to the manual import, over which I have more control. My verifiers tell me they never get any response to querying BirdTrack records within iRecord, a feature that was supposed to be a selling point for the automated system.

**Comment by DavidHepper** [comment]
We urgently need to resolve this as I'm receiving as stream of complaints from verifiers. We need to change the method by which the Output Map Reference (OMR), labelled 'Grid ref' in Details, is computed and apply the new method retrospectively to all Odonata records within the 'BirdTrack non-avian taxa' survey dataset and then set them back to Pending. This process should drop (delete or not import) records that resolve to Hectad or vaguer.
Unfortunately, it is impossible for me to see the verbatim values received from BTO even though the precise point is helpfully plotted on the map in iRecord! Example: In record 28796286 shown above, the location marker is to the left of the centre of TG1142. As @johnvanbreda points out, after the 1,528 metre radius of uncertainty is applied, the larger red circle is larger than this square. However as discussed later with @kitenetter, it is not bounded within TG14 but also part of TG04 (specifically TG0942) so that even TG14 is spuriously accurate and a strict interpretation would compute only TG. We are moving far from a useful value.
I propose that spurious accuracy is tolerated to avoid discarding large numbers of records. Where the original uncertainty is below 70 metres it should stand. Where it is above 70 metres it should not be used but the monad containing the Lat,Long should be used as the OMR and the original uncertainty put into the Sample Comment.

**Comment by kitenetter** [comment]
Action being taken under #1597 and #1598 - closing this one.
