### ISSUE TITLE
Can verifier notifications include a link to the record in verification page view?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1342]
Verifiers receive notifications of edits to records that have previously been verified. The notification includes a link to the record's display page, but the verifier cannot verify the record from that page, and there is no easy way for the verifier to find it on their verification page. They can of course copy the record ID and paste that in to the filter box on the verification page, but that requires quite a lot of steps and is not sustainable where large numbers of records are being dealt with, and for verifiers with multiple roles it can take a long time to find the record in question.

Is it possible to set up a link that could be included in notifications to verifiers and that would take them to their verification page with a 'pre-loaded' filter for the record they need to see?

A less ideal alternative would to be to enable a set of verification status buttons to appear on the record view page, when viewed by a relevant verifier.

**Comment by johnvanbreda** [comment]
Changing the link to a filtered version of the verification page is slightly complicated by the fact that we'd also need to include the context in the link, otherwise the default context might not contain the selected record so it wouldn't appear. But, the notifications system is not likely to be able to obtain the context in order to provide it in the link. 

An option might be to allow the link containing a record ID to filter to that record ID without applying the current context (perhaps using some sort of authentication token to ensure only the user who received the email can use the link). But it's not a trivial solution unfortunately.

**Comment by kitenetter** [comment]
I suspected this would not be an easy win. I will close for now (only been requested by one verifier at the moment).
