### ISSUE TITLE
Verifier struggling to log in

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1354]
We've had this report from a very dissatisfied verifier, who I think is trying to use the links from the "records to verify" notification emails to go to their verification page:
"if there is too long a gap between you sending me records to verify, then I have to log in again every time and increasingly it does not recognise my password - so I have to keep changing my password which means crossing off my old password in my note book and writing a new one in so I do not forget it."

I can't reproduce this - is there any reason why passwords would fail to be recognised? And do we have any control over how often users get logged out of the system, or is that more likely to be a result of their browser settings?

**Comment by johnvanbreda** [comment]
No reason I'm aware of. There was an issue after switching servers (e.g. to Pantheon) which can cause something similar - @BirenRathod suggested clearing cookies, but I don't think that can be the issue here. I'm not sure about controlling the session expiry but I'd imagine there is a PHP ini setting or similar, so this can be looked into further if you think it's an appropriate solution.

**Comment by kitenetter** [comment]
This doesn't seem to be a widespread issue so will close.
