### ISSUE TITLE
Please change the Status picklist in Verify to a multi-selection list

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1376]
I've never liked using the `Quality > Records to include` picklist in `Verify > Create a filter`, other than values 'Pending' and 'All records'. These two are clear and obvious. Many of the other entries are arbitrary and poorly-worded. Please consider changing it to a list where we can multi-select the statuses we wish to include. 
Especially arcane is `Not accepted as reviewer unable to verify records only`, that selects rejected records with decision (status 2) shown in the Detail section only as a red 'X' on white icon.
The list could be vertical, with the familiar icons. Additional buttons for 'Select All' and 'Clear All' would be useful.

**Comment by kitenetter** [comment]
Not sure the list is arbitrary but agree it is poorly worded! And I can see the benefits of having a simpler list with multi-selection tick boxes.

The short-term work-around may be to use the overall "Status" dropdown rather than going via "Create a filter", but will look at other options alongside other proposals for improvements to filtering.

**Comment by kitenetter** [comment]
Revised wording and consistent optiosn between quick filters and 'create a filter' options are proposed in #1487 - closing this issue.
