### ISSUE TITLE
enable verifiers to download sensitive records at full resolution

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1394]
Not currently certain if this is something that used to be available, but at the moment verifiers can only download sensitive records with a blurred grid ref and no location name.

Butterfly Conservation have requested that verifiers should have access to full resolution for the Garden Butterfly Survey (for which all records are marked as sensitive) and potentially for all other sensitive records.

There is a technical question about how we can make this happen, but before we proceed with that we need to work through the implications, e.g. will we need to ask verifiers to sign a data processor agreement and specify how sensitive records need to be handled outside Indicia.

**Comment by johnvanbreda** [comment]
There are 2 methods of authentication for Elasticsearch in play here. First, using a custom alias setup on the ES server allows us to apply any custom filter for any authorised group of users. There is one for iRecord reporting (with a limited set of websites, showing blurred records only, hiding confidential and unreleased data), plus one for iRecord verification (a different limited set of websites, with full precision records and showing confidential and unreleased data).

The second approach is to send the website authentication details and the task (reporting/verification etc) then the warehouse can work out the correct list of websites. For verification, it filters to show the full precision records but does not include confidential or unreleased data. 

So, in order to switch to the 2nd dynamic method of authorisation, I'd need to change the warehouse so that the verification mode always allows confidential and unreleased data to be included. I just want to check that's OK before proceeding as this would mean that any other verification pages (e.g. on a record centre site like ERCCIS, or NatureSpot, iRecord Saint Helena etc) would also see confidential and unreleased data. Is this acceptable @kitenetter? I think it's OK since we are already doing this on iRecord.

The advantage of the 2nd method of authentication is that it can dynamically apply the correct sharing mode on the download page according to the selected filter (and therefore can dynamically allow sensitive records to download at full precision). So we can switch method once the above change is made, if agreed.

**Comment by kitenetter** [comment]
I don't think we can proceed on this until we move to setting up data processor agreements with verifiers and other downloaders.

**Comment by kitenetter** [comment]
Need to break this issue down into smaller steps based on NCEA scoping.

**Comment by kitenetter** [comment]
Being addressed under issues starting from #1713 - closing this one
