### ISSUE TITLE
Enhance spreadsheet upload process

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1405]
This new issue is an attempt to bring together outstanding issues from #999 #879 #301 and #34 

- [x] First task is to reinstate the test version of the new uploader.

Requirements list for all users (based on the existing uploader, some of these may not be relevant to the new uploader):
- [x] Set defaults so that users are always offered the "iRecord Import" survey and the "UK Master List" species list. For the latter it should not be too easy to choose anything else! However, users do need to be able to get to the other options if needed.
- [x] The current tick boxes to remember the field mapping are not working
- [ ] We need an undo button! Or a data management tool that allows whole sets of imported records to be deleted. (This may be covered already in the new uploader.)
- [ ] Remove the 'non-recommended' attributes from the very long list of attributes to match when using the "iRecord Import" survey (in a similar way to the attribute controls available for the DRN survey)
- [ ] Add some more Help text to the import pages themselves (it's in the guidance document, but some hints on the pages would help)
- [x] if a csv file has column headings that iRecord thinks it understands, it skips over the field mapping page. This is dangerous, and we should ensure that the field mapping is always displayed for a final check before importing.
- [ ] Check whether there is anything we can do to ensure that when importing records based on taxon name strings they are linked to current, rather than redundant, name strings (very occasionally in the past names have ended up linked to redundant UKSI names, which causes problems)
- [ ] Decide how/if to make "Lookup of existing records" available (it is a useful function but dangerous without guidance, which is not currently available)
- [ ] It would be useful if the import process would drop any record matching an existing External Key value (if specified), so that duplicates are not imported.
- [ ] Update Help/Guidance document to cover any changes

Additional functions for verifiers only
- [ ] Ability to import datasets as already verified
- [ ] Ability to choose to import into the 'private' website (#1396) or the public iRecord website

We will probably need to break this issue into smaller units once the new version starts being tested.

**Comment by cubitmg** [comment]
Rather than an Undo button to delete the records from the most recent import, the 'data management' alternative which would list all imports and allow the deletion of records from any of these would be much preferred based on my experience of other applications. Finding problems with an import file's records does not always come to light immediately. This would link to #1294.

**Comment by johnvanbreda** [comment]
The new uploader is available at:
* live - https://irecord.org.uk/import/v2
* test - https://test-brc-irecord.pantheonsite.io/import/v2 (links to live database)
* dev - https://dev-brc-irecord.pantheonsite.io/import/v2 (links to dev database, for testing PHP 8.1)

**Comment by johnvanbreda** [comment]
Coding done for the second task - "Set defaults ". Lists of options in the Import Settings can be limited by specifying a semi-colon separated list of options in the config. A special * option indicates that the user should be able to override the restricted list of options and a default selection can also now be set in the config.

Third task "The current tick boxes to remember the field mapping are not working" - the new import has a different approach to remembering mappings, where you are able to save a number of different templates for future use (instead of a single list of remembered mappings).

Task 7 - the mappings page is never skipped in the v2 importer if all the columns are automatically matched or remembered from the template.

**Comment by johnvanbreda** [comment]
Thanks @cubitmg - all useful feedback. I've changed the code for the next release to match all your suggestions, except I didn't add an hourglass to the background processing just yet (I wasn't sure if I wanted to attract attention to this bit), plus the 2nd point about auto-detection of the spatial reference system is a bigger change that probably ought to be fed through the system as a separate issue.

**Comment by cubitmg** [comment]
Thank you @johnvanbreda.

Happy to create a separate issue on the Spatial Ref. System.

One other thought on this is that the page currently advises "Note, if you have a file with a mix of spatial reference systems then you need a column in the import file which is mapped to the Sample Spatial Reference System field containing the spatial reference system code.", which I understand, but it isn't clear what value this field should be set to in that case?

It might be possible to have something fairly straightforward to pick out the spacial ref system using preg_match and these regex expressions?
For OSGB:  /^[snhtoSNHTO][a-hjzA-HJ-Z]([0-9][0-9])+/  (this covers all likely ones or /[a-hjzA-HJ-Z]{2}[0-9]+/ to cover every possibility)
Irish: /^[iI]?[a-hjzA-HJ-Z]{2}([0-9][0-9])+/ where the initial optional [iI] depends on whether you want to support that letter as a prefix as the BTO do.
The lat/long option maybe best as a function checking for numbers within the appropriate +/- 90 or 180 values. although I think the following regex works (allowing ; or , as a delimiter between lat and long values): /^([-]?(([0-8]?[0-9])(\.(\d+))?)|(90(\.0+)?))[,;][-]?((((1?[0-9]?[0-9]))(\.(\d+))?)|180(\.0+)?)$/

**Comment by kitenetter** [comment]
Additional requirement is to ensure that on import the standard record attributes are mandatory, especially for stage, and especially for Lepidoptera, although I think this is desirable for all taxa.

**Comment by kitenetter** [comment]
A user reports that when using the new importer in training mode, records are being treated as normal, non-training, records on import. The new importer needs to be able to recognise training mode.

**Comment by cubitmg** [comment]
> Thanks @cubitmg - all useful feedback. I've changed the code for the next release to match all your suggestions, except I didn't add an hourglass to the background processing just yet (I wasn't sure if I wanted to attract attention to this bit), plus the 2nd point about auto-detection of the spatial reference system is a bigger change that probably ought to be fed through the system as a separate issue.

I have tried the importer again (Live and Test systems) this evening and the wording changes make things much clearer.
I found a couple of things to feed back on though,
1) The progress bar on the Select File page never quite reaches 100%. The Next button can still be clicked, but could be disconcerting to a new user.
2) When I accidentally selected a file where the first sheet was not the records sheet (it was a README page), on the Import Settings page the progress bar got stuck at about 70% of the way across and the application hung and wouldn't allow Next to be clicked.
3) When I sorted out my input spreadsheet I got through file selection import options and the field mapping screens (and all of the fields were found automatically - thank you), however, on the Value Matching form it gets as far as the 'Finding lookup fields that need matching' process and hangs. The file only has one record (attached). [Test Moth Record File.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/10717438/Test.Moth.Record.File.xlsx)

**Comment by johnvanbreda** [comment]
* The importer now handles importing in training mode correctly.
* The progress bar on the Select File page now goes to 100% when file upload is complete.
* Selecting a spreadsheet with an empty first sheet should now give an error message rather than hanging.
* The test moth record spreadsheet failed due to a bug in the lookup of taxa using external key. I've fixed this
* I've also implemented better code for lookup matching against location name/code for samples that link to locations.

**Comment by cubitmg** [comment]
Thanks @johnvanbreda 
Can you let us know when it is available to retest and in which environment(s)? 
One other thought is that there is no 'escape' from having to click 'Next'. A 'Previous', 'Cancel', 'Restart' or 'New Import' button would be helpful as an option?
Also, when one gets to the end with a successful import there isn't anywhere obvious else to go next. Maybe an 'Import another file' button? It would be nice to have a button that 'Explored' the imported records, but obviously that won't work because of the processing into ElasticSearch delay.

**Comment by kitenetter** [comment]
@johnvanbreda I've been trying and failing to find some more time to work on this, so have decided it's best to pass on the feedback I have available. See this Word doc (if you want it added directly to Github I'll try and do that next week):
[iRecord import v2 testing.docx](https://github.com/BiologicalRecordsCentre/iRecord/files/10941402/iRecord.import.v2.testing.docx)

**Comment by cubitmg** [comment]
There now appears to be a check on key fields being present including date? This doesn't appear to accept just Date Start, Date End and Date Type any more? I had to change the input file to have a single date field for the import to proceed. Presumably the iRecord import should support either date import approach?

A date range such as 01/08/2021-31/08/2021 in the date field imports OK, but when I tested a few weeks ago some date range types don't set the correct Date Type field when importing. Which date field approach should be used (and specifically which should I use for my Validator application)?

**Comment by johnvanbreda** [comment]
@cubitmg you are right - the importer has inadvertently blocked the ability to use the separate date fields. Noting that I need to fix this in the next iteration.

@kitenetter I've done most of the points in the Word doc:
- File name shown next to the icon when you pick an upload file.
- All the restricted options controls can now toggle from restricted to unrestricted and back again, not just 1 way.
- Added moth and dragonfly surveys and removed iRecord general.
- Spatial systems listed in alphabetical order.
- Improved the auto-matching of column titles like location and recorder names.
- Fixed some bugs which caused the validation failures you got when you tried to upload rules.
- On the last tab, the fixed values are shown as text rather than just an ID (e.g. a website title rather than ID).
- A few text edits as suggested.

We can turn off a list of fields for import, would you like to suggest a list? Or is it essential that the user can still access these fields, even if initially hidden?

Yes - you can make the stage term mandatory for iRecord import, though that limits one of the use cases for this dataset, which has a flexible format so it can import from a wide range of historic datasets, some of which may not have stage.

**Comment by cubitmg** [comment]
Hi


I've had another go with the V2 import and here is some feedback if that is useful. Things seem to be getting more difficult.

I can't work out what column name to use for Recorder Name to be picked up automatically. I tried 'Recorder Name', which used to work I think, but no longer. Also tried 'Sample attributes - Recorder Name' and 'Recorder' neither worked.

'Quantity' gets picked up when using iRecord Import, but not iRecord Moths for which Qty is required. The former or either option would be better.

Source of imported records - only available for iRecord Import, but not iRecord Moths.

'Sample comment' and 'Occurrence comment' both recognised which is good, but the destination dropdown just says 'Comment' for both of them. The drop down needs to be opened to see which one is being used which is not very intuitive or worse just breeds a culture of encouraging the user to assume it must be correct which isn't great.

Vice county supplied works with iRecord Import but not iRecord moths?

Is there going to be a help screen (not a user guide) that lists what column names are supported? (Or maybe from a personal point of view can you just tell me?!)

Thanks
Mark

**Comment by kitenetter** [comment]
Thanks @cubitmg 

Help and guidance is definitely going to be needed for this page and we are looking at options for how best to provide that.

There will always be differences between the different surveys that users choose to import into. The "iRecord Import" survey has a fairly broad set of attributes that allow for importing across a wide range of taxon groups. The "iRecord moths" survey is what is used for data entry on the iRecord moths recording form, and is also the same as that used by NMRS Online, and thus has fewer options for importing into, but is more consistent with the NMRS format. This is another thing that we need to make clear to users.

**Comment by cubitmg** [comment]
OK, thanks @kitenetter. A few thoughts then:
Suggestion: Put the accepted column names into the selection drop-down list (to avoid having to have a separate help screen). At the top of the screen where it says "Select which database field each of your import file's columns should be mapped to." add to this "Note in the drop-down selection list the automatically recognised column names are shown within [Square brackets]."
Bug?: I eventually found "Sample Recorder Names" as a column header would pick up that Sample field, but this doesn't 'tick' the Recorder Name 'Required field'. The Selection drop down has Recorder Names under Sample and Recorder Name under 'Sample attributes for selected survey'. Does the former map to the same iRecord database field as the latter? If not should it even be in the list? If it does map to the same thing then it should 'tick' the Required field.
Question: What column names would automatically pick up the Sample attributes for selected survey Recorder Name?
Question: Is there going to be a Butterflies survey type (or does 'iRecord Import' need to be used?
Bug?: The input file column name was Method, and this matched against Method. However, I was then prompted as if the Sample method (lookup in database) had been selected. I reselected the Survey's method and not matching issues arose. I don't know what is going on here.
Bug: Everything seemed ok, but got a generic 'Error occurred on server' message so no idea what the problem was.
Question: do the Record status and Record substatus do anything yet (assuming these are Validation fields)?

Thanks, Mark

**Comment by robin-hutchinson** [comment]
Related to this issue: https://github.com/BiologicalRecordsCentre/iRecord/issues/1364

The new importer does allow importing on Channel Island grid references (a user has tested this out) - there are a couple of import systems with very similar names that don't all work for WV- grid references but they have worked out that the correct one is "UTM 30N (ED50)". Would it be possible to edit the name of this one to make it clearer (e.g. "UTM 30N (ED50) - Channel Isles Grid"), please?

**Comment by cubitmg** [comment]
On @kitenetter advice, I have tried importing using 'iRecord import' rather than 'iRecord Moths'.
- Using a csv file (attached) works OK through most steps as long as I choose to import the Taxon field, but when it gets to 'Checking data' it seems to freeze. (The 'Recorder name' isn't picked up automatically though.)
- If I choose to import using 
[Test Moth Records 2021 short - iRecord.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/11383059/Test.Moth.Records.2021.short.-.iRecord.csv)
[Test Moth Records 2021 short - iRecord.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/11383060/Test.Moth.Records.2021.short.-.iRecord.xlsx)
the TVK as the species then it doesn't recognise the TVK numbers. One of these is NBNSYS0000146497 for Dysstroma truncata,Common Marbled Carpet which is the same TVK as iRecord downloads for that species, so I think it is OK?
- When I try an import the XLS file (which does have a lot of other worksheets) then it goes into a loop displaying "Loading records into temporary processing area. (66%)".

**Comment by cubitmg** [comment]
Having a 'Back' or 'Previous' button on the page to the left of the 'Next' button would be valuable. The Browser back button works  OK in most cases.

**Comment by kitenetter** [comment]
To pick up on some of the bullet points above from @cubitmg 

> Suggestion: Put the accepted column names into the selection drop-down list (to avoid having to have a separate help screen). At the top of the screen where it says "Select which database field each of your import file's columns should be mapped to." add to this "Note in the drop-down selection list the automatically recognised column names are shown within [Square brackets]."
> Suggestion: Alternatively where it currently has 'suggestions' these could include or even actually be the column text that would be picked up automatically.
> Suggestion: The Field suggestion buttons are nice, but it is't obvious what they mean or the difference between them?

Agree that the field names need to be handled better.

> Bug?: I eventually found "Sample Recorder Names" as a column header would pick up that Sample field, but this doesn't 'tick' the Recorder Name 'Required field'. The Selection drop down has Recorder Names under Sample and Recorder Name under 'Sample attributes for selected survey'. Does the former map to the same iRecord database field as the latter? If not should it even be in the list? If it does map to the same thing then it should 'tick' the Required field.
> Question: What column names would automatically pick up the Sample attributes for selected survey Recorder Name?

As shown in the existing guidance document, under nearly all circumstances it is better to use "Recorder Name" (singular) not "Recorder Names" (plural), but this is obviously not a user-friendly distinction and will be addressed.

> Question: Is there going to be a Butterflies survey type (or does 'iRecord Import' need to be used?

We've never been asked to set up a separate butterfly survey structure on iRecord. As discussed via email, we will remove the Moth survey from the initial choices offered on import.

> Bug?: The input file column name was Method, and this matched against Method. However, I was then prompted as if the Sample method (lookup in database) had been selected. I reselected the Survey's method and not matching issues arose. I don't know what is going on here.

Not sure I follow that but will test - was this in iRecord moths rather than iRecord import?

> Question: do the Record status and Record substatus do anything yet (assuming these are Validation fields)?

We do not intend these fields to be used on import, and therefore will address whether they can be hidden.

**Comment by kitenetter** [comment]
I'm going to close this lengthy issue and start to add more focused issues to deal with the various points raised.
