### ISSUE TITLE
Species details map - some dates displaying incorrectly

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1433]
The map can appear to show records for time-periods far earlier than the actual records specify, for records which span more than a year @burkmarr

**Comment by burkmarr** [comment]
It looks like there are two problems. First is that year is retrieved from the Elasticsearch ‘year’ field and this is not populated where a record spans more than one year. So we probably need to do something more sophisticated with years (which will be problematic because someone could stick a threshold in the middle of a record’s year range). Secondly, the records with no year are being coloured as if their year were ‘0’.

**Comment by burkmarr** [comment]
@Sam-Amy @kitenetter - After thinking about this, I've realised that a record with a year range really should be treated as a number of records - one in each year of the range. So not as problematic as I thought.

**Comment by burkmarr** [comment]
There remains a problem with the temporal distribution by year chart. Currently this is aggregating on the event.year field - so one value is returned for each year which is the number of records recorded in that year. I can't think of a way to include records which span a number of years in this aggregation.

@johnvanbreda - do you know if it is even possible to perform a similar ES aggregation - i.e. count the number of records that occurred in each year - that includes records that span more than one year, so that they increment the count for every year they span? I can't see a way to do it, in which case I'll need to update that chart with some text which indicates that records spanning more than one year are excluded.

![image](https://user-images.githubusercontent.com/9275178/223714828-6d4de2ca-1828-4417-add9-dbf451a0b3be.png)

**Comment by DavidRoy** [comment]
@burkmarr I'd be tempted to remove records that span years.  They should be a minor contribution, at least for the recent period

**Comment by johnvanbreda** [comment]
@burkmarr not without either adding a new field or modifying the year field to an array, so it can hold a list of all years spanned. Or you can do calculations in an ES Query using Painless scripting, so I'm sure it's possible, but both options seem like a lot of effort and potential performance knock-on effects considering David's last comment.

**Comment by DavidRoy** [comment]
As long as we are clear on what the plot is showing.  We should also discourage inprecise records ;-)

**Comment by burkmarr** [comment]
Thanks @DavidRoy and @johnvanbreda - I will add some caveat to indicate what the plot shows then.

**Comment by burkmarr** [comment]
@Sam-Amy @kitenetter - the fix I applied is testable on the burkmar2 multidev site now, e.g. https://burkmar2-brc-irecord.pantheonsite.io/species-details?taxa_taxon_list_id=76635

If you are happy with it I can do a hotfix and push it to the main site.

**Comment by Sam-Amy** [comment]
Looks good to me @burkmarr, though the reference to records spanning more than one year seems only to relate to the chart. Could perhaps add 'and the map above' here, if not under the actual map?

**Comment by DavidRoy** [comment]
I think that's right as the map and other chart deal with the year-span records sensibly?

**Comment by Sam-Amy** [comment]
Ah yes I see, sorry, I misseunderstood that.

**Comment by DavidRoy** [comment]
I might have misunderstood too! @burkmarr to confirm

**Comment by burkmarr** [comment]
Yes the map chart deals with them.

The last chart - within year phenology - obviously relies on records with full dates that can be assigned to a given week. So temporally imprecise records always ignored. My own view is that this is self-evident and not worth an explanation. Also it is not possible to relate dots represented on the map to the within year phenology chart.

In contrast, I think the explanation is useful on the records by year chart because a user might see records represented on the hectad map and be able to discern a year for them, but notice that they are not represented on the records by year map (as was the case for the example given).

**Comment by burkmarr** [comment]
I've just realised that this change never made it through to the live website. I have now included in same branch that I'm using for https://github.com/BiologicalRecordsCentre/iRecord/issues/1527. If that change goes ahead, I will publish the two together. Otherwise I will publish this change on its own.

**Comment by burkmarr** [comment]
This is now fixed on live (and deployed as a hotfix to client_helpers.) @Sam-Amy - if you are happy with this, you can close this issue.
