### ISSUE TITLE
Update Woodland Trust boundaries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1443]
The Woodland Trust boundaries are used for WT's custom Explore page. They have supplied a new set of boundaries, which are saved in:
`W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\iRecord\Boundaries\Woodland Trust`

The new boundaries need to replace the existing set.

@burkmarr are you okay to get these imported (once the UKSI update is out of the way)? And if so is it worth you going through the process with myself, Sam and Robin, or is this best kept as a developer task?

**Comment by burkmarr** [comment]
@kitenetter - I intended to do this and document it for you, but as is often the case, there are a few issues to address first. I was going to update the boundaries via the upload shapefile feature of the warehouse interface and then delete any existing sites that weren't in the new list. 

Within a spatial data type (in this case _Woodland Trust site_ - type id 17546) the warehouse matches new geometry in the shapefile to existing sites in the DB by matching their names. The existing _Woodland Trust site_ locations in the warehouse (1049 of them) all have unique names - which is great. For example these are the existing names with 'Common Wood' in their name:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/9275178/266b4359-3837-40df-9603-98cb3bc5dd0e)

But in the new shapefile (1057 sites), there are many duplicate names:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/9275178/5c0e3829-58f2-409b-9cbc-3d10894bb635)

In the case of 'Common Wood', there are no matches for the existing site names suffixed with location.

I could delete all the existing sites and then import these new boundaries as new sites - then the duplicate names would not create a problem. But if the WT wanted to update smaller groups of sites in the future then the duplicate names could be an issue. So I don't know if you want to check this naming issue out with the WT before we proceed? I attach a list of existing names in case it's useful.

(btw - whichever route we take, there will be a lot of re-indexing of existing sample and occurrence cache records.)

[existing-wt-sites.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/12259258/existing-wt-sites.csv)

**Comment by kitenetter** [comment]
I will check with WT if there is an option to make the names unique.

Regarding the process generally, can @johnvanbreda advise if there are any other options we should look at for updating boundary layers:
- could/should we move to using some sort of unique ID for individual sites, to avoid problems with non-unique text strings?
- is there anything we can do to mitigate the amount of re-indexing, or is that just an unavoidable cost of all boundary changes?

**Comment by johnvanbreda** [comment]
The SHP uploader built into the warehouse needs a unique name because we often get SHP files with several polygons per site, so we need to combine them into a single site based on name. I would also suggest that having duplicate site names within the same layer will cause unhelpful confusion elsewhere in the system, so I would prefer to modify the SHP file first to make the names unique (e.g. adding Parish or VC name etc) before upload.

We could potentially alter the code to allow an option for the names to be considered unique based on the code field, rather than the name. It would help load the sites in correctly, but would still be confusing from the user perspective.

Re-indexing is inevitable if site boundaries are changed unfortunately.

**Comment by burkmarr** [comment]
@kitenetter - have you had any communication with WT re unique names for the woodlands?

**Comment by kitenetter** [comment]
@burkmarr yes I did, but I failed to pass it on, sorry - will forward the email to you.

**Comment by burkmarr** [comment]
@kitenetter. This is done now and all the re-indexing complete. I've documented the steps below, as discussed, but these kind of updates are probably best discussed on a case by case basis. Worth special consideration is the amount of spatial re-indexing required. Because there were only 1000 or so WT sites which are all relatively small, then relatively few occurrences/samples would be affected and I didn't worry about batching the update. But if we were updating VCs, for example, then the majority of occurrences/samples would be affected, so we would need to consider batching the updates into manageable chunks.

- In this case, WT had supplied us with a shapefile and a separate spreadsheet which resolved duplicate names. I used QGIS to update the shapefile in line with the spreadsheet. (Using the QGIS filter feature to limit the view to each name in question.)
- I then checked the shapefile to ensure that there were no remaining duplicate names. The way I did this was to use QGIS to save a copy of the shapefile as a CSV, then I opened the CSV in Excel and did a pivot table to count the number of occurrences of each name. There remained one instance where a name - _College Wood_ - was used by two features. I checked these features in QGIS - the woods were in the same general area (Oxfordhshire area) but were too far apart (c 20 km or so) to be different parts of the same wood, so I used QGIS to give these unique names. I did this based on the general pattern used by WT - adding a suffix with the name of the nearest settlement - _College Wood (Nash)_ and _College Wood (Woodcote)_. (If there had been lots of cases, I'd have suggested getting back to WT, but since there was only one I was content to do this myself.) Note that if the two sites had been close enough that they were clearly different parts of the same site, I would have instead merged the two features in QGIS to create a single multi-polygon feature.
- In QGIS I checked the coordinate reference system of the shapefile which was EPSG:3857 (WGS 84 Pseudo-Mercator) as this would be need later when uploading into the warehouse.
- I made a note of the number of features in the shapefile - 1062.
- I saved the shapefile from QGIS and then zipped up the various shapefile files into a single zipfile.
- I went to the Locations page on the warehouse website (https://warehouse1.indicia.org.uk/index.php/location) and used the controls at the foot of the page to select and upload the zip file.
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/9275178/dbb5d052-befa-4fac-86b6-794a2672b66c)
- In the form that appears, I filled in the necessary values:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/9275178/3fcf8a69-91c7-4d6b-8ee9-8a9367df8684)
- Note that it is important to ensure that the default website matches the existing value for the location type otherwise new features will be created instead of updating the existing ones.
- In the column-matching table, it is most important to select the correct shapefile attribute (_Column in DBF file_) to the _Name_ attribute as this is what the matching is done on. The existing WT features also have a _Code_ attribute corresponding to the values of the _manunit_ shapefile attribute, so I also mapped these (but Indicia does not match features based on this).
- I clicked the _Upload Data_ button. A bunch of messages appeared telling me where features had been uploaded or inserted.
- When uploaded through the website like this, Indicia automatically adds the work queue tasks to redo the spatial indexing for the inserted/updated features.
- Using the warehouse website, I checked the `location_type_id` for the _Woodland Trust site_ type - 17546 - as I would not need this in pgAdmin.
- Since the shapefile contained the latest _complete_ set of WT sites, any existing sites that weren't either updated or inserted during the operation just undertaken would actually need to be deleted, so I first needed to identify these in pgAdmin:
```SQL
select * from locations
where location_type_id = 17546
and deleted = false
and updated_on < '2023-09-12'
```
- This identified 36 features. If there had been only a handful, I could have noted their IDs and then deleted them from the warehouse interface which would have taken care of inserting the necessary tasks in the work queue to amend the spatial indexing of any occurrences/samples overlapping the deleted sites. However because there were a large number, I decided to do this via pgAdmin. First I updated the deleted flag for these records:
```SQL
update locations
set deleted = true, updated_by_id=<my_warehouse_id>, updated_on=now()
where id in (select id from locations
where location_type_id = 17546
and deleted = false
and updated_on < '2023-09-12')
```
- Then I inserted tasks into the work queue to take care of the indexing:
```SQL
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)  
select distinct 'task_spatial_index_builder_location_delete', 'location', id, 70, 2, now() 
from locations  
where id in (select id from locations
where location_type_id = 17546
and deleted = true
and updated_on > '2023-09-12')
```
- I checked the number of WT sites in the DB:
```SQL
select count(*) from locations
where location_type_id = 17546
and deleted = false
```
- This resulted in 1062 which matches the number of sites in the shapefile supplied by WT.

**Comment by kitenetter** [comment]
Thanks for documenting this @burkmarr. It looks like this update has also fixed the problem on the Woodland Trust Explore page, where the chosen site name was not matching up to the correct polygon - that seems to be working correctly now.

I will let WT know, and pass on the names for the two College Wood locations. Closing.
