### ISSUE TITLE
UKSI update: fungus getting included in moth verification filter

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1453]
Some moth verifiers use a filter for macro or micro species that we set up as a scratchpad. The scratchpad for macros has list id 3930.

Since the UKSI update, macro-moth verifiers are seeing records of the tar-spot fungus Rhytisma acerinum in the verification grid.

I can't see anything anomalous about the way that Rhytisma acerinum is stored in the warehouse.

I also can't see anything anomalous about the list in the scratchpad edit view. 

However, I did notice that all the scratchpads have an "Explore records" link, and it seems that for all scratchpads that link opens up a page that is showing all records, with no taxonomic filtering. E.g.:
https://irecord.org.uk/all-records?taxon_scratchpad_list_id=3930

So there are two possibly unrelated questions:
1. Why is Rhytisma acerinum being included in the macro-moth list?
2. Why are the scratchpad Explore links not doing any taxonomic filtering?

**Comment by johnvanbreda** [comment]
2 was simply a missing control on the Explore page that enables reading the scratchpad ID from the URL parameters.

1 was a lot more complex. The problem here stems from UKSI. There is a redundant entry in the ORGANISM_MASTER table "NBNORG0000085435" for "Rhytisma", which has the parent_key set to organism key NBNORG0000027799 which corresponds with Noctuidae. I think this entry is one of several "broken" entries that are effectively disabled in UKSI, but our code picks them up in case they get promoted or repaired by one of the continuous update operations and we don't actually have a specification for when they should be disabled.

I've fixed the parent for the redundant entry so I think it's now OK. Will email Chris about checking the parent of this particular ORGANISM_MASTER entry.

**Comment by johnvanbreda** [comment]
Closing as done.
