### ISSUE TITLE
Please pause vague Odonata records from BTO

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1455]
Please pause receiving Odonata records from BTO BirdTrack that compute to an Output Map Ref of a 100 km or 10 km grid square, pending further discussions. If this is not possible, e.g. (and this is speculation) because the OMR is only computed after the record is accepted, please pause receiving all records from this source.
Geographically vague records are reducing the quality of our data and, for various reasons, are easily accepted accidentally while thinking they are more precisely positioned observations. There are multiple problems with the current imports.
See also unresolved issues:  
- #1360 
- #1316

**Comment by johnvanbreda** [comment]
We have the following code running for the BTO imported Odonata data - the 3 outer if statements apply the following logic in order:
* If a grid reference provided with the record which is over 1km precision, then skip the record.
* If a point provided with unknown precision, then skip the record.
* If a point provided with precision > 1000 then annotate the record.

```php 
      if (!empty($observation['gridReference']) &&
        (($observation['projection'] = 'OSGB' && strlen($observation['gridReference']) < 6) ||
        ($observation['projection'] = 'OSGI' && strlen($observation['gridReference']) < 5))) {
        // Exclude if grid reference over 1km.
        return FALSE;
      }
      if (empty($observation['coordinateUncertaintyInMeters']) && empty($observation['gridReference'])) {
        // Exclude point data with unknown precision.
        return FALSE;
      }
      if (!empty($observation['coordinateUncertaintyInMeters']) && $observation['coordinateUncertaintyInMeters'] > 1000) {
        if (!empty($observation['occurrenceRemarks'])) {
          $observation['occurrenceRemarks'] .= "\n";
        }
        $observation['occurrenceRemarks'] .= "BTO Coordinate Uncertainty: $observation[coordinateUncertaintyInMeters]m!";
      }
```
So, shall I change the last IF statement so that if the precision of a point record is > 1000, then the record should be skipped? @kitenetter please confirm you are happy with this proposed change.

**Comment by kitenetter** [comment]
@johnvanbreda are we able to restrict this to Odonata records - I think so, since we are applying some custom filtering to this group already? If so I'm happy with this change as a stopgap measure while we try to address the underlying problems further with BTO.

(If it will apply to all taxon groups it is more problematic, but again I think we can live with it as a stopgap.)

@DavidHepper we are also intending to add an additional filter on the verification page to make it easier to include or exclude records of differing levels of precision. Will that help, or do you think your verifiers would still prefer not to see these records at all?

**Comment by DavidHepper** [comment]
There are valuable records in there somewhere. We don't want to exclude them for ever but to work out a way to store the more precise map reference, even if its accuracy is slightly spurious, and then allow them through. So whatever is done should not prevent these records from being imported later and if that means pausing _all_ Odonata from BTO then so be it.

**Comment by johnvanbreda** [comment]
@kitenetter please confirm if this change is still required as I know there have been more recent discussions - i.e. skip records of Odonata where the coordinate uncertainty > 1000?

**Comment by DavidHepper** [comment]
@kitenetter - have you passed on the spec we agreed? I need to issue a newsletter to my verifiers and would like an ETA for the reprocessing.

**Comment by kitenetter** [comment]
Currently being handled under #1597
