### ISSUE TITLE
UKSI update: moth scientific name missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1458]
In the warehouse we have the English names "Emperor" and "Emperor Moth" available, and each is linked to the scientific name "Saturnia pavonia". However, the scientific name has been marked in the warehouse as redundant, and I assume that is the reason why the scientific name has vanished from the data entry forms.

The redundant flag can be see via the taxon search:
http://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-key=&filter-key_type=org&filter-taxa_taxon_list_id=194114&filter-taxa_taxon_list_id%3Ataxon=Emperor

but I don't know what controls that flag - I can't see any setting for it on the taxon page:
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/194112

Also, can we make the English name "Emperor" unavailable for data entry, so that we use "Emperor Moth" (to avoid confusion with "Emperor Dragonfly").

[Both English and scientific names for this moth are missing from the iRecord app, will add an issue for that separately.]

**Comment by JimBacon** [comment]
Investigation is needed soon, since this may be the tip of the iceberg. There may be a query to run which would fix this and any other similar problems, saving you the trouble.

If this is a much recorded species, and it is causing bother, you could tick the box now. There might be a good reason why it is disabled but I haven't seen a hint of it yet.

**Comment by johnvanbreda** [comment]
Some background - 
* The "redundant" field on the taxon search is just mapped to the inverse of the allow data entry flag so this indicates that allow data entry is off. 
* Allow data entry can end up being set to false for several reasons:
  * The taxon is edited via the warehouse UI and the checkbox is unchecked.
  * When the UKSI sync scripts run, if the taxon TVK existed in the warehouse UKSI list copy previously but can no longer be found, then it will either get deleted (if there are zero records) or flagged as allow data entry=false (if there are records).
  * If the UKSI data for the name has any of the following, then it will be flagged as allow data entry false: nameserver.deleted_date is set, organism_master.deleted_date is set, organism_master.redundant_flag is set, taxon_version.date_to is set). You can see the logic for this in the all_names query at https://indicia-docs.readthedocs.io/en/latest/administrating/warehouse/importing-uksi.html.
* Recently, the UKSI sync script was modified so that redundant names are pulled in from UKSI (as described in the bullet immediately above) whereas formerly they were skipped unless already imported. This is because in the new continuous update approach, we might get an instruction to promote a redundant name so it is no longer redundant, so we have to keep a copy even if not currently active. So I am not surprised there are 17K names with allow data entry = false and I don't think this is a sign of a problem.
* The outputs of each of the queries used to extract data from UKSI are left in the database schema called uksi. So I can run this query to see what information was received for S. pavonia: `select * from uksi.all_names where item_name='Saturnia pavonia'`. I can see that the redundant flag was false which means the taxon should be available. However allow data entry is false which means it has been set to a different state than expected from the UKSI data. Interestingly the taxa_taxon_list record has an updated_on value that indicates it was changed the day after the UKSI update, not during the update itself. 

So, I think this is possibly just a manually edited mistake and @kitenetter, yes, it should be find for you to check the allow data entry flag.

**Comment by johnvanbreda** [comment]
@JimBacon I'll see if I can work out a query that finds taxon names where allow data entry=false but UKSI thinks they should be redundant=false. Especially any edited around the same time as S. pavonia.

**Comment by johnvanbreda** [comment]
Good news. If I query for names where UKSI indicates that a name should be enabled but the warehouse indicates otherwise, then I get 26K records. But if I modify this query to exclude rows where the TVK exists in the database with allow data entry enabled (i.e. there is a second, good copy of the record so the UKSI sync script has re-instated the name at some point then there are only 3 rows returned:

```sql
select an.organism_key, an.recommended_taxon_version_key, an.input_taxon_version_key, an.item_name, cttl.id, cttl.cache_updated_on 
from uksi.all_names an
join cache_taxa_Taxon_lists cttl on cttl.search_code=an.input_taxon_Version_key and cttl.allow_data_entry=false
left join cache_taxa_taxon_lists cttl2 on cttl2.search_code=an.input_taxon_Version_key and cttl2.allow_data_entry=true
where an.redundant=false
and cttl2.id is null
```
returns
```
"organism_key"	"recommended_taxon_version_key"	"input_taxon_version_key"	"item_name"	"id" "cache_updated_on"
"NBNORG0000027071"	"NBNSYS0000156325"	"NBNSYS0000156325"	"Saturnia pavonia"	194112	"2023-04-13 21:16:10.735652"
"NBNORG0000091514"	"NHMSYS0021241572"	"NBNSYS0000022498"	"Ectopsocus briggsi"	611902	"2023-04-14 12:45:35.660472"
"NBNORG0000091514"	"NHMSYS0021241572"	"NBNSYS0000022498"	"Ectopsocus briggsi"	312433	"2023-04-14 12:45:35.636856"
```

I've checked the updated_on value in the taxa_taxon_lists table itself (not the cache) and this confirms that all 3 edits were made on the 13th or 14th, i.e. after the UKSI update rather than during.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda 

The change to E. briggsi was done by me in response to a request from the recording scheme, so it is correct that data entry is disallowed. (Although I believe UKSI has now updated the name attribute to reflect that this is now an aggregate name, so our version of this one may be out of line with UKSI.)

I have no memory of editing S. pavonia.

It is pretty much peak season for S. pavonia so I will tick the box to allow data entry.

Will that automatically feed through to the app or does anything else need to be done for the app?

**Comment by johnvanbreda** [comment]
@kitenetter I think @kazlauskis can pull the changes into the app but he needs to trigger the process manually, I may be wrong though. 
The Elasticsearch lookup tables shouldn't be affected as they are not concerned with data entry.

**Comment by kitenetter** [comment]
@johnvanbreda I have now ticked the data entry box for S. pavonia. However, I also notice that there are no Pantheon attributes set up for this taxon, and I don't think that is correct - I thought all the resident macro-moths should have Pantheon attributes? Has this taxon somehow got over-written?
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/194112

**Comment by robin-hutchinson** [comment]
In case this is relevant for this issue - David found that some preferred names are listed multiple times in cache_taxa_taxon_lists (specifically Acronicta cinerea) - I've found that the duplication comes from each of the entries having a different organism key, which I think comes from the junior synonyms of the name (the organism keys were re-assigned when the names were merged), but only one organism key is allow_data_entry = true:

select distinct cttl.family_taxon, cttl.taxon,  cttl.search_code as name_tvk, cttl.external_key as rtvk, cttl.default_common_name common_name, t.organism_key, cttl.preferred, cttl.allow_data_entry
from cache_taxa_taxon_lists cttl
join taxa t 
on cttl.taxon_id = t.id
where taxon_list_id=15
and cttl.language = 'Latin'
and cttl.taxon_group_id = 114
and t.organism_key in ('NBNORG0000117328', 'NBNORG0000057281', 'NBNORG0000059421', 'NBNORG0000057282')

I think this would probably account for a lot of the redundant names?

**Comment by kitenetter** [comment]
I have marked the vernacular "Emperor" as allow data entry = FALSE.

The Access database for Pantheon version 3.7.6 does not appear to contain any trait data for Saturnia pavonia (which surprises me) so it seems likely that there is no issue here. Closing.
