### ISSUE TITLE
Have the record cleaner checks stalled?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1463]
I'm not seeing any record cleaner checks being applied to records added from Sunday evening (30 April) onwards. Has something stalled?

**Comment by BirenRathod** [comment]
@kitenetter I have added comments here -> https://github.com/BiologicalRecordsCentre/ABLE/issues/511

**Comment by BirenRathod** [comment]
@kitenetter During scheduled tasks run, I found these alerts in the log files -> 1. alert: Unable to save ecobat sample: {"sample:entered_sref":"The spatial reference is not recognised."} 
2. alert: Unable to save ecobat sample: {"sample:date_start":"Please specify a date that is not in the future."} 
which took longer to finish schedule task process.

Any idea?

**Comment by johnvanbreda** [comment]
@BirenRathod although the Ecobat messages do indicate some invalid data that is not being processed which should be tidied up at some point, this is not the source of the slow performance. The cache builder module is causing the scheduled tasks to take a long time and I suspect this is because of the problem with spatial indexing blocking the other process mentioned elsewhere. Hopefully it will return to normal later today as the spatial indexing issue has been fixed.

**Comment by johnvanbreda** [comment]
> Thanks @johnvanbreda. is that ok if start the scheduled_task now?

Already done...

**Comment by kitenetter** [comment]
Record cleaner checks seem to be running slowly again at the moment, looks like none have been applied for 30 hours or so.

**Comment by kitenetter** [comment]
The checks are up-to-date again now, so I think things were just running slowly over the weekend. Closing again.
