### ISSUE TITLE
Limit to total overlapping sites on "My Sites" page?

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1470]
One user has reported an SQL message showing that the My Sites page is timing out before loading their list of sites, I can recreate the issue when masquerading as them (user 69434):

![Screenshot (59)](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/367a9276-a266-465b-a816-622bf11a1ee4)

I can access the My Sites page through my own account so I think the issue might be the amount of information to load on their page. According to their message, they have 20 sites that share a border, and also another site that overlaps all of these (I'm not sure if they also have other sites that are in a different location). Is there a limit (that we know about) to the number of sites that can be created through one iRecord account?

**Comment by johnvanbreda** [comment]
I don't think there is any issue with the site boundaries overlapping. This is simply an issue of data scale - as the size of the database has grown, the number of records checked to see if they overlap each site boundary means the query performance is no longer acceptable.
Options are:
1. Remove the count of records/species per site (easy and the query will then be very fast).
2. Add an index on cache_occurrences_functional created_by_id and public_geom (may not be possible due to this requiring a combination of spatial and normal index, will make the query faster but also has an overhead of maintaining the index).
3. Write a bit of custom code that loads the sites list, then queries each boundary to count records and species using Elasticsearch (should be reasonably quick but depends on the ES server not being overloaded, will take a few hours to write the code).

**Comment by kitenetter** [comment]
@johnvanbreda I would favour option 1 in the short term - shame to lose the counts but it's a lot better than not being able to access the page at all!

Option 3 might be worth exploring in the longer term.

**Comment by johnvanbreda** [comment]
Done
