### ISSUE TITLE
Add Creative Commons licenses to iRecord

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#15]
Implement Creative Commons licensing within iRecord, for clarity and to facilitate data- and photo-sharing with NBN. 

Questions:
- How has this been done in Consultants Portal (e.g. which CC licences are offered)?
- Should we offer separate licencing of records and photos (if we don't is there a risk that some recorders will be unwilling to add photos to iRecord with their records)?

Terms of Use of need reviewing alongside this.

**Comment by johnvanbreda** [comment]
See https://github.com/Indicia-Team/warehouse/issues/15 for a discussion of licencing support on the warehouse and Constultants Portal. 

In summary, we already have an implementation of CC licencing in the code so just need to configure it to appear on iRecord. User's would then have an option to opt-in to a CC licence on their profile and this would then apply to all their existing records. David had some concerns about allowing choice of different licences on a per user/record level (which this allows) because of the implications for datasets on the Gateway so it might be that we at least encourage people towards a single license.

On the Consultants Portal things are a bit different as the license is applied per-project not by the user.

David and I both agreed that the photo and record should be licensed as one. I'd prefer to keep things simple as possible.

**Comment by DavidRoy** [comment]
Thanks for reminding me about this previous (lengthy!) discussion.  To summarise the iRecord perspective:

1. We set a default licence for iRecord as CC0
2. Single licence for records **and** photos
3. Individual users can set their own licence which differs from the default, but we advise against doing this
4. We export data to the NBN Gateway/ALS based on dividing up records into CC0, CC-BY, CC-NC etc

John - can you give an estimate on the effort to implement this and add it to the iRecord priorities speadsheet

**Comment by charlesroper** [comment]
Has any progress been made with this? What's the current status? For the FSC data, we'd certainly like apply either CC0 or CC-BY to data in our activities.

**Comment by johnvanbreda** [comment]
There is a module available for Drupal 7 which allows users to pick a license and it operates as described above. However I think there has been further discussion on forcing iRecord to a particular CC licence due to the way the Atlas works - we could fairly easily do this I think so this is a "political" rather than a "technical" issue. @kitenetter or @DavidRoy may have more to add.

**Comment by kitenetter** [comment]
This topic needs some further thought and development to ensure that the implications of applying record-level licences are properly worked through, e.g. for data that is downloaded from iRecord and managed by schemes passing it to NBN. Having discussed with @DavidRoy we think this is not currently a priority but likely to come back into the frame in future.

**Comment by burkmarr** [comment]
Discussed at planning meeting on 24/07/2019. We will implement licensing on photos only and publish new T&Cs. Opened a new issue for this: #638
