### ISSUE TITLE
Incorrect linking for taxon

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1506]
This applies to Welsh Chafer, Hoplia philanthus. 

The name "Hoplia philanthus" does not appear in the autocomplete taxon box when using an "Add a list of records form". However, it does appear if using the "Enter a casual record form".

On both forms it is possible to enter "Welsh Chafer".

If you go to the [species details page](https://irecord.org.uk/species-details) you can find "Hoplia philanthus" in the autocomplete taxon box. However, the resulting page links to species name "Unknown" and appears to show a map of all taxa:
https://irecord.org.uk/species-details?taxa_taxon_list_id=217186

I cannot find Hoplia philanthus via the warehouse interface. And in the warehouse, genus "Hoplia" has no children listed:
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/202029

I don't understand what is causing this but it appears that a link. and/or a taxon name, has become lost.

**Comment by johnvanbreda** [comment]
I found that the preferred flag had been removed from the preferred version of the name - presumably as an attempt to clean up one of the other taxonomy issues. I reset the data to the same as provided in the last full UKSI update using the following:
```sql
update taxa_taxon_lists set allow_data_entry=true where id=217185;
update taxa_taxon_lists set preferred=true where id=217186;
-- Ensure the names update in cache tables.
update taxa_taxon_lists set updated_on=now() where taxon_meaning_id=92104
```

**Comment by burkmarr** [comment]
@johnvanbreda this was reset for https://github.com/BiologicalRecordsCentre/iRecord/issues/1476 because the search_code is different from the external_key. I updated 385 USKI ttl entries identified by this criterion. Those ttl entries are identified in an intermediate table - iss_1476_affected_ttl - which I haven't yet deleted. Was there something wrong with our logic in identifying these taxa to reset those flags?

**Comment by burkmarr** [comment]
Is this what you mean for the first part @johnvanbreda?
```sql
select taxon_meaning_id, count(*)
from taxa_taxon_lists
group by taxon_meaning_id, preferred, taxon_list_id, deleted
having taxon_list_id = 15
and preferred = true
and deleted = false
and count(*) <> 1
```
It only suggests a couple of problems:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/9275178/1774175f-cdd2-43e0-866e-d87a275f3663)

**Comment by burkmarr** [comment]
@johnvanbreda - I've realised that the query above is not picking up those cases where a taxon concept has no preferred entry in taxa_taxon_lists. This query shows that there are 283 of those:
```sql
select distinct taxon_meaning_id from taxa_taxon_lists
where taxon_meaning_id not in(
	select distinct taxon_meaning_id from taxa_taxon_lists
	where taxon_list_id = 15
	and deleted = false
	and preferred= true
)
and deleted = false
and taxon_list_id = 15
```
I'm not sure on where to go with this though.

**Comment by johnvanbreda** [comment]
I've tried a different approach - this came up with 285 rows (placed into a temp table for ease in the next set of queries):
```sql
select taxon_meaning_id, sum(case preferred when true then 1 else 0 end)
into temporary broke_meanings
from taxa_Taxon_lists 
where deleted=false
and taxon_list_id=15
group by taxon_meaning_id
having sum(case preferred when true then 1 else 0 end)<>1;
```

I then used this table to create another table with suggested taxa taxon list IDs to set to preferred, based on the external key and search code matching. This finds 84 meanings that can be fixed in this way:
```sql
select ttl.taxon_meaning_id, ttl.id 
into temporary suggested_preferred
from taxa_taxon_lists ttl
join taxa t on t.id=ttl.taxon_id and t.deleted=false and t.search_code=t.external_key
where ttl.taxon_meaning_id in (
	select taxon_meaning_id from broke_meanings
)
and ttl.taxon_list_id=15;
```

Here's a script to apply the suggested fixes (which I've not run yet):
```sql
update taxa_taxon_lists 
set preferred=true 
where id in (select id from suggested_preferred);

-- Set updated metadata on the others so they pick up the new preferred name.
update taxa_taxon_lists 
set updated_on=now(), updated_by_id=3 /* your user ID */
where taxon_meaning_id in (select taxon_meaning_id from suggested_preferred);
```

Here's a query that looks for any left over meanings from the broke table which are not covered by the suggested fixes, where the taxon data appear to be valid (i.e. data entry allowed so not an old expired taxon, and the data aren't deleted). There are 161 still to fix.
```sql
select ttl.id, ttl.taxon_meaning_id, t.taxon 
from taxa_taxon_lists ttl 
join taxa t on t.id=ttl.taxon_id and t.deleted=false
where ttl.taxon_meaning_id in (select taxon_meaning_id from broke_meanings)
and ttl.taxon_meaning_id not in (select taxon_meaning_id from suggested_preferred)
and ttl.allow_data_entry=true 
and ttl.taxon_list_id=15 
and ttl.deleted=false
```

Looking at the data for some of these, it appears they are cases where the taxon is shared with a child list of list 15 and the preferred name only exists in the child list, not list 15 itself. This needs more investigation (probably a problem in the UKSI sync handling of child lists).

Finally I guess we should rebuilt the taxa.yml lookup data for Logstash.

**Comment by burkmarr** [comment]
Thanks for the analysis @johnvanbreda. Is the part you marked with a comment (set updated metadata...) there to trigger an update of the cache_taxa_taxon_lists table?

Shall I go ahead and run those queries to update the ones we can and do the necessary with logstash?

**Comment by johnvanbreda** [comment]
@burkmarr yes, if you agree with the queries then you may as well run them. The "set updated metadata" is indeed to ensure the cache tables are updated. I suppose in theory after the taxa.yml file is updated, requeuing any records for the changed taxa_taxon_list_ids for update in Elasticsearch could be of benefit. This can be done by running a query like the following, as simply updating the record with no change will fire the trigger that updates the tracking sequence number:
```sql
update cache_occurrences_functional 
set website_id=website_id
where taxon_meaning_id in (select taxon_meaning_id from suggested_preferred)
```

**Comment by burkmarr** [comment]
I've run the SQL to update those that we can currently fix, updated ES taxa.yml, restarted logstash and finally updated cache_occurrences_functional as suggested above.
