### ISSUE TITLE
Question: iNat edits

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1519]
I've been asked to clarify how edits in iNat link back to iRecord.

1. For records that have not been verified yet, I'm pretty certain that if the identification or location details are changed on iNat, those changes will be passed into iRecord and the previous version of the record will be overwritten - is that correct?
2. What happens if information is added to the iNat 'annotations', e.g. to add a sex or stage term to an iNat record - will that also be seen as an edit and therefore the new annotation data will be brought into iRecord?
3. The above applies only to records that have not been verified in iRecord. Once a record is verified it becomes locked, and any subsequent changes in iNat will not over-write the iRecord version. However, what happens if a record is marked in iRecord as queried (rather than verified) - does that also result in the record becoming locked?

**Comment by johnvanbreda** [comment]
@kitenetter 
To answer 1 and 2, we use the iNat API's updated_since field to filter for records updated since we last requested the data. If we get a new copy of an existing record, then we update it. So in theory at least, the answer to both these questions is yes, as long as the iNat updated_since filter is doing as I expect (I've no reason to believe otherwise).

The only state that locks the record is record_status=V, i.e. the record is accepted in some form. So a query or rejection should not prevent the record being overwritten.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda that is good to know. Closing.
