### ISSUE TITLE
Performance - only rebuild the Stats views overnight?

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#152]
Enhancement suggestion:
Views/reports under the **Summarise menu** are slow to appear. They only need to be rebuilt once per day so long as text at the top warns that they may be out of date by 24hr. This change would thereby reduce the load on the iRecord server.

**Comment by johnvanbreda** [comment]
Removing the Quick Win? label. This isn't ideally tackled just by changing caching settings as the reports driving this have not been looked at for a long time. Instead I'd suggest that the report selector prebuilt form has an option added to allow it to switch to using uniquely indexed location layers (such as the vice county one). Rather than using the index_locations_samples table to do the counts, it can then do the count using cache_occurrences_functional.location_id_vice_county. Other similar improvements should be made to the other reports.

**Comment by DavidHepper** [comment]
Timeouts are still an issue. I see cache_occurrences_functional is being discussed at #509 and wonder whether the Stats views could be reviewed again.

**Comment by johnvanbreda** [comment]
The Stats views are a good candidate for a move to ElasticSearch. Which particular stats would you be keen to see first @DavidHepper?

**Comment by DavidHepper** [comment]
Good! **Verifiers Summary** would be the most helpful one.
And a similar one to show the number of Unreviewed records (in our case by VC) would be enormously helpful in working out who needs assistance / nagging.

**Comment by kitenetter** [comment]
I think this has been addressed with the ES report pages. Closing.
