### ISSUE TITLE
Change recorder name on past records

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1520]
A user (ID 41908) who has changed their name has requested that all old records be changed to the new name. They are also high up on the leaderboard and concerned that all their records remain together there, and the new name they are now using is of course starting a new leaderboard entry.

I have checked all records to see if any were entered that have a completely different recorder name, i.e. anyone else's records; there were none, and the only names are variations on the old name, and very recent records under the new name. The file attached here lists all record IDs not made under the new name, and therefore requiring editing, retrieved with:

SELECT o.id
FROM cache_samples_functional s
JOIN cache_samples_nonfunctional snf ON s.id = snf.id
JOIN cache_occurrences_functional o ON o.sample_id = s.id
JOIN cache_taxa_taxon_lists cttl ON o.taxa_taxon_list_id = cttl.id
WHERE s.created_by_id = 41908
AND snf.recorders not like *new name here*

- Would it be possible please for all record IDs in the attached (n = 7083) to have recorder name edited to the one I will email you with shortly @johnvanbreda (or see recent records)? 
- [records for name change_ID_41908.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/11957863/records.for.name.change_ID_41908.csv)
- It is important that the updates should not result in the records being triggered for re-verification though - is it possible to do this so that if they have been verified they remain so (perhaps you omit updating the "last_edited_on" field)?

**Comment by Sam-Amy** [comment]
Hi @johnvanbreda, will it be possible to make this change soon please? I'll email you the name again. The recorder is very keen for this to happen asap. Thanks.

**Comment by johnvanbreda** [comment]
That's done - it may take an hour or so for changes to ripple through.

**Comment by Sam-Amy** [comment]
Great, thanks John

**Comment by Sam-Amy** [comment]
Still seem to be changes pending? Here is an updated list of records to change to the name emailed. Thanks.
[ID41908_name_change_2.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/14922309/ID41908_name_change_2.csv)

**Comment by johnvanbreda** [comment]
Hi @Sam-Amy, I'm not working on the basis of updating against IDs from a CSV file, mainly because the raw data would still exist in the system somewhere and would then overwrite the reporting output values if that record were ever updated, resetting the value to the old one. Instead I've been trying to track down the raw data for that user ID and modify it, then refresh the reporting output data. I've just searched again and corrected ~550 samples with a first name and surname attribute, so hopefully it will be sorted now.

**Comment by Sam-Amy** [comment]
OK, thanks, that's great. There are now no wrong names but
7,806 records where recorders format = surname, firstname
138 records where recorders format = firstname surname

The latter are the newest ones from apps. Do you know what they would need to do to ensure any future records from the app have recorders in the format 'surname, firstname'? Then they could manually edit those last 138 if they really want everything to appear togethr in the overal and app league tables.

**Comment by johnvanbreda** [comment]
Yes, that's a wider issue though - the app names are not consistent with the default behaviour of the warehouse. We should either change the app or change everything else, but I think that needs feedback from @kitenetter as to which is most appropriate. Changing to match the app may be a fair bit of work.

**Comment by Sam-Amy** [comment]
Ah yes, I can see various issues about this now i.e.

[https://github.com/BiologicalRecordsCentre/iRecord/issues/428](https://github.com/BiologicalRecordsCentre/iRecord/issues/428)
[https://github.com/BiologicalRecordsCentre/iRecord/issues/468](https://github.com/BiologicalRecordsCentre/iRecord/issues/468)

**Comment by kitenetter** [comment]
For some time I had managed to persuade the app to use the same name format for my own records as the website does. But I see that the app behaviour seems to have changed again. My records up to the end of 2023 are showing as recorder "Harvey. Martin C." (which matches the website), but since the beginning of 2024 it is using "Martin C. Harvey". I don't know why that has changed. Need some more info from Karolis about how the app generates recorder names.
