### ISSUE TITLE
LNHS boundary

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1531]
London Nat Hist Soc have requested that we add their boundary to iRecord to allow filtering and downloading. As discussed, we intend to add this to the warehouse as a non-indexed boundary, with location type “Miscellaneous boundaries”.

LNHS do not have a GIS layer, but the boundary is a 20-mile (32 km) radius based on St Paul's Cathedral (TQ32048114).

**Comment by burkmarr** [comment]
I've added the LNHS boundary to the Miscellaneous boundaries on the warehouse. It appears in the dropdown list when creating a filter in iRecord and is selectable. However, on applying the filter there is an ES error. I wondered if the location needed to be added to the ES locations.yml file, but the query to set that up suggests that this is only done for indexed location types. Also there is no trace of Kew Wakehurst (which also has a type of Miscellaneous boundary) in the locations.yml file (in GitHub) and filtering against that works fine. What step am I missing here @johnvanbreda?

**Comment by johnvanbreda** [comment]
The error here is logged in the warehouse logs - it is "Provided shape has duplicate consecutive coordinates". Can the boundary geometry be tidied up using QGIS or similar?

The locations.yml file is used to provide lookup data for any locations that may get indexed. I suspect it has not been updated - see https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/docs/locations-update-detail.md for notes.

**Comment by burkmarr** [comment]
Thanks John. I generated the boundary in QGIS by buffering a point, but there were indeed duplicate coordinates (start & end), so I modified the geometry and re-uploaded. Now it is working. @kitenetter - the name of the boundary is _LNHS boundary_.

**Comment by burkmarr** [comment]
btw @johnvanbreda - would you like me to update the ES locations.yml?

**Comment by burkmarr** [comment]
@johnvanbreda - I've regenerated the locations.yml, pulled to ES server and restarted logstash. The only changes were a name change to one country (St Helena) and the addition of the biogeographical regions (which I added a few months ago for the eBMS verification rules). I incremented the cache_occurrences_functional tracking value for all records with one of the affected locations in their location_ids. That amounted to just under 200,000 records which will have been mainly eBMS records because spatial indexing for biogeographical regions is limited to the eBMS datasets.
