### ISSUE TITLE
Allow users to reassign records to activities

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1533]
We get occasional requests for records to be added to, or removed from, activities, usually because the user forgot to link them in the first place, or wasn't aware that an appropriate activity existed. E.g. #1469 

Feature request: provide function for user to select a set of records and assign them to a group_id, or remove a group_id from them.

**Comment by kitenetter** [comment]
Being tackled via NCEA. Closing.

**Comment by kitenetter** [comment]
@johnvanbreda were we able to tackle this as part of previous NCEA work? I have another request to link a set of records to an activity, and there are one or two similar issues still open. Is a tool to enable this likely to be available soon or do we need to ask you to do a database update in the short term?

**Comment by johnvanbreda** [comment]
I don't think there was an issue for this in the NCEA project so it wasn't picked up. An easy way to approach this might be to update the bulk editor tool (also developed for NCEA, but not released to live) so that it allows the activity to be altered.

In the short term a manual update may be the simplest approach.

**Comment by kitenetter** [comment]
Agree that this would be a useful addition to the bulk editor tool. Will keep it open as a new feature request.
