### ISSUE TITLE
Could blurring by a verifier avoid the need for redetermination

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1590]
If a verifier blurs the location of a sensitive record, the record has to be reverified in order for those changes to be implemented. This two step process seems cumbersome and is not obvious. If this second step is missed record locations may still be publically apparent even though steps have been taken to hide it. If blurring is carried out by a verifier could this be accepted by the system immediately?

**Comment by kitenetter** [comment]
@Sam-Amy can you explain the context, is this for records where the recorder did not think they were sensitive but the verifier wishes to hide the location? And that the verifier is doing this by editing the record? That's not a situation I've encountered before. I wouldn't expect the record to need to be re-verified in order to apply the blur, I would expect that to happen as soon as the record is edited (give or take the time needed to refresh the elastic data). But all edited records then need to be re-verified.

**Comment by Sam-Amy** [comment]
Thanks Martin
