### ISSUE TITLE
User bulk record update - location

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1594]
Could the records in the file below all be updated so that the location name is "Backgarden Marehay" and the grid reference is SK39924906, please?

Similar request to https://github.com/BiologicalRecordsCentre/iRecord/issues/1538 and https://github.com/BiologicalRecordsCentre/iRecord/issues/1469

[Records Update SK39924906 Backgarden Marehay.csv](https://github.com/BiologicalRecordsCentre/iRecord/files/13489822/Records.Update.SK39924906.Backgarden.Marehay.csv)

**Comment by kitenetter** [comment]
@robin-hutchinson it is possible to do these sort of updates via the spreadsheet importer, as long as we know exactly which sample IDs to apply them to. Can talk you through it via Teams if you wish.

**Comment by robin-hutchinson** [comment]
That would be great, thanks!

**Comment by DavidHepper** [comment]
Could we have a joint session on Update Imports, please? I need to fix a large block but am stuck because it seems to need a Sample ID before it will match on Occurrence ID key. But the downloads from iR used to obtain the Occurrence Key don't seem to contain this Sample ID.
Also, it's confusing that the field names in the Import and Export have different names but I can live with that.
Finally, this feature isn't included in the Guidance doc version 3.2.
(I've recommended to my verifiers not to use Update imports.)

**Comment by kitenetter** [comment]
Currently waiting on UKCEH IT to provide access to the Indicia database. Will revisit in January.

**Comment by DavidHepper** [comment]
Thanks. I have an urgent need to update a large block of records that were imported last Jan (2023) before updating NBN from iRecord.

**Comment by DavidHepper** [comment]
Bump. I don't want to have to ask for a large deletion.
(Also, is it possible to clear a field to blank or null using Update?)

**Comment by kitenetter** [comment]
@DavidHepper I have been testing the imports linked to existing sample and occurrence IDs, and have hit problems, so it looks like this functionality will require maintenance work before it can be used. Which means that the only options for bulk updates at the moment is for you to specify which records need to be changed in which way, and for us to request one of the development team to do a database update.

We are planning to do some work on record editing facilities later this year but I don't think we'll be able to address this in the immediate future (i.e. it will be months rather than weeks).

**Comment by DavidHepper** [comment]
Thanks. Update-Import is a potentially useful feature but I can see that it has potential to cause trouble in each of coding, testing and use. I suggest removing it.

If an update-import requires a Sample ID then I wouldn't be able to use this at present because the necessary _downloads_ for constructing the sheet only include Sample Method and Sample Comment. And then there are the missing fields: #1608.

Some while ago there was talk of being able to reverse (delete) a whole spreadsheet import. This ought to be easier to code and test so I wonder whether implementing this would be a better use of resources.

**Comment by kitenetter** [comment]
The original request to update a set of grid refs and location names has now been completed via an import linked to the occurrence IDs. I'm closing this issue, but realise that there are wider questions over how this process works that we will need to come back to.
