### ISSUE TITLE
Birdtrack: mapping of output grid ref

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1598]
This change applies to the mapping of the currently selected record.

The pinpoint marker will be removed (we may need to adjust the line thickness for records that have a small radius of uncertainty in order to ensure visibility).

A radius will be displayed that shows the coordinate uncertainty.

A grid square will be displayed that shows the output grid ref.

Related to #1597 

@DavidHepper

**Comment by johnvanbreda** [comment]
Now done. The full precision geom is coloured red (including the radius if imprecise) and a blue square is added showing the public geometry if sensitive. I've also added a "map legend" note to the details when this happens so it is clear.

**Comment by DavidHepper** [comment]
Thanks, John. This works for most e.g. 34432847 but using the same shade of red for the full precision geom as for the shaded disc beneath causes trouble for common species when the default 'Grid map of currently selected species' is ticked: it's invisible against solid red. Random example: 34445148 fails to show NR73768529. 
Could the underlying disc be graded to a maximum opacity of 70% instead of the current 100%? 
Otherwise I'll have to advise verifiers to select the Heat map option (with a mouse move and another two clicks) instead - after every refresh, as the setting isn't remembered.
