### ISSUE TITLE
Unexpected Value Exception error

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/iRecord#1609]
Every time iRecord website updated, it generates this error -> UnexpectedValueException: base:Downloads has no corresponding route. in Drupal\Core\Url->getRouteName() (line 567 of /code/web/core/lib/Drupal/Core/Url.php). 

After that, the home page doesn't display. It works after clearing the cache of the Drupal by using "Flush all caches."

@johnvanbreda is it related to Downloads?
See this-> https://irecord.org.uk/admin/reports/dblog/event/269 event for more info.

**Comment by johnvanbreda** [comment]
I think this is not caused by Indicia code. It's possibly the routing in Drupal's menu system for the menu item that points to the Downloads page, but this is handled within the Main Menu not Indicia. Looking at the config, the Download records page doesn't create a menu item via the Edit tab - instead the menu item must have been manually added to the main menu and just pointed to the /downloads path. We could try adding the menu item via the node's Edit tab and swapping out the existing menu item to see if that fixes it. 

Does the test iRecord instance also show this problem? If so I could try to fix the menus on that instance first to see if it makes a difference (plus plan the most efficient way to swap the menus over).

**Comment by BirenRathod** [comment]
@johnvanbreda Yes, this also shows on test iRecord. I just updated the latest iForm code, so you can see that. I haven't cleared the cache on the test site yet, so you don't see the home page. but you can access the site through the admin page once logged in. Also, I haven't updated the code on the live iRecord site yet.

**Comment by johnvanbreda** [comment]
Thanks @BirenRathod. I've tried out my proposed fix (making the download records page have a menu item created using the option on its Edit tab, rather than a manually created link on the menu list terms page) and that has fixed the test site. However changing the menu may have cleared whatever was broken in the cache so it's hard to be sure if this is a genuine fix. I've done the same on live iRecord so hopefully now fixed. Please can you check next time you do an upgrade?

**Comment by BirenRathod** [comment]
@johnvanbreda I will do when I do next update.

**Comment by BirenRathod** [comment]
@johnvanbreda This works now after I have done an update from upstream. so ok to close.
