### ISSUE TITLE
Enhancement: bulk Delete of records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#163]
It would be most useful to allow bulk delete of records. This is especially the case where an Import is found to have contained duff data. 
Ideally, the import should have been tested with a representative handful of records before a large spreadsheet is imported so that this requirement does not arise. This doesn't always happen.

Clearly, access control on this feature would have to be tight.
An obvious idea for implementation would be to allow selection of multiple records in the grid and then a single Delete instead of the current record-by-record method.

There is a discussion of this feature for iRecord Apps > http://www.brc.ac.uk/irecord/node/3781

**Comment by kazlauskis** [comment]
I double this. When testing stuff bulk delete would be useful. I would say that other actions like changing date, location name, recorder names etc to multiple records at the same time could be potentially useful to others.

**Comment by BUDDBILL** [comment]
I support this, but it must be available in Explore as well as Verify. I recently imported records of 'Emperor' which were interpreted as 'Emperor moth' instead of 'Emperor Dragonfly' - because they are not in the same taxon that I have verify rights for, I can't see them in Verify. This also raises the question of why the Import process didn't flag up an error when an incomplete Common name had multiple matches against a full Common name.

**Comment by johnvanbreda** [comment]
@BUDDBILL unfortunately "Emperor" is given as a complete common name for the moth but not the dragonfly in UKSI, explaining why the import succeeded against the wrong taxon.

So the requirement is:
1) On the verification page, change "Review tick list" button to "Select multiple records". When this option is enabled, as well as the existing verification buttons, add a Delete button with an "are you sure" confirmation.
2) On Explore my records, at the bottom of the grid, add a button "Select multiple records". When pressed, tickboxes appear in the grid by each record ID. When some are ticked, all ticked records will highlight on the map and a "delete ticked records" option is available.

**Comment by kitenetter** [comment]
@johnvanbreda I agree with your requirement 2, that would be very useful. I'm wary of requirement 1 though - I'm not sure the original request from @DavidHepper was to be able to delete other people's records? And even if it was I think that opens up some tricky questions around data ownership. So for me the requirement is only to have editing tools for one's own records, which are presumably best implemented through Explore rather than through Verify.

The most frequent request for bulk deletes comes from people who upload entire sets of data and then realise that something has gone wrong. These uploads can be very large, in which case having to tick each individual record before deletion is a big task. If we were able to filter by import_id and then delete **_all_** from that import I think people would find that useful.

**Comment by kitenetter** [comment]
@johnvanbreda a "my imports" page sounds like a very good solution.

I can still see a case for your requirement 2 (adding tick boxes and a delete button to the "my records" page), but I would regard that as a lower priority than the "my imports" option.

**Comment by DavidHepper** [comment]
Whatever we do someone will find it either too restrictive or too lax! 
I'm inclined towards:
- delete should be available only at Explore, not Verify, to cope with Bill's case of the missing Emperors;
- record selection should be by tickbox only, allowing importers who get it wrong to repent at leisure which ticking records...

@johnvanbreda I'm not asking to be able to delete other users' records. Only records initially entered or imported by the current user should be _deleted_, though we can't prevent others from being _selected_. It might be useful if the deletion process could indicate on completion that "_n_ of _m_ selected records were deleted".

In the case of BDS dragonfly imports it is relatively easy to create a filter on the Explore screen that selects only records imported in one batch because the form (survey) is unique to imported records but is this is the case for other groups? In the case of Soldierflies, for example, how easily could all records of a duff import batch be identified? Only by near-contiguous record IDs?

**Comment by BUDDBILL** [comment]
Hi
Having just done a search for ‘Emperor’ on the UK Species Inventory, it returned 10 names (including ‘Emperor Goose’ which is a new one on me); however 5 of these were marked as ‘Not recommended’, including ‘Emperor’ itself. Would it not be possible for the Import process to reject Common names that are ‘Not recommended’?
Regards
Bill

**Comment by kitenetter** [comment]
@DavidHepper most people who are using the iRecord CSV import are importing into the "iRecord Import" survey. I guess I could use a range of record IDs if I needed to select a set of records but it would be a lot easier to be able to select by import batch. Imports often consist of hundreds of records, sometimes thousands, so I'm not too keen on the tick-box approach!

@BUDDBILL I agree it would be useful to restrict the vernacular names to those most widely used but I'm not sure how easy this is to do. As far as I'm aware all vernacular names are flagged as "Not receommended" because the recommended name is always the scientific name. However, the "Emperor" name is marked in UKSI as "junior synonym" whereas "Emperor Moth" is marked as "accepted name", so if that has been done consistently within UKSI it might be possible to filter things that way.

**Comment by BUDDBILL** [comment]
I’m sorry this has gone slightly off-topic, but the NHM website UKSI enquiry does show Recommended Common Names:

Having said that, some of the scientific species names that are recommended in the UKSI leave me somewhat confused e.g. Calopteryx syriaca – but what do I know?

Regards
Bill

**Comment by johnvanbreda** [comment]
Code in develop branch - will need a report with the [misc_extensions.imports_grid] control added.

**Comment by johnvanbreda** [comment]
Hi @DavidHepper. The next release of the warehouse is a bit bigger than normal (v2) so is currently on the dev warehouse awaiting testing and approval. Hence this one is taking longer than normal to deploy. I hope to get the updates done in the next week or two.

**Comment by DavidHepper** [comment]
Bump...

**Comment by DavidRoy** [comment]
Review and update.  Create specific issues, particularly deletion of necessary records

**Comment by kitenetter** [comment]
Three new issues extracted, closing this one.
