### ISSUE TITLE
ES errors

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1659]
If I try to add or edit a verification role I'm getting "Elasticsearch query failed".

**Comment by kitenetter** [comment]
Actually this seems to be a general problem across iRecord.

**Comment by Sam-Amy** [comment]
In case linked to the earlier issue where new records were not showing since late on 25/03, John said via email:
"There were a couple of issues, both almost certainly as a result of the disk space problem on warehouse1. The spatial indexer had crashed on a block of records which then causes other scheduled tasks that depend on spatial indexing to get backed up. Also the Logstash feed of records into Elasticsearch had crashed, leaving a flag indicating it was still running the process so subsequent attempts to start failed. Both fixed, it will take a little while for everything to catch up. There should be no side effects other than a delay on when records are available for reporting and a delay on sending notifications."

**Comment by johnvanbreda** [comment]
Am investigating data not showing on Elasticsearch - unfortunately the live environment seems to be behaving differently to my test setup. This is a different issue to records not feeding through the Logstash pipeline as reported earlier.

**Comment by johnvanbreda** [comment]
Can you try now please @kitenetter, also let me know if you are still seeing other errors?

**Comment by Sam-Amy** [comment]
Explor all records/my records are now showing fine for me

**Comment by kitenetter** [comment]
Okay for me too, and the verification filters seem to be back to normal as well. Closing.
