### ISSUE TITLE
iNat import - odd behaviour

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1665]
Hi @johnvanbreda is there something odd going on with the iNat imports? A verifier has asked why some 'research grade' records in iNat are not coming through to iRecord, e.g. [this one](https://www.inaturalist.org/observations/205489219) which was added to iNat 4 days ago and reached research grade the same day.

And then when I went to see which other records were coming through, there seem to be a lot of iNat records appearing that were originally entered into Indicia in 2021, but are now showing as having been last updated today. I can't see anything that is likely to have caused an update.

An unverified example is https://irecord.org.uk/record-details?occurrence_id=22580402

And [this bee-fly record](https://irecord.org.uk/record-details?occurrence_id=22559858) was added to Indicia in 2021, and I rejected it in 2022, but it is now showing as having been edited today. Even if it had been edited at the iNat end (which I don't think it has) then I wouldn't expect an edit to over-ride the verification decision.

**Comment by johnvanbreda** [comment]
A few things going on:
1) European Holly Leafminer is not a name on UKSI and we've never populated the table for mapping non-standard names, so that record cannot import.
2) Lots of iNat records previously came through with photos that had strange codes added to the URLS, which are now being tidied up and it seems they are being passed through the API as updates. For example record 22580402 has 2 photos - look at the URLs of each to see what I mean.
3) The code only blocks an update of a verified record, not a rejected one (after all, the update might be new information or a more accurate location). Unfortunately, in this case the photo tidy up is triggering an overwrite of the rejected record. It's hard to know what to do about this without writing custom code to handle the specific case of ignoring updates if it's just the URL of an image being tidied in this fashion.

**Comment by kitenetter** [comment]
Point 1
"European Holly Leafminer" is Phytomyza ilicis, which is a standard UKSI name, and we have imported many records of this taxon from iNat previously. Are you saying that the English name has to match UKSI? I thought we were matching scientific names.

Other examples of recent non-import are for taxa that only have a scientific name, e.g. [Cerodontha iridis](https://www.inaturalist.org/taxa/1122251), another taxon that has imported okay previously.

Point 2
Is this a change at the iNat end, or is it something that you've done to address #1661 ?

**Comment by johnvanbreda** [comment]
1. You are correct, this should have matched on P. ilicis. There is something wider going on here, I wonder if it is related to the clock settings on our server being set to UTC rather than Europe/London (I've raised a ticket about this). It would need a bit of effort to investigate properly so please let me know if a priority.
2. This is a change at the iNat end, we haven't changed any code in this area since last year.

**Comment by kitenetter** [comment]
It does seem strange that no Agromyzidae records have been imported since 30 March, but for other taxon groups there have been imports. Will review in a couple of weeks and see if the problem remains.

**Comment by kitenetter** [comment]
As far as i can see there have been no new iNat records imported for any sighting after 25 March, so this will need investigation.

**Comment by kitenetter** [comment]
It appears that the large number of 'edited' iNat records (as a result of the photo URL changes) is reaching the capacity for the import process and that the newer records are therefore getting 'stuck'. Presumably this will eventually resolve itself once the photo URLs are all dealt with. Closing for now.

**Comment by kitenetter** [comment]
For reference, the updated iNat records are still accompanied by duplicated photos with odd codes in the URL. For instance [record ID 22982750](https://irecord.org.uk/record-details?occurrence_id=22982750) ([iNat ID 98782037](https://www.inaturalist.org/observations/98782037)) was re-imported at 11:35 this morning (having originally been supplied in Oct 2021). The iNat version has just a single photo, but the newly imported version in iRecord still has two:
- https://inaturalist-open-data.s3.amazonaws.com/photos/164543945/original.jpg
- https://inaturalist-open-data.s3.amazonaws.com/photos/164543945/original.jpg?1634730166

So we appear to be getting lots of re-imported records but no benefit.

@johnvanbreda let me know if you think there is anything we can or should do to investigate this further.

**Comment by johnvanbreda** [comment]
I've fixed the pagination when there are lots of records. We should perhaps run a query to clean up the duplicate image URLs at some point.

**Comment by kitenetter** [comment]
The lack of any new iNat records since 26 March is causing alarm for people who are worried that their records have got lost, and the duplication of photos for many of the recently re-imported observations makes life unnecessarily difficult for verifiers.

Can we confirm that the problems arise at the iNat API end of things, or has something gone wrong with the way we process the records in iRecord?

**Comment by johnvanbreda** [comment]
Nearly fixed now @kitenetter - it should be bringing new records again, though hasn't quite caught up. It turns out the extra record volume was causing memory errors on the new server so it was never finishing.

**Comment by johnvanbreda** [comment]
All caught up and back up and running now.
