### ISSUE TITLE
How can I enable editing for a BRC Open Access survey?

### ISSUE THREAD

**Issue by robin-hutchinson** [BiologicalRecordsCentre/iRecord#1668]
I'm trying to edit records from the BRC Open Access website in iRecord, but it doesn't look like editing is possible at the moment. Is there a setting I can change to permit this?

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/a5e82484-a338-4cc0-ae0c-807462c0034a)

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/aa31599a-bf18-4e95-b6a0-3edfef615716)

**Comment by robin-hutchinson** [comment]
In the website agreement it looks like editing permission is given:

![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/95474755/d1843cc4-a540-45df-aa69-0e19bb1440eb)

**Comment by kitenetter** [comment]
Just to add that these records are editable from the verification page, but not from the Explore page (when logged in with the account used for uploading the records).

**Comment by johnvanbreda** [comment]
Because we encourage users to edit records on the website they were submitted from to ensure that the most accurate form is used, we disable the edit icon on records that are from other websites. On the verification page we don't do this as verifiers may not be able to edit from the originating site, so we fall back on the edit-generic-record form. 3 options:
1) Use the verification approach.
2) Create the edit link yourself, by adding the ID to the URL https://irecord.org.uk/edit-generic-record?occurrence_id=
3) I could alter the code to enable the generic form for all websites (or, better, only if the source website does not specify the input form which means it would work for imported datasets like BRC Open Access and iNat only).

**Comment by robin-hutchinson** [comment]
Thank you John - seeing as the data is being uploaded for the schemes (and so they are likely to also have verification access), the verification will work as long as I explain that to the schemes. At some point it would be useful to be able to enable editing for other websites (where there isn't a public interface as we upload to BRC Open Access on the schemes behalf through Indicia) but I don't think it is essential at the moment.

**Comment by kitenetter** [comment]
John's option 3 above might be useful if we encounter similar issues in future, but for now I think the edit from the verification page will suffice. Closing.
