### ISSUE TITLE
Verifier can't access - elastic search query failed error

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1669]
User 67892 is a verifier, but upon navigating to the verification page gets 'Easticsearch query failed error'. No problem on the explore all records page (and no records themselves to view on the explore records page). 

I have tried removing and re-adding their verification permissions, and checked that their verification filter still exists. 

The verification filter is based on a scratchpad called '[Marine excluding birds](https://irecord.org.uk/scratchpads/edit-scratchpad?scratchpad_list_id=4590)' which although it looks fine, when I try and create a new filter with it brings up the same elastic search error. 

Can you suggest anything please @kitenetter or @johnvanbreda ? Thanks

**Comment by kitenetter** [comment]
The scratchpad defines a long list of higher-level taxa that contain a mix of marine and non-marine species. The ES error message is associated with the scratchpad rather than the verification role.

I also just tried to recreate the scratchpad, and there do seem to have been some changes in the higher taxonomy (some of the names in the original list are no longer recognised). But even after recreating it and checking that all the taxa are recognised it is still generating an ES error:
https://irecord.org.uk/scratchpads/edit-scratchpad?scratchpad_list_id=8908

So I'm stuck. Over to John!

**Comment by Sam-Amy** [comment]
I've just made a new scratchpad too - was about to see if it works. It didn't.

Note to self: I have for now given the user access to all records (this filter was for all excluding birds), in the offshire NI region, and she can now access the verification page and will just ignore birds for now until we fix this.

**Comment by johnvanbreda** [comment]
I can see the issue here - the list of taxa is too long, but I can also see a problem in the code which expands the list of higher taxa to find all the contained taxa before sending the query to Elasticsearch, whereas it can actually just allow Elasticsearch to filter the unexpanded list against the higher taxon IDs array stored for each taxon. I'll work on a fix.

**Comment by Sam-Amy** [comment]
No idea of the technicalities, but I did wonder if there might be any way to just remove certain taxa from a filter instead, though the use cases are probably so limited it wouldnt' be worth it.

**Comment by robin-hutchinson** [comment]
Hi John, I've just had a message from the verifier. It looks like elastic search is still failing on this scratchpad, is there a way I could work around this?

**Comment by robin-hutchinson** [comment]
Thanks John - I've just tried but am still getting the elastic search failed query, is this going to be deployed on Indicia in the next big update? If so I can let the verifier know.

**Comment by johnvanbreda** [comment]
Github auto-closes the issue when you commit a change which tags that it fixes the issue - it doesn't wait for the change to go live though! I'll do that now and will post back shortly.

**Comment by robin-hutchinson** [comment]
Ah sorry I didn't realise that! Thank you!

**Comment by johnvanbreda** [comment]
It should be live now...

**Comment by robin-hutchinson** [comment]
Success, thank you!!!
