### ISSUE TITLE
Downloaded data splitting across two lines

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#167]
A small proportion of records in the downloaded datasets are getting split over two lines - see row 10 below:

![image](https://cloud.githubusercontent.com/assets/16039111/23047393/7741dae2-f4a7-11e6-9536-94586ceaeef1.png)

I guess this happens if someone adds tabs or line breaks into the comment field?

Maybe we can address this as part of #74

**Comment by kitenetter** [comment]
I'm beginning to get reports about this from other users as well, so maybe it is something that has only recently started happening?

**Comment by colinharrower** [comment]
I was having an issue trying to read in a download from iRecord in csv format into R. Depending on the way in which I tried to load the file it would either give an error about a specific row not having the correct number of columns or alternatively (and more dangerously) would import without warning but the loaded object would not have the correct number of rows.

On investigation it turns out that this issue stems from using double quote to enclosing character fields when they contain embedded control characters or the delimited but not always enclosing the fields. Specifically the problem arises if the data set contains character fields that aren't double quote enclosed that happen to contain unpaired quotation marks. In this case R either returns an error or more commonly thinks the unpaired quotation mark is actually the start of a quote and will ensure that all text till the next quotation mark (across lines in the file if necessary) is part of that field. This throws the alignment of the entire file out after the first unpaired quotation resulting in mangled fields and a file with potentially less records if R does succeed in loading the file.

For example the export I had issues with contain record 4414557 which has the following in the Sample comment field:

`Dead otter measuring 48.5"`

where the double quote symbol is being used as an inch symbol. There was a similar issue with a value in the Comment field where there it looks like the recorder wanted to quote a word but is missing the closing quote:

`Did not see Hedgehog "Herbie from late November 2015 till June 2016`

Altering these lines in the csv data file so that the relevant fields were enclosed in double quotes the unpaired quotation marks were escaped by placing another double quote in front of it, e.g.

`"Did not see Hedgehog ""Herbie from late November 2015 till June 2016"`

fixed this issue for R allowing the file to be read correctly. Modifying the existing code that checks & fixes  the character fields to also look for unpaired double quotation marks and then enclosing the fields and escaping the unpaired quotation marks should fix the issue.

In regard to the embedded line returns I did notice that if I exported the same mammal data as csv versus tsv that the line returns are still present in character fields but not escaped in the csv causing additional line breaks in the csv file when viewed in a text editor (excel does handle these correctly due to the enclosing in quotations) meaning that he number of lines in the file is not an indication of the number of records.  In contrast the embedded line returns are completely removed from the tsv file downloads where each record in the file is on a single line and the number of lines in the file is 1 less than the number of records in the file. I'm guessing there is a reason for this but it seems odd that the data itself is modified, albeit in a minor way, between the 2 download formats and I can't help but slightly feel that keeping the line returns in the csv download fields could cause problems for users under certain uses cases but will rarely provide any benefit.
