### ISSUE TITLE
Some records displaying incorrect date

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1688]
Some records via explore pages and record details page showing an incorrect date (despite correct date entered and shown on recording form).

Occurrence_ids: 35731810, 35731809, 35731808, 35731807. They all show Date of 04/05/2024 and Submission Date also 04/05/2024, but the date entered, and still visible when 'edit this record' is selected is 27/04/2024. 

These were entered as a Plant Survey on the iRecord app.

**Comment by mikeprince** [comment]
To add a little to this, this was a list of records entered in the app on 04/05/2024 but with the date of observation set to 27/04/2024. iRecord ignores the backdated date entered, and treats them as records from today when you view the observations. When I edit an observation the correct date is shown however.

**Comment by DavidRoy** [comment]
is this an app issue @kazlauskis

**Comment by johnvanbreda** [comment]
From looking at the data, I can see that this is a plant survey from the app where the parent sample (the grid square) has the correct date of 27/04 and the child samples for pinpointed plants have the date the form was submitted rather than the date of the survey. So it does look like an issue with the way the app submits surveys if the submission is done on a different day to the actual data entry.

I can write a query to fix the existing data but this will need an app fix.

**Comment by johnvanbreda** [comment]
Out of ~75000 pinpoint samples from the app plant survey, 723 have child samples which match the date of submission, but don't match the date on the parent sample, including Mike's list. Assuming that the parent sample has the correct date as input, these can be updated to match the parent sample.

Before I do this, any thoughts on whether this is the correct fix and safe to do?

**Comment by sacrevert** [comment]
I haven't used the iRecord plant survey for some time, but, in general, some recorders have historically accumulated records for a square over some.extended period, only adding new taxa on later dates. Is it possible that some people have used the app in this way, creating a 1 or 2 km area and then accumulating records over time? Is this possible with the app?

**Comment by johnvanbreda** [comment]
Good question - although I guess this is possible, the date of the child records would be ambiguous as I don't think the app allows the user to set it?

**Comment by kazlauskis** [comment]
Yes, this is something that should be fixed in the app first. If users change the survey date AFTER adding species, the new date isn't synchronised with the existing list entries. i.e. the app copies the survey date for new species entries only, it doesn't sync it back to existing ones. This has been the case since the survey was introduced in the app 7+ years ago, so it might affect quite a few samples.

@johnvanbreda I can change the code in the app but I would prefer if the app didn't have to keep the survey and subsample dates in sync. I don't think we have any app surveys where subsamples have a date option, so users will only set the parent survey date. Could we add an entry [here](https://github.com/Indicia-Team/warehouse/blob/39bb5fd958fe860a27f76181269ee6a7606fe2ee/application/models/sample.php#L267) so that upon submission subsamples that have no date set would inherit the survey's date?

**Comment by johnvanbreda** [comment]
@kazlauskis doesn't line 285 already do that? The problem here is that the app isn't submitting a sample without a date, it's submitting a sample with the wrong date. So if you change it to submit no date on the sub-samples it should automatically pick up the parent sample date.

**Comment by kazlauskis** [comment]
Ah, in that case it is an easy fix for me. I just don't set the subsample date.

**Comment by mikeprince-ne** [comment]
> I haven't used the iRecord plant survey for some time, but, in general, some recorders have historically accumulated records for a square over some.extended period, only adding new taxa on later dates. Is it possible that some people have used the app in this way, creating a 1 or 2 km area and then accumulating records over time? Is this possible with the app?

That is a good question. If it was something that was desirable, then an end date on the survey would probably be the most sensible implementation (rather than allowing individual sample dates). Otherwise I expect by far the commoner use case is people just entering and submitting sample records after the actual single survey date. E.g. when they get home, finish identifying specimens etc.

**Comment by sacrevert** [comment]
@mikeprince-ne sounds like it is a bug rather than this anyway. Also, the plant card does support vague dates, so this is already accommdated (although I'm not sure whether the vague dates are supported by the app or not in this case)

**Comment by Sam-Amy** [comment]
Closing but see [https://github.com/NERC-CEH/irecord-app/issues/283](https://github.com/NERC-CEH/irecord-app/issues/283)
