### ISSUE TITLE
Taxa missing from website dropdown (but not app)

### ISSUE THREAD

**Issue by Sam-Amy** [BiologicalRecordsCentre/iRecord#1724]
Chionoloma tenuirostre var. holtii appears to have dissappeared from the UK Master List on iRecord, though it is still available as an option on the app. 

It is still present on the UKSI sandbox: [https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021614629](https://uksi-sandbox.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021614629)

It seems to be marked redundant in the warehosue, but this shouldn't be the case: [https://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-key=NHMSYS0021614629&filter-key_type=tvk&filter-taxa_taxon_list_id=&filter-taxa_taxon_list_id%3Ataxon=](https://warehouse1.indicia.org.uk/index.php/taxa_search?filter-taxon_list_id=15&filter-key=NHMSYS0021614629&filter-key_type=tvk&filter-taxa_taxon_list_id=&filter-taxa_taxon_list_id%3Ataxon=)

**Comment by sacrevert** [comment]
@burkmarr please reassign if this is not for you, just wondered whether there was any link to your other work in this area

**Comment by burkmarr** [comment]
The taxon was during the June 12th incremental update:

![image](https://github.com/user-attachments/assets/641fff0f-7e0a-44bc-a4cf-5529da09055b)

It looks like the parent organism was changed. Looking at the record in pgAdmin, the allow_data_entry flag is set to false, but I don't think the amend taxon operation will have done this. I've changed the allow_data_entry flag so that it appears in the iRecord data entry now, but I can't explain why it was set to false.

**Comment by sacrevert** [comment]
Happy to close this unless @johnvanbreda thinks that anything needs investigating?

**Comment by johnvanbreda** [comment]
Actually I found a bug and I suspect the amend taxon operation did set allow data entry to false, due to a mistake in the way the code was reading boolean values from the uksi_operation.redundant database field. Now fixed. I've also reset the flag for 4 obscure taxa which were similarly set to allow data entry = false.
