### ISSUE TITLE
Request to edit user name

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#183]
One of the BDS verifiers took over a user account from a previous person. All the relevant details have been updated in the new user's profile, but the underlying database still stores the original user name. When auto-messages are sent out on behalf of the current verifier (Martin Roberts) they are displaying the previous user name (P_Ashton).

Can we edit the username in tables "users" for this user? Details:
- id in table users = 98406
- id in table people = 98725

More generally, is there a reason why iRecord users cannot update their own usernames once set?

**Comment by JimBacon** [comment]
Ooooh! It jars my sensibilities to read that!

Why would you take over someone's account? Surely the right thing is for each user to have their own, properly configured account? This sounds  more like a misuse of the system than a bug. Doesn't it risk losing the traceability of who did what?

Alternatively, if you specifically want to de-personalise it and lose traceability then just create an account called BDS Verifier.

**Comment by kitenetter** [comment]
@JimBacon I take your point, but in this case the deed has already been done - everything about the account is linked to Martin Roberts except the original username. Please can we make an exception this once?

**Comment by JimBacon** [comment]
I should be able to fix it. 
(Sorry for closing the issue earlier... just a bit of careless clicking, not intentional.)

**Comment by JimBacon** [comment]
Hi Martin,

I logged in to the warehouse and was able to update the user name. I think you could do this too. See screen shot below. 
On reflection, one reason why there may be no facility for users to change their Warehouse username is that, until you mention it now, I was unaware of it ever being visible anywhere. I wonder why it is being used in the messages you report. Much better to use their chosen name I would have thought. Perhaps that is a bug.

![capture](https://cloud.githubusercontent.com/assets/2545390/24259567/29dcadc4-0fe9-11e7-815f-0166cc9dc83c.png)

**Comment by kitenetter** [comment]
Thanks @JimBacon 

One question: is there any reason why I shouldn't edit that further to "Martin_Roberts" just for complete clarity?

As far as I'm aware, the only place where this particular version of the user name appears is in the auto-emails that iRecord sends out:

![image](https://cloud.githubusercontent.com/assets/16039111/24263651/aebe3c5e-0ff5-11e7-8ef5-eceb6473449c.png)

**Comment by JimBacon** [comment]
Yes. The reason is that there is already an account with username "Martin_Roberts".  

The code generating the emails runs on the warehouse.  It can be found in the function runEmailNotificationJobs() in file modules\notification_emails\plugins\notification_emails.php.

It gets the contents of the email from the notifications table, data field which is created by the function notify_verifications_and_comments_scheduled_task() in file modules\notify_verifications_and_comments\plugins\notify_verifications_and_comments.php

The query that ultimately does the job can be found in function selectVerificationAndCommentNotifications() in file application\helpers\postgreSQL.php. The key part of this is 
```
select rn.*, u.username
from records_to_notify rn
join occurrences o on o.id=rn.id
left join notifications n on n.linked_id=o.id 
          and n.source_type=rn.source_type
          and n.source_detail=rn.source_detail
join users u on u.id=coalesce(rn.occurrence_comment_created_by_id, o.verified_by_id)
where n.id is null
and o.confidential=false;
```
Another join to the person table would allow the person name to be returned rather than the username.

**Comment by kitenetter** [comment]
I think it is preferable to link to the Person name rather than the User name, if that code can be modified without any other implications.
