### ISSUE TITLE
Unhelpful Drupal "Access denied ..." page when following verification email links requiring login

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#185]
**AvB:** With the iRecord email situation it more complicated, we have a link we want to keep, however it depends on the state of an external system (iRecord) whether the verification link works or not, but our email is unaware of the user's login state on iRecord.

Thinking off the top of my head (and this may not be an optimal solution), one way to fix your emails would be to direct them to a completely different page on iRecord. This page would have some code on  it to detect the user's login state and would automatically forward the user to the correct page once that detection is made (either login page or the verification page).
I believe that the login page could be made to then automatically go straight to verification once login is made.
I believe this way you would not get authorised messages in your emails.

**Comment by kitenetter** [comment]
@sacrevert I don't understand this issue - is it connected to the notification emails that iRecord sends out to people? These contain record IDs that are hyperlinked to the records - are you highlighting a problem with what happens if you click on that link while not being logged in to iRecord?

If so a resolution of #158 may help.

**Comment by kitenetter** [comment]
Have not had recent reports of this problem - closing.
