### ISSUE TITLE
Include "Method" in data downloads

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#193]
This request has arisen from verifiers for moths, who need to access the "Method" data from the moth recording form alongside the data from the general forms, but is likely to be more widely useful as well. Linked from #74 

1. New system function?
There are method attributes in numerous surveys, so in order to include a Method attribute in the generic download I assume we will need to create a new System function for Method, and then add a Method column to the download format.

2. Multiple attribute issue
However, there is a complication in that some surveys, including iRecord Import, have more than one Method attribute. iRecord Import currently has three attributes that may potentially contain Method information:
- Sample method (from controlled termlist)
- Observation type (from controlled termlist)
- Method (free text)

Do we have any mechanism for combining data from multiple fields into a single column for download? Or should we consider having multiple Method-related columns in the download (e.g. a termlist Method **and** a free-text Method)? Or do we have to choose just one of the iRecord Import Method attributes and treat that as the system function one?

**Comment by johnvanbreda** [comment]
Unfortunately having spent a while thinking about this one I don't think the ideal solution is at all quick. In my opinion, we've historically been a bit lax on the way that sample method, record/observation type and record capture method terms are used with a lot of muddling between the 2 lists. This applies to Recorder 6 as well, not just Indicia, so it might be worth considering this before making any changes. The concepts used in the warehouse data are:
* Sample method - the method of sampling should be something like "field observation", "timed count" or "transect". Most of our data are either linked to the core samples.sample_method_id field or a custom attribute designed to store a sample method. Although many of the terms used are OK as sample methods, we also have terms in a termlist called  Ladybird Habitat and BRERC Record Type which probably don't belong here.
* Record type - traditionally used to store what the record is of (e.g. track, spraint) but has a tendency to include sample methods (caught, camera trap, auditory - heard are all examples in the warehouse data). We also have voucher specimen which might actually be closer to a correct use of the record type field. Note that in Darwin Core, type is used to capture “the nature or genre of the resource”, e.g. "StillImage", "MovingImage", "Sound", "PhysicalObject", "Event", “Text”, further muddling things.

The core data model already includes a field for sample method (samples.sample_method_id) which points to a controlled termlist. It was added as a core attribute rather than just using a custom attribute because it is used in the data model in a foreign key in the table which links sample attributes to survey datasets - allowing sample attributes to be only linked to the survey dataset within the context of a single sampling method. E.g. in UKBMS we can capture different attributes at the transect level to those captured at the section level. However quite a few survey datasets have added their own sample method attributes probably because it gives them more precise control over the term list available. Similarly, the iRecord Import dataset has a sample method attribute which is free text.

We should actually be promoting a stricter separation of these concepts - in my opinion:
* Sample method (transect, field observation, pitfall trap etc)
What the record was of (whole organism, body part, track/sign/auditory etc).
Custom attribute set (the group of custom attributes used by the input form, allowing separation of the attributes used by parent and child samples as per the UKBMS example). The attribute set might map 1:1 to a sample method but not necessarily. 
Plus occasionally it might be useful to include record capture method (record card, data logger) or voucher specimen as separate attributes, though I think as these would be occasional attributes there is no need for a system function. 

Therefore I think the ideal situation is:
Add a system function for sample attributes called “sample method” which could be used by existing free text or lookup sample method custom attributes.
Add a system function for occurrence attributes called something like “record of”. 
We should also have some documentation to make use of the system functions absolutely clear (e.g. the documentation could appear in the warehouse when you pick a system function).
Rename the existing samples.sample_method_id field to samples.attribute_set_id and refactor the code to match.
Review the existing custom attributes for both sample method and record of/type and assign to system functions as appropriate.
Review the use of samples.sample_method_id (now samples.attribute_set_id). Create a custom sample method attribute to capture all the values which are actually sample methods (hopefully all of them). Then delete any values from samples.attribute_set_id which are not actually used to define a limited set of attributes for the sample method. We’d have to proceed carefully coordinating with the website owners to ensure the forms are corrected. We’ll then have a consistent use of the samples.attribute_set_id and the sample method custom attribute - the latter can be included in the download reports.

Accepting that this solution is quite extensive, an simpler approach which is at least a step in the right direction and should solve the main requirement is:
Have a system function for sample attributes called “sample method” which could be used by existing free text or lookup sample method custom attributes. 
Review existing sample custom attributes and set the sample method system function against those where it is felt to be appropriate.
Put a special case in the code which adds system function attributes into the reporting cache tables so the sample method values also include the term pointed to by samples.sample_method_id

The column included in the reporting cache tables (and downloads) will only hold one sample method value - if a single record has several custom attributes using the sample method system function or sample_method_id field I’ll have to just pick one.

**Comment by kitenetter** [comment]
Yes that is complex isn't it. I agree that it would be ideal to do an extensive review of this in order to future-proof the system, and the longer we wait to do that the harder the job will be. But that will need to be considered in any longer-term prioritisation of tasks.

In the shorter-term your 'simpler approach' seems like a good thing to do as it will to a large extent address the issue that has been raised by users.

If we opt for the simpler approach are we making the more extensive review any more difficult?

I will discuss with @DavidRoy what priority we can give this.

**Comment by johnvanbreda** [comment]
I think the simple approach is compatible with the proposed full solution, so no, we won't be making things more difficult.

**Comment by DavidRoy** [comment]
I agree on implementing the simple improvements now, and then considering longer term requirement

**Comment by johnvanbreda** [comment]
Ok, will do. Should the sample method column now appear as a standard column in all downloads?

**Comment by DavidRoy** [comment]
Yes

**Comment by johnvanbreda** [comment]
Ok, I've done this. Let me know when existing attributes are set up as sample methods in their system function though so I can manually update the cache tables.

**Comment by kitenetter** [comment]
@johnvanbreda this is only tangentially related to the above discussion, but can you let me know whether it is possible to assign the same system function to two attributes in the same survey. The example I have in mind is for the Mammal app, which (in common with other apps) has two attributes for storing a count, one that takes a precise number and one that takes a range.

Can I assign the "Count/abundance" system function to both, and if not is there a preference for which one I should choose (I'm tempted to go for the precise number but I suspect that more records have the range).

**Comment by kitenetter** [comment]
I can confirm that the Sample method system function has been applied to all the sample attributes I can find that appear to be method data (from https://github.com/BiologicalRecordsCentre/iRecord/issues/193#issuecomment-317374269 above).

There are some surveys that store method data as an occurrence attribute (e.g. the "Moth Night Method" attribute), is there any way of linking these in so they also appear in the sample method column in any download?

Would be useful to know the answer to https://github.com/BiologicalRecordsCentre/iRecord/issues/193#issuecomment-331549439 above as well.

**Comment by johnvanbreda** [comment]
I've updated the existing data. 
I don't think we can easily store occurrence attribute data as a sample attribute - there will be issues with aggregating a list of different terms for example. Why is it done this way?
Regarding the question about 2 sample attributes both with the same function, this should be OK as long as there is only one or the other. If there are both attributes set then I think only one will appear in the method column as it stands.

**Comment by kitenetter** [comment]
With the proviso that we may need to come back to the more complex options presented above by John, I'm closing this one for now.
