### ISSUE TITLE
Extending filtering to include BC Branch locations

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#2]
Load BC Branch layer as a location set

Add BC Branches to Explore filters on iRecord

**Comment by johnvanbreda** [comment]
Done.

- Renamed location type to Butterfly Conservation branch
- Made locations of this type public and mark deleted the locations_websites records to unlink them
- Configured spatial indexer to cover this location type and ran a script for initial population of the index
- Fixed a bug in the locations views so mark deletion of the website links records is respected.

**Comment by DavidRoy** [comment]
Works well on the explore filter, but the filter setup for activities does not include the BC Boundaries as an option.  I notice a few differences in what's available between the different places where filtering is available

**Comment by johnvanbreda** [comment]
Missed that one, now done. What other differences are you aware of?

**Comment by DavidRoy** [comment]
The activity one has a category of 'miscellaneous indexed boundaries...'.  Is there a reason this is not on the general explore filter?

**Comment by johnvanbreda** [comment]
This layer was created specifically to expose custom boundaries for a couple of activities with large and complex boundaries, so that they could be indexed. The 2 examples are NI and Cairngorms. The layer could indeed be exposed everywhere else but is this going to cause a bit of confusion as people might expect additional boundaries to be available?

**Comment by DavidRoy** [comment]
Makes sense.  Let's leave as is.
