### ISSUE TITLE
Pop-up VC chooser when grid square overlaps boundaries

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#202]
Recording schemes like records to be attributable to VC.

Suggestion: VC chooser pop-up when less precise (10, 2, 1 km?) grid cells overlap VC boundaries. Also provide 'Don't know/both' option so as not to alienate recorders without knowledge of VC system.

**Comment by sacrevert** [comment]
It would be good if this could also be applied to the iRecord site list page [https://www.brc.ac.uk/irecord/enter-record-list]
At the moment, even if a site boundary is clearly within a vice-county, if the spatial ref is vague, then the records are still linked to multiple VCs with no way for a verifier to edit (outside of changing the spatial ref).
e.g. [https://www.brc.ac.uk/irecord/enter-record-list?occurrence_id=960332]

Allow for VC chooser, or, add VC field to record page so that verifier can edit (or both).

**Comment by johnvanbreda** [comment]
@kitenetter Do you agree this should go on the generic recording forms?

**Comment by kitenetter** [comment]
I think this would be a helpful development, especially as it would lead to records being more likely to be assigned to the correct VC verifier. As long as:
- It doesn't slow things down too much (e.g. when calculating whether the grid ref does overlap more than one VC)
- It isn't too onerous for the recorder (my feeling is that it is not too onerous, because it is unlikely to arise very often, although I guess if your preferred recording site happens to overlap a VC boundary it could become frustrating)
- A "don't know" option is available as Oli suggests

If we make this available, it will inevitably produce some records with the VC allocated incorrectly, so it would be good to allow both recorders and verifiers to be able to edit it after the record has been entered.

I am assuming that the entered VC will be stored as a separate attribute from the calculated VC; if so, then we probably need to make both available in any download reports, in order to allow for any inconsistencies to be picked up. (I think we already store an "entered VC" as part of the iRecord Import survey, where the same potential inconsistency issue arises.)

If it goes on the generic recording forms then there is also an argument for adding it to some of the other forms such as the moth recording one and the dragonflies forms (both of which are taxon groups that utilise VC recorders for verification).

**Comment by sacrevert** [comment]
>I am assuming that the entered VC will be stored as a separate attribute from the calculated VC; if so, then we probably need to make both available in any download reports, in order to allow for any inconsistencies to be picked up. (I think we already store an "entered VC" as part of the iRecord Import survey, where the same potential inconsistency issue arises.)

Not sure I understand why this is necessary. If there is no ambiguity then why allow an entered VC that is different from the calculated one, if there is ambiguity, then why store a calculated VC?

**Comment by kitenetter** [comment]
My understanding is:
When importing records into iRecord via CSV files it is possible to import a value for the VC. However, recorders can and do sometimes misallocate the VC. So in the import scenario we store both:
- The user-specified VC (which is a single value but may be incorrect)
- The VC calculated from the grid ref (which should not be incorrect but may result in multiple values, or incorrect single-values based on proportional calculations - I can't remember which of those two approaches is currently being used)

So in the case of imported records the user-specified VC acts as a useful source of additional information for those records whose grid refs overlap more than one VC polygon.

With the pop-up chooser option there is less chance that the VC will be completely wrong, since the user will only be choosing from limited options in specific cases (where the grid overlaps a VC boundary). And having thought it through I guess we **do** want this to over-ride the calculated VC, because if it doesn't then it will fail to allocate records to their correct verifier.

However, there is still room for users to make the wrong choice, which implies that an edit facility will be needed. I would be nervous about allowing edits to the attribute that stores the calculated VC. Is it possible to make the VC editable only if it was entered manually?

Or am I worrying too much about something that is not likely to occur very often?

**Comment by johnvanbreda** [comment]
The import version of the Vice County attribute is different to the one on the Vascular Plants form. The import version is just a simple number which sits in the sample's data values. The sample will then have a separate calculated VC linked to it, using the one with the most overlap in cases where this is needed. The VC attribute value is then available simply as a useful piece of additional information that might help e.g. during verification.

The vascular plant form VC field has a system function linked to it, Linked Location ID. This value actually stores the ID of the chosen VC in the locations table, rather than the VC code. The key difference though is that when there is a linked location ID field value, the spatial indexing on the warehouse will force the calculated VC to be the one provided by the recorder. 

The verifier can edit the record and change the linked vice county, e.g. https://www.brc.ac.uk/irecord/edit-generic-record?occurrence_id=6003908. 

If we do add the vice county field to the default forms, we could hide it so that the only implication is that the user will be asked to confirm when the record lies along a boundary. As Martin says, this will get annoying if you regularly record along a boundary though.

**Comment by kitenetter** [comment]
Does the edit page allow any the linked VC to be changed for any record, or just those for which the pop-up came into action? If the former there is a small risk that people might edit the VC when they shouldn't (e.g. there are parts of VC Berkshire that most people think are in Oxfordshire).

Other than that, the decision rests on the balance between providing this useful additional function vs keeping the forms simple, and it's hard to know where that balance should lie. I am slightly in favour of adding the pop-up to the generic forms. Does @DavidRoy have a view?

If we do implement it, can we:
1. Exclude the 'aggregate' VCs from the list (e.g. "Yorkshire" - are there others?)
2. Add the VC numbers to the dropdown as well as the names (some people are more familiar with one or the other, and the names are inconsistent in different references)
3. Enable a smart auto-fill, so that you can find a county by typing any part of its name or number, without having to use wildcards

**Comment by sacrevert** [comment]
For what it's worth I'm in favour of adding it to the generic form. I think all three of the suggested enhancements are worthwhile too.

**Comment by DavidRoy** [comment]
I agree to adding to the generic forms

**Comment by kitenetter** [comment]
The question of how to deal with records with grid refs crossing VC boundaries has come up quite a lot recently, especially from the recent recruitment of additional county recorders for some schemes. I'll put this into the September milestone so that we can consider what priority to give it.

**Comment by kitenetter** [comment]
@kitenetter to check that the existing plant form approach is sufficient, and identify any additional functions required

**Comment by kitenetter** [comment]
Discussion moved to #827 - closing.
