### ISSUE TITLE
SSSI layer available for use within iRecord

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#210]
Load layers into Warehouse1 and make available for use within activities and filtering

Source = 
https://data.gov.uk/dataset/sites-of-special-scientific-interest-england3

**Comment by DavidRoy** [comment]
Extend to also importing AONB layers 
https://data.gov.uk/dataset/areas-of-outstanding-natural-beauty-england1

**Comment by burkmarr** [comment]
@DavidRoy @johnvanbreda @kitenetter @BirenRathod 

I have sourced SSSIs and AONBs for England, Wales, Scotland & NI and combined them into two shapefiles. They are large shapefiles with complex geometry. Below are some statistics for them and for the current Vice County layer for comparison. (AONBs and SSSIs consist of multi-part polygons so, for example, 88 AONBs actually comprises of 4,431 individual polygons - mainly due to small coastal islets.)

VCs: **157** polygons & **1,281,620** vertices
AONBs: **4,431** polygons & **2,530,618** vertices
SSSIs: **31,806** polygons & **15,508,735** vertices

We know that the VC layer is complex - you can see how much more complex these two are, particularly SSSIs. So I want to ask opinions about the possible implications of loading these into the Warehouse as locations for filtering and reporting.

**Comment by DavidRoy** [comment]
Thanks Richard.  This is very useful background.  Let's hold off any further action until we've completed our wider review of priorities

**Comment by johnvanbreda** [comment]
When this does bubble up as a priority again, it would make sense to load onto the dev server then look at the performance of st_intersects queries for these polygons. We can of course add them to the spatial indexing, though this may cause a fairly large overhead on the background tasks.

Another thought would be to load up some of the polygons on the dev server and look at whether st_simplify or other PostGIS functionality can reduce the vertices count without changing the boundary too significantly. They may be more detailed than we need.

**Comment by BirenRathod** [comment]
I would certainly recommend first to play around on dev warehouse, so we could figure out any performance issue.

**Comment by kitenetter** [comment]
I'm not aware of any current demand for this, so am marking as deferred and closing.
