### ISSUE TITLE
Show full attribute when mouse-hovering in a list

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/iRecord#237]
For example hovering on record's location in the list should give its full coords, set in the 'title' attribute. At the moment it shows *'Click the row to highlight the record on the map. Double click to zoom in.'*

**Comment by japonicus** [comment]
What do you mean by 'full coords'? 

Does this mean showing a grid-reference rather than a lat/lng co-ordinate - in that case I'd suggest that rather than displaying the grid-reference only while hovering it should be the default view.  (or the default to show could be determined by a user-preference setting).

Is anything known about what proportion of iRecord users prefer lat/lng co-ordinates to grid-references (I suspect very few)?

I like having useful info in tooltips, but there are also drawbacks: values can't be copy-and-pasted and hovering is impossible on touch-based devices.

**Comment by kazlauskis** [comment]
Say, expand and show the full location name. Or for those records that do have lat/longs then show the full version.

**Comment by kitenetter** [comment]
Not sure which list/s this is referring to - from the Explore menu the lists generally do show full site name and spatial coords don't they? And you can always click through to the original record to see any further details. Closing for now.
