### ISSUE TITLE
Unexpected choices of location when logged in/out

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/iRecord#249]
On https://www.brc.ac.uk/irecord/enter-casual-record, when I start typing a location, existing locations are offered.

When logged in I am offered my own locations or group locations based on https://github.com/Indicia-Team/warehouse/blob/master/reports/library/locations/my_sites_lookup.xml

When logged out I am offered locations created by all users plus public locations.

It just struck me as odd that the offerings should be so different. A lot of the user-created locations seem to just be grid squares and I'm not sure it is worth encouraging their re-use by anonymous users. Conversely, the public locations which have been carefully added might be well worth reusing by logged in users.

An upshot is that, when logged in, if I enter Otmoor I get no matching locations but when logged out I get 6

I think there must be scope for improvement.

**Comment by johnvanbreda** [comment]
I agree - this is incorrect, you definitely shouldn't see other user's sites. Questions:
1) When logged in, should you see just your own sites (including sites for activities if entering activity records), or your own sites plus public sites (perhaps limiting this to a know set of layers, e.g. SSSIs)? I think the former, since the expectation is that you will manage your own list of sites and can add public sites to this list if they are of interest to you.
2) When logged out, should you see no sites at all, or be allowed to search public sites (perhaps limiting this to a know set of layers, e.g. SSSIs)?
These questions might be best directed to @kitenetter.

Another related bug is that if not logged in, but entering records for an activity (which is possible), you should see that activity's sites in the search results but you don't at the moment.

**Comment by JimBacon** [comment]
I don't recall - how does one add public sites to a personal list?

There is no facility for managing and updating personal sites is there?

My impression from my encounter with this yesterday was that a personal site might just be the first grid square where you make a record at a location so that subsequent records at the same 'location' are actually near by but not within the 'location' boundary... Yes, after a little test, I see the casual recording form allows me to create locations but not draw boundaries so if I create a location for my local park it is actually just a particular grid square within the park. That doesn't strike me as being as good as it could be.

**Comment by johnvanbreda** [comment]
You can enter a place name and a grid reference on a recording form, then click Remember Site to store the grid reference under that site name (I think you've discovered this). Plus you can go to Explore > My Sites for a site management tool - this allows you to edit existing sites (e.g to add a proper polygon to the above), add new custom ones, or select a site from pre-existing ones to add to your list.

**Comment by JimBacon** [comment]
Thanks. Seems I've never examined this before!
Mostly I can't get past a 500 internal server error (timeout?) to reach this page.
I did get by once and seemed to have permissions to edit public locations. I wanted to see if any user could do this but have had to give up because of the errors.

**Comment by JimBacon** [comment]
I can skip over the My Sites page and, masquerading as an ordinary user, edit a vice county such as https://www.brc.ac.uk/irecord/my-site-details?location_id=1120. I don't think that should be allowed. Maybe that is another issue though. I also note there seems to be an offset between this boundary and where Google maps think it is - a reprojection error perhaps?

**Comment by kitenetter** [comment]
I thought I'd added a comment to this earlier on today, but it seems to have vanished! Did anyone see it?

Main gist was that I agreed with @johnvanbreda's suggestions for point 1 above, and that I would vote for seeing no sites when logged out (point 2).

**Comment by johnvanbreda** [comment]
Jim - the 500 errors might be related to trying to load "My Sites" as admin - since admin "owns" a huge number of sites this fails. If you were logged in as a normal user let me know. Also should your comment about editing sites as a normal user go into a new issues?

I've added a commit to the develop branch so when not logged in, the location autocomplete control reverts to a normal text input control so you can't search for public sites.

**Comment by johnvanbreda** [comment]
Now deployed.
