### ISSUE TITLE
Suggested improvements to species name searching

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#262]
The German users of Indicia at DeutschlandFlora have requested some improvements to the way species searches work. Since this is an opportunity to improve the search for all users including iRecord I thought I would post details of the suggestions here for further discussion. It would also be good to incorporate any ideas from the iRecord App ( @kazlauskis ) to make a consistent best approach available for all.

The current situation is that most species name searches are performed by simplifying the search term and using the simplified version to compare against similarly simplified versions of the taxon name stored in the cache_taxon_searchterms.searchterm field. We simplify the search term to increase the chance of a hit irrespective of things like spacing/capitalisation/punctuation, whilst ensuring that database indexes work well. At the moment, the simplification process:

- lowercases the term
- removes all spacing and punctuation
- changes "ae" to "e" since that is sometimes a source of confusion in latin names

A good example is "7-spot ladybird" which simplifies to "7spotladybird" in the database field. Therefore if you type "7 Spot", "7spot", "7-spot", "7 - spot" or anything similar, they will all find the correct term.

The request from the German users is to allow a search where you can type the first few characters of each epithet in the species name. So, you can type "arn mon" to find "Arnica montana" for example. The problem we have currently is that the simplification process strips the spaces, so although we can treat the space in the searchterm as a wildcard, we cannot ensure that the characters intended to find the start of the 2nd epithet will not hit characters that are in the middle of the 2nd epithet. In order to not break existing searches (since we cannot guarantee that all clients will be updated at the same point in time) I propose to add a 2nd searchterm_v2 field which uses a new simplification algorithm:

- lowercase the term
- replace hyphens with a space
- replace any whitespace sequence with a single space (so double spaces, tabs etc become single spaces)
- strip all other punctuation (e.g. apostrophes). 

We won't bother changing ae to e - that seemed to cause more problems than it is worth. Our example of "7-spot ladybird" now resolves to "7 spot ladybird". The negative difference is that now, typing "7spot" won't work as you need a space or hyphen to split 7 from spot. The positive difference is that now we have the option of a "words begin with" mode (which could be turned on and off through configuration) that treats spaces as a wildcard then a space, so you could type "7 s l" for "7 spot ladybird" or "arn mon" for "Arnica montana" without risk that the 2nd or subsequent search tokens hit characters that are contained within, rather than at the beginning of, a word in a species name.

I'd be interested to hear about what processes are applied when searching terms in the iRecord app to make it more tolerant of different ways of typing the name, to see if we can benefit from the same.

**Comment by JimBacon** [comment]
You don't mention that the German requirement is almost satisfied by the existing 2-3 character search.
i.e. if they would type "armon" rather than "arn mon" it would work. Was this not of interest to them?

**Comment by kitenetter** [comment]
Would this proposal mean that we would lose the ability to enter the 2+3 abbreviated name (e.g. armon in Jim's example)? If so that will be unpopular with some of our users, as the 2+3 convention is quite well-established in the UK.

For those occasions where the 2+3 abbreviation returns a lot of name options it might be useful to be able to type 3+3 or some other combination, but I would prefer to keep the current 2+3 option if we can.

**Comment by japonicus** [comment]
A further advantage of keeping spaces and therefore allowing matching at the beginning of words is that searches need not be anchored to the start of the name, so that results for 'squirrel' would include 'red squirrel' and 'grey squirrel'. This works in the app but not on the website at present.

It would be good if the simplified names also striped rank keywords ('subsp', 'var' etc).

If revising name matching then it would be great if treatment of hybrids could be improved.  Hybrid matching doesn't work well at the moment (in either the app or website).  

It would be useful if the internal normalisation stripped off leading 'x' from hybrid genera and species, so that searching could be less exact, allowing:

'X Dactyloglossum drucei' ~ 'Dactyloglossum drucei'
'Carex x limula' ~ 'Carex limula'

Ideally, multiple normalised names need to be cached for hybrids, so that
'Carex aquatilis x bigelowii' ~ 'Carex bigelowii x aquatilis'

To allow multiple hybrid permutations and to accommodate continued support for 2+3 names without spaces, could I suggest storing the normalised names cache in a separate table, so that multiple simplified variants could be linked to a taxon.

"Arnica montana" would link to 'armontana' and 'arnica montana'.
"Carex aquatilis x bigelowii = C. x limula" would link to 'caaquatilis', 'carex aquatilis bigelowii', 'calimula' and 'carex limula'

Searches would match by adding wildcards after spaces as you suggest, so that spaceless 2+3 search would query as 'caaqu%'; 'arn mon' as 'arn% mon%'

This also allows refinement of 2+3 without spaces into 2+_n_, allowing someone to keep typing to refine the search (which currently doesn't work for 2+3 codes).

Because hyphens are nasty I'd suggest generating normalised names both with and without, so that both '7spot' and '7 spot' are allowed (storing simplified versions: '7spot ladybird' and '7 spot ladybird').

**Comment by johnvanbreda** [comment]
Having considered the requirements, I think that we should add a full text index to the unsimplified versions of all the taxon names in cache_taxon_searchterms. This allows searching for any word in the phrase and the phrase is normalised to remove issues regarding punctuation and case sensitivity. We can use a clever sort order to return the best matches at the top of the list, so we don't get too many issues caused by widening the search in this way. Just to be clear:
* @kitenetter this approach does not stop us using the 2+3 character abbreviations as well.
* You can use this approach to look for whole words, or words beginning with (e.g. arn mon to find Arnica montana etc). This would be an option for the form designer and we'd default to find words beginning with the input text.
* You can search for any word in the phrase, not just the first word, and the index still gets used. We can push searches against the first word towards the top of the results.
* @japonicus This approach does not extend the 2+3 abbreviations to 2+n as you suggest - I'd rather consider that as a separate requirement. There are ramifications though, as you will get a lot more hits on 5 character codes which previously may have returned only a few.
* Because we are searching for any words in the phrase you can find Common Dolphin by typing just dolphin.
* More complex searches are possble, e.g. "carex and (paup or grant)" returns both Carex paupercula and Carex x grantii. This fixes the issues with hybrids mentioned above.
* Also regarding hybrids, 'Carex aquatilis x bigelowii' ~ 'Carex bigelowii x aquatilis' so Carex aqua would return both but would prioritise the first, whereas Carex big would return both but prioritise the 2nd.

I've created a simple search page on the dev warehouse which lets you fire tests against this method of searching - let me know if you would like me to send you the link.

I've attached a technical note on how this will be achieved for anyone that wants to comment.

[Full text species name search.docx](https://github.com/BiologicalRecordsCentre/iRecord/files/1208857/Full.text.species.name.search.docx)

**Comment by johnvanbreda** [comment]
For those following this, the search algorithm has been updated:
* Option to control which name types are included - latin, synonym and common names.
* Option to include or exclude the author string as part of the searched text. This fixes the main issue I had in feedback - that author strings were causing hits.
* If you insert a wildcard at the beginning or middle of a word, then full text search does not work so the search reverts to a simple indexed search.
* Includes a highlighted version of the search term (showing which bits matched the search) in the response.
* Option to enable 2+3 abbrevations (which only works when you enter exactly 5 chars).
