### ISSUE TITLE
Error with bulk verification

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#276]
Marked as urgent as affect the verification system.

Reported by Pat Batty, attempting to bulk verify for an individual recorder (Stewart, Thomas).  Occurs through Bulk edit option and when filtering and using 'Verify grid'

Error message reported:
<div class="error">cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.<br/>URL:https://warehouse1.indicia.org.uk/index.php/services/data_utils/bulk_verify<br/>Server response<br/>{"error":"general_errors.Array to string conversion","code":8,"file":"D:\\web sites\\warehouse1\\application\\libraries\\ReportEngine.php","line":1012,"trace":[]}</div>{"error":"general_errors.Array to string conversion","code":8,"file":"D:\\web sites\\warehouse1\\application\\libraries\\ReportEngine.php","line":1012,"trace":[]} records processed

**Comment by johnvanbreda** [comment]
This should now work.

**Comment by DavidHepper** [comment]
This issue appears to have returned for Pat since the Warehouse 2.0 release. She was using Verify Grid for single recorder "Inskipp, Carol" in Scotland. 
The error line number differs from before:
`<div class="error">cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.<br/>URL:https://warehouse1.indicia.org.uk/index.php/services/data_utils/bulk_verify<br/>Server response<br/>{"error":"Array to string conversion","code":8,"file":"D:\\web sites\\warehouse1\\application\\libraries\\ReportEngine.php","line":1259,"trace":[]}</div>{"error":"Array to string conversion","code":8,"file":"D:\\web sites\\warehouse1\\application\\libraries\\ReportEngine.php","line":1259,"trace":[]} records will be affected. Are you sure you want to proceed? `
