### ISSUE TITLE
Queried records - inconsistent status or terms on records?

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#279]
Currently, if I query a record via the Verification Grid the record is flagged with the yellow "Queried" icon. If I mouse over this icon I see the text "Not reviewed, query raised".  However, if I look at the "Record Status" field in the "key Facts" box I see the record status as "Not reviewed".

This raises a couple of questions:

1) Is this difference between "Not reviewed, query raised" and "Not reviewed" purely down to the text display on this screen?

2) Does the record actually appear on reports and record statistics as "Not reviewed".  If so then this is incorrect as the record has been set to "Queried" status.  This could have implications for things like "backlog reporting" etc etc

3) Particularly with reference to the "standard" verification terms being developed by the NBN Data Verification Working Group, is this terminology of "Not reviewed" correct?  The record has been reviewed and has had a query appended to it.  Should not these records have the status of either "reviwed, requires confirmation" or just "requires confirmation"?

**Comment by johnvanbreda** [comment]
1. Yes. I agree the label in the record details pane should reflect the queried status and I've updated it to do so.
2/3 - I think we need some clarity from @kitenetter and the working group as to when a record transitions between being not reviewed and reviewed. The alternative point of view is that querying a record is part of the process of reviewing and that the record is not reviewed until the answer is received and processed - this viewpoint gives a better metric when assessing the whole process rather than just the actions taken by the verifier.

**Comment by MNSmith** [comment]
We get enough questions about "why aren't my records being verified?" and to many recorders "not reviewed" = "not looked at at all", so the terminology here is important.

I'm going to put on my working group member hat her for this comment.  In my view, records arrive onto the system at "not reviewed" status.  Any action taken by a verifier is a "review" of some sort, whether that results in a record being accepted, rejected or set to "Queried" status.  Setting a record to "queried" status indicates that the person conducting the review requires further information to process the record which, if not forthcoming over a reasonable period of time, may result in the record being set to "not accepted, unable to verify".  So, setting a record to "queried" status means that a) the review process has begun and it is no longer classed a "not reviewed" and b) flags up how many records are in the state of "limbo", which is useful for backlog reporting.  I'll be interested to hear other views but it may be worth bringing this up at the nest working group meeting.

**Comment by kitenetter** [comment]
Currently, a queried record is given an additional independent "Queried" tag, while its verification status remains as "Unconfirmed: not reviewed".

I agree with Matt that classing queried records as "not reviewed" (in verification status 2) is confusing, but it does seem logical to have queried records under "Unconfirmed" as a verification status 1.

As things stand, under the status 1 category "Unconfirmed" our only options for status 2 are "plausible" or "not reviewed". I don't think we should use "plausible" for queried records.

So if we are to change things, our only option seems to be to add a third status 2 term under "Unconfirmed" - presumably this third term could simply be "queried".

When we carried out the review of terms in 2015 we agreed that queried records should be handled independently of the verification terms. I can't remember all the reasons put forward for that view, but I can see that the queried status is different to the other terms, in that it is a temporary flag rather than a verification decision. And of course there are downsides to adding to the existing set of terms: it makes an already fairly complex system more so, and at a time when the idea of standardising verification terms is still quite new it could be counter-productive to make another change.

As far as I can see we are left with a binary choice:
1. keep things as they are
2. introduce an additional status 2 term "queried"

At the moment I feel that option 1 has the fewer disadvantages. Can anyone suggest any further options?

**Comment by johnvanbreda** [comment]
Personally I think the approach as it stands is correct. The queried status is not a verification decision as such, it's a verification action. If I am given a document to review and I decide to ask questions about it, I would describe the review at this point as "in progress" rather than "completed", at least until the responses have been received and actioned. 

However I also agree with Matt, in that where any report is given that gives a record's status, the Query flag is an important part of this status especially where the report output might be used to assess verifier performance. Otherwise there is a risk of misunderstanding "not reviewed" to mean "not actioned" which would be incorrect. 

If we ever start sending unverified records to the Atlas then we certainly want to ensure the queried flag is included with the record.

Other than that, are there any reports coming out of iRecord where the queried flag should be included but isn't?

**Comment by kitenetter** [comment]
Queried status is now being included alongside the two verification statuses in the standard downloads.

We do need to consider this for NBN Atlas DwC reports, as some partners are sending unverified records to NBN. Will pick that up in #386.

Not aware of any other reports where this is an issue, so will close for now.
