### ISSUE TITLE
Verification grid sref column output

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#280]
The iRecord verification grid currently displays the spatial reference as it was entered by the recorder, to ensure that the full precision is available even for blurred records. This has the disadvantage of the output format varying for each record, e.g. there are records shown in WGS84 or OSGB even for a single locality. In the reporting cache tables there is a column output_sref which contains the sref in a standardised format depending on the position on the map, e.g. references over GB are always shown in OSGB and records over Ireland are always shown in OSIE. This makes the display more consistent but the output is then blurred and asian hornet records (for example) are shown as a 100km square name for example.

So, the requirement is to add a new full precision version of the output_sref column and to switch to this report column in the output when the user has verification rights. The output_sref full precision column can then be used in the verification grid.

**Comment by MNSmith** [comment]
John, it might be worth checking the point about blurred Asian Hornet records.

Looking at the AH verification grid and map, the only 100k mapped dots are those where we had a problem with the geo-location format earlier in the year when we were only seeing the OS grid square letters  - eg SU or SK.  This meant that we saw 100k blue squares which blanked out the whole map and hid previous underling records.  While the geo-location was fixed those records continued to display at 100km square level.  This problem was one of the reasons I raised an issue about only displaying the record being examined on the map.  As this request now appears to have been put in place ( thank you) this problem has now gone but the few records affected will still carry the 100k dot code.

Current incoming AH records are not blurred, if I click on them I am taken to the exact geo-location specified in the record on the map.  The same applies to records verified as "correct".

**Comment by johnvanbreda** [comment]
Matt, agreed - I was using this as an example since I'd been working on the requirements for the new NNS alert workflow functionality which will result in all asian hornet records being initially blurred. The principle in the original post still applies though.

**Comment by kitenetter** [comment]
@johnvanbreda I think this can be closed but re-open if not!
