### ISSUE TITLE
Unable to view recorder Experience details from form 27|64

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#281]
One of my verification grids is filtered on "Aculeates; UKBMS" with data coming from form 27|64.  On the "Experience" tab I can see the various numbers for verified and unverified records for "Species X" on the box, but clicking on these numbers returns an empty records list.

**Comment by johnvanbreda** [comment]
The Explore page, used to show the data underlying the numbers on the Experience tab, is limited to records which are viewable in public reports on iRecord. Hence the UKBMS dataset does not appear.

@DavidRoy & @kitenetter do you agree a potential solution is to set up a "verification explore" page which displays all records available for verification, to use when you click on these linked? A savvy verifier would be able to change the URL to view any other verifiers verification records though.

**Comment by DavidRoy** [comment]
I would support a 'verification explore' page as you suggest.  I think the risk of misuse is low.

**Comment by kitenetter** [comment]
I agree with @DavidRoy - if we do want to reduce the small element of risk, are either of these feasible:
- Set up the 'verification explore' page so that it picks up on the current user's verification filter (but this may be problematic for verifiers with multiple filters)?
- remove any download options from the 'verification explore' page?

**Comment by johnvanbreda** [comment]
Done
