### ISSUE TITLE
Recorder's data unavailable after changing email address

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#288]
See iRecord forum post
https://www.brc.ac.uk/irecord/node/7152#comment-3943

@johnvanbreda please can you advise

**Comment by johnvanbreda** [comment]
Response added to forum:
"It looks like in 2014 you were given restricted rights to download all butterfly records, but the filter was set up incorrectly so it actually applied a limit to your reporting rights instead of download rights. I've corrected this filter so your reporting rights are now back to normal and the records should appear OK now."
