### ISSUE TITLE
Question: "Input still in progress" records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#342]
Every so often we get people enquiring why their downloaded data includes records with verification status "Input still in progress" or "Data entry in progress". Three questions:
1. Am I correct in saying that "Input still in progress" equates to "Unconfirmed: Not reviewed"?
2. Am I correct in thinking that if a verifier assigns a verification status to the record that will over-ride the "Input still in progress" flag?
3. Is it worth running a database query to change the status of all "Input still in progress" records to "Unconfirmed: Not reviewed"?

Most of these appear to relate to old records that have been imported, e.g. via UKBMS or NPMS. Two example records:
- https://www.brc.ac.uk/irecord/record-details?occurrence_id=1714054
- https://www.brc.ac.uk/irecord/record-details?occurrence_id=1508794

**Comment by johnvanbreda** [comment]
Record status=I (input still in progress) was intended to allow capture of partially complete record forms, with the recorder then returning to complete them at a later date at which time the record status should be set to C.
This status could have been used by mistake (especially if using the importer where you can choose the record status) and in this case it would be fine to update the status to C.
It could also have been used deliberately, though I'm not aware of any datasets doing this in the UK.

**Comment by DavidRoy** [comment]
Some early implementations of the transect/plot recording forms used this status so there are occurrences in the database with record_status = I.  This affects early UKBMS and NPMS mainly.  This needs correcting but has never been prioritisedpartly because of the potential implications for the scheduled tasks.

**Comment by johnvanbreda** [comment]
Regarding the scheduled tasks, as this is a simple flag change for unverified records there are no implications if we just do a manual update of the cache tables, rather than rely on scheduled tasks. 
I suggest we identify a list of the surveys which have this flag for some records and double check we are happy to make the change for each of them, then do a simple update query on the occurrences and cache_occurrences_functional tables.

**Comment by JimBacon** [comment]
For info, I am deliberately using a record status of I for the honey monitoring scheme at present. Mind you, this is on the sample.record_status, not the occurrence, so it may not crop up in any work done on this.

**Comment by johnvanbreda** [comment]
Here's the raw count data from the warehouse for records with record_status=I:
website_id;website_title;survey_id;survey_title;count
7;"Norfolk Biodiversity Information Service";121;"NBIS Lepidoptera Transects survey";160
7;"Norfolk Biodiversity Information Service";292;"CWS digitisation species name check";31290
23;"iRecord";133;"Moors for the Future Bumblebee Transects";948
23;"iRecord";374;"iRecord App";2
27;"UKBMS";64;"UKBMS Transects";573067
27;"UKBMS";170;"UKBMS Timed Counts";257
31;"iRecord";374;"iRecord App";1
32;"National Plant Monitoring Scheme";229;"(inactive) Old Paths survey";11813
44;"Consultants Portal";160;"Amphibians";3102
44;"Consultants Portal";161;"Bats";258
44;"Consultants Portal";168;"Birds - breeding";87
44;"Consultants Portal";248;"General records";1565
45;"Lincolnshire Environmental Records Centre";153;"LBC Garden Bird Survey";8508
51;"GIGL";186;"Royal Parks Survey";13
86;"SpotABee";405;"Spot A Bee";17

**Comment by kitenetter** [comment]
Based on comments above I think we could and should update the status for the UKBMS and NPMS records. However, I'm not sure about the others, and would be nervous of changing them without knowing more about the background (i.e. has the "I" status resulted from forms/imports being given an incorrect code, or was there some other reason).

**Comment by kitenetter** [comment]
Another consequence of these Record status=I occurrences is that they get included in any data exports to NBN where the export specifies that unverified records should be included (or to be more precise the specification is for queried and rejected records to be excluded).

I don't think we should be exporting Record status=I occurrences because:
- They end up with a null entry in the identificationVerificationStatus attribute, and I'm not sure how NBN handles this
- I believe I'm right in saying that Record status=I occurrences had hidden from the iRecord verifiers, and these records are therefore not only unreviewed, but also unreviewable!

I propose these actions:
1. Exclude Record status=I occurrences from the NBN exports - I guess this could either be done in the NBN export report, or it could be added to the general iRecord filters, so that if some has chosen to filter for "Exclude not accepted records" or for "Exclude queried or not accepted records" the Record status=I occurrences also get excluded.
2. Update the Record status=I occurrences for those datasets where there is no reason to exclude the data. I think this ought to be done for website 27;"UKBMS", but I don't know enough about the background to why this Record status was used for the other websites.

One issue with updating the UKBMS data is that presumably this would cause a large number of records to appear for verifiers. If we do update the UKBMS record status, does this trigger the auto-verification process, so that a large proportion of these records would then flow through as auto-verified?

[Of the other websites listed, I suspect some of them have used Record status=I occurrences for data that is not thought to be high quality enough to be exposed for verification; but that's unlikely to apply to all of them, and the next priority for me would be to work out why so many Consultants Portal records have status I]

**Comment by DavidHepper** [comment]
I'm not qualified to comment on the detail of how this should be fixed but offer a few observations:
- In the raw counts list above, website_id values 23 and 44 have the same website_title "iRecord". Is this legal?
- Does your raw counts list include records with a visible progress value of "Data entry in progress" or only of "Input still in progress"?
- Half a million records with status 'I' in *UKBMS Transects* looks worrying to me. I think you're right to be concerned that they might auto-verify.
- One *UKBMS Transect* record with ID *2317989* was entered in 2015 and verified on 18/04/2018, though no verifier name is recorded. (It is Odonata in Surrey so was in fact verified by Bill Budd.) These records _are_ seen in Verify (and can be verified) but only by changing the filter to show 'All records'. This verified record now shows a green tick in the ID column but a cogwheel in the Auto check column.
- Surely dropping completely any weird (obsolete?) verification status and progress status values such as 'I' should be a priority in order to simplify and speed up queries.
I hope this is constructive.

**Comment by kitenetter** [comment]
This is being addressed in #670 - closing.
