### ISSUE TITLE
Additional filtering required for NE data

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#351]
NE wish to be able to filter out the data that they are adding to iRecord, both for their own download purposes and for export to NBN. Most of this data will be loaded into one of the NE-specific surveys, which our current filters allow us to select. But some of the data will be added via the iRecord app and linked to an NE Activity. So the requirement is for our filters to be able to specify a set of records linked to a particular Activity, in addition to those in a particular survey.

Ideally we should be able to set up a single filter that picks up all records from all NE surveys **_AND_** all records from all NE Activities (bearing in mind that some records will be linked to BOTH the NE survey and an NE Activity).

Beyond the NE requirement, having the ability to filter records generally by their linked Activity will provide additional flexibility for reporting and downloading.

**Comment by johnvanbreda** [comment]
@kitenetter The NE case is special I think, so would it be worth a custom version of the Explore page linked to their activity which provides the filter for records in their survey OR activity?

Isn't the latter requirement met by adding an explore report to the activity so you can follow the link in the list of activities?

**Comment by kitenetter** [comment]
@johnvanbreda my understanding is that NE need to be able to work with a set of "all NE data" that encompasses:
- all records that have been added to the "Natural England Surveys" survey
- AND all records that have been added to the "NE NNRs" survey
- AND all records that have been added to one of the NE Activities (most of which will go into the "Natural England Surveys" survey but some will originate from the app)

NE have two priorities:
- to allow Andy Webb to download "all NE data" so that he can track what is happening to the NE project as a whole
- to allow iRecord to export "all NE data" to NBN. 

I'm not sure that a custom explore page by itself will achieve those two priorities will it?

(And for the more general 'nice-to-have' requirement, we are sometimes asked to provide a verification filter for a particular activity and in such cases it would be good to be able to filter for activities in the same way one can for surveys - but that isn't essential to fulfil the NE requirement.)

**Comment by johnvanbreda** [comment]
As I think this is a slightly unusual issue I've solved it using a couple of custom reports rather than updating the core code to cope with the filters. So, now the DwC export configuration points to a report with this custom filter and the filter attached to the export itself is actually an "all records" filter so the report does all the filtering. Similarly, there is a new download page which Andy can access (Explore > Download > Download Natural England records) which is linked to a download report with this custom filter.

For information, the custom filter in the report SQL is as follows:
```SQL
where o.website_id=23 
and (
  o.survey_id in (97, 509)
  OR o.group_id in (973, 978, 1120, 1275)
)
```

Therefore if there are new groups or surveys to include, then the custom filter in the following 2 reports will need updating:
* brc_reports/reports/projects/irecord/occurrences/filterable_dwc_nbn_occurrences_ne.xml
* brc_reports/reports/projects/irecord/occurrences/filterable_occurrences_download_ne.xml

These are in the BRC reports git repository.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - that's all looking very promising. At the moment I'm getting quite a different result from Andy's custom download compared to the DwC export. Is there a reason for that or do we need to adjust one or other of the queries? I can't see any reason why the DwC export should not include the higher total.

(There are 11 rejected or queried records in the Andy Webb download that should be excluded from the DwC export, but I can't see any other reasons for the difference.)

![image](https://user-images.githubusercontent.com/16039111/41235802-7ad1c65e-6d87-11e8-85c8-9ffc9cacb125.png)

**Comment by johnvanbreda** [comment]
2 things going on here:
* Zero abundance records are exluded from the DwC archive (which I suspect is correct).
* A database quirk means that records of now redundant taxa (according to the recent UKSI update) were being excluded. Now fixed.

**Comment by kitenetter** [comment]
@johnvanbreda in the "filterable_occurrences_download_ne.xml" report, can we add another column to display attribute "Survey reference code" (attr_ID 1144).

This is the same attribute that gets output as "datasetID" in the NBN DwC report.
