### ISSUE TITLE
Responsive displays

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#37]
BDS: - The use of iFrames by the Verify page is really hard for anyone without an extremely high screen resolution. Nested scroll bars, both vertically and horizontally are seriously problematical. My own testing indicates: 
- A vertical resolution of 1600 px would be necessary to avoid the outer vertical scrollbar. This is not a realistic prospect so vertical scrolling is clearly necessary. Fair enough. 
- A horizontal resolution of 1580 px is necessary to avoid the recordset list horizontal scrollbar. Avoiding this is highly desirable since the scrollbar is typically not even visible without scrolling vertically first to bring it into view! 
- This indicates the optimum screen size for Verifiers to be around 1600 x 1020, which is nearly Full HD / 1080p. Few laptop screens are either capable of this resolution or readable without a magnifying glass when set to it. If an external monitor will always be needed we need to say so.

**Comment by johnvanbreda** [comment]
Have enabled responsive tables on the list of records which helps a lot with narrower screens. Still more to do on this though.

**Comment by DavidHepper** [comment]
This is still highly desirable. Having nested *vertical* scroll bars, one for whole screen and a second just for the grid, could be avoided at most times by giving the user the choice of the number of records shown in a page of the grid. 
For example, on my 23" monitor (1680 x 1050 @ 125% dpi) I would choose to show 9 records rather than the current fixed value 30. This would allow the paging control buttons and the indicator "Showing records x to y of z" to be visible without scrolling even if a couple of grid rows are expanded.

**Comment by DavidRoy** [comment]
@JimBacon can you look at this one please.  It is for larger screens, so a different responsiveness question than we've been concerned about so far (i.e. most effort has been for mobile devices)

**Comment by kitenetter** [comment]
Hopefully less of an issue with the ES verification page. Closing.
