### ISSUE TITLE
Change from email address on iRecord verification

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#387]
Change to “verifier@brc.ac.uk” rather than the noreply one it currently is.

There is a change in the develop branch that allows the email to be provided in the verification page configuration.

**Comment by JimBacon** [comment]
At least noreply indicates that you should not bother trying to reply to the email. Using a phoney email is worse, in my view, as people will assume they can reply and will be more frustrated than before when there is no repsonse.
...Or has someone set up an email server on the brc domain that I don't know about?

**Comment by BirenRathod** [comment]
I was going to mention the same thing because no email with that address has been set up yet. At least I haven't got that information.

**Comment by johnvanbreda** [comment]
This is the "from" header, not the reply-to. The verifier's email goes in reply-to so there is no need for this account to exist.

**Comment by DavidHepper** [comment]
I don't understand the implications of this. Is this address ever stored within the record or is it only for notifications?

**Comment by kitenetter** [comment]
@DavidHepper this is a presentation issue: currently, if a verifier sends an email (from within iRecord) to query a record, the recorder receives an email that appears to come from "noreply@brc.ac.uk" (or it might be ceh.ac.uk, I can't remember which). In fact the recorder **can** reply to this email, and it will be directed back to the verifier's own email address, but the issue is that recorders may be discouraged from replying to the email because they think the "noreply" prevents them from doing so. The suggested change is simply to remove this discouraging element.

**Comment by DavidHepper** [comment]
Thanks! That's a great improvement. I support the change to “verifier@brc.ac.uk”. Sending 'from' “verifier@brc.ac.uk” is good for deliverability: mails should pass SPF, for example, and BRC could encourage people signing up to iRecord to whitelist this simple address.

**Comment by johnvanbreda** [comment]
Now applied.
