### ISSUE TITLE
RSPB boundary filter fails to download records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#393]
I've just set up a download filter for records overlapping the RSPB Lakenheath Fen boundary:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=4991

I then masqueraded as Will George in order to run the download, but after what felt like several minutes I got a timeout message:
`{"error":"general_errors.There was an SQL error: ERROR:  canceling statement due to statement timeout - \n  SELECT  distinct on (o.id) o.id as \"occurrence_id\",\n'iBRC' || o.id as \"recordkey\",\no.external_key as \"external_key\",\nsnf.website_title || ' | ' || snf.survey_title || coalesce(' | ' || snf.group_title, '') as \"source\",\ncase when onf.sensitivity_precision is null then o.sample_id else null end as \"sample_id\",\ncttl.preferred_taxon as \"taxon\",\ncttl.default_common_name as \"common\",\ncttl.taxon_group as \"taxon_group\",\ncttl.kingdom_taxon as \"kingdom\",\ncttl.order_taxon as \"order\",\ncttl.family_taxon as \"family\",\no.taxa_taxon_list_external_key as \"taxonversionkey\",\no.taxa_taxon_list_id as \"taxa_taxon_list_id\",\ncase when onf.sensitivity_precision is null and onf.privacy_precision is null then o.location_name else 'Sensitive. Lat long is approximate.' end as \"location_name\",\nsnf.public_entered_sref as [... etc. etc.]`

Is that a problem to do with current server capacity or if there a more generic problem running download queries against relatively complex boundaries? There should only have been around 1,700 records involved.

**Comment by kitenetter** [comment]
I've just tried again and this time the download succeeded. If somebody made changes, thank you! If not it appears to have been a temporary glitch. Closing.

**Comment by kitenetter** [comment]
I had hoped that this was a one-off glitch, but Will George at RSPB reports that more often than not the download takes 5-10 minutes and then results in the SQL error message as shown above, so it looks like we do have an underlying issue here.

**Comment by johnvanbreda** [comment]
@kitenetter One thing I've just discovered. The current download query currently adds a join to the People table, in order to get the ID values for the "recorder_person_id" and "determiner_person_id" fields. These fields are included in the download with the intention that giving people an ID value can be beneficial rather than relying on a name which might not be unique, especially if trying to use the download to import into different systems. In the case of this particular query, removing the 2 fields and the join to the people table makes a huge difference to the performance - it seems that the additional join "tips the balance" causing the query optimiser to fail to choose a good plan. The result is an increase from ~8s to over 6 minutes for the query!

I tested a few other example download queries and found that the change was less obvious - there was an improvement of up to about 10% or so. 

So - the question is, are these fields actually being used in the download files, or can I remove them? If they are being used, then perhaps they should be added to the reporting cache tables.

**Comment by kitenetter** [comment]
Difficult to know if they are being used - I don't use them, and I don't think anyone has ever mentioned them to me, but of course there may be people relying on them. Presumably we could remove them for now, and if anyone objects they could be added back in via the cache tables at a later point?

**Comment by johnvanbreda** [comment]
Fields removed - download seems much faster at least for this example.
