### ISSUE TITLE
Extend download functionality

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#4]
**Needs some discussion, but preliminary discussion of issue is:**
It is currently possible to download all available fields for records, but only by choosing the download format that matches the route by which the records arrived on iRecord. It is very difficult for people downloading data to know what that route was, and therefore to select the appropriate survey to download.

Option 1: One way of making this work more effectively would be to make it clear to people which surveys contain records for their area of interest. So that if, for instance, when downloading records for soldierflies, it would be good to know which surveys contain soldierfly records, and ideally how many records for each, and what additional data fields are available that aren’t in the standard download. I can then make an informed decision about whether I want to deal with the complexity of downloading lots of separate datasets, or whether I am happy to compromise and just do a standard download.

Option 2: An alternative would be to expand the fields available in the standard download, so that any custom fields from particular surveys were added to the right-hand side of the download spreadsheet, but this could rapidly result in spreadsheets with an excessive number of columns and similar data held in different columns.

Option 3: A better solution might be to do some mapping of custom fields to standard fields, so that data arriving in a custom field in one survey format gets included if there is An equivalent field in the standard download.

**Comment by johnvanbreda** [comment]
Option 3's approach already exists through the idea of attributes having a "system function". This allows attributes with different labels and structures to be flagged as having the same semantic meaning, e.g. the abundance or habitat data. 
So, should we try to examine existing fields to look for commonality, then map to existing (or new if necessary) system functions so they can be output in the same columns?
System function tagged columns will output with very good performance when we adopt the new cache structure.

**Comment by kitenetter** [comment]
I'll look at mapping the existing fields, and will update the download specs document from previously.

Should we be looking to have:
**Option A**: a pre-defined download format that includes as many of the relevant fields as possible, but doesn't give users any choice in what they get (other than filtering for a set of records)? 
Or:
**Option B**: is there scope for setting up a download function whereby users can choose what fields they wish to download in which order (e.g. via a set of tick-boxes)?

If we go with option A I think we will need to carry out some consultation with NSS and LERCs in order to ensure that we have some consensus and avoid further requests for the format to be adapted in future. But if option B is feasible I think we can avoid consultation on the basis that users will have the choice.

**Comment by kitenetter** [comment]
Additional requirements (via Bat Conservation Trust):

- Allow iRecord to export records to the Gateway at the resolution at which the recorder has agreed to make them publicly available. 
At the moment a recorder can choose to ‘blur’ their records on iRecord if they are sensitive. However, when the data is exported to the NBN Gateway it is exported at the original unblurred resolution and the record is flagged as sensitive. As a result the record is invisible to everyone apart from those granted enhanced access to the iRecord data set. If sensitive records could be instead be exported at the ‘blurred’ resolution they could be made publically available rather than hidden. This need will become even more critical with the switch to an ‘Atlas..’ portal without enhanced access.

- Allow iRecord to export the full range of attributes collected to the Gateway. 
At the moment only a limited set of standard attributes are exported to the Gateway. For bats this means critical information such as the record type (roost, in flight etc.) and how the species was identified is lost. This issue also affects other taxon groups. The utility of the data available on the Gateway and future portals would be vastly increased if these additional attributes could be included when the data is exported.

**Comment by kitenetter** [comment]
MH to separate into short-term bug fixes and longer-term solutions, and to separate out issues with NBN exporting.
