### ISSUE TITLE
Development of download reports for large organisations

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#401]
This arises from RSPB's request to be able to download the iRecord data from all their reserves, and is likely to be needed by other organisations in future. At the moment we don't have a simple way of setting up a download for multiple sites, and there are performance issues to consider (e.g. #393). 

One option is to build on the automated reporting functions that John developed for exporting to NBN - that seems like a good model to use (RSPB would like to pick up a refreshed dataset every six months or so). But we'll need a slightly different report (e.g. to include verifiers' names) and to address the multi-site issue.

**Comment by johnvanbreda** [comment]
You can already set up a filter with multiple site boundaries, then use the filter in an Indicia auto export. Also you can change the output format to CSV and change the report used. 
My main concern is performance - have you tried a report against all RSPB boundaries? We may need to add the boundaries to the indexed sites.

**Comment by DavidRoy** [comment]
I recommend adding 'organisation' boundary-sets to the indexed sites.  Are there implications for doing so?

National Trust boundaries also to be added to indexed sites

**Comment by kitenetter** [comment]
Setting up filters for "all RSPB reserves" is a time-consuming task with each individual reserve being added one at a time. Is it worth developing a function to select "all boundaries of a particular type [such as RSPB]" or is that more effort than the resulting benefit would justify?

**Comment by johnvanbreda** [comment]
At the moment adding an indexed site requires a new database column per type, which has been OK when there have been only a few administrative indexed site types. If we move towards more flexibility in the types of sites that are indexed then I'd recommend a structural change to the site indexing so we don't need to do this. It would also fix the issue where a record can't exist in multiple vice counties if it overlaps a boundary (at least not for the purposes of report queries that perform well). 

The suggested change is to:
1) Add a location_ids column to cache_samples_functional and cache_occurrences_functional. This would be an integer[] datatype allowing an array of integers to be linked to a record or sample. Add an index to this column.
2) Update the contents of this field to store the indexed sites the sample intersects with (using index_locations_samples as a source).
3) Drop the index_locations_samples table
4) Remove the location_id_* columns from cache_samples_functional and cache_occurrences_functional.
5) Tidy up the code for populating the location_id_* columns and index_locations_samples columns, so that the links go in the new location_ids column.
6) Remove the code which generates the script required to add new indexed sites.
7) Update all reports and code which use index_locations_samples or one of the location_id_* columns to use the new location_ids array column.

This would result in things being a bit tidier than they are now and at least the same performance (better for a few cases) with the ability to add new indexed site layers without updating the database schema.

**Comment by DavidRoy** [comment]
This use of Indicia is growing so I would support this change.  Is it sensible to undertake this work alongside other warehouse updates due to be implemented?

**Comment by johnvanbreda** [comment]
Yes, as this is a structural change including it in v2 makes a lot of sense.

**Comment by johnvanbreda** [comment]
@kitenetter we could use a database query to pull out the full list of IDs, then modify the filter definition.

**Comment by johnvanbreda** [comment]
The structural changes required (removal of index_locations_samples, removal of location_id_* fields and replacement with cache_occurrences_functional.location_ids which keeps all the indexed locations in one place are now committed to the develop branch.
