### ISSUE TITLE
Inconsistent access to record editing for an individual user

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#410]
User "juliawilson" (Warehouse User ID: 85080) has added records to iRecord using a custom recording form (https://www.brc.ac.uk/irecord/enter-bss-urban_flora?group_id=150&implicit=) that feeds in to the "BSS Urban Flora project" survey.

When Julia goes to her "My records" page, the records are all listed and are all viewable. But it appears that only some of them are editable - others produce the message "Access Denied. You are not authorized to access this page."

Example of a non-editable record: occurrence_id=7068229
Example of an editable record: occurrence_id=7524556

I can't see why some records are editable and others aren't - what am I missing?

**Comment by johnvanbreda** [comment]
The difference between the 2 example records is the one which is editable does not have the input form path stored with the record - normally iRecord based forms will do this should store the input form, so I don't know why they are different. Is there anything special about the way the record was added?

Without knowing the input form, iRecord diverts the edit link to the edit-generic-record page which works OK (though the form looks different to the originall BSS Urban Flora form).

With the input form known, then the link for the record ID goes to the correct BSS Urban Flora form, though it does not embed the group ID in the link. As the form is locked so that it can only be used in the BSS Urban Flora group context, the form rejects the request as unauthorised since it expects &group_id=150 to be in the link. If you add this to the link, then it works. Also, if you use the Activity Explore report to access the edit link instead of My Records, then it also works. So there are 2 workarounds possible - either add &group_id=150 to the URL or access the link via the Activity Explore.

There is a wider fix required to the My Records page (and All Records when viewing your own data) - the links generated should include &group_id=... for group linked records. I'll let you prioritise that before working on it.

**Comment by kitenetter** [comment]
Both of the two record examples seem odd to me, in different ways.

**Example of a non-editable record: occurrence_id=7068229**
This one must have been entered via the Activity, but it cannot be accessed via the Activity's Explore report, because the record is at a location that is not within the polygons used for the activity's reports (which are much more restrictive than the activity's data entry pages). It seems that the only way to edit this record is to manually add "&group_id=150" to the edit URL obtained from the main Explore - My Records view.

So this is an anomaly that arises from the way in which the Activity has been set up and used. It would be solved by the wider fix that John describes.

**Example of an editable record: occurrence_id=7524556**
I don't know how this was entered. It has ended up in the survey that is associated with the activity ("BSS Urban Flora project"), but appears not to be linked to the Activity. So it appears in the activity's explore report, but cannot be edited from there ("You are trying to access a page which is not available for this group"). It can only be edited from the Explore - My records page, i.e. without the "&group_id=150" parameter.

It feels unhelpful for these related records to require completely different approaches to being edited, but I can't work out what a full solution would be. Hopefully it is a one-off that is confined to this particular activity set-up.

**Comment by kitenetter** [comment]
Now being looked at under #882 - closing this one.
