### ISSUE TITLE
Simplified activity summary report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#43]
The iRecord butterflies app simplified summary is on the BC website now.
http://butterfly-conservation.org/8803/irecord-butterflies.html
based on 
http://www.brc.ac.uk/irecord/butterfly-app-summary-2016-simple?external=t

1 issue to resolve.  The species table should be restricted to 10 items.
1 suggestion.  Could this type of report/form be made available to any activity

**Comment by johnvanbreda** [comment]
I've limited the species count to 10.

I've also implemented an equivalent page which is for linking to any groups. An example is http://www.brc.ac.uk/irecord/simple-activity-summary?group_id=438&implicit=f. However note that there is an issue in the client PHP code which prevents the list of species being filtered appropriately for the group (https://github.com/Indicia-Team/client_helpers/issues/31) so this will not work properly until that issue is fixed and deployed.
