### ISSUE TITLE
How to edit taxon list in verification filters?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#451]
This filter was set up to include about 8 families of slug:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=5539

The verifier has asked if we can remove one of the families, but there doesn't seem to be an option for doing that - when I look at the "What" part of the filter it no longer shows any information about the families included.

Will I have to create a new filter from scratch or is there a way of editing the existing one?

**Comment by kitenetter** [comment]
For now I'm setting up a new verification filter for slugs, since I can't see how to edit the existing one.

When I try to add family Arionidae, I get three versions of it:

![image](https://user-images.githubusercontent.com/16039111/51673082-0be3af00-1fc5-11e9-861f-41faa3b9ad36.png)

Why have we got three? Do I need to add all three to the filter to ensure that is includes the required species?

**Comment by johnvanbreda** [comment]
Latter issue fixed in the code. The 3 names are synonyms with different authors, but the same species name, so it doesn't matter which you pick. The first is the correct accepted name.
When the develop branch is next applied, the species search will detect the duplicates and exclude the unnecessary synonyms.

**Comment by kitenetter** [comment]
@johnvanbreda I think this can be closed?

**Comment by johnvanbreda** [comment]
Agreed.
