### ISSUE TITLE
App photos not getting saved to warehouse

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#454]
Since sometime on 5 December, the majority of photos attached to app records are failing to display within iRecord (error: "The requested content cannot be loaded. Please try again later.").

I just tried to upload a photo myself, and the app told me it had timed out; however, the record has appeared on iRecord, minus its photo:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=8700211

The oldest instance of this problem that I can find is:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=8685908

Not sure if this is an iRecord issue or an app issue. Marked as urgent because we are accumulating a potentially large number of records with missing photos.

**Comment by kazlauskis** [comment]
Hi @kitenetter, OK I will look into this asap.

**Comment by johnvanbreda** [comment]
Hi @kazlauskis - I've already spotted the issue and fixed it. Biren has changed the location of the interim image upload folder so that it is in the sites/default/files location rather than the module location. This is needed for the eventual move to Pantheon. However the indicia API module had code in it which appended the relative interim_image_folder path to the client_helpers folder, which is now wrong. I've fixed it by using data_entry_helper::getInterimImageFolder which can generate absolute paths that are correct.

**Comment by kazlauskis** [comment]
Well done @johnvanbreda, thanks for the fix. @BirenRathod when doing changes to the website that could potentially affect the apps, I am more than happy to test if everything still works with the apps before going live.

**Comment by BirenRathod** [comment]
@kazlauskis 
I already done those changes on Pantheon separately. so sites on Pantheon works fine. What we need is the code should be commit into repository, so it will deploy equally every where.

**Comment by johnvanbreda** [comment]
@BirenRathod The changes to upload.php have been replaced by a tidier version which is aware of configuration in helper_config.php, by passing through a destination parameter. Ideally you should not need a special version on Pantheon anymore. This is not the same code as the indicia-api - the problem was that the code in indicia-api assumed the upload folder for interim files was inside client_helpers, when it is now in files. Indicia-api has now been fixed.

**Comment by kitenetter** [comment]
Question: is it possible to retrieve the photos that have failed to display, or are these lost? There aren't many records affected, but would be good to know if we do have any options for the few that are.

**Comment by johnvanbreda** [comment]
@kitenetter Unfortunately no, the images are lost on the server. They are still on people's devices though unless they've deleted the records, though I've no good ideas for a simple way to recover them.

**Comment by kazlauskis** [comment]
We can do some hacky fix to reupload the pics from the iRecord App, but this would take some time to build in.

**Comment by BirenRathod** [comment]
> @BirenRathod The changes to upload.php have been replaced by a tidier version which is aware of configuration in helper_config.php, by passing through a destination parameter. Ideally you should not need a special version on Pantheon anymore. This is not the same code as the indicia-api - the problem was that the code in indicia-api assumed the upload folder for interim files was inside client_helpers, when it is now in files. Indicia-api has now been fixed.

Of course I don't need a special version of code on Pantheon after these changes. Thanks @johnvanbreda for making these changes.
