### ISSUE TITLE
UKBMS records remaining in verification queue

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#460]
User Harry Clarke is butterfly verifier for Surrey. He has reported a number of issues since 13 December:
His verification grid is currently showing 129,457 records. Many of these are UKBMS transect records that pass all autochecks - my understanding was that auto-verification was being applied to these, and that they should not therefore be in the queue for manual verification?
If I masquerade as Harry I am able to navigate through all 129,457 across 4,316 pages; however, Harry reports that once he gets past page 16 the system is telling him there are no more records:

> I have no problem is viewing the records online on the Verify page, and setting the filters, which first informed me that there were 5000 odd records, and then scrolling through the pages it then informed me that there are 129,457 records, which is clearly very wrong. After about page 16, it then told me no data available when clicking on the next page.

**Comment by DavidHepper** [comment]
There have always been miscalculations of the navigation controls (counts and pages). They affect me as Odonata verifier for all areas, for example if I restrict Where to one VC. Initially the Verify page shows me the number of unreviewed for the VC but it then updates after several seconds (of me doing nothing) to show the total number of unreviewed across all VCs and it shows navigation links to pages beyond the initial (accurate) set. See also #340.

**Comment by johnvanbreda** [comment]
No, it was Andrew according to the Git logs.

**Comment by DavidRoy** [comment]
@andrewvanbreda 
hi Andy, can you pick this up as part of your NPMS work.  I think the auto-verify is not working fully for both the UKBMS and NPMS

**Comment by andrewvanbreda** [comment]
@DavidRoy OK, yes I will take a look at this issue (although I haven't read through the comments yet)

**Comment by andrewvanbreda** [comment]
Hi,

The query that that collects there data looks quite simple. However I cannot check the database directly.
It looks to me like the identification difficulty would be most likely culprit. Do we know the identification difficulty of some of the records?

@johnvanbreda  I am assuming that there haven't been any changes to the way occdelta works recently

**Comment by johnvanbreda** [comment]
Hi @andrewvanbreda I don't think this is a recent problem. Running the query which the module uses to detect records that can be auto-verified returns more than a million rows, roughly equally spread through the dataset. So, I've just copied the queries out and ran them to update the status of these records. The cache update is too slow to run straight off though so I've added the updates into the work_queue table, meaning they will ripple through over the next few days. That means Harry's verification queue should dramatically shrink.
I've had a look at the list of records being passed to the occdelta table to see if there are gaps due to a bug elsewhere and there don't seem to be. It wouldn't make sense anyway because the data_cleaner module uses the same queue and the records that I've autoverified had passed data cleaner tests so they must have been processed. My suspicion though is that the auto_verify module depends on being run AFTER the data_cleaner for each record, but it isn't so doesn't work. An incoming record goes into occdelta, then goes to auto_verify which skips the record as data_cleaner_result is null (it expects true). It then goes to data_cleaner and data_cleaner_result is set to true. It doesn't then get requeued into the next occdelta batch so fails.
2 approaches to fix this:
1) Update the task scheduler to allow tasks to declare other tasks they depend on. I'm not sure about this approach because the occdelta list passed to each task can be different if they are out of sync so I think this approach improves the situation but is not a 100% fix.
2) Update the auto-verify module to use the work_queue module. It can then only accept tasks after the data_cleaner has done it's thing. I can do this but would need @DavidRoy to confirm this is a priority for me.

**Comment by andrewvanbreda** [comment]
Hi,

Yes the auto_verify module will always check for data_cleaner_result=true. I think this was always a requirement for the module.
Why is it not running after the data cleaner though? Can't the modules run order just be set?
This was tested so am surprised an issue like this never came up. Has the work_queue changed things?, I don't know so much about that area.

The module does have a mode where it can check cache_occurrences_functional instead of occdelta, switching that on would have probably processed the data you needed to process, although that mode shouldn't be left on all the time.

**Comment by johnvanbreda** [comment]
Although tested, I don't think this module has ever behaved correctly. When I ran the same query against cache_occurrences_functional, it found ~ 1.2m records that should have been auto-verified. Approx 200,000 of these were in the range 0 - 1m, indicating the problem is old, not just since the work_queue changes (which haven't really affected occdelta by the way).
There is no run-order setting for the modules - I suspect they are running alphabetically.

**Comment by andrewvanbreda** [comment]
The requirement was always that record cleaner must of passed the record. If the data cleaner is running after, then those occdelta records won't be showing as passed and will essentially be forgotten if you don't use the module's process_old_data option.
It is doing what it was designed to do from what I can see.
I don't see how the module would behave incorrectly as it just runs some sql to determine what to verify, then verifies the records.
This is easy to check if this is the issue, as you could switch the process_old_data option in the config file on the module.

How are you deciding those records should be auto-verified? Are you using the sql from inside the module?
Switch on the modules process_old_data option and see if it starts working.

**Comment by andrewvanbreda** [comment]
Actually I just checked, I included code in scheduled_tasks.php that should force the data cleaner to run before auto_verify

    // Make sure data_cleaner runs before auto_verify module.
    if (array_key_exists('data_cleaner', $sortedPlugins)) {
      $sortedPlugins = array('data_cleaner' => $sortedPlugins['data_cleaner']) + $sortedPlugins;
    }

Trying to look in Warehouse log to see if that will give me an indication of the module running order. Can't even see a reference to auto verify. Perhaps that isn't being logged. Can we check that order.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Is it possible to check the actual module running order on the live Warehouse. If the data cleaner is not running before auto-verification that would be a major problem. Am particularly suspicious this is the problem, if the same query is working on cache_occurrences.
To be clear I fear this is the issue.
1. auto verifier runs. 
2. It checks the occdelta table (new and updated records) for ones that have passed the data cleaner. 
3. It doesn't find any because the data cleaner hasn't even run yet
4. The data cleaner runs.
5. The next time scheduled tasks runs the same problem occurs, as the previous new/updated records we tried to process are no longer new, so no longer appear in occdelta. 
Any further records that are now in occdelta have not been through the data cleaner yet.

**Comment by andrewvanbreda** [comment]
Hi

I looked at this again on my own box.

Firstly I checked the running order of the modules and auto_verify was after the cache_builder and data_cleaner, so that isn't the issue.

My conclusion is actually it seems to be trying to work. It seems to be setting up the Insert/Update/Query statements OK.
However something odd seems to be happening, possibly something that didn't used to happen. It is possible the module has been affected by changes outside of it, although don't hold me to that statement.

Firstly, are there any records at all with record_decision_source='M' in the live Warehouse occurrences table? The last date of a record like this would tell us when it stopped working.

Anyway, onto my tests.
In the code, there is a $subQuery variable which holds the statement which we use to limit all the Update statements with.
e.g.
UPDATE occurrences
SET
record_status='V',
record_substatus='2',
release_status='R',
verified_by_id=1,
verified_on='$verificationTime',
record_decision_source='M'
WHERE id in
($subQuery);

I checked and all these UPDATE statements appear to be passed to the system to be run OK, so it looks like $subQuery is the likely culprit (this is re-used amongst all the statements we run, so if this $subQuery returns nothing, then nothing is run).

Now in theory I can just log this variable and then run it separately (on its own) in Postgres to make sure it is returning something.

I couldn't actually do this because it refers to a table called occDelta, which only returns new/updated records, and I can't query this from Postgres. 
(FYI the definition of $subQuery is as follows)

$subQuery .= "
    JOIN surveys s on s.id = delta.survey_id AND s.auto_accept=true AND s.deleted=false
    LEFT JOIN cache_taxon_searchterms cts on cts.taxon_meaning_id = delta.taxon_meaning_id
    WHERE delta.data_cleaner_result=true
    AND delta.record_status='C' AND delta.record_substatus IS NULL
        AND (($autoVerifyNullIdDiff=false AND cts.identification_difficulty IS NOT NULL AND cts.identification_difficulty<=s.auto_accept_max_difficulty)
        OR ($autoVerifyNullIdDiff=true AND (cts.identification_difficulty IS NULL OR cts.identification_difficulty<=s.auto_accept_max_difficulty)))";

The occDelta table is a bit like cache_occurrences but only contains the latest records.
However I could mnaully change the same query to use cache_occurrences instead. Doing this I actually found that this $subQuery query does indeed return what I had expected.
So the interaction with occDelta looks to be at fault.

Luckily the Auto Verify module has two modes.
I decided to switch the mode of the Auto Verification module on my machine to "process old records" mode.
This actually uses cache_occurrences instead of occDelta as it wants to process records from all time.

This worked first time. It verified everything I expected.
This means the problem is with the module's interation with occDelta.

So (unless John has a better idea about occDelta) I suggest we change this module to just run in process_old_data mode, but we could put a SQL limit option so it only processes a certain number of records at a time, It could also have a date cut-off.

I think actually these would be simple changes to make, although there would need to be some testing time.


@johnvanbreda Do you think my solution is sensible? (unless you can think of why occDelta isn't working anymore in this situation)
@DavidRoy Let me know if you want me to implement this solution and take the budget from NPMS?

**Comment by andrewvanbreda** [comment]
Just one further note: the module can currently  just be switched to "process old records" mode, but there might be speed implications if it starts processing lots of old data, hence the changes I suggested to put in date limits, row limits.

**Comment by andrewvanbreda** [comment]
Hi all,

I have fixed and committed code to fix the auto-verifier as a hotfix.

From the tests I performed, Indicia changed the way it was interacting with the module (not sure why this changed), so one of the module's modes stopped working.
Essentially, I removed the broken mode and it now uses a mode that works on the occurrences/cache_occurrences tables directly (this mode always existed but was not intended as the primary mode, just for processing old records).
Without modification, this does cause problems though, so have added new options to control the  module.
These are
- Control the maximum number of records processed at once
- Control the oldest date of records to be processed
- Control the oldest occurrence ID of occurrences to be processed

This can all optionally used together so that only records passing all those tests are processed.

The code is in the Master branch via a hotfix (as  well as develop).

Note that if the old config file is accidentally used the module simply will log that problem and not run. By default the new options file has the number of records to process as 0, so if it runs before you are ready it won't do anything.

I do not know what further testing you might want to do, but note the essential logic of the module has not changed.

I think the module change should also be more reliable, previously Indicia would supply a list of new (or newly updated records) to process.....so if there was a problem for some reason during that "Run" of the module, then those records would not be supplied as changed by Indicia again and would not be processed in further runs.
I do not think that situation will happen, it will always process all records providing they meet the criteria set by the module's options.

**Comment by andrewvanbreda** [comment]
I forget to mention, there is a slight change to the way the verifier operates, previously it was not setting the updated_on, updated_by_id fields
Now it does (sets updated_by_id to 1).

Thanks @burkmarr for the link to the other issue. I will have a read through it as soon as I can.

**Comment by burkmarr** [comment]
No worries @andrewvanbreda - I'm actually working on that one now, but I haven't got to the point of changing the auto-verifier code yet; currently working on the stuff around it to allow restricting taxa to be recorded against the survey. I put the link to this issue in for my own benefit.

**Comment by johnvanbreda** [comment]
@burkmarr given that you are looking at this area of code, shall I wait for you to confirm a good point to apply Andy's hotfix to the live warehouse? I assume it might be worth doing both this and your changes together?

**Comment by burkmarr** [comment]
Sounds sensible @johnvanbreda. This is taking me longer than I'd hoped, but it's introducing me to lots of stuff that I haven't dealt with before.

**Comment by andrewvanbreda** [comment]
@burkmarr 
OK, let me know if you need any help with the auto verifier as I wrote it originally.

**Comment by burkmarr** [comment]
Thanks @andrewvanbreda.

**Comment by kitenetter** [comment]
@burkmarr is this still a live issue or can it be closed?

**Comment by burkmarr** [comment]
@kitenetter - I didn't work directly on this one. I worked on a related issue in which I referenced this one. It looks like @andrewvanbreda fixed this - https://github.com/BiologicalRecordsCentre/iRecord/issues/460#issuecomment-541354664.

**Comment by kitenetter** [comment]
Thanks - I will close this.
