### ISSUE TITLE
Some CEDaR records not being included within NI boundary for verifier

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#465]
The moth verifier for Northern Ireland has a filter set up to include all moths within the NI country boundary. I've been asked to set up a filter for him that includes all moths from CEDaR as a source. The CEDaR filter includes a number of moth records that are well within the NI boundary, but that do not get displayed if the NI country boundary is included as part of the filter.

Does this mean that some records are failing to be linked to the country as a location? If so can we correct that?

Examples of record IDs that are from CEDaR and within NI but not shown the NI boundary is used as a filter:
8591078
8138332
7090124
5109825
3731792

**Comment by johnvanbreda** [comment]
Having checked a few, they mostly seem to relate to records on small islets in the Belfast lough or similar. If you look at the loaded polygon for NI (http://warehouse1.indicia.org.uk/index.php/location/edit/1612) you will see that it attempts to do a cut out so that only the land masses are included, with quite a complex boundary around the lough and it's islets. You will also notice that due to a presumable projection error the boundary lines are consistently offset and therefore do not accurately align with the islets. Hence the records are not going to be picked up.
I am not sure that a boundary for NI really needs to cut out the lough? If I were doing a map of NI fish I might expect the records to be included!

**Comment by kitenetter** [comment]
Thanks @johnvanbreda, good to know the cause, and I agree we don't need to cut out the lough. We need to review the NI boundary in any case as we've been asked to add a marine buffer, and an error has come to light where the part of the western boundary is incorrect, so I will pick that up under a wider 'boundary review' issue. Closing this issue.
