### ISSUE TITLE
Report of timeout error on verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#466]
This is another error relating to butterflies in Surrey, so may be linked to #460 - this one is a timeout error message from the verification grid:

![image](https://user-images.githubusercontent.com/16039111/50598150-c50d0880-0ea1-11e9-8413-5590fe5e4ef0.png)

**Comment by johnvanbreda** [comment]
I've explored this query now and have found that it falls into the category of PostgreSQL's query planner not understanding that the records will all be old (due to the updated_on filter) and therefore picking a query plan that doesn't work well since it searches the most recent records first. I can't really do much about this without writing a very specific index that handles just this type of query (i.e. a combined vice county, taxon group, updated on filter for verification) and then any small change to the filter setup will probably still cause problems. 
A future move towards Elasticsearch should fix this. The only other alternative is to limit the options on the filter tool and write indexes for all likely combinations.

**Comment by kitenetter** [comment]
Closing on the assumption that the Elasticsearch option is now close to implementation.
