### ISSUE TITLE
Clarify messages sent out in notifications emails

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#48]
A number of iRecord users are replying to the automated email notifications sent out from the iRecord email address, in the expectation that this is how to respond to any comments and record cleaner results shown in the email.

Suggest adding a line at the top of all notification emails:
- Please do not reply to this email regarding notifications for your records - if you need to contact a verifier who has commented on your record you need to go to the record on the iRecord website and add your comment there.

And then under "Comments on your records":
- To respond to any of these comments please find your record on the iRecord website and add your reply there - if you reply to this email it will not be seen by the verifier who has commented.

And under "Record Cleaner results for your records":
- These messages are generated automatically by iRecord in order to highlight records that may need further checking, and there is no need to reply to them (please do not reply to this email address). The record cleaner messages do not imply that the record is necessarily incorrect. You may be contacted by an iRecord verifier if further information is needed.

It would also be good if the "Record ID" column in these messages could by a clickable hyperlink to the record in question, especially for "Comments on your records" where the recorder needs to refind their record in order to respond.

I'm happy to make the above text edits if we agree they are useful, and if someone can show me where to edit them!

**Comment by kazlauskis** [comment]
I just had a thought that it would be rather easy to add a bit of styling to the notifications that could greatly enhance the emails. Make it feel like it is not just some machine error log :)

We could use something like [Zurb Ink](http://zurb.com/ink/index.php). Or otherwise, you could go far with plain text edit.

![screen shot 2016-09-07 at 13 38 29](https://cloud.githubusercontent.com/assets/7383162/18312224/852f2a00-7500-11e6-90ca-039622b69f2f.png)

**Comment by kitenetter** [comment]
Replaced by #209 - closing.
