### ISSUE TITLE
Limits needed for auto-verification 

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#486]
Two issues have come to light relating to auto-verification:

**UKBMS records**
Currently these are being auto-accepted if they pass all checks; however, the UKBMS data entry forms allow many different species groups to be recorded, and I think it is incorrect for auto-verification to be applied to all species groups.
- Proposal: restrict UKBMS auto-verification to records of butterflies.

**NPMS records**
Some NPMS data is being entered with a very imprecise grid reference (100km square in at least one case). It feels wrong for such imprecise records to be auto-verified, so ideally I'd like the auto-verification process to be applied only to records located to 1km square or better. That would allow verifiers to contact the recorders in question and find out if it is possible to locate the 10km and 100km records more precisely.
- Proposal: restrict auto-verification (for NPMS in particular but really for auto-verification in general) to records with a grid reference precision of 1km or better

**Comment by DavidHepper** [comment]
Both your proposals are strongly supported here.

**Comment by MNSmith** [comment]
Can we please have the UKBMS input form only allow species level records, at least for "non-butterfly" species.  Despite many requests and comments to iRecord, we are still (STILL !!!) getting hundreds of "Bombus" records input from the Jersey BMS scheme recorders which all seem to be input at the same central point.

**Comment by DavidRoy** [comment]
Sorry for continued frustration on this.  I have been trying to kill off this issue.  See: https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/69

Can you give me some example IDs so I can reopen the issue

**Comment by MNSmith** [comment]
Hi David

Screenshot attached of some of the most recent records.  One thing to 
note, these records appear on the grid with my "Hymenoptera - Aculeates" 
filter, not the one I have set for "Aculeates - UKBMS".  I never see 
this problem on the "Aculeates - UKBMS" grid.

Do you think the person entering these is getting past the fix applied 
to the UKBMS input form by entering the records using the more general 
default iRecord data entry forms or is there something else causing a 
problem.  For all of these the survey code is

27|64  (UKBMS - Transects), so should these be appearing on the 
"Aculeates - UKBMS" grid or is perhaps the system directing them elsewhere?

Regards

Matt

---------------------------------------------------------------------------------------------------------
Matthew Smith BSc ARCS FRES MCIEEM
Consultant Ecologist
24 Allnatt Avenue
Winnersh
Berks
RG41 5AU
Tel: 0118 979 4313  Mob: 07710 160 690

**Comment by kitenetter** [comment]
The issue of non-butterflies being auto-verified has been raised again, and I think we need to prioritise this when we can.

**Comment by kitenetter** [comment]
Hi @burkmarr is it okay that I've reassigned this one to you to investigate the two issues detailed in the first comment in this thread.

**Comment by burkmarr** [comment]
@kitenetter, see below with reference to first comment. We need @johnvanbreda's take on this too.

> UKBMS records
> Currently these are being auto-accepted if they pass all checks; however, the UKBMS data entry forms allow many different species groups to be recorded, and I think it is incorrect for auto-verification to be applied to all species groups.
> Proposal: restrict UKBMS auto-verification to records of butterflies.

I think that this is the more difficult of the two proposals because, in the general case, it requires the addition of some configuration whereby the taxonomic group to which auto-verified taxa must belong can specified. It looks to me as though the right place to do that is on the definition of the survey which is the same level at which auto-configuration is enabled (and the 'auto accept maximum difficulty' is defined). 

So I think that this would require the addition of a new field on the Survey table which would accept a list of taxon identifiers - I suppose UKSI keys - that could be entered via the Warehouse's Survey admin form. (For UKBMS surveys I guess this could just be the single taxon Papilionoidea - NHMSYS0000503590.)

Then the auto_verify plugin SQL could be enriched to ensure that only taxon occurrences that reference a taxon path that includes a 'taxon meaning' associated with one of the specified taxa qualify for auto-verification. I think that this could be done reasonably efficiently because all the required info is in cache tables, but it would need some care to ensure that the new SQL has minimal impact on the performance of the auto verify scheduled task. 

> NPMS records
> Some NPMS data is being entered with a very imprecise grid reference (100km square in at least one case). It feels wrong for such imprecise records to be auto-verified, so ideally I'd like the auto-verification process to be applied only to records located to 1km square or better. That would allow verifiers to contact the recorders in question and find out if it is possible to locate the 10km and 100km records more precisely.
> Proposal: restrict auto-verification (for NPMS in particular but really for auto-verification in general) to records with a grid reference precision of 1km or better

It's easier if we make this a general requirement rather than one which can be applied for particular surveys by configuration. Assuming we make it a general requirement then I think that this can be achieved by enriching the SQL the auto_verify plugin again, joining the cache_occurrences_nonfunctional table and only qualifying occurrences that have an output_sref corresponding to 1km square or better (for output_sref_systems that support that work on appropriate grid, e.g. OSGB and Irish grid). Again we'd need to do this as efficiently as possible in order to have minimal impact on the scheduled task.

**Comment by DavidRoy** [comment]
@sacrevert for info in the context of NPMS.  i'm surprised that >1km records get through the input system

**Comment by sacrevert** [comment]
@sacrevert @burkmarr I'm aware of the handful of records at 100km, I imagine these are the result of system errors in the first few years of the scheme, but I haven't checked them individually. At some point I will look into them. It shouldn't really be possible to make records at >1km through the website; probably this has been fixed, but I would have to double-check the situation.

**Comment by DavidRoy** [comment]
thanks.  Seems like a legacy issue, therefore not a priority to add extra complexity to the auto-verification system to deal with this?

The taxon filter for auto-verification is much more important in my view

**Comment by sacrevert** [comment]
Agreed.

**Comment by johnvanbreda** [comment]
@burkmarr I agree with your synopsis above. Is there anything specific you want me to comment on?

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I just wanted to know that I was barking up the right tree.

**Comment by burkmarr** [comment]
So we'll just proceed with the option to limit the taxonomic scope then. @johnvanbreda, can you give me any pointers on how to proceed when a data model update is required?

**Comment by johnvanbreda** [comment]
In the warehouse module `indicia_setup` there is a db folder which contains a folder for every release version that has a schema change. So, you can do a feature branch, up the 2nd version number (2.36.0) meaning you will want a folder called version_2_36_0. Then create a SQL file with the schema change in it, named yyyymmddhhmm_<brief_description>.sql.

I imagine you want a text array field to hold a list of keys? Traditionally you might have used another table but that's probably overkill and requires more joins to query.

**Comment by burkmarr** [comment]
Cheers @johnvanbreda - that's useful. I was thinking an array too. Often it is likely to be a single (or no) value I think.

**Comment by burkmarr** [comment]
@johnvanbreda - I'm updating the model via SQL in the auto_verify plugin since it only needs to be updated if the auto_verify modue is enabled.

![x](https://user-images.githubusercontent.com/9275178/66320489-d397bd00-e916-11e9-8552-69a3f30ba93d.JPG)

I specified the new field, auto_accept_taxa_filters, as a text array type. The database update worked fine when I incremented the Warehouse version number and started my local warehouse.

I'm updating application\views\survey\survey_edit.php to include the new field but I'm having difficulty dealing with the text[] data type - I can't find a data_entry_helper to help me work with it. Do you have any suggestions or pointers?

(I could specify the new field as a simple string type instead and parse space separated TVKs from it.)

**Comment by johnvanbreda** [comment]
@burkmar - in `application/views/attribute_by_survey/attribute_by_survey_edit.php` we use a species_checklist control to capture links between dynamic attributes and the taxonomy branch they link to. You could do the same here? Some notes on the differences:
* You don't need to set the occAttrs property as you only need to capture a taxon name.
* In the controller class prepareOtherViewData method, you need to capture your existing taxa and store in a the $otherData variable for the view to use (look for the example `$otherData['taxon_restrictions']`). 
* This data needs to be fed into the species_checklist control as existing rows in the view (see how taxon_restrictions is handled again).
* Look for `postSubmitTaxonRestrictions` for an example of how the save works. You'll need to modify the approach if you want to capture the external_key rather than taxon_meaning_id of course.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - that's a good model. I think that I should mirror this approach as closely as possible, including using taxon_meaning_id rather than external key, for the sake of consistency.

**Comment by burkmarr** [comment]
@johnvanbreda - on my development setup I have a problem that is preventing the species_checklist control from rendering/working properly. I need to sort this out before I can pursue the route we've discussed.

The image below is from a clean install of 2.35.1 (develop branch). I reached it from the 'survey settings' button for a custom attribute. Any idea what might lead to this? Have I ommitted some configuration?

![Capture](https://user-images.githubusercontent.com/9275178/66392478-e0281e00-e9c7-11e9-9650-53c9cbd54535.JPG)

**Comment by johnvanbreda** [comment]
I think your client_helpers version is slightly out of date - can you make sure you have this commit in it please:
https://github.com/Indicia-Team/client_helpers/commit/7e7c77490f0190cdfe59667b10e2b6effc1a37f1

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - that was the problem.

**Comment by burkmarr** [comment]
See also https://github.com/BiologicalRecordsCentre/iRecord/issues/460#issuecomment-541354664

**Comment by burkmarr** [comment]
@johnvanbreda - I'm struggling to understand where to code the updates to the new surveys.auto_accept_taxa_filters field [an integer array that will store taxon_meaning_id values]. In a previous comment, you said:
> Look for postSubmitTaxonRestrictions for an example of how the save works.

I found 'postSubmitSaveTaxonRestrictions' which is called from a 'postSubmit' method in both the sample_attributes_website_Model and Occurrence_attributes_website_Model. Should the functionality to update the surveys table go into a postSubmit method in Survey_Model?

**Comment by johnvanbreda** [comment]
In the taxon restrictions code, the postSubmit of an attributes/websites join model detects any additional restrictions data from the species checklist grid and converts it into records in the appropriate taxon_restrictions table. If your model is similar and you have a separate survey_auto_verify_taxa table then this does sound like the right approach with a postSubmit method in the survey_model. However if you are planning to save the list of taxon_meaning_ids in an integer array in a field inside the surveys table, then it would make sense to detect the data from the species_checklist in a preSubmit method and reformat it into the submission. In the preSubmit method you can format the data into $this->submission['fields']['fieldname'] but I'm not sure if it will cope with an integer array. It will need a bit of experimenting I think.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I'm pursuing the latter approach so I'll try with the preSubmit reformatting.

**Comment by burkmarr** [comment]
Hello @johnvanbreda. From your previous comment:

> detect the data from the species_checklist in a preSubmit method

I'm having trouble with this. If I echo `$this->submission` from the preSubmit method, I can't see the input values from the species_checklist control. Using Chrome dev tools I can see the form input tags are there right enough, but their values are not reflected in the model submission structure.

What do I need to do to make them available?

**Comment by johnvanbreda** [comment]
See  `base_attributes_with_taxon_restrictions_model.postSubmitSaveTaxonRestrictions`. The data won't be in the submission since it's not a standard part of your survey's submission structure, so you need to extract it from the $_POST data. This function should give you an idea of how to pick up the data from the relevant form fields.

**Comment by burkmarr** [comment]
Many thanks @johnvanbreda.

**Comment by burkmarr** [comment]
https://github.com/Indicia-Team/warehouse/pull/335. Code not yet complete, but would like @johnvanbreda to review.

**Comment by burkmarr** [comment]
See also https://github.com/Indicia-Team/warehouse/pull/336

**Comment by burkmarr** [comment]
@BirenRathod - I need to update the Dev Warehouse and to carry out some tests with the latest develop branch. Can I just go ahead and pull the latest code or do we need to do anything first e.g. stop scheduled tasks?

**Comment by BirenRathod** [comment]
@burkmarr 
As long as you are not updating data, it is fine to do that. Also, you don't need to stop scheduled task for pull code. For you info, please take clone the current code of warehouse folder first, so if anything goes wrong, you restore it from it.

**Comment by burkmarr** [comment]
Pull request to fix minor problem with new species checklist on survey edit page. https://github.com/Indicia-Team/warehouse/pull/339

**Comment by burkmarr** [comment]
@kitenetter - this conversation has become somewhat split between this issue and one of the related pull requests (https://github.com/Indicia-Team/warehouse/pull/336). In the pull request you mentioned that you could import a mixture of butterfly and non-butterfly records into the survey UKBMS WCBS-BC (on dev) for me to test against. Is that something I can help with? If so, can you outline the steps required to do it?

**Comment by burkmarr** [comment]
@kitenetter @johnvanbreda @DavidRoy @BirenRathod - Please note that I just found a bug in a part of the code I did for this which has already been pushed to the live (and dev) warehouses which means that creating a survey in the warehouse currently fails. This is fixed in an update I just made to this pull request: https://github.com/Indicia-Team/warehouse/pull/339

@johnvanbreda - does this require a hotfix do you think?

**Comment by burkmarr** [comment]
I updated a pull request conversation instead of this issue again! For the latest, see: https://github.com/Indicia-Team/warehouse/pull/336#issuecomment-550336976

**Comment by burkmarr** [comment]
With the recent warehouse release, the changes to limit auto-verification to specific taxon groups for a survey, along with @andrewvanbreda's changes to the auto-verifier limits configuration, are implemented. In line with Andrew's advice to be conservative with the limits on auto verification, I've set the parameters a follows:
```php
$config['auto_accept_occurrences_with_null_id_difficulty']='false';
// Note that -1 (or less) is unlimited, 0 processes nothing
$config['max_num_records_to_process_at_once']=500;
$config['oldest_record_created_date_to_process']='01/11/2019';
// 1 (or less) is effectively unlimited
$config['oldest_occurrence_id_to_process']=1;
```
With those settings, the auto-verifier will only attempt to auto-verify records created since the start of this month and will only try 500 at at time. We should review these settings at some point.

I have updated the four UKBMS surveys to limit auto-verification to these taxa: Hesperiidae, Lycaenidae, Nymphalidae, Papilionidae, Pieridae and Riodinidae.

@kitenetter - do you want to leave this open for a while to see how things go?

**Comment by andrewvanbreda** [comment]
@burkmarr Your understanding of what the settings do is correct. There is also an oldest_occurrence_id_to_process setting but in this case the date restriction is newer so effectively the oldest_occurrence_id_to_process is not relevant

**Comment by DavidHepper** [comment]
This is complex. Could someone give me a layman's summary of where we're at with the unsetting of Auto-verify for non-butterfly records in the UKBMS surveys, please?

**Comment by andrewvanbreda** [comment]
Hi @DavidHepper 
I think your answer is the programming is done and is going through final testing by Rich Burkmar before it can be used. He would need to comment on how far he has got with the testing.

**Comment by burkmarr** [comment]
@andrewvanbreda - I ran a test on the dev warehouse which I accidentally documented on the pull request rather than this issue: https://github.com/Indicia-Team/warehouse/pull/336#issuecomment-550336976. It looked okay so is now configured on the live site - see below.

@DavidHepper - I configured the four UKBMS datasets in the Warehouse  to restrict auto-verification to the following butterfly families.  I did this on November 11th.

![image](https://user-images.githubusercontent.com/9275178/69254664-82821680-0bae-11ea-8dd9-0ca3f0740005.png)

With those settings, no non-butterfly records entered into these datasets since Novmber 11th should have been auto-verified. However, I've just rechecked all four datasets and, in every case, the Taxon restrictions are set as follows:

![image](https://user-images.githubusercontent.com/9275178/69254885-cc6afc80-0bae-11ea-83d6-f100148a674e.png)

With those settings, no butterflies outside of those two families will have been auto-verified either. I'm at a loss to explain why they are set like that. Assuming no-one actually removed the other families, I'll need to look for a programatic reason why they might have changed.

In the meantime, I've just removed all the taxonomic restrictions so that any butterfly species normally eligible for auto-verification are now eligible again (but so are non-butterflies now of course). I'll start investigating this now.

**Comment by andrewvanbreda** [comment]
@burkmarr You should be able to query the database and see the updated_on, updated_by_id on any deleted rows. I can't access the database, otherwise I would offer to help

**Comment by burkmarr** [comment]
Hi @andrewvanbreda - the taxon meaning IDs are stored as an array in a single field in the surveys table. But I could have examined the the update_on and updated_by_id values before I reset them! Too late now. You live and learn.

**Comment by burkmarr** [comment]
There is a programatic reason - but I haven't got to the bottom of it yet. When I try to set these six families on any of the UMBS surveys - when I go back to them only two are saved. But setting these families on the test survey works okay: http://warehouse1.indicia.org.uk/index.php/survey/edit/1

I'll continue with this tomorrow.

**Comment by andrewvanbreda** [comment]
@burkmarr 
Nothing obvious springs to mind. You might want to change the order you add them to see if the problem is with two always being saved, or whether it is the individual items causing the trouble.
If it is species, then it could be preferred ones are being saved, and non-preferred ones aren't. 
These are just a couple of thoughts without me trying anything by the way, they might be nonsense

**Comment by burkmarr** [comment]
@andrewvanbreda @kitenetter @DavidHepper @johnvanbreda 

It transpires that you can only add two taxa at a time to the taxon restrictions on a survey, but if you add them in batches of two, saving the survey each time, you can add more. So I have reinstated the butterfly family filters on each of the four UKBMS surveys now. 

I am going to raise a separate issue to address this 'foible' of the taxon list control (or perhaps its implementation on the survey form - whichever the case proves to be).

In some ways this has been a good test of both the new taxon restriction functionality and Andrew's changes to managing the auto-verify workload.

During the period when only the families Hesperiidae and Riodinidae were allowed as candidates for auto-verification (from some time during 11th November until late yesterday) only a few skippers were auto-verified. So the very restrictive taxon filters, though incorrectly set, worked.

Once I took off all the filters yesterday, Andrew's new workflow ensured that  records from these datasets that were incorrectly filtered out as candidates auto-verification, between 11th and 20th November, again became eligible and were dealt with, in batches, overnight.

It does mean, of course, that some non-butterfly records in these datasets were also auto-verified overnight, but these just get added to those that we will deal with for issue #692.

@DavidHepper - now that the full butterfly family filters are correctly set on the four UKBMS datasets again, no non-butterflies from these datasets should be auto-verified from this morning onwards. I will look at this over the next few days and if all seems to be operating as designed on Monday, we should be able to move onto issue #692 and address the incorrectly auto-verified non-butterfly taxa.

**Comment by burkmarr** [comment]
Latest check on this since the filters were reset correctly (from yesterday onwards) shows new records added to the four UKBMS datasets as follows:
- 1131 auto-verified butterfy records
- 271 butterfly records not auto-verified
- 22 moth records not auto-verified

I'll update these figures over and/or after the weekend.

**Comment by burkmarr** [comment]
Latest check on this since filters were reset on Nov 21st shows new records added to the four UKBMS datasets as follows:

- 2475 butterfy records **auto-verified** 
- 2964 butterfly records **not** auto-verified
- 12 bird records **not** auto-verified
- 3 beetle records **not** auto-verified
- 5 hymenopter records **not** auto-verified

It looks to be working as expected.

**Comment by burkmarr** [comment]
@kitenetter - there was a mistake on the previous update, I should have subtracted 2475 from 2964 to give 489 butterfly records not auto-verified.

The lastest figures are below. I think this looks to be working properly now, so can we close the issue?

From Nov 21st, new records added to the four UKBMS datasets were either auto-verified or not as follows.

**Auto-verified**:
- 6570 butterfly 

**NOT** auto-verified:
- 17 bird
- 8 reptile
- 6 flowering plant
- 3 beetle
- 14 dragonfly
- 22 hymenoptera
- 117 moth
- 1 true fly
- 1269 butterfly

**Comment by kitenetter** [comment]
That looks good @burkmarr, thanks to all involved, good to be able to close such a lengthy issue! And that means we can now move on to #692
