### ISSUE TITLE
Locality (vice-county) not being computed for recent records

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#491]
Records being entered or imported over the weekend are being Auto-checked but no Locality is being assigned. This doesn't *seem* to be related to particular VCs or forms.
Examples: 
- 9079421 - East Norfolk
- 9081075 - Wiltshire
- 9082355 - Montgomeryshire
Sorry to report another urgent one but we're at risk of having people enter or import twice because they think the first failed.
David

**Comment by kitenetter** [comment]
@DavidHepper do you mean that the vice-county is not being assigned, and that therefore the records are failing to appear in the verifier's view? It looks like that is what is happening for the examples you give.

**Comment by DavidHepper** [comment]
Yes.

**Comment by johnvanbreda** [comment]
Hi @DavidHepper this should be OK now. The background processes had come across a strange error caused by emailing a particular verifier's email address, causing the processes to abort. I've now changed it so this sort of thing just gets logged and the email isn't sent, so the background processes can proceed.

**Comment by DavidHepper** [comment]
!! Thank you. I take it the processes will catch up with work not done.
