### ISSUE TITLE
'Longhorn Beetle' incorrectly associated with Pyrrhidium sanguineum 

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#496]
Forum post: https://www.brc.ac.uk/irecord/node/7587 (text below)

To resolve - all records received using the common name ‘Longhorn Beetle’ be changed to ‘Cerambycidae’.

Forum post:
I've just run a search under 'Explore All Records' for Pyrrhidium sanguineum and it returns a lot of erroneous results, including other longhorn beetles, bugs and a wasp. It seems that the filter is picking up any records labelled with the common name 'Longhorn Beetle' rather than restricting the search to the scientific name only.
 
The second question is why has Pyrrhidium sanguineum been given the common name 'Longhorn Beetle', when this should refer to the whole of the Cerambycidae? It's an extremely bad and confusing name choice. An alternative name in use is 'Welsh Oak Longhorn Beetle', which at least has the advantage of being unique although it doesn't seem very appropriate for a species distributed across three continents. Even within the UK it seems misleading for a species that is becoming more widespread in England.

**Comment by kitenetter** [comment]
I can't reproduce the search problem.

It appears that in UKSI "Longhorn Beetle" is linked to the family Cerambycidae:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000168579

The species Pyrrhidium sanguineum has no vernacular name listed as a synonym:
http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000011041

@johnvanbreda can we change the iRecord dictionary to match UKSI, or does this raise difficulties for records that have been entered using the vernacular?

Presumably this will get picked up next time we update to UKSI, but there does seem to be potential for confusion when the update is applied.

**Comment by kitenetter** [comment]
I've now understood the search problem - it's not that the search is producing records that are not linked to Pyrrhidium, it's all a result of people adding records of unidentified insects and calling them "Longhorn Beetle", which then gets linked to Pyrrhidium sanguineum. So if you search for Pyrrhidium sanguineum you get a list of records with photos of all sorts of things that aren't Pyrrhidium sanguineum. Unfortunately one of these erroneous records has been accepted by a county verifier.

So we do need to remove the link in iRecord between "Longhorn Beetle" and "Pyrrhidium sanguineum" so that it matches the current UKSI behaviour.

**Comment by kitenetter** [comment]
Additional app-related issue (@kazlauskis): for records originating from the app, it looks like they may be being entered as "Longhorn Beetle" but the record page on iRecord shows the "name as entered" to be Pyrrhidium sanguineum:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=6946078

I strongly suspect that the "name as entered" really should be "Longhorn Beetle", so it looks like the app is capturing misleading information from records added via common names?

**Comment by johnvanbreda** [comment]
Longhorn beetle now links to Cerambycidae, matching UKSI.
