### ISSUE TITLE
Map display in activities should not show sensitive records that overlap area

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#5]
Problem raised by Bringsty Common activity but presumably applies elsewhere. Problem is that records marked as sensitive, and records mapped at 10km precision, are swamping the small area of Bringsty Common and making it hard to work with the data that is genuinely associated with the common. 

Suggest solution = removing sensitive records from display altogether, removing 10km-level records from activity summaries

**Comment by johnvanbreda** [comment]
I've done the following:
For all activity summary maps, when zoomed out to a wide area, there are no changes. E.g. Dipterists Forum map at default view.
When zoomed in far enough to show records at full resolution, they are not shown if over 1km precision. 
Same as above for activity explore pages.

I have not removed sensitive records, since the grid square size limitation should fix this anyway and they should really appear in stats I think?
Also, should the standard explore pages also hide large squares when zoomed in?

**Comment by kitenetter** [comment]
I think this resolves most of the issues raised by Bringsty Common, thanks, but my opinion is that sensitive records should be removed from zoomed in views and related stats. The example that raised this issue was this otter record:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=2950700

The record is not from Bringsty Common, but because the location is blurred it gets included in the species list. If Bringsty Common try to generate species lists from iRecord for their newsletters or reports they will have to remember to remove this species (plus at least one other similarly misleading sensitive record), which is in my view unnecessary work for them and potentially very misleading, e.g. if the data is used by someone at local level who is unaware of the sensitivity issue.

Re the standard explore pages, I would prefer not to see large squares when zoomed it, although I suppose the ideal solution would be to have an option button whereby you could choose to include or exclude them.

**Comment by johnvanbreda** [comment]
I agree. If we leave confidential records in the report in any way, then we either accept that large blurred records will get included incorrectly sometimes, or we would have to use the unblurred record version to determine inclusion. Doing the latter would of course make it possible to get a good idea of a sensitive record's location in some cases. 
David - shall remove large squares from the Explore pages when you are zoomed in? I.e. when you get to the level that you can see full precision, anything over 1km could be removed.

**Comment by DavidRoy** [comment]
I agree to removing large squares from the explore pages when zoomed in.  Thanks for a resolution to this

**Comment by DavidRoy** [comment]
I agree to removing large squares from the explore pages when zoomed in.  Thanks for a resolution to this

**Comment by kitenetter** [comment]
This issue has been raised again in connection with Activities for local groups. The blurred records are not being displayed on the maps, but they are getting included in the grid of records, and this is misleading and causes people to doubt the usefulness of the iRecord data. I'm not sure whether this has always been the case, or whether it is something that has crept back in again after we fixed it previously - I think the latter?

The example this time comes from Holtspur Bottom. Their Activity includes a list of records:
https://www.brc.ac.uk/irecord/groups/explore?group_id=1463&implicit=

A number of blurred records are included with grid reference "SU", which has added unlikely things such as Otter and Montagu's Harrier to the reserve list.

Can we go back to excluding records that are at a resolution of more than 1km from zoomed in views/local activitites?

**Comment by kitenetter** [comment]
This does not appear to be causing problems at the moment. Closing.
