### ISSUE TITLE
Activity pages going missing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#518]
Two of the bee-fly watch activity pages have apparently been 'unlinked' from the activity in the last day or two, not sure what might have caused this:

![image](https://user-images.githubusercontent.com/16039111/54377684-8f448700-467d-11e9-8c1d-9494f7b4ad5a.png)

**Comment by kitenetter** [comment]
In fact the 'summary' and 'details' reports are now missing from the list of available forms for use in activities, and are thus missing from all activities as far as I can tell. This is therefore a high priority to sort out.

**Comment by johnvanbreda** [comment]
Fixed. At some point, duplicate url aliases have been created (no idea why or when) so that activities/summary was also available at groups/summary. This caused the code to compare your linked page (groups/summary) with the first found alias for the page (activities/summary). I've cleaned up all similar duplicate aliases and repointed all the group pages to the correct versions.

**Comment by DavidRoy** [comment]
Thanks for resolving.  Duplication of filters reported here. https://github.com/BiologicalRecordsCentre/iRecord/issues/508

Needs fixing if this issue is not to reappear?
