### ISSUE TITLE
Elastisearch - Column Headers and Search boxes

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#575]
**Verification Grid - Column Headers and search fields.**

Fixed column header search boxes. At present the column headers and search boxes are contained within the scrolling frame of the grid, which means if I scroll down through the records ticking selection boxes and the like, I then have to scroll all the way back up to the top to carry out an action. Can we have these buttons fixed in place please.

**Comment by kitenetter** [comment]
Related issue from @MNSmith 

**Verification Grid - Action Buttons**

Fixed Action buttons. At present the Action buttons are contained within the scrolling frame of the grid, which means if I scroll down through the records ticking selection boxes and the like, I then have to scroll all the way back up to the top to carry out an action. Can we have these buttons fixed in place please.

**Comment by johnvanbreda** [comment]
Scrollbar moved onto tbody element which fixes both these issues.
