### ISSUE TITLE
Time attribute on PoMS FIT Count form has stopped working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#584]
This refers to the PoMS FIT Count form:
https://www.brc.ac.uk/irecord/poms-fit-count-form

This includes an attribute for "Start time (BST)" (sample attribute ID 1056), which expects a time in 24-hour clock format. However, when saving the record, it fails to save ("The data could not be saved"), with an error message against the Start time attribute:

![image](https://user-images.githubusercontent.com/16039111/56959076-28ebc900-6b44-11e9-8bf3-e7fa80596430.png)

This was working until very recently (error reported today, 30 April, and subsequently replicated by me). As far as I know there have been no edits to the form nor the underlying survey.

**Comment by BirenRathod** [comment]
@kitenetter 

I found that in sample attribute setting of "Time of count start (PoMS)" has got time validation rule check is on, which is wrong because it has got text datatype assigned in the database. Below is the screenshot.

![image](https://user-images.githubusercontent.com/5941255/56980164-89dec580-6b73-11e9-8cf3-566ce8dc82ee.png)

**Comment by kitenetter** [comment]
Thanks @BirenRathod, that seems to have fixed the problem. This raises the question of why the setting has changed in the last few days. Closing.
