### ISSUE TITLE
Two iRecord accounts linked to one warehouse user

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#587]
A user has managed to create two iRecord accounts linked to the same warehouse user:
https://www.brc.ac.uk/irecord/user/9681
https://www.brc.ac.uk/irecord/user/49815

If I masquerade as the two user accounts in iRecord I see exactly the same set of 750 records.

Both of these iRecord accounts link to user ID 70083 in the warehouse. That user has two email identifiers, which match the two iRecord accounts. 

The user wishes to retain iRecord account 9681 (which is linked to email 1), and delete iRecord account 49815 (which is linked to email 2), BUT they want their account linked to email 2, and to delete email 1. 

The entry in the Person table in the warehouse is linked to email 1.

I think that what I need to do is:
1. Edit the email address in the warehouse People table from email 1 to email 2
2. Edit the email identifiers in the warehouse User table to delete email 1
3. Delete iRecord account 49815
4. Edit the email address in iRecord account 9681

Questions:
- Is that the correct sequence of edits and deletes?
- Can I be certain that by doing this the user will still be linked to their 750 records?

**Comment by burkmarr** [comment]
@kitenetter. It would have been nice to try this out on dev first, but the second account isn't on there. Would it be best to do this via the user interface? What about this workflow:

1. Log in to iRecord as admin.
2. Go to https://www.brc.ac.uk/irecord/admin/people
3. Filter on the name of the second user (that you want to delete), and copy the email address somewhere safe.
4. Delete this user (with the default deletion options).
5. Masquerade as the user you want to keep.
6. Change the email address linked to their account on their profile page.

I guess that Drupal checks to see if email addresses are duplicated, but since the second account is deleted first, I think it should be okay. Can you think of any reason that this won't work?

**Comment by burkmarr** [comment]
@kitenetter - shall I go ahead and do this?

**Comment by kitenetter** [comment]
@burkmarr if you have time to tackle this that would be great thanks - let me know when completed and I will inform the user.

**Comment by burkmarr** [comment]
@kitenetter. I think this is done now. Masquerading as first user (now with email set to that previously used by second user) now lists 895 records under explore my records. (For step 6 I changed the email using the admin account as I think would have had to supply password if I did it as the user.)
