### ISSUE TITLE
Activity map incorrect

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#588]
Maps within Activities are not showing correctly.  A consequence of recent mapping changes.  Examples are overview tab on:
https://www.brc.ac.uk/irecord/irecord-app-summary
https://www.brc.ac.uk/irecord/butterfly-app-summary-2019

I've not checked other activity summaries but likely to affect them all?

**Comment by kitenetter** [comment]
I'm finding some odd mapping behaviour when adding records as well - having zoomed in to the aerial photo level, if I zoom out again it seems to get confused, and sometimes shows "no mapping available", and sometimes seems to lose the display altogether.

**Comment by kitenetter** [comment]
Also, on the Explore pages, it doesn't seem to be possible to zoom out far enough to see the whole of the UK.

**Comment by burkmarr** [comment]
@DavidRoy - activity maps: I think the problem here is solely that the initial view is zoomed in. There's no zoom control, but on my browser (Chrome) I can zoom out by clicking on the map, holding down control and using the mousewheel. Unfortunately as well as zooming the map in or out, it also zooms the web-page! However, once I'm zoomed out, it seems to me there's no difference between the live site and the dev site (where recent mapping changes not deployed), so it seems to me that this is just a problem of new mapping changing out the initial zoom is set. Do you agree or have I missed something. (Does anyone know why no zoom control is on these activity overview pages?)

@kitenetter - zoom out limitation: It looks to me as though the limitation on zooming out is a feature of the OS mapping. For example see here on the dev site: http://test.brc.ac.uk/irecord_dev/enter-casual-record (I don't think the new basemap functionality is implemented on the dev site). You can zoom out as far as you like with OSM, but not with the OS layers. So if this is important, maybe we'd need to rethink which maps are included in the dynamic switching - or even add a third (e.g. OSM) for when users zoom out a long way? What do you think @johnvanbreda ?

@kitenetter - odd mapping behaviour. I can't reproduce the kind of things you're reporting there so if you could experiment to come up with some reproducible steps and/or take some screen shots, that would be useful. 

However, I can generate some confusing behaviour on data entry forms. When zoomed very close in with the Google Satellite layer showing, the zoom control is longer than it is when zoomed out with the OS layer showing because, like OSM Google layers have  more available zoom levels than OS. So if I start zooming out now by clicking on the minus at the foot of the zoom control, it is fine until the layers switch. Once the layer has switched to OS and I go to zoom out again by clicking my mouse, thinking that I've still got it positioned over the minus at the foot of the zoom control, it all goes wrong and zooms back in, switching to Google Satellite again. That's because when the map switched to OS and shortened the control, my mouse was not longer positioned over the minus of the zoom control, but over the map and when I clicked the software interpreted that as me selecting that position for my grid reference and zoomed in on it, changing the Google Satellite as it did so. Could that have explained some of the strange behaviour you've had? I don't know what the answer to that is.

Note thought that if the confusing zooming behaviour is considered very serious we can switch it off for the time being by changing the basemap configuration - we don't have to change the software.

**Comment by johnvanbreda** [comment]
@burkmarr The zoom out limitation of OS Leisure is a bit limiting for overview maps. I'll have a look at tidying the code to make it possible to have dynamic layers with 3 or more sub-layers, so we can use OSM or similar when zoomed out. I've started looking at this and also noticed that because the zoom level and x/y coordinate system used for the different map layers is different, you get odd effects. E.g. if we store an x,y and zoom setting for OS Leisure in the cookie stored between page loads, on the next page load it doesn't realise which sublayer is loaded and you can end up with maps in odd places. I think this is part of the explanation for activity maps being in the wrong place.
