### ISSUE TITLE
iRecord butterflies user statistics report - convert to ES

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#591]
The user report within the iRecord Butterflies app, statistics for 2019 league position currently shows '-1'.  This is due to league position being removed from relevant report for performance reasons:
library/totals/user_survey_contribution_summary.xml

For backwards compatability, convert to Elastic Search version?

**Comment by johnvanbreda** [comment]
Yes - this report was a significant culprit during recent performance issues, since it does a count of all app records on each hit. As it was timing out I felt it was reasonable to replace it with a performance version with a few bits of info missing rather than leave issues on the server.
Options are:
1. As the server is now performing well, replace the old report. It will still be slow, but not so bad now there is enough RAM.
2. I can fairly easily set up Elasticsearch aggregations for this info. So we could release a new app version with a replacement report.
3. If a new app version is not possible, then we would need to implement a layer in the code which detects this report and redirects the query to Elasticsearch. That sounds like a slightly fiddly approach but may be the only way.

**Comment by DavidRoy** [comment]
We  have a new version of the app being tested but it is a minimal update to fix mapping and other issues caused by software updates.  Could you implement #2 and #3.

Does this also provide what's needed for https://github.com/BiologicalRecordsCentre/ABLE/issues/56?

**Comment by kitenetter** [comment]
I think this has been superseded with the new version of the app - closing.
