### ISSUE TITLE
Possible problem with changes to country boundaries

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#612]
I've just had a message from one of the Northern Ireland verifiers to say that he is being asked to re-verify records that he'd previously verified. This has set alarm bells ringing - has the recent update to the NI boundary caused the records to be re-indexed and thus trigger them to be shown as having been edited?

If so we may need to reset the date_of_edit to avoid verifiers be shown all the records they've previously verified.

Assigning to @johnvanbreda as I think he fixed a similar problem before in #516 

Tagging @burkmarr to apologise for not having thought about this in time to warn that it could be a problem when updating the polygon layers

**Comment by burkmarr** [comment]
@kitenetter I also updated the current boundaries for North Devon VC and BC boundary for Devon to include Devon for this issue: https://github.com/BiologicalRecordsCentre/iRecord/issues/406 a couple of weeks ago. Have verifiers reported similar issues there?

**Comment by johnvanbreda** [comment]
@kitenetter I don't think that updating a location boundary will change the verification status any more - that issue was fixed. We now use an independent tracking ID to force changes through to Elasticsearch rather than changing the updated on data so the verification status does not get affected. This is confirmed by the following query that shows there are still loads of NI records which were verified before Rich last updated the boundary:
```sql
select count(*) from cache_occurrences_functional where location_ids @> ARRAY[1612] and record_status='V' and verified_on<'2019-05-27'
```

So, I think there is another reason why these records are requiring re-verification.

**Comment by kitenetter** [comment]
Thanks John, good to know that it isn't a more general issue.

I will ask the verifier concerned to let me know if he is seeing this repeatedly. I've not yet had reports from other verifiers so hopefully it is a one-off issue. Closing.
