### ISSUE TITLE
Elasisearch - Species names column - text wrap issues.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#618]
Looking at the Aculeates grid today, some of the longer species names are text wrapping in a very "broken" way.
![names 2](https://user-images.githubusercontent.com/18451743/59265040-6ca21a00-8c3c-11e9-8906-921b9df47a43.jpg)
![names 3](https://user-images.githubusercontent.com/18451743/59265041-6d3ab080-8c3c-11e9-8b59-dab2cc5c93d7.jpg)
![names 1](https://user-images.githubusercontent.com/18451743/59265042-6d3ab080-8c3c-11e9-8245-d0554605311e.jpg)

**Comment by MNSmith** [comment]
Seeing similar issues on the Recorder Name column as well today.

**Comment by johnvanbreda** [comment]
The styling which allows scrolling of just the table body has an unfortunate side effect of fixing the column widths to equal widths. 

Fixed in the code. Will need to remove the custom page CSS and instead use the new scrollY option to get the table body to scroll properly with variable column widths.
