### ISSUE TITLE
"Verification - new" displaying all records, not picking up on verifier's filter

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#628]
Verifier Dave Slade (user ID: 252) had been set up under the old system, with the verification role added via his user account page. I have removed that role, and he should now be linked to two verification filters under the current filtering system.

If I masquerade as Dave and go to the old verification page, all is well, I can look at butterflies in Glamorganshire or switch to moths in Glamorganshire.

If I masquerade and then go to the new verification page, there are odd results: the grid is displaying **_all_** butterfly records, not just those in Glamorganshire, and is also including taxa that aren't butterflies - maybe it is displaying all taxa for all locations?

Also, there is no context drop-down box to allow switching between butterflies and moths.

If I use a 'nocache' link it all goes back to normal (but the change was made last week so caching should not still be an issue?):
https://www.brc.ac.uk/irecord/elastic/verification?nocache

**Comment by johnvanbreda** [comment]
The expiry of a cached file has 2 elements:
1. Time - the default behaviour is that cached information never expires for the first hour after the last refresh (this setting is overridden in some cases so it's not always an hour).
2. Random element - even after an hour, there is only a 1 in 10 chance of the cache data refreshing. This is to prevent a page with multiple report queries from refreshing them all at exactly the same time. 

It was the random element that prevented the refresh here. I refreshed the page a few times and it started to work.

I've commit a change to the develop branch of code so that once the time goes over 3x the minimum time to expiry, the random element is removed so it will always refresh at that point.
