### ISSUE TITLE
iNaturalist data - redeterminations over-written on reimport?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#641]
https://www.brc.ac.uk/irecord/record-details?occurrence_id=9901039

Record 9901039 was automatically imported onto iRecord from iNaturalist. Three months ago the record was verified in iRecord following a redermination to a different species (Teleiodes luculella to T. vulgella).

Today, the verifier received notification that Admin Core changed the det. back to the original (incorrect identification) at three months and two days ago. 

Labelled as urgent given impact on verifiers

**Comment by johnvanbreda** [comment]
I think there are 2 things going on here:
1. The original decision on how the data flows (as discussed with @kitenetter) was that any changes on iNaturalist would overwrite the iRecord copy, thus resetting the verification state. This was then going to be reviewed. An alternative would be to "lock" records on iRecord once verified.
2. I think the problems in #633 mean that change tracking got broken and we accidentally re-imported a lot of data that didn't need to be. 

Given that #633 is not properly resolved yet, the important thing is we don't re-start the import without understanding why the change tracking didn't work and without agreeing on how to handle any changes to verified records.

@DavidRoy, @kitenetter any thoughts on how to handle changes to already verified records?

**Comment by kitenetter** [comment]
Suggest parking this until we complete a review of the iNaturalist process, see #684

**Comment by kitenetter** [comment]
My current thinking, based on experience with the iNat records in 2019, is that once a record has been verified on iRecord it should be locked, and not overwritten. This is mainly because the identifications on iNat can potentially change quite frequently as the agreed IDs move up and down the taxonomic hierarchy.

This means that the 'iRecord view' of the iNat record will in some cases end up being different from the 'iNat view' of what should ideally be the same record, but in the absence of full synchronisation between iRecord and iNat I think this is the best that can be achieved, without adding unreasonably to verifiers' workloads.

**Comment by kitenetter** [comment]
Closing, but may need to revisit if we are able to develop further links with iNaturalist.
