### ISSUE TITLE
Adding new species/updating UKSI

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#65]
We currently have two requests for species to be added to the dictionary. The first is already in the UKSI so is presumably waiting for us to update:
- Parablennius pilicornis (request from Esther Hughes at MBA): https://data.nbn.org.uk/Taxa/NHMSYS0021126091

The second appears to be a vagrant from the USA and isn't yet on UKSI:
- Stramonita haemastoma floridans (request from Andy Dinsdale)

Three questions arise:
1. When can we next schedule an update to UKSI?
2. Is it worth adding in Parablennius pilicornis direct to iRecord in the meantime (and if so is that something I can do)?
3. What's the procedure for dealing with requests for species not yet in the UKSI - presumably we need to coordinate with Chris Raper but are we able to add them direct to iRecord in the meantime?

**Comment by kazlauskis** [comment]
We will have to think of some way to update the list without affecting the apps much. The main problem is  that if the warehouse list changes along with species IDs then records saved locally on devices and not yet submitted to the warehouse will have species ID mismatch. 

@johnvanbreda  - I was wondering if one could submit a record where species identity (_taxa_taxon_list_id_) is an NBN key?

Alternatively, maybe a record could specify UKSI list version:
_taxa_taxon_list_id_: 1423
_taxa_taxon_list_version_: 2

**Comment by JimBacon** [comment]
'species ID' is a rather vague phrase. I think you are referring to the taxa_taxon_list_id. 
The update surely cannot change this id otherwise all the existing records made against that list would then be incorrect. Assuming I am correct, you have nothing to worry about.

**Comment by johnvanbreda** [comment]
Correct Jim. The taxa_taxon_list_ids are in fact persistent in that I don't delete them during the UKSI update, only mark them as not for data entry. So the app could in fact submit against the old id and it would still make a valid record. Perhaps the real question is whether after each UKSI update we should regenerate the list of species loaded into the app code, preferably by a fairly automated process.

Going back the original questions:
- I heard from Richard Shotbolt today that the BMS updates are pretty much ready. When these are available I'd like to do an update, because it means we can go live with the BMS site. My best guess therefore is that this is no more than a week or two away.
- You could indeed add the species to iRecord (i.e. add it to the warehouse copy of the UKSI list) without specifying a TVK. We could then update it later to the correct TVK when Chris publishes it. It's important that this step is done manually though as my automated scripts would create a new copy of the taxon rather than update the existing one (as it would not be able to be sure it's not a homonym). I suppose the only reason to do this though is to placate the recorder - Chris can normally churn out a new TVK for you pretty quickly so I've tended to wait in the past. I could indeed explain how to do the addition to the warehouse if you want.
- I think this is more or less the same question as the above - ideally requests go to Chris, he creates a TVK then tells me the name, author, output group and parent, I then add them to the UKSI list via the user interface of the warehouse.

Its worth adding to this thread that the current script for syncing UKSI changes into the warehouse is pretty complex at the moment and therefore harder to maintain than I'd like. It would be nice to work out ways of making this process much simpler although I appreciate that might not be a small task in itself.

**Comment by JimBacon** [comment]
Hi John, 
When you say you mark a taxa_taxon_list_id as not for data entry during the update, I assume this is only a very small proportion, where there has been some change meaning they are no longer preferred, and that the overwhelming majority remain unchanged. Is that right?

**Comment by johnvanbreda** [comment]
Yes it should be a small proportion but its not a name becoming non-preferred that triggers it. In normal use, if a preferred name becomes a synonym through taxonomic name changes, then it is still valid and data entry is still allowed. The not for data entry flag would normally only be split for things like species name splits where the old taxonomic concept is no longer best practice but can't be automatically mapped to one of the new species names. 
If you look at the UKSI list on the warehouse there are approx 1500 not for data entry records that were last changed in April 2015, during an UKSI update. There are very few others.

**Comment by DavidRoy** [comment]
Am closing this now.  I suggest we re-open another UKSI update issue when timely.
