### ISSUE TITLE
Records not linked to Vice-counties

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#656]
Reported via iRecord forum, user = MikeF, reports...

I have a few records that are on the border of the Vice Counties of Surrey and East Sussex. They should all be in East Sussex, but if a Vice County filter is applied they appear in neither county. As a result verifiers do not see them. My records are 11515539, 11514788, 11514696, 11514676, 11514631. They are all now in West Sussex administrative county.

**Comment by kitenetter** [comment]
The only slightly unusual thing I can see about these records is that they have been entered using 10-figure grid references. Does that cause problems for our boundary indexing (can't see why it should)?

**Comment by burkmarr** [comment]
Doesn't seem to be due to bad geometry or anything like that. The query below in pgAdmin works fine - indicating that the records are all within East Sussex as the user says.
```sql
set search_path to indicia, public;
SELECT cof.id as oid, l.id as lid
FROM cache_occurrences_functional cof
INNER JOIN locations l
ON ST_Intersects(cof.public_geom, l.boundary_geom)
where (l.id = 735 or l.id = 736)
and (cof.id = 11515539 or cof.id = 11514788 
or cof.id = 11514696 or cof.id = 11514676
or cof.id = 11514631)
```
![image](https://user-images.githubusercontent.com/9275178/63852877-38afd880-c991-11e9-812b-6da9fa54a066.png)

**Comment by burkmarr** [comment]
I'll see if I can check the indexing.

**Comment by burkmarr** [comment]
None of those records correspond to samples that are in index_locations_samples:
```sql
set search_path to indicia;
SELECT cof.id, cof.sample_id, ils.*
FROM cache_occurrences_functional cof
left join index_locations_samples ils on ils.sample_id = cof.sample_id
where cof.id = 11515539 or cof.id = 11514788 
or cof.id = 11514696 or cof.id = 11514676
or cof.id = 11514631 
```
![image](https://user-images.githubusercontent.com/9275178/63858285-2471d880-c99d-11e9-94ec-c18fc6dd38a3.png)

Could this be related to https://github.com/Indicia-Team/warehouse/issues/329?

**Comment by johnvanbreda** [comment]
@burkmarr index_locations_samples is, confusingly, a deprecated table and not longer being updated. It was just left in place after the v2 upgrade to allow time for reports to be updated to the new method (cache_occurrences_functional.location_ids). I guess we should review and remove it now at some point.

This query shows that 1 of the records has now been successfully indexed to both East Sussex and the combined Sussex "super Vice County":
```
select o.id, o.location_ids, l.name
from cache_occurrences_functional  o
left join locations l on o.location_ids @> ARRAY[l.id] and l.location_type_id=15
where o.id in (11515539, 11514788, 11514696, 11514676, 11514631)
```

This query shows that none of these records are pending indexation:
```
select * from work_queue where record_id in (11515539, 11514788, 11514696, 11514676, 11514631)
```

This query shows that the situation is identical in the samples cache data, as you might expect:
```
select s.id, s.location_ids, l.name
from cache_samples_functional s
left join locations l on s.location_ids @> ARRAY[l.id] and l.location_type_id=15
where s.id in (6596299,6596317,6596319,6596345,6596589)
```

I tried hacking out the query from the spatial index builder that should update these samples and it seemed to work (without actually making changes). So I think either:
* The work queue tasks were never created
* The work queue tasks were created and removed from the processing tasks without actually being applied
* The work queue tasks were applied but failed to update the tables at that point in time. 

I can't see any particular errors in the logs around the time the work queue processing should have been happening for these records. It may be worth checking to see if this is more widespread and adding tasks to the work queue to update the samples (which automatically does the contained occurrences) for any samples that are not properly spatially indexed.

**Comment by burkmarr** [comment]
Thanks for correcting my misunderstanding John - I'll look at it a bit more this morning.

**Comment by burkmarr** [comment]
@johnvanbreda can you check my undestanding?

I ran this query to see how many occurrences are not indexed against any locations (and not pending indexing):
```sql
select count(*) from cache_occurrences_functional o
left join work_queue w on w.record_id = o.id
where o.location_ids is null
and w.record_id is null
```
There are 25,791. Listing the records I noticed that a lot of them had iNaturalist external keys, so I counted those and they account for 18,161 of them. The remaining 7,630 were entered via many different input_forms (over 90 different ones) - I can't see any sort of pattern there. I suppose that a few of these might be marine records that are not within any of our indexed locations, but I don't think that accounts for many.

A similar query to above using cache_samples_functional indicates 22,181 samples. I noticed that the iNaturalist records each appears to belong to a separate sample which would explain the similarly high number.

Is this too many samples to add to the work queue?

**Comment by johnvanbreda** [comment]
@burkmar thanks for the analysis. I wonder if there is a problem with the iNaturalist import? This does use ORM to post records so it ought to fire the hooks to generate work queue entries. Having said that, as it seems to have worked for most of the records this might be related to a one-off problem.

Of the remaining 7000+ records, a good many might be from outside the indexed area as iRecord does receive occasional records from people testing it from around the world. But you may as well re-index them just in case. Some might be for European continental records which will get assigned to a Countries 2016 polyon since this layer was only added recently and I only bothered to index the ABLE records against it.

I don't think that's too many to add to the work queue, it has done bigger batches before.

**Comment by burkmarr** [comment]
The records originally by MikeF are now indexed against East Sussex - I have updated the forum thread. I have added the unindexed samples to work_queue which I did like this:
```sql
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on) 
select distinct 'task_spatial_index_builder_sample', 'sample', s.id, 70, 2, now() 
from cache_samples_functional s
left join work_queue w on w.record_id = s.id
where s.location_ids is null
and w.record_id is null
```
Today there were 22,323 such indexed samples - an increase of 142 since I counted them yesterday. Unless those 142 are all outside any indexed locations, then there may be some ongoing problem which we need to keep an eye on. I'm going to close this issue now since MikeF's original problem is fixed. After the current work queue has been processed, I will keep an eye on the unindexed samples for a while and if it looks like its an ongoing problem, I will reopen.
