### ISSUE TITLE
Explore filter - bug in taxon tree element of filter

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#66]
See: http://www.brc.ac.uk/irecord/node/3860

Tephritidae within the Familes and higher taxa element, returns weevil records in error.

I have replicated this.

**Comment by kitenetter** [comment]
I was just about to report something similar:

- Go to Explore - My Records
- Set "What" filter to family Cimbicidae (a sawfly family)
- Only record listed is for Snowdrop (plant)

The family names and other higher taxa are being displayed correctly in the grid, the problem seems to be confined to the filtering. 

I've also got the second issue that the user reports, whereby the species- and family-level filters can be filled in once (in the "What" part of the filter), but then become unresponsive if you try to use them a second time.

**Comment by johnvanbreda** [comment]
Martin, can you raise your second issue as a separate issue please. I'll take a look at the filtering problem.
