### ISSUE TITLE
Question: how many species can be added to a verification filter?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#673]
We have a request to set up a verification filter for 400 invasive species, from various taxon groups.

- Will our filters cope with 400 species in one definition, or will this need to be split into a number of separate filters?
- Am I correct in thinking that the best approach would be to define the filter programmatically, rather than trying to add this many species via the usual filter set-up interface?

**Comment by johnvanbreda** [comment]
Actually I think the ideal approach here is to use a scratchpad (i.e. a Pantheon style pasted species list), then use that in the filter. The only part of this which isn't already possible is the selection of the scratchpad list in the filter builder tool so that would need to be implemented. The NT are already using scratchpad lists for filtering: https://www.brc.ac.uk/irecord/national-trust/species-lists.

So, I'd propose an option to select an existing scratchpad list in the What section of a filter. Maybe only enable this for admin verification filters at the moment?

**Comment by kitenetter** [comment]
Okay, if we can implement the scratchpad lists in the "What" section of the filter that would be good, and I agree that this should only be for admin-managed verification (and download) filters, at least for now.

Will the scratchpad approach also allow for lists of higher taxa to be set up, e.g. to make it simpler to create filters for groups such as aculeate Hymenoptera that currently require about 20 individual families to be selected each time a filter is created?

**Comment by johnvanbreda** [comment]
Yes, scratchpads allow hierarchical querying of the contents. BUT, isn't the problem here that UKSI does not recognise aculeates as a taxon, so the hierarchy skips from family to Hymenoptera? Here's an illustration:
```sql
select cttl2.taxon
from cache_taxa_taxon_lists cttl
join cache_taxon_paths ctp on ctp.taxon_meaning_id=cttl.taxon_meaning_id
join cache_taxa_taxon_lists cttl2 on ctp.path && ARRAY[cttl2.taxon_meaning_id] and cttl2.taxon_list_id=15 and cttl2.preferred=true
where cttl.taxon_list_id=15 and cttl.taxon='Lasioglossum calceatum' and cttl.preferred=true
order by cttl2.taxon_rank_sort_order
```
Outputs:
```
"Biota"
"Animalia"
"Arthropoda"
"Hexapoda"
"Insecta"
"Hymenoptera"
"Halictidae"
"Lasioglossum"
"Lasioglossum calceatum"
```

So, even with hierarchical filtering we are still stuck with a long list of families. But, the scratchpads approach does at least tidy this up.

**Comment by kitenetter** [comment]
Yes, there is no way round the list of families for the aculeates, but if I can set up that family list once as a scratchpad list and then re-use it each time it is needed that will be very helpful.

**Comment by kitenetter** [comment]
Scratchpad lists working well for verifier filters - closing.
