### ISSUE TITLE
VC assignment inconsistency between Verify and 'Verify - new'

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#679]
Steve Preddy (BDS, Monmouthshire) reports that although the GR of old record 91754 has been edited to ST36 and in 'Verify - new' the Vice County field shows 'North Somerset'. So far, so good.
However, in classic 'Verify' the Location field shows 'Monmouthshire|North Somerset'. 
According to Cucaera, ST36 is unambiguously 'VC6 North Somerset'. 
Is this a more general update problem or because of the editing of the GR?

**Comment by johnvanbreda** [comment]
@DavidHepper ST36 does just slightly clip Monmouthshire so the assignment of both VCs is technically correct. The ES version of the page is showing the first found VC due to the way the code is written, whereas you are seeing both on the old verification page.

@kitenetter presumably the new verification page should show both VC names in the record details?

**Comment by DavidHepper** [comment]
I'm not so sure about that. ST37 clips a sand bar of Monmouthshire but ST36 isn't within a country mile of it. 
![image](https://user-images.githubusercontent.com/24915271/65916567-7c9d5f80-e3cd-11e9-8e81-83da8af95c67.png)

**Comment by DavidRoy** [comment]
VCs have a marine buffer.
![monmouth](https://user-images.githubusercontent.com/2699478/65941395-d8460800-e422-11e9-8fce-b2f9f587f19f.png)

**Comment by johnvanbreda** [comment]
Yes - I did check that ST36 clips the VC boundary which it does because of the marine buffer.

**Comment by DavidHepper** [comment]
Thank you, both. I now see that the apparent buffer on the Cucaera map is probably the low tide extent whereas the marine buffer is much larger. 
I don't think the ES version should use the 'first found' VC but include both/all, as previously agreed for the classic version.
The lesson of this for our recording scheme seems to be that I need to insist on more precise grid references than hectad in order to avoid these problems for all but a very few records.

**Comment by DavidHepper** [comment]
Following up on this, it is most important to BDS for records to be assigned to both/all VCs touched by the Output map ref, as in the classic version. Verifiers can act accordingly to review the record themselves and, if necessary, refine the map ref to nudge it into the correct single VC. The current situation is a niggle to those verifiers who are currently unable to see some records that belong to their patch.

**Comment by johnvanbreda** [comment]
@DavidHepper the code does now index against all VCs touched by the record - that's not the problem. The issue is just that the label shown for the VC only finds one location name to show even if there are multiple. I've just added a code change so all the VC names would show in a semi-colon separated list after the next update.

**Comment by DavidHepper** [comment]
That's just the job, thanks.
