### ISSUE TITLE
Species map page - tick boxes hidden behind map

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#686]
This applies to the maps accessed via Explore - Species maps (https://www.brc.ac.uk/irecord/species-maps). You can add multiple species to the map, and each additional species gets shown above the map with a tick box, but once you go over about four species the tick boxes get hidden from view behind the map.

Assigning @burkmarr to have a quick look and see if this is easy to fix, but if not we can schedule later on as resources allow.

**Comment by johnvanbreda** [comment]
My recollection is that this was designed to only show max 4 species layers at a time.

**Comment by kitenetter** [comment]
The species grid on the left does allow you to select more than four species, and dots continue to get added to the map, but the tick boxes above the map are limited to four. If we can't expand the tick boxes perhaps we should limit the selection altogether to a maximum of four?

**Comment by burkmarr** [comment]
@kitenetter and @johnvanbreda. After some investigation and experimentation this is what I have found and what I've come up with...

- The limit on the number of layers is coded to be dependent on the number of styles specified when the form is edited ('SLD from geoserver...' field under 'other map settings'). So by adding new styles in there (which must first be defined in Geoserver) or simply repeating those already shown, you can increase the number of layers that can be displayed on the map.

- As new layers are added beyond this limit, layers on the bottom of the stack are meant to be removed. However there is a bug that results in more layers than the 'limit' being added if any of the displayed layers are not currently visible in the grid (e.g. if a filter has been applied). This might account for your impression that this was the default behaviour Martin.

- As you've noted Martin, the height of the box that displays the layers in the legend is fixed (90px) so if more than 4 layers are added, they are not visible. I think that this has been coded to ensure that long legends don't detract from the map (pushing it down the page). I'm sure that also accounts for the cylcing of instructional messages too.

I propose this solution:

- Allow the legend box to expand with the items that it contains (pusing the map down the page as it grows).
- Remove the limit to the number of layers that can be added (or set it to something like 20) - it's easy enough for users to remove them.
- Add a checkbox that can be used to show/hide the instructions.
- Add a checkbox that can be used to show/hide the legend items. This mitigates against the fact that with many layers added, the map would be pushed a long way down the page.

This is what it looks like on my localhost setup:

Here are more than four layers added. If we do this, we should go and define more styles on Geoserver (easy enough - I can do that) - maybe aim for 10 point styles. (I've just spotted that the instructional text will need updating to account for the change in layer limit.)
![image](https://user-images.githubusercontent.com/9275178/67011599-d731fd80-f0e7-11e9-8d6b-45469c0bcc1b.png)

Here is the same thing with istructions removed:
![image](https://user-images.githubusercontent.com/9275178/67011888-4f002800-f0e8-11e9-82fc-714a50b453a8.png)

And here with legend removed:
![image](https://user-images.githubusercontent.com/9275178/67011919-60e1cb00-f0e8-11e9-80d9-c408a3614e2e.png)

(There are no dots on the maps because 1) I don't have any records for those taxa on my DB and 2) I have a problem with my local Geoserver.)

These code chanes are pushed to GitHub on branch iss-686, but I haven't made a merge request yet - let me know what you think.

**Comment by johnvanbreda** [comment]
I don't have any problems with the proposal. A couple of thoughts:
1) When setting up new styles, see colorbrewer2.org for colour palette ideas. 
2) If the map now moves around on the page, you might need to call map.updateSize() after a move? If the map seems to redraw OK on several browsers then you are probably fine.
3) Moving this page to ES at some point seems sensible.

**Comment by burkmarr** [comment]
@kitenetter - are you happy with this proposed solution? If so, I will go ahead and make a pull request.

**Comment by kitenetter** [comment]
@burkmarr proposals look excellent. Is there a limit to how many species can be added to the map altogether? The user whose request led to this issue wanted to have c. 30 species on the map. If that is not achievable then so be it - can the limit be added to the instructions text?

**Comment by burkmarr** [comment]
No limit, but in my experience showing more than an handful of different species on one map results in an unusable map. Lets set a limit of 30 for now. Could be difficult to come up with 30 different point styles but I'll see what can be done. I'll add the limit to the instructions.

**Comment by burkmarr** [comment]
@johnvanbreda - quick_species_maps has both a CSS and a SASS SCSS file. I've not used SASS before but I know they are compiled to CSS. I need to add some styles - should they go in the CSS, SASS or both?

**Comment by johnvanbreda** [comment]
You update the .scss file, then use sass from the command line to compile it to the css file. No manual edits to the css file.

**Comment by burkmarr** [comment]
Code submitted in pull request. I still have the Geoserver styles to add, but this will work without them - and just cycle through whatever is available and declared in the form.

**Comment by burkmarr** [comment]
@kitenetter - this is now available on the live site. I've added some extra styles but whether we need more or fewer depends on how users will use it. But, of course, different people may use it in different ways. A short-coming of this tool is that users can't choose a particular style for a particular layer, the code simply cycles through those available, assigning them sequentially. As John suggested, if there is a demand for a tool like this, it might be worth thinking about a more extensive reworking using ES at some point.

**Comment by kitenetter** [comment]
Thanks @burkmarr that addresses the issue as raised and makes these maps more usable. As you say, there is a wider issue that we need to come back to around what types of mapping and reporting we provide for users and recording schemes, and we need to set aside some time to review that when we can. Closing this issue.
