### ISSUE TITLE
Update recorder league table

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#7]
Data missing from recorders' league table.   
http://www.brc.ac.uk/irecord/recorder-league

For example, Andy Musgrove has submitted thousands of records but his total in the league table is only 30-odd

**Comment by johnvanbreda** [comment]
I think a bug occurred when Andy switched email accounts around, resulting in his records being left against an old deleted account. I've moved them into the new account which fixes the user league. 
I've quickly checked the data to confirm this problem is not widespread - it isn't. 
I've also checked the code and it looks OK. This area should be tested further though so I'll leave this open.

**Comment by DavidRoy** [comment]
Thanks
