### ISSUE TITLE
Elasticsearch: taxon name not displaying in grid

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#706]
This hasn't caused any problems but is a bit odd. The record concerned is:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=12069634

The record is of a moth species that was only added to the iRecord dictionary a couple of weeks ago. The record page shows the full taxon information, and on the new verification page that information also appears in the record details panel, but in the grid the taxon name is missing:

![image](https://user-images.githubusercontent.com/16039111/67947724-301b8e80-fbdc-11e9-9434-a5d0937932fd.png)

**Comment by kitenetter** [comment]
This name is still missing from the new page at 9 Jan 2020.

**Comment by johnvanbreda** [comment]
Need to regenerate the taxa.yml file then either refresh the entire index, or just the records for any changed taxa.

**Comment by kitenetter** [comment]
@johnvanbreda is that going to need doing every time we add a new species? Do we need to set up a new procedure or workflow operation to cover this?

**Comment by johnvanbreda** [comment]
If a species is recorded that Elasticsearch does not recognise, then it will appear in the Taxon name field, but not the accepted taxon name and common name fields. Although we could probably improve the logic in the importer to fix this, the name will never be completely correct in ES without updating the YML files because we won't have other info like the taxonomic parents. So, ultimately, yes, we will need to update the taxa.yml and taxon-paths.yml files and refresh the relevant records in the index.

I've just rebuilt the YML files and started a background index refresh.

**Comment by johnvanbreda** [comment]
OK after refresh so closing.
