### ISSUE TITLE
Record deletion request

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#707]
David Hepper requests the deletion of a set of occurrences following an import that went wrong:
"Please delete all records with Source ID 23|346 and Record ID between 12085167 and 12090702 inclusive."

To be on the safe side I assume we'll need to filter on created_by_id as well, which will be warehouse user ID 18856.

**Comment by kitenetter** [comment]
Awaiting confirmation that this is still required (I expect it is).

**Comment by DavidHepper** [comment]
I've been looking for all records imported with 'iRecord | DRN dragonfly imports' that had the Occurrence Comment mangled by a bug in the import system, fixed in #717 (20/11/2019 09:50). 
I found them by looking for 'comments' (field name displayed as "Occurrence Comments") = "1" or "Y", or blank when a comment was expected.

All these are imports with Source = 'iRecord | DRN dragonfly imports' = 23|346.
**Start of Range	End of Range	Source	Imported on	Imported by User	Comment**
12044180	12046940	23|346	26/10 and 27/10	Averill, Mike	Due to bug in import process
12085167	12090702	23|346	31/10	Hepper, David	Bedfordshire records, due to my error and the bug in import.
12128608	12128943	23|346	04/11	Winter, Paul David	Due to bug in import process
12132980	12133756	23|346	05/11	Winter, Paul David	Due to bug in import process
12171094 	12171809 	23|346	11/11	Averill, Mike	Due to bug in import process
12195753	12195836	23|346	15/11	Smallshire, Dave 	Due to bug in import process
12197010	12198590	23|346	15/11	Nick Tribe	Due to bug in import process
12199727 	12199928	23|346	16/11	Simonjoseph1967@sky.com 	Apparently unaffected but safer to delete anyway
12200041 	12200062 	23|346	16/11	David Clarke 	Due to bug in import process
12643651	12652812	23|346	23/01/2020	Hepper, David	Due to unexpected duplication between Bugalert records and others already imported.

I appreciate that this is a sizeable job but it is really urgent, given our schedule for the State of Dragonflies 2020 work. Some people have already reimported their ranges but others are waiting for the deletions.

**Comment by kitenetter** [comment]
@burkmarr I've assigned this to you but let me know if this is a problem, and if you need me to do any preparatory work (e.g. to find the user IDs for the people who did the uploads).

Here is @DavidHepper 's list as a spreadsheet:

[DRN records to delete.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/4109261/DRN.records.to.delete.xlsx)

**Comment by burkmarr** [comment]
@DavidHepper - to identify the records for deletion, I'm assuming that all records between in each of those ID ranges that were imported by the person you've identified can be deleted. Is that right?

**Comment by DavidHepper** [comment]
No, not necessarily, @burkmarr . There's always a chance that two people were importing at the same time. The combination of range, CMS User and Source will uniquely identify those records to be deleted.
This is now really urgent, please. We're supposed to finish verifying by 31 Jan so we can hand over records to CEH for analysis. These duff ones are clogging the verify queues!

**Comment by burkmarr** [comment]
@DavidHepper & @kitenetter. The deletions are done now. Let me know if there are any problems.

12044180 12046940 23|346 26/10 and 27/10 Averill, Mike - **54 deleted**
12085167 12090702 23|346 31/10 Hepper, David - **4997 deleted**
12128608 12128943 23|346 04/11 Winter, Paul David- **325 deleted**
12132980 12133756 23|346 05/11 Winter, Paul David - **739 deleted**
12171094 12171809 23|346 11/11 Averill, Mike - **712 deleted**
12195753 12195836 23|346 15/11 Smallshire, Dave - **82 deleted**
12197010 12198590 23|346 15/11 Nick Tribe - **1480 deleted**
12199727 12199928 23|346 16/11 Simonjoseph - **194 deleted**
12200041 12200062 23|346 16/11 David Clarke - **22 deleted**
12643651 12652812 23|346 23/01/2020 Hepper, David - **9044 deleted**

**Comment by DavidHepper** [comment]
Thank you, Rich! Much clearer now.
