### ISSUE TITLE
NBN data exports - grid reference error

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#71]
This arises from exporting data to the NBN Gateway using the data flow filters.

A proportion of exported records are ending up with no data in the GridReference field. I have been able to find three different sources that produce this issue:
1. For at least some records entered via Garden BioBlitz (some of which gave a postcode as the primary location), the calculated grid ref is not getting picked up in NBN export. This applies across most if not all Garden Bioblitz years. Example occurrences:
2. 961989
3. 999633
4. 963698 (Northern Ireland)
5. For at least some records that have been flagged as sensitive, no grid ref is being passed to NBN. Presumably what should happen is that the blurred grid ref should be used in such cases. Example occurrences:
6. 2529144
7. 2520046
8. Some records entered via CEDaR have missing grid references - I can't see an obvious reason for this. Example occurrences:
9. 1015234 (entered via CEDaR form)
10. 2070138 (entered via Moths form)

Not sure if these errors also occurs in user and LRC downloads when the "NBN Exchange" format is chosen.

**Comment by MNSmith** [comment]
It would be very useful if the "NBN Exchange" format report actually produced a file which is suitable for immediate upload to the NBN Gateway - ie it follows the format requirements produced by the NBN.  At the moment is does not and requires a lot of manual intervention to make it so.

**Comment by kitenetter** [comment]
@MNSmith I take it that you mean the NBN Exchange format option from the Download page? If so I'll raise that as a separate issue - the issue referred to above is for a separate set of data exports that BRC carries out on behalf of those recording schemes that wish us to send verified data direct to NBN.

**Comment by MNSmith** [comment]
Yes - the NBN Exchange formatoption on the download page is what I mean, so a separate issue would be helpful.

**Comment by johnvanbreda** [comment]
@kitenetter Currently the NBN export uses the public reporting format, which drops grid references where sensitivity or privacy might be a concern. The circumstances when this occurs are:

- The record was flagged as sensitive.
- The sample containing the record was flagged with a privacy precision. This behaves exactly like a sensitive record but reflects a privacy concern about the site rather than a risk to the site. The example here is the Garden Bioblitz where we did not want to give out locations of gardens (especially as many minors took part). 
- The record is inside a sample that contains another sensitive record, even if the record itself is not sensitive. Perhaps over-zealous, but I was concerned that it would be easy to work out the location of a record if you knew which sample it sat within. 

Although using the output_sref field as you suggest for blurred records sounds like a way forward it is a bit tricky because the output sref field might not be in the same projection or format as the one that was input. As far as I can see, the guidelines given with the NBN Exchange format don't say that you need to blur records yourself if they are sensitive.  Therefore I propose the following changes:

- Send the output to the Gateway at full precision. According to the notes in the exchange format, "A sensitive record has additional access restrictions applied to it on the NBN Gateway" so we would be relying on those access restrictions.
- Set the sensitive flag in the Gateway output data for sensitive records AND those belonging to a private sample.

**Comment by johnvanbreda** [comment]
Closing as new process available for Atlas DwC-A exports
