### ISSUE TITLE
species name inconsistency between old and new verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#713]
This applies to record id 12166897, which originates from NatureSpot and uses a NatureSpot aggregate taxon that is not available in the UKSI.

On the main iRecord details page the aggregate name is correctly displayed:
https://www.brc.ac.uk/irecord/record-details?occurrence_id=12166897

On the old verification page the agg. is correctly displayed:

![image](https://user-images.githubusercontent.com/16039111/68584722-4cd78200-0478-11ea-8b9a-25f0fbbaad62.png)

On the new verification page the agg. is **_not_** correctly displayed:

![image](https://user-images.githubusercontent.com/16039111/68584690-33363a80-0478-11ea-90a2-84b86aae4f95.png)

![image](https://user-images.githubusercontent.com/16039111/68584749-5e208e80-0478-11ea-9ef3-3381cca68682.png)

**Comment by johnvanbreda** [comment]
Elasticsearch is using UKSI as a dictionary to look up the correct names where a TVK is provided. Where a name isn't on UKSI, such as this aggregate, it really shouldn't have the same TVK as a UKSI name otherwise the concepts get muddled. So this is really a problem with the NatureSpot list data, not the code.
