### ISSUE TITLE
Question: why are RSPB data imports not editable?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#724]
I'm working on some data imports for the RSPB. These get imported into the RSPB Species Data website (id = 97), and during import both the sample:created_by and the occurrence:created_by atributes are set to “RSPB_Dataunit” (the RSPB dataunit account, warehouse ID 93139).

On iRecord, if I masquerade as the RSPB account, and go to My Records, I can see all the imported records but I cannot edit them.

The website agreement for the RSPB Species Data website has the box ticked for "Provides data for editing" but not for "Receives data for editing".

Why are the records not editable in iRecord, is it an issue with the website agreement or is there something about the way that I'm importing the records that causes problems?

In my role as verifier I **_can_** edit the RSPB records, so it seems odd that a verifier can edit them but the record originator can't.

**Comment by kitenetter** [comment]
Hi @johnvanbreda is this an easy one to answer?

**Comment by johnvanbreda** [comment]
Records from a different website are not normally editable on iRecord because we don't have the input form setup. The exception to this is the Verifier role where we provide a generic record editing form. A solution might be to enable the generic editing form for all records from outside iRecord, as long as the website agreement allows this.
