### ISSUE TITLE
Data protection / licence implications of "Post to British Dragonfly Society recording?" y/n box

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#730]
![image](https://user-images.githubusercontent.com/24915271/70238930-37493580-1762-11ea-8e3a-6937709f4a49.png)
This field started to appear recently at the top (as if very important) of the 'What Did You See?' tabbed page of the Taxon-specific recording form for Dragonflies. 
- The default radio button is 'No'. Could this be changed to 'Yes', please?
- It appears to change the survey between **iRecord | iRecord Dragonflies** and the new survey sub-type **iRecord | iRecord Dragonflies | British Dragonfly Society recording** 
- What is the implication of selecting 'No'? Does it mean we cannot use the record? Does the record no longer have a **CC BY** licence?
- Why was this feature added?

**Comment by kitenetter** [comment]
Hi @DavidHepper as far as I'm aware this is not a new feature. It interacts with the Activity pages. Because you are a member of the "British Dragonfly Society recording" activity, you are given the option of linking your records to that activity. The records still go into the same survey in the database, and they are still available to BDS in the normal way, the only difference is the addition (or not) of a flag to link them to the Activity. 

It has no impact on CC licences (we have not yet implemented record-level licences in iRecord).

**Comment by kitenetter** [comment]
Closing.

**Comment by DavidHepper** [comment]
It would be useful to make the meaning clearer. 
I'm struggling to think of a scenario where the recorder would _not_ want the record included in the Activity. At present it looks as though the default is to opt out of being included in all BDS research.
