### ISSUE TITLE
'Sample Method' is prompted for by the Import page but not stored

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#731]
We religiously select 'Field observation' when prompted for 'Sample Method' on the import page but it seems to be ignored by our data source 'iRecord | DRN dragonfly imports'. I don't see it when the record is edited or exported. 
Why is this field on the Import page rather than being a column of the spreadsheet being imported? It is the only such field treated this way.

(This issue is now separated from the original report in a Comment attached to #717.)

**Comment by DavidHepper** [comment]
Or is it stored correctly but the field not shown in the Details pane when a record is selected?

**Comment by kitenetter** [comment]
John's comments under #717 implied that the value is not being stored, rather than not being displayed.

A workaround might be to import "Field observation" as the sample method in the csv file, rather than using the import page option.

But of course since the import page provides such as option it ought to work, so that needs investigating.

**Comment by kitenetter** [comment]
The data structure for DRN imports does not include an attribute for "Sample method", hence no such value can be stored. The import page option will not be offered in the new version of the importer (soon to be available for testing). Closing.
