### ISSUE TITLE
Data downloads – suggested actions part 1

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#74]
This picks up from #4 . I’ve tried to break things down into things that we can do quite easily (I hope) and things that will take longer or need more thought (see #75 ). These are the things I hope we can do easily.

**Output grid ref**
This is mostly working well but for records outside the UK (including from the Channel Islands) this column is being populated with lat/longs. Since lat/longs have columns of their own, they don’t need to appear in the Output grid ref column. For the Channel Islands, it would make more sense to use the Channel Islands grid ref for the Output field, while for other overseas records Ouput grid ref should be blank.

**Vice county**
This is an essential field for many recording schemes, but currently is much less helpful than it should be:
- it sometimes includes the ‘pseudo-vice-counties’ of Yorkshire or Sussex
- it is sometimes left blank
- the vice-county names used are not standardised with other systems, nor with the list of vice-counties on the BRC website
- the VC number is not given

Suggested solutions:
- Can we remove all references to the two pseudo-vice-counties?
- Can we run a database update to ensure that all records have a vice-county allocated to them where appropriate?
- Can we edit the list of vice-county names to make them more compatible with other lists (and if we do will that cause problems elsewhere, e.g. with the verification filters)? (Problem: there doesn't seem to be much consensus on what the correct names are!)
- Add an additional column that gives the vice-county number (which is much easier to work with when collating with other external data) [if we do this the issue of non-standard VC names become less pressing]

**State**
At the moment we are only showing the old level 1 verification terms (Verified/Rejected etc.) We need to change this, or add to it, to display the new two-tier verification terms. Suggest having two fields:
Verification status: Accepted / Not accepted / Unconfirmed
Verification detail: Correct / Considered correct / Unable to verify / Incorrect / Plausible / Not reviewed

**attr_biotope**
Not currently getting populated. Do we need two columns to display the two tiers of habitat?

**Date**
It’s very difficult to use the downloaded Date field consistently at the moment because it includes vague dates. We need three columns:
- Date
- Date to
- Compiled date (i.e. the column we currently have that mixes vague dates and single-day dates – this may be easier for some users who simply wish to display the data, but the two separate Date and Date to fields are needed for use with external databases)

I would also prefer the date columns to appear earlier in the sequence of colunms than they currently do (see below for reordering).

**External record keys**
For those records that have come in to iRecord from other systems, and have retained a field for the record ID in the external system, it is essential that we include this attribute in the download, otherwise it is impossible to track data across multiple systems.

**Determiner vs attr_det_full_name**
It’s not clear to me why we need both of these fields – can we remove one of them?

**Reordering of columns**
This isn’t vital, but I think it would make a more logical sequence.

![image](https://cloud.githubusercontent.com/assets/16039111/17066592/a6afac80-503f-11e6-8644-e0ebc3aea9f7.png)

**Comment by DavidRoy** [comment]
Small additional requirement = strip spaces out of OS grid references.
http://www.brc.ac.uk/irecord/node/3973

**Comment by johnvanbreda** [comment]
Should we be stripping spaces out at the point of download, or perhaps prevent them being input in the first place?
Another idea would be to build in the tidying up of grid references into the report cache table generation code. So we still have the original as entered, but have a clean copy for reporting.

**Comment by kitenetter** [comment]
I guess some users prefer to be able to input grid refs with spaces - some people find it easier to type and understand SU 123 456 as opposed to SU123456. But I don't see any need to retain the spaces following data entry, so they could be stripped out as the record is saved. 

If you do think there is any need to retain what the recorder originally entered then tidying them up as part of the report generation would be fine, but I don't think there is any real need to retain the spaces.

Does this have any implications for data that is imported into iRecord via a csv, or from other websites/apps? Do we need to retain some flexibility there, in which case stripping out as part of report generation might be the better option?

**Comment by DavidRoy** [comment]
I favour saving without the spaces as I can't see any benefit of keeping spaces.  It then simplifies reporting.  But I agree that we can allow gridrefs to be entered with spaces for those who prefer this - perhaps we need a message on the input forms so that users aren't surprise if they subsequently want to edit records?

**Comment by kitenetter** [comment]
For clarification, the above discussion is initially focused on the standard download format that is available to all users. A separate (but similar) download is also available for LERCs - it probably makes sense to have the same changes made to the LERC format, but we are awaiting feedback on whether there are any different requirements from the LERCs.

**Comment by DavidRoy** [comment]
Small addition to this issue.  Strip out text codes (e.g. &#) from .csv download fields.  Example is:
http://www.brc.ac.uk/irecord/record-details?occurrence_id=4236774

Field value for 'Record comment':
A Male (same as yesterday's?)
gets translated to:
A Male (same as yesterday&#039;s?)

Other fields where this occurs are 'Record name', 'Site name' etc.

**Comment by japonicus** [comment]
> Strip out text codes (e.g. &#) from .csv download fields.

While I agree that html entities shouldn't appear in csv output, I think this reflects a problem with the data entry or import code rather than with the csv download view.  The character entities should have been interpreted before being stored in the database - so that the raw database content is clean and doesn't contain entities.

There appears to be quite a widespread problem with character encoding at the moment.  If using iRecord for data entry, no escaping of sensitive characters occurs at all - which makes it trivial to maliciously or innocently enter records that break html formatting or editing.

e.g. these two records on the dev website:
http://192.171.199.230/irecord7/record-details?occurrence_id=4338397
This displays correctly but the ' "A" ' in the recorder name in double-quotes means that that field is corrupted on the edit form (it truncates at the first double-quote)

http://192.171.199.230/irecord7/record-details?occurrence_id=4338396
demonstrates unescaped html. The example is obviously deliberate abuse, but similar behaviour could be triggered inadvertently just by including a less-than symbol in a comment - which would be quite reasonable to do innocently.

Both these records currently display correctly if exported as csv.

At the moment the iRecord mobile app stores escaped html (unlike iRecord) which means that the records display correctly on the website (without security holes) but if exported as CSV would contain html entities rather than the correct characters. I assume that the butterfly app that generated your example record also encodes entities.

I think the 'correct' behaviour would be to store unescaped html in the database but to escape content wherever it is displayed as html (so that character encoding is always a function of the view code - just as the csv view currently correctly escapes '"' characters).

**Comment by kitenetter** [comment]
Additional requirement/suggestion:

Currently the download provides hyperlinks directly to images associated with a record (sometime multiple links strung together if there is more than one image). I think it would be more useful if we:
- Add a column that gives a hyperlink to the record page (rather than direct to the image)
- Add a column that is a yes/no for whether one or more images is present in the record
- Remove the column that we currently have for hyperlinks to the images themselves

**Comment by johnvanbreda** [comment]
Hi @kitenetter, does @DavidRoy agree with the proposed change to the images column? I am aware that a link to the record page does not give the same functionality as having the image filenames. This would affect any code written to extract the images from a download, though I'm not sure if anyone has done that.

**Comment by kitenetter** [comment]
Additional requirement: the download to include a column for "Activity" that will show which Activity a record has been contributed to, if any. (Requested by TWIC but useful more generally.)

**Comment by DavidRoy** [comment]
Sorry for delay in responding to this thread.  I agree with Martin's suggestions about how to handle image information within downloads

**Comment by kitenetter** [comment]
Two additional requests have arisen for the download procedure:
1. Addition of an attribute that allows "Queried" records to be identified (they are no longer distinguished in the "State" attribute)
2. Addition of (one or more) Method attributes

I will add a new issue for the second of those requests, as it is not straightforward.

**Comment by kitenetter** [comment]
Additional requirement based on feedback from verifiers: can we rename the "Grid reference" column as "Original location reference" or similar? Calling it "Grid ref" is misleading as it may contain lat/long and other coordinates, which leads people to get annoyed (and to overlook the "Output grid ref").

**Comment by DavidRoy** [comment]
I'm not sure if this is related to John's last comment (about leaving output grid empty for lat/long records), but a view has been expressed (e.g. by some LERCs) that it is awkward having grid refs and lat/long spatial locations stored in the same column of downloads.

**Comment by johnvanbreda** [comment]
> attr_biotope
> Not currently getting populated. Do we need two columns to display the two tiers of habitat?

As far as I can see, it is populated where the system function is set to biotope for the attribute on the warehouse. However if you run the following query you will see there are many potential attributes that don't have their system function set:
`select * from sample_attributes where (caption ilike '%habitat%' or caption ilike '%biotope%') and coalesce(system_function, '') = '';`
Habitats can potentially be several levels deep, not just 2. Perhaps a generic change so that any hierarchical termlist attributes are output with their ancestry in the reporting cache tables (used to populate the downloads), e.g.:
"Grassland >> Dry grasslands including chalk downland"

**Comment by DavidRoy** [comment]
@kitenetter - can you set the system function for relevant habitat attributes.  I don't see any reason not to

@johnvanbreda I would support the generic change of using a standard notation for multi-values for attributes

**Comment by johnvanbreda** [comment]
Closing issue as everything now covered by the sub-issues.
