### ISSUE TITLE
Menu structure for verifiers' guidance

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#741]
Following on from #519 I have created a page to signpost verifiers to resources that are only intended for verifiers:
https://www.brc.ac.uk/irecord/resources-verify

My intention was to have that page as a sub-menu under "Verify - new". But this has taken me back to a long-standing problem, which is that if a top-level menu item has children, you then need to double-click on the top-level item for it to take effect.

I don't want to make verifiers have to double-click to get to their verification page, so I have removed the resources sub-menu again for now.

Is there a way of changing the menu behaviour so that a menu item with children does NOT require a double-click?

**Comment by burkmarr** [comment]
@kitenetter. I'm not sure what you mean - can you clarify?

I added some dummy submenu items on iRecord dev (under 'verify' rather than 'verify - new' because that's not on there). The image is shown below. Is that the sort of structure you mean? If so, where is it that you want to avoid mouse clicks?

![image](https://user-images.githubusercontent.com/9275178/72254691-bdc42300-35fc-11ea-91e2-5828c635a071.png)

**Comment by kitenetter** [comment]
In that example, what I find is that when a submenu exists, the top level menu requires a double-click to access it.

At the moment, I can go to the top-level "Verify", click on it once, and the verification page opens. Once a sub-menu exists, I have to click on "Verify" twice in order to access the verification page.

**Comment by burkmarr** [comment]
@kitenetter - this behaviour is controlled by a module called Superfish and associated JS library. Our main menu is a Superfish menu. There is a configuration option (see below) where we can turn this behaviour off - so that clicking once on the main menu item goes straight to the link. (We'd need to select the ```Disable``` option.)

A potential problem with that is that this behaviour is really designed so that touch screens can be used - which includes mobile devices and tablets but, increasingly, laptops too.

So a better option might be to leave it enabled, but to also select the ```Hiding the sub-menu on the second tap, adding cloned parent linkes to the top of the sub-menus as well``` option.

I've set these options on dev iRecord - so you can look at the way it affects behaviour, e.g. on the Explore menu.

Presumably the objection to requiring two clicks is that it is not intuitive. But repeating the main menu item in the sub-menu gets over that in my view. It is pretty clear, after the sub-menu appears on the first click, that the top item in the sub-menu needs to be selected to go where required.

![sf-touchscreen](https://user-images.githubusercontent.com/9275178/72260192-35e51580-360a-11ea-9a57-7cce2a1fad7c.JPG)

If you want to change these options yourself on dev to try things out, they are here: http://test.brc.ac.uk/irecord_dev/admin/structure/block/manage/superfish/1/configure

I think you will need to log on as admin.

**Comment by kitenetter** [comment]
The behaviour on the dev site solves the problem of parent menu links appearing not to work if users don't know about double-clicking, but instead it adds a problem of the parent menu item appearing not to work if users don't spot that it is repeated in the submenu.

That may not be a big change but it is a change and it may confuse some people, and it just doesn't seem very elegant to have the same menu item shown twice. And it means that menus without submenus behave differently from menus with submenus.

My ideal would be for the menus to work in the same way as they do on the main UKCEH website, where the top-level item can be accessed via a single click, but the submenu items are also displayed and can be chosen via a single-click instead. If there's no obvious way to achieve that via superfish then I think my preference is to keep things as they are.

@burkmarr let me know if you disagree, otherwise feel free to close this issue.

**Comment by burkmarr** [comment]
@kitenetter - I've set the 'Disable' option on the sf-Touchscreen. I think that gives you what you're after. It might compromise behaviour on touch-screens though. Have a look at dev again and see what you think.

**Comment by kitenetter** [comment]
I'll have another look

**Comment by kitenetter** [comment]
I think that the dev site implementation works well via a keyboard, but I've struggled with it on a touchscreen.

Also, @BirenRathod tells me there are plans to implement a different way of handling menu functionality that should address this issue, so I don't think we need to do any more at the moment. Closing.

**Comment by BirenRathod** [comment]
@kitenetter 
I think you could create or migrate this issue into iRecord Drupal 8 migration. It is really a minor issue which could be resolve in Drupal 8 anyway.
