### ISSUE TITLE
NBN data exports and other downloads - sensitive records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#77]
At the moment a recorder can choose to ‘blur’ their records on iRecord if they are sensitive. However, when the data is exported to the NBN Gateway it is exported at the original unblurred resolution and the record is flagged as sensitive. As a result the record is invisible to everyone apart from those granted enhanced access to the iRecord data set. If sensitive records could be instead be exported at the ‘blurred’ resolution they could be made publicly available rather than hidden. This need will become even more critical with the switch to an ‘Atlas..’ portal without enhanced access. (Originally requested by Bat Conservation Trust.)

For those schemes that download data from iRecord into an external database, sensitive records are currently excluded from the download (even though they are visible to verifiers in the verification grid). It would be good to use the same approach here as for NBN, i.e. to allow download but only at the resolution specified by the recorder.

**Comment by MNSmith** [comment]
If sensitve records are currently excluded from downloads then that effectively prevents those organisations who are allowed to download verified data (eg LRCs, appropriate recording schemes etc) from getting hold of the records.  I have always been of the opinion that "blurring" records is purely there so that the records can be mapped for public consumption at one resolution but seen in full by those who need to see the data.   If records for things like EPS species are not making it out of iRecord to LRCs then what is the point of the record?  Download of sensitive records should be at full resolution for approved downloaders, I would expect that any records that I verify (and have download rights for) would actually download..  I'm not sure if recorders know what effect blurring records is actually having, ie it never leaves iRecord except at the blurred resolution.
.

**Comment by johnvanbreda** [comment]
@MNSmith I agree with this - I've proposed this solution as part of the fix for #71 as well.

**Comment by kitenetter** [comment]
Closing, but need to update our documentation following move to DwC exports for NBN Atlas. See #407
