### ISSUE TITLE
LERC download role getting hidden?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#786]
In order to access the LERC download options, an LERC has to have an iRecord account that has been given the role of "regional collator". When they go to the LERC download page they should be able to download all relevant data in one go (subject to the current limit of 20,000 records) from :
https://www.brc.ac.uk/irecord/lrc-download-2

However, it appears that if a user has both a "regional collator" role AND a "survey downloader" role, the "survey downloader" role takes precedence, and disallows the "regional collator" role.

My own "Martin C. Harvey" account has both roles, but if I go to the LERC download page I can only choose one of my two "survey downloader" options - I have lost the ability to download all records for my area.

![image](https://user-images.githubusercontent.com/16039111/73673586-c7462580-46a6-11ea-8356-81e28a1bf098.png)

I'm not sure if this is something that has changed recently - possibly not, as I think I've only recently had both roles, so I may not have noticed this mismatch before.

Question for @johnvanbreda - is there a quick solution to this, or will it be best addressed through the move to ES downloads?

**Comment by johnvanbreda** [comment]
Just noting what's happening - will think about a solution later. The survey downloader role is not the problem, but because there are data flow filters attached to your account with "defines permissions" set to true, these act as a global limit on the data accessible to you for this type of download. Rather like contexts for a verification. Therefore, although the report still works as a regional collator download, it has the additional filter of your chosen context.

**Comment by kitenetter** [comment]
I think this has been resolved via #987 - closing
