### ISSUE TITLE
Recorder name formatting.

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#80]
Karolis suggested I open a thread regarding this point.

At present Recorder names are arriving on the records and the verification grid in either [Firstname] [Lastname] format or [Lastname] [Firstname] format.  The second style seems to be a holdover from the old "JNCC Recorder" style while the former is more typical of the modern style of forms.

It would be useful to have the Recorder names displayed in one consistent style across iRecord.  My preference would be for [Firstname] [Lastname] format.

**Comment by kitenetter** [comment]
@MNSmith this is difficult, and probably impossible, to achieve with any degree of consistency. On iRecord itself, where users are logged in and have included their name in their use profile then iRecord sets the default as "Surname, First name" for the Recorder and Determiner fields. But for data arriving via apps and other systems there may be different defaults, and for data that is imported from spreadsheets or via users who are not logged in the recorder name will appear in whatever format the user has chosen.

Surnames and first names are stored as two separate fields in the user accounts, but in the actual records all that is stored in a single text string, so we don't have any automatic way of recognising and formatting surnames and first names as two separate entities.

I agree that a consistent format in names is desirable, but there is a trade off between consistency and the ability to bring together data from many sources, and iRecord has opted for maximum flexibility rather than maximum consistency on this occasion.
