### ISSUE TITLE
Request to update a set of records

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#803]
A verifier has entered a set of 452 records with the count attribute set to 0 (zero). Consequently, iRecord has treated these as records of absence, whereas they were intended to be records of presence (but with no count).

The records can be found via:
```
SELECT o.id AS ID, o.created_by_id, o.zero_abundance
FROM occurrences o
WHERE o.created_by_id = 200253 AND o.zero_abundance = TRUE
```

We need to update the record to set o.zero_abundance to FALSE, and ideally we also need to update the quantity attribute to be null, rather than zero. I'm not sure how that attribute needs to be updated, or indeed whether it actually needs updating or whether the quantity attributes for this set of records should be deleted.

What happens if someone enters a record with no quantity, does that mean that no quantity attribute is generated for the record? If so, then deleting the relevant quantity attributes for these 452 records would seem to be the best option.

And then we'll need to update caches as usual.

**Comment by burkmarr** [comment]
@kitenetter - I've done some tests on my local instance for an attribute with system function of sex_stage_count. When values of 0 were entered, a record was inserted into the occurrence_attribute_values table but not when no value was entered. So I think that the relevant records need to be deleted from the occurrence_attribute_values table. I propose just setting the deleted flag rather than actually removing them.

**Comment by burkmarr** [comment]
@kitenetter - I've done as outlined above, so this should all be okay now.

**Comment by burkmarr** [comment]
@kitenetter - I guess this can be closed now?

**Comment by kitenetter** [comment]
Yes, thanks - closing.
