### ISSUE TITLE
Automatic rule checks "passed" for rare alien

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#810]
Record 11827096 of _Browallia speciosa_ (source: 32|154 -- NPMS Inventory level)  apparently passed all automatic record checks. Is this a bug relating to the fact that the species is not actually covered by the rule checks?

**Comment by DavidRoy** [comment]
I think Andy is best to advise on this as he developed the rule-check code I believe.  I would not expect this to be how it works though

**Comment by sacrevert** [comment]
@DavidRoy Can you add @andrewvanbreda to this repo? I don't have permission and he is not available as an assignee.

**Comment by DavidRoy** [comment]
have sent an invite for andy to join

**Comment by andrewvanbreda** [comment]
@sacrevert @DavidRoy 
H,
I don't think I wrote this code. It would have been a while ago so I can't remember precisely, so I will check early this afternoon for you and give you my thoughts, I definitely wrote code that use the rule checks, just maybe not the checks themselves, I will remember once I see the code itself. I will take a look at GitHub and let you know who is best placed to answer

**Comment by andrewvanbreda** [comment]
@sacrevert @DavidRoy
This is a function of the Data Cleaner isn't it?
Looking at the history, I have never committed any code to this module, so you might want to check with John about the bug.
(I have just written loads of code that does loads of stuff that uses the output of the data cleaner)

**Comment by DavidRoy** [comment]
ok, thanks for checking.  We'll discuss with John

**Comment by johnvanbreda** [comment]
Unfortunately it's hard to distinguish between "passed" and "not checked" because there are a variety of possible rules and levels of checking - it's not a simple state change. For example in some non-UK surveys we have used the data cleaner to pick up unusual attribute values so the records are looked into more thoroughly. For some species you might not consider it important to check the time of year but for others it's essential. Likewise for range checks which may not be important for a ubiquitous species.

Currently the green thumb icon indicates that a record has completed passing through the data cleaner, but does not indicate what rules were actually applied if any. A quick change would be to clarify the hint text. A more comprehensive change would be to either show which rules have passed as separate icons.

**Comment by sacrevert** [comment]
We implemented specific checks for the NPMS survey (32), e.g. common species that are not out of range are autoverified. I forget who implemented this however. Could someone check as to whether we have a situation where something that is not covered by the Record Cleaner receives a green thumb due to a "not checked" outcome? @johnvanbreda @andrewvanbreda

**Comment by kitenetter** [comment]
We also have this issue as #746 - not sure where best to continue to track the issue

**Comment by johnvanbreda** [comment]
@sacrevert that's correct - something receives a green thumb once the record has passed through Record Cleaner, whether there are zero, one or more rules doesn't matter.

Thanks @kitenetter - I thought this was a duplicate. Will close this one as it's a general issue.
