### ISSUE TITLE
Convert iRecord Explore reports to Elasticsearch

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/iRecord#811]
The occurrences/filterable_explore_list.xml and occurrences/filterable_explore_list_mappnig.xml reports are now the most significant consumer of CPU resources on warehouse 1, particularly from iRecord. Convert pages using these reports to Elasticsearch where possible.

**Comment by johnvanbreda** [comment]
Will come back to this once the V4 code (in the develop branch) is deployed as it contains lots of updates to the ES client code.

**Comment by johnvanbreda** [comment]
Now deployed:
https://www.brc.ac.uk/irecord/elastic/explore/all
Also the My Records version is similar but also demonstrates the new downloads functionality:
https://www.brc.ac.uk/irecord/elastic/explore/my

These may not be quite perfect but I think they are now close enough that the big performance improvement makes up for any deficits. In particular there are limits on pagination and which columns you can sort on for the Species, Families and Groups tabs. I can change the aggregation mode which will allow pagination and sorting on the text columns on these tabs at the expense of being able to sort on the stats columns. As you can download easily I think this is OK?

Also would be good to add a Photos tab at some point.

**Comment by DavidRoy** [comment]
Thanks @johnvanbreda .  Looks good to me from the bit of testing i've done.  
@kitenetter's via is critical to this but one option is to make this available alongside the existing reports and invite feedback from iRecord users.

**Comment by burkmarr** [comment]
It's excellent @johnvanbreda. I have some questions on it relating to #800 which I've just posted on that issue.

**Comment by kitenetter** [comment]
Edit button to add to "My records"

**Comment by kitenetter** [comment]
Individual bugs to be reported as separate issues.

**Comment by johnvanbreda** [comment]
Edit button already on My Records.

**Comment by kitenetter** [comment]
This is a "My records" page with a longer list, where the right-hand button/s gets hidden under the scroll bar:

![image](https://user-images.githubusercontent.com/16039111/83570745-7f34f380-a51e-11ea-8620-7bf8bbe22cee.png)

**Comment by johnvanbreda** [comment]
I've added the edit button to Explore my records and also improved the algorithm for setting column widths (in develop branch).

**Comment by kitenetter** [comment]
Set up Help page, publish ES explore pages, retaining links to old Explore pages to provide an overlap for a short time.

**Comment by kitenetter** [comment]
@johnvanbreda 

The current situation with the aliases for the Explore pages is:
- standard "Explore all" page (node 168): alias = all-records
- ES "Explore all" page (node 7613): alias = elastic/explore/all

I had been thinking that what I should do is change the aliases to:
- standard "Explore all" page = all-records-old
- ES "Explore all" page = all-records

However, what are the implications for the Explore links for a particular taxon, as accessed from an individual occurrence page such as this example for Ivy Bee:
https://www.brc.ac.uk/irecord/all-records?filter-date_age=&filter-indexed_location_list=&filter-taxon_meaning_list=83778

I haven't been able to get the additional parameters for taxon_meaning _list etc. to work with the "elastic/explore/all" URL. Is there a way of enabling the parameters with the ES page?

If not, should I choose a new alias for the ES page and leave the old page under its current alias in order to allow the taxon filtering to remain available?

Are there any implications for the Explore pages linked to activities (which have a different node: 831)?

**Comment by johnvanbreda** [comment]
I think I should fix the problem with the filters in URL parameters not applying to the ES Explore pages.

The activity Explore page will remain using the old code at the moment but we should indeed swap to the new ES based code at the moment - so they will continue to work as they are.

**Comment by kitenetter** [comment]
@johnvanbreda we've had a few enquiries from users who are getting timeout messages when using the Explore pages. Is the URL parameter issue a simple one to fix? If it isn't simple I think I should make the ES pages available under a new alias, and then we can swap the aliases round once the parameters are available.

**Comment by johnvanbreda** [comment]
@kitenetter I've fixed the URL parameters but in doing so have discovered an issue with the BWARS species list data which means the parameters in the example above won't work (?filter-date_age=&filter-indexed_location_list=&filter-taxon_meaning_list=83778). Taxon meaning ID 83778 points to Colletes hederae on the BWARS list, which was set up ages ago to support the single species recording forms. This taxon was created before our current way of syncing names with UKSI and as a result, it's become disconnected from the UKSI version of the name with a different taxon meaning ID.

When you filter for taxon_meaning_id=83778 on the warehouse data, as a result of the above it works OK but only returns BWARS data. You need to filter `filter-taxon_meaning_list=83778,189094` to get both versions.

When you filter for taxon_meaning_id=83778 on the Elasticsearch data, it performs an additional step. First it tries to convert the taxon meaning ID to the accepted name's TVK using a query on the taxon list data. Once it has the accepted name TVK it can filter the Elasticsearch data (as this maps to a GBIF Taxon_ID). But, because taxon meaning ID 83778 only exists in a list which does not belong to iRecord, it fails to find the TVK. So the Elasticsearch report finds nothing. Interestingly, because the Elasticsearch data is stored more accurately mapped to the UKSI list, filtering on taxon meaning ID 189094 actually works and returns data from both iRecord and the BWARS site.

I can think of 3 possible ways of fixing this:
1. Tidy up the BWARS species data to map them correctly back to taxa in UKSI (this applies to a handful of other species). 
2. Abandon the BWARS species list and modify the recording forms to record directly against UKSI (plus update old data to point to UKSI).
3. I could write a report which converts any taxon meaning ID to an accepted name TVK from UKSI, e.g:
```sql
select distinct cttl.external_key
from cache_taxa_taxon_lists tsearch
join cache_taxa_taxon_lists cttl on cttl.taxon_list_id=15 and (cttl.search_code=tsearch.external_key)
where tsearch.taxon_meaning_id=83778
```

I think 3 is the best solution as it makes the filter more tolerant of different list setups. Option 2 might also be worth considering. I'll think more when it's not late on a Friday...

**Comment by kitenetter** [comment]
@johnvanbreda I'm trying to understand the scope of the problem here. As you've described, the problem with the BWARS version of Colletes hederae (taxon meaning ID 83778) is that the taxon meaning ID does not belong to iRecord.

There are a large number of taxon lists in the warehouse that belong to websites other than iRecord, so does that mean that all these 'external' taxon lists will fail to generate an ES Explore page, or is there something specific about the BWARS setup that is different from, for eaxmple, CEDaR or NatureSpot?

**Comment by johnvanbreda** [comment]
The filtering problems are now handled by the way the Elasticsearch proxy works, no longer having the issue with website permissions. So I think this is now ready to deploy?

**Comment by kitenetter** [comment]
Currently working on a Help page for the new Explore functions. Questions arising:
1. The "Status" dropdown can conflict with the settings under "Create a filter". I think we found a way of linking these two filter functions so that if one was changed the other was also changed to match - can that be implemented?

**Comment by burkmarr** [comment]
@kitenetter the new `[statusFilters]` control is linked to the `[standardParams]` ('Create a filter') control if they are used together on the same page, e.g.:
```
[statusFilters]
[standardParams]
@taxon_list_id=15
````
See here for example: http://test.brc.ac.uk/irecord_dev/node/7625. Changing the value in one automatically changes the value in the other.

**Comment by kitenetter** [comment]
Thanks @burkmarr. I'm hoping to link the filters on this page:
https://www.brc.ac.uk/irecord/elastic/explore/all

I tried adding in "[statusFilters]" just above the "[standardParams]" in the user interface for that page:
`[statusFilters]
[standardParams]
@overridePermissionsFilters=true
@allowSave=true
@taxon_list_id=15
@indexedLocationTypeIds=[15,1370,2188,1103,2187,5702]
@otherLocationTypeIds=[2412, 17856]
`

However, that does not seem to have linked the two filters. Am I misunderstanding?

**Comment by burkmarr** [comment]
@kitenetter - I'm looking at that page now. It appears to be working to me. Click on 'Create a filter' to expand the standardParams control. Then change the 'Quality>Records to include' - you will see it reflected in the statusFilters control (labelled 'Records to include') which is just above the standardParams control. Similarly, changing the value in the statusFilters dropdown, changes the the value of the quality in the standardParams.

Don't forget that there is a manually defined 'Status' drop-down on that page. That cannot be linked - the statusFilters control replaces it; so all of the following gubbins can be removed from the form def:

```
<label for="filter-status">Status:</label>
<select id="filter-status" class="es-filter-param" data-es-bool-clause="must" data-es-field="" data-es-query-type="query_string">
    <option value="NOT identification.verification_status:R">All records excluding not accepted</option>
    <option value="">All records</option>
    <option value="identification.verification_status:C AND identification.verification_substatus:0 AND NOT identification.query:Q">Pending</option>
    <option value="identification.verification_status:V">Accepted</option>
    <option value="identification.verification_status:R">Not accepted</option>
    <option value="identification.verification_status:C AND identification.verification_substatus:3">Plausible</option>
    <option value="identification.verification_status:C AND identification.query:Q">Queried</option>
    <option value="identification.verification_status:C AND identification.query:A">Answered</option>
</select>
```

**Comment by kitenetter** [comment]
Thanks @burkmarr - maybe I was being impatient last night when the linked filters did not seem to take effect straight away.

Two further questions:
- Is it possible to set a default so that when the ES Explore pages are opened they display "Exclude queried or not accepted records"?
- Is it possible to adjust the wording and ordering of the entries in the status filter?

The wording I would like to use is in the spreadsheet below - if it is possible for me to edit the dropdown list let me know, otherwise I'd be grateful if you could make the changes.

[Status terms for Explore.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/5497545/Status.terms.for.Explore.xlsx)

**Comment by kitenetter** [comment]
@burkmarr can we discuss the previous comment this afternoon - having second thoughts about the best way to deal with this.

**Comment by burkmarr** [comment]
@kitenetter - I don't know the answers to these without looking into the code. I suspect that the answer is no without some coding for both. Note that the standalone statusFilter is basically using code from the standardParameters control, so altering the order would affect both controls.

**Comment by kitenetter** [comment]
Help page now drafted here:
https://www.brc.ac.uk/irecord/explore-and-filter

It's a bit of a monster! Comments/corrections welcome.

**Comment by kitenetter** [comment]
We agreed to link the two status filters, and to retain the existing (long) list of status options, including those for 'not accepted' records.

**Comment by kitenetter** [comment]
Now implemented on the live site. Fingers crossed that we can close this!
