### ISSUE TITLE
ES verification: error message

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#816]
I've now seen this two evenings in a row:

![image](https://user-images.githubusercontent.com/16039111/77591537-114dc980-6ee8-11ea-8adc-145a5260f953.png)

It's a bit demoralising, because it popped up this evening when I was re-verifying the records I'd spent time verifying last night, and I'm left wondering whether I'll have to do them again tomorrow night.

Since I haven't been expecting it I haven't managed to capture a HAR file but will try to do so next time.

**Comment by kitenetter** [comment]
Same error again about ten minutes after refreshing the page. HAR file:

[www.brc.ac.uk_Archive [20-03-25 22-40-41].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4383996/www.brc.ac.uk_Archive.20-03-25.22-40-41.zip)

**Comment by kitenetter** [comment]
Same error again tonight, after about 20 minutes of verifying.

[www.brc.ac.uk_Archive [20-03-26 23-06-50].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4390459/www.brc.ac.uk_Archive.20-03-26.23-06-50.zip)

**Comment by johnvanbreda** [comment]
Thanks for the HAR files which were useful. In the first I could see that you verified 21 records and Elasticsearch reported that it had updated 20, hence the error. The update is done by the same proxy as used to display the records on your screen, so the fact that you managed to select these 21 records for verification means they must have been available within ES for verification. So, I can't see why ES would report only 20 updates. If an update is missed, then the normal Logstash background process will pick this up in the next 15 minutes or so anyway. The code is fairly simple so I can't see how it could have accidentally only requested 20 records to be updated. My best guess is that because Elasticsearch is reporting the updated count before actually finishing the updates, so a second or two later you would find they'd all been updated.

In the circumstances I think the error message is actually more of an issue so I've changed the code so if there are minor discrepancies they won't be reported. I'll close this now but please re-open if further issues occur.

**Comment by kitenetter** [comment]
I'm continuing to get the same error message from time to time, and with random effects on the records that subsequently get displayed in my verification grid - sometimes I'm seeing records reappear after they've previously been verified, sometimes they seem to go through okay.

I've been restarting Firefox in an attempt to clear the problem, which means I keep forgetting to re-open the Network panel, so as yet I haven't been organised enough to capture a HAR file.

However, I also got the "elasticsearch query failed" error message at one point today, and I did capture the HAR file for that:

[www.brc.ac.uk_Archive [20-03-29 16-21-11].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4399178/www.brc.ac.uk_Archive.20-03-29.16-21-11.zip)

**Comment by kitenetter** [comment]
I think I managed to capture it this time:

[www.brc.ac.uk_Archive [20-03-29 17-05-54].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4399197/www.brc.ac.uk_Archive.20-03-29.17-05-54.zip)

Today it appears to only be happening when I do this:
- Use the bulk verification tick boxes; and
- tick just some of the boxes; and
- attempt to set them to plausible

Can't guarantee that has always been the pattern but it has been on more than one occasion.

**Comment by kitenetter** [comment]
Another example today. Because it results in some records staying in the grid following verification, it is quite problematic - I either end up verifying the same records repeatedly, or else (when using the tick boxes to verify) I have to keep unticking the first few records, which adds considerably to the time it takes to work through records.

[www.brc.ac.uk_Archive [20-04-11 23-13-55].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4465538/www.brc.ac.uk_Archive.20-04-11.23-13-55.zip)

**Comment by kitenetter** [comment]
This error now seems to be happening every time I use the tick boxes to mark multiple records as "Plausible". It's making it very difficult to deal with the current influx of bee-fly records so I'm bumping into the current milestone if possible.

**Comment by johnvanbreda** [comment]
I'm now fairly certain this was to do with incorrectly counting sets of updated records when they contained sensitive records. Now fixed.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda. I didn't get any problems with it last night (I didn't remember to look for whether sensitive records were involved, but I did a lot of records so I'd be surprised if there weren't some sensitive ones included). Much appreciated.
