### ISSUE TITLE
handling of upper and lower case in email addresses

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#824]
This problem has arisen in connection with the LERC Wales app, but I'm not sure if it applies elsewhere. I'm also not sure if it requires a solution on the app or more generally - I think the latter?

We have had several users create accounts via the LERC Wales app using email addresses that are identical to addresses already in the warehouse, with the exception of the first lettter of the address being upper case rather than lower case. The warehouse treats these as two separate entities and thus the user ends up with two unlinked accounts, leading to time-consuming requests to merge accounts at a later stage.

Can we set the warehouse to check for upper/lower case anomalies to prevent duplicate accounts being registered?

Marking as urgent to avoid havig to deal with lots of merge requests.

**Comment by johnvanbreda** [comment]
I believe this issue is already fixed, though there are quite a few accounts created prior to the fix which still have the problem. The problem is they need resolution by manual inspection.

Here's the bugfix:
https://github.com/Indicia-Team/warehouse/commit/fc8fb0d63ae7cf811bb01282b3f19e807e401661#diff-3d9468dfbc1a3817bfeb349c3f6b308c
