### ISSUE TITLE
Bugs in "Explore all records" filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#83]
Reported by David Hepper of BDS (the issues relating to the filters will presumably be common to other places where the filters are used, i.e. the verification grid):
- When a Filter is created in Explore all records that includes two Watsonian VCs in the Where condition, and a record's grid square straddles the border of the two VCs, duplicate records appear in the grid below without explanation, and distort the number of records in the resulting grid. 
- The dialog boxes for various Create Filter conditions (in both Explore and Verify) are too small vertically. As the criteria are refined, the Cancel and Apply buttons are pushed down below the bottom edge and require us to scroll the dialog window in order to click them. These buttons should not scroll. :: - see #86
- You cannot refine a When condition. On clicking the When button of an unsaved filter a second time, all fields revert to empty. This contrasts to Where conditions which retain and display their current settings. :: - see #87

**Comment by johnvanbreda** [comment]
As these are 3 separate issues, I've moved the 2nd and 3rd points into their own issues (#86 & #87). Therefore the only remaining point on this issue is the duplication of records which overlap a boundary.

**Comment by johnvanbreda** [comment]
Some preliminary investigation. The query currently joins to the index_locations_samples table with a filter on the 2 location IDs and since there are 2 hits for each record, the records get doubled up. 2 possible ways forward are:
- Improve the query used so that it only returns a distinct copy of each record (e..g using distinct on). There is a possibility of a performance hit and/or needing to update the report engine code to better cope with distinct on when sorting on different columns (which currently doesn't work).
- Switch over to using the location_id_* fields in the cache tables. The problem with this approach is that currently any record that straddles boundaries does not get indexed. We really need to implement a way of identifying a single vice county for each record even if the record straddles boundaries. There are other issues relating to vice counties which cover this.

Current suggestion is to implement other changes relating to records straddling boundaries first then revisit this.

**Comment by johnvanbreda** [comment]
This filters by location_id_* fields in the cache tables, which link the record to the VC they most overlap with. Therefore there is no duplication anymore.
