### ISSUE TITLE
Unhelpful English name lookup

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#837]
@burkmarr could you look into this one please. We have two bee species in genus Osmia that have similar vernacular names:
- Osmia bicornis = Red Mason Bee
- Osmia bicolor = Red-tailed Mason Bee (also =Two-coloured Mason Bee)

A bee recording project is currently being promoted in northern England, where Osmia bicolor does not occur. Unfortunately, if you type in "Red Mason Bee" to the iRecord forms, all you are offered is "Red-tailed Mason Bee", which is leading to records of the wrong species.

In a way it's a shame that these two species have been given names that are so similar both for the scientific and vernacular names, but we can't do anything about that,

Can we change the behaviour of the look-up so that both species appear when you type in "Red Mason Bee", and preferably so that it shows "Red Mason Bee" first and "Red-tailed Mason Bee" second.

Relates to #669

**Comment by burkmarr** [comment]
@kitenetter - I'll take a look this morning.

**Comment by burkmarr** [comment]
@kitenetter - this problem doesn't occur on dev (i.e. Red Mason Bee is in drop-down list) and sure enough there is an entry for 'Red Mason Bee' in the UK Master List on dev warehouse but not on live warehouse. I don't know why the difference - both lists were updated with the same UKSI stuff last year (around September). 
```
select preferred_taxon, taxon, search_name, * from cache_taxa_taxon_lists
where taxon_list_id=15
and preferred_taxon like 'Osmia bi%'
```
```
select * from taxa_taxon_lists ttl
join taxa t on t.id = ttl.taxon_id
where t.taxon like 'Red Mason%'
and ttl.taxon_list_id=15
```
@johnvanbreda - whatever the cause, would it be feasible to workaround this by manually inserting a row an in the cache_taxa_taxon_lists table so the taxon is found when users search on 'Red Mason'? Do you foresee any problems with me doing that?

**Comment by johnvanbreda** [comment]
Use the web UI to add the missing common name. Then, check the record in the taxa table - the external key should be the preferred name TVK (according to http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000169832 it should be NHMSYS0000876509) and the search_code should be the vernacular name's TVK: NBNSYS0000169832.

Don't just add to the cache_taxa_taxon_lists table as this would miss out storing the underlying raw versions of the data.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I've done that. I wasn't aware that taxa could be added like this - I should have thought to look, but I probably would have needed your advice re the search_code anyway. @kitenetter I think it will become searchable once the associated task on the work_queue has be processed and inserted a corresponding record in cache_taxa_taxon_lists table. I'll keep an eye on it.

**Comment by johnvanbreda** [comment]
@burkmarr FYI - the way we use search_code is unique to the way that we ensure existing names are recognised when doing the UKSI update.

**Comment by burkmarr** [comment]
@kitenetter - 'Red Mason Bee' appears in the drop-down now, though the scientific name is not shown. @johnvanbreda is there an easy way to fix that?

@johnvanbreda - I'm still trying to understand the root of this problem. The 'Red Mason Bee' is represented in the 'Garden Bioblitz Ticklist 2013' (list ID 74) which is a child list of the UK Master List (ID 15). On dev there are entries in the taxa_taxon_lists table for 'Red Mason Bee' against both lists, but on the main warehouse it is only represented in taxa_taxon_lists for the 'Garden Bioblitz Ticklist 2013' (twice with different taxon_meaning_ids) and not against the main list. I guess that's why it doesn't appear in the dropd-down list.

May be this happened during the last UKSI update, though why it occurred on live and not dev, I do not know. Do you think that we should try to fix this or, given that it is not a widespread problem, just deal with it as we have done so far?

**Comment by kitenetter** [comment]
Thanks @johnvanbreda and @burkmarr - closing.
