### ISSUE TITLE
Two questions re multiple verifications

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#847]
Verifier A has verified a record; Verifier B then re-verified that record, giving it a new status, at which point Verifier A received a notification. Verifier B then re-verified the record for a second time, and this time Verifier A doesn't think they received a notification.

Should they have received a notification, or do notifications only go to one previous verifier, not to both?

Related to this, Verifier A asks if we can add a further filter to the verification page. We already have a filter for "all records verified by someone other than me", and we've now been asked for "all records that I originally verifier but someone else has subsequently re-verified". Is that possible or does the querying become too complex?

**Comment by johnvanbreda** [comment]
Both verifiers would have been sent a notification, though it is likely the first verifier didn't because the previous notification was counting as existing and not acknowledged via the iRecord UI, therefore the system didn't see the need to repeat it.

That proposed filter would require updates to the Elasticsearch index as it only tracks the most recent verification, so would be a "medium" scale task.

**Comment by kitenetter** [comment]
Thanks for the info John. This issue has not arisen again, so I think we can archive it for now. Closing.
