### ISSUE TITLE
Odd behaviour on ES verification page

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#875]
This is unlikely to be having any widespread or serious effect, but I just filtered some records to exclude a particular species, by using the exclamation mark in the filter box (see screenshot below). I then used the tick boxes to accept 120 records showing in the grid. However, the records did not get removed from view - they look as if they are unverified in the grid, but are showing as verified if I click on the comments.

![image](https://user-images.githubusercontent.com/16039111/85183326-3b165280-b283-11ea-9e8e-5273745a4f9f.png)

When I removed the exclamation mark filter, the verified records disappeared from the grid as normal. So there seems to be some interaction between using the exclamation mark, and the verification behaviour.

**Comment by kitenetter** [comment]
I've now had a couple more examples of the grid failing to remove records that have been bulk verified via the tick boxes, and this time there was no filtering using an exclamation mark. I had filtered using the recording name, and I had the grid set to display 120 rows. As before, the verification decisiosn can be seen in the comments for each record, but the records have remained in the grid.

HAR file:

[www.brc.ac.uk_Archive [20-06-20 15-32-40].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4808043/www.brc.ac.uk_Archive.20-06-20.15-32-40.zip)

**Comment by kitenetter** [comment]
I closed down iRecord, went back in, refiltered my records, and this time the grid failed to remove the verified ones on the first attempt. Will try clearing cookies. Another HAR file:

[www.brc.ac.uk_Archive [20-06-20 16-03-47].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4808094/www.brc.ac.uk_Archive.20-06-20.16-03-47.zip)

**Comment by johnvanbreda** [comment]
@kitenetter One thing I think the HAR files show is that when you verified the last batch, your filter was set to "Exclude not accepted records". The new Elasticsearch verification page does not remove records from the grid if they remain in the scope of the current filter (unlike the old one which did, because refiltering to check was too slow). Therefore if you moved a batch of 30 from "pending review" to "accepted as considered correct" they were still in the scope of the filter so the grid did not need to update.

Does this provide a possible explanation?

**Comment by DavidRoy** [comment]
@johnvanbreda could the verification page be 'laggy' when the scheduled tasks has a big backlog, e.g. when loading historic UKBMS data as is currently happening.  The work-queue can get upto 100k records for example

**Comment by johnvanbreda** [comment]
@DavidRoy the verification does request that Elasticsearch does a near-instantaneous update when you verify the records, independent of the queueing systems. So that should not be the issue here.

Note that when you add a record or verify a record it appears instantly in the cache data. The work queue then processes the record to add it's custom attribute data and location indexing. So there will be a lag where, for example, a county recorder won't see a record due to location indexing delay. The work queue system is designed to allow prioritisation though, so we could improve this quite a bit if it's an issue (e.g. do the locations first).

**Comment by kitenetter** [comment]
I do still find that the grid refreshes erratically, and sometimes does not remove verified records from the pending view. Will close this one for now but re-open and regenerate a new HAR file next time it occurs.
