### ISSUE TITLE
Forcing users to log in before submitting records to BDS

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#889]
We would like our BDS recording forms to force users to be logged in, please. This is due to the number of records from casual observers that the verifier is unable to query for lack of an email address. Currently these have to be rejected or marked Plausible because we have no means of contacting the observer/recorder unless the name is recognised.

Might it be possible using a parameter in the links from our website to achieve this? From time immemorial our links have been of the form: 
http://www.brc.ac.uk/irecord/enter-[formname]**?group_id=149&implicit=t**
but I don't know the significance of the existing two parameters. Removing them seems not to make a significant difference.

**Comment by kitenetter** [comment]
@DavidHepper we can set the forms so that they require people to be logged in. 

However, there is another option. On recent iRecord forms, if they are used by a non-logged-in users then two things happen:
- The user is encouraged to log-in or register if they can
- If they don't, they are required to provide an email address (and are encouraged to provide a real name)

For the generic forms this is the wording that appears for non-logged-in users:

![image](https://user-images.githubusercontent.com/16039111/89055854-081bb000-d353-11ea-935c-4ccc31bc75f5.png)

The presence of a mandatory email attribute means that verifiers can contact recorders even they aren't logged in. The email address is displayed as an attribute on the verification page (in the record details section) and it is possible to use the query button to send an email to them (although we currently have an issue with the query button behaviour for non-logged-in users, see #894).

There are of course other disadvantages to people not logging in, e.g. the recorder experience data cannot be calculated, and if you definitely want to restrict the BDS forms to logged in users we can do that, but let me know if the above email capture would be a better step, at least to try out first.

**Comment by DavidHepper** [comment]
Yes, your newer scheme ticks our boxes. It's less likely that new visitors will be put off by a requirement to register. The CDR can always nag them later! Please go ahead.

**Comment by kitenetter** [comment]
@DavidHepper the two dragonfly forms now ask for user name and email address if the user is not logged in. Closing.
