### ISSUE TITLE
Indexed site boundaries and custom download for Kew

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#890]
A request for download access for Kew for their sites.  Initially Wakehurst.  Requirements are:
- New site type = 'Kew'
- import Wakehurst site boundary in Indicia to be used for iRecord (need to decide if site boundaries are 'public')
- index records against site boundary to support download and reporting
- setup custom ElasticSearch download page

**Comment by burkmarr** [comment]
I'm thinking that the location type 'Miscellaneous indexed boundaries' be a suitable home for this, but that might not be the case if there are likely to be many other Kew sites. We could set up a new type, but that would only seem worth doing if there are going to be a few. Are there likely to be more @DavidRoy?

The currently indexed site types on the Warehouse are:

- Vice County
- LRC Boundary
- Country
- Cairngorms NP NNR
- Miscellaneous indexed boundaries
- Butterfly Conservation Branch
- National Trust site
- NUTS Level 2
- NUTS Level 1
- Countries 2016
- RSPB Reserves
- Country territorial waters
- Woodland Trust site
- AONB
- National Park
- National Nature Reserve
- Site of Special Scientific Interest

**Comment by DavidRoy** [comment]
Agreed.  Only likely be 2 sites I think

**Comment by johnvanbreda** [comment]
Is it worth experimenting with not actually indexing these sites? If the boundaries are simple the download might work OK.

**Comment by burkmarr** [comment]
@johnvanbreda - I didn't realise that this was a possible course of action. Would that just work for ES download or would it work for reporting too?

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I'll give it a try without indexing then and see how it fares. @DavidRoy - where can I get the boundary(ies) from?

**Comment by burkmarr** [comment]
@johnvanbreda - I've created a new non-indexed site 'Kew Wakehurst' from a shapefile and I cannot see how to use this to filter records via the standard parameters control. I can type a site name in there, but the wording - 'search for site names containing' - suggests that will just look for records where the location name includes the string I put in. When I tried with the site name 'Kew Wakehurst' (for records from the last five years) it timed out.

The following query in PgAdmin on the live warehouse took around 2 min 40 secs 11,000 records, although it consistently takes less that two seconds on dev warehouse (around 7,000 records).
```
select * from cache_occurrences_functional
where st_intersects(public_geom, (select boundary_geom from locations where name = 'Kew Wakehurst'))
```

**Comment by johnvanbreda** [comment]
I think the way your query is written, it prevents the query planner using the index on public_geom due to the subquery. If you rewrite as the following, then it uses the index (you can check this by adding EXPLAIN before the query to inspect the plan):
```sql
select o.* 
from cache_occurrences_functional o
join locations l on st_intersects(l.boundary_geom, o.public_geom) and l.name='Kew Wakehurst'
```

This takes about 12 seconds on a cold run, then less than a second once the query result is cached.

The search for site names containing box is doing an un-indexed place names search. I haven't used that feature for ages but I can imagine it will only work when further limiting an already limited subset of records, not when limiting the whole dataset.

The standard params tool has a configuration to set up which layers are available to pick from:
```
@indexedLocationTypeIds=[15,1370,2188,1103,2187,5702]
@otherLocationTypeIds=[2412]
```

You need to add the Kew site to a layer that's somewhere in this configuration. As the National Nature Reserve layer is the only non-indexed one available I think you need to add a new location type, e.g. "Miscellaneous sites" and change the site to this location type, then add the location type ID into the @otherLocationTypeIds config.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda.

**Comment by burkmarr** [comment]
I've added the site 'Kew Wakehurst' to a new type 'Miscellaneous sites' (which is for miscellaneous non-indexed sites), and made that site type available from the filter builder (standard parameters) control on the following forms:

- https://www.brc.ac.uk/irecord/all-records
- https://www.brc.ac.uk/irecord/my-records
- https://www.brc.ac.uk/irecord/elastic/explore/my

Performance seems okay to me. Currently the site is public. I will look at setting up a custom ES download page once we have a general ES download page set up (which shouldn't be too far off now).

**Comment by johnvanbreda** [comment]
Also, should you do https://www.brc.ac.uk/irecord/elastic/explore/all and https://www.brc.ac.uk/irecord/verification?

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I've added it for those too.

**Comment by burkmarr** [comment]
@kitenetter @johnvanbreda - I overlooked the fact that there are two elements to this issue: 1) provide a facility to search for records in the Kew Wakehurst boundary and 2) provide a facility for Valentine Seymore to use it to download the records. I closed the issue after we achieved the first, but Valentine has been in touch today to ask how he can download the data and I realise that we still haven't published a form that allows him to do it. 

We can use the new Explore page, filtering on 'Miscellaneous boundaries...>Kew Wakehurst' to see all the records, but we haven't enabled a download button on species records on that page yet. If we're not ready to make that facility generally available, we could define a simple download page where users can download based on permissions filters (and obviously give him a suitable filter).

How shall we progress it?

Rich

**Comment by johnvanbreda** [comment]
@burkmarr If the generic download page were functionally complete, then I would expect it to allow people to download records using any download filters that Martin creates for them. Wouldn't the [permissionFilters] control provide for this?

**Comment by burkmarr** [comment]
@johnvanbreda - yes it would. We could create the page now - it's just a question of what controls to put on it. We could supply a page with just the permissionFilters control or something more complex.

**Comment by burkmarr** [comment]
@kitenetter -  I've just set up a simple download based only on permission filters so that the Kew can get the data they're after: https://www.brc.ac.uk/irecord/elastic/download-pfilter. I'm just waiting to hear from them what iRecord account they want me to give the permission filter to. (I set one up for myself against Kew Wakehurst and it worked fine.) Closing this again now.
