### ISSUE TITLE
Review options for use of Google satellite data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#891]
Use of Google satellite data incurs costs that reduce the development budget.  Currently, the layers are not used below a given level of zoom - a setting across the whole of iRecord.

Options to be discussed:
1. implement more precise logging of map layer use across iRecord pages
@BirenRathod can you advise on Drupal logging modules.  https://www.drupal.org/project/jsnlog only available in Drupal 8.

Also discuss option of adding a new service call to the Warehouse that would allow us to log diagnostics, sent from iForm Javascript, into Kohana logs. This would allow us to log the page URL every time a pan/zoom involving the satellite layer took place – which should be a good enough proxy of use.

2. Based on logging, consider alternative approaches across the site

3. Are there calls on the Google maps service that we've not considered

**Comment by kitenetter** [comment]
@BirenRathod to check what is available via Google logging.

Alternatively @johnvanbreda suggests building a custom logging facility to track this via open layers.

**Comment by BirenRathod** [comment]
@DavidRoy 
After I checked my previous mails, I have no recollection of suggesting above Drupal's module. 

Some interesting facts I found from below link which suggests that once the page loads using Google Map API, it starts counting the request. So it doesn't matter just using for zooming, panning or other effects because it doesn't generate extra page. So script used for OSMap & Google Map will count at the same time.

https://stackoverflow.com/questions/16860068/google-maps-offline-not-tiles-but-javascript/16862334#16862334

In this scenario, precise logging of map layer could be found from Google Map API console which you can found from below link.
https://console.cloud.google.com/google/maps-apis/metrics?project=irecord-project

**Comment by BirenRathod** [comment]
@johnvanbreda if you are still interested to build logging facility to track Goolge map layers which you can find from this link -> https://stackoverflow.com/questions/65720241/how-to-decrease-the-google-maps-api-hit-count-by-calling-it-only-when-user-scrol

**Comment by johnvanbreda** [comment]
The above link is for loading Google API when the map window is scrolled into view. Instead we'd need to exclude the Google Maps API from the page header, instead the indiciaMapPanel would have to load the Google Maps API only when the Google layer is activated.

**Comment by BirenRathod** [comment]
@johnvanbreda Did you not scrolled down the page? I am suggesting the code uses in initializeMap() function.

**Comment by BirenRathod** [comment]
@johnvanbreda Of course you don't need to use map-panel id.

**Comment by johnvanbreda** [comment]
@BirenRathod the initializeMap() function in that example uses intersectionObserver to load the Google Maps API when the map enters the viewport. As our maps will enter the viewport but with a non-Google layer visible, it needs to load the Google Maps API only when a Google Maps layer is activated.

**Comment by BirenRathod** [comment]
@johnvanbreda the key thing is to use intersectionObserver. I can't suggest which way to use without trying into code, so I leave that up to you. I can't find any other way on Google unless to contact them.

**Comment by johnvanbreda** [comment]
New code pushed to develop so Google maps API is not loaded until the layer comes into view.

We still need to implement this or similar on the Elasticsearch/Leaflet code.
