### ISSUE TITLE
Allow verifiers to filter for records verified by other verifiers

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#9]
Essential requirement for verifers to be able to easily see what other verifiers are doing. 

A verifier should be able to see the verified records within their filter, but verified by others? Perhaps a log of recent verification events matching your filter would be useful?

**Comment by johnvanbreda** [comment]
A verifier can change the quality filter on their verification page to show all records including verified, or verified only etc. So they can indeed see all verifications even by other verifiers.
I can see 2 possible enhancements that might meet the "log" requirement.

- Add a verified on date column to the grid (which could be hidden when showing pending records). This would let them sort by verification date to create a sort of log.
- Move the grid onto a tab set and add a 2nd tab called log. This would contain a log of all verification events matching their filter (rejections etc all included). Columns could include date, verifier, status/substatus, species, date, map ref, comment. 

The 2nd option is more powerful, but adding tabs does slightly further clutter the UI.
Please confirm which option is preferred.

**Comment by DavidRoy** [comment]
The key requirement is to be able to filter by verifier name, so that a verifier can exclude records they have reviewed themselves.  The second option (second tab) would fit the requirement.  Do you foresee performance issues?

**Comment by johnvanbreda** [comment]
Not really, performance should be OK as the 2nd tab will only load when you access it. It's more a concern that inserting the row of tabs in the UI will shift everything else down a bit. I guess I can style the tabs to be a bit smaller than default though. I'll also need to style it to remove the default padding inside a tab panel so we don't lose additional space.
Is that OK?
A further thought - once we've accepted the idea of extra tabs, we can start to do things like add a "stats" tab which could show you how many records you've verified vs left to verify etc.

**Comment by DavidRoy** [comment]
Agreed that there are good potential spin-offs.  I've asked Martin for his view.  Assuming he agrees then we should go ahead.  What is your estimate for time to develop?

**Comment by johnvanbreda** [comment]
About half a day.

**Comment by kitenetter** [comment]
This all sounds good. The tab idea meets the key requirement for being able to filter to view all records that have been verified by someone other than the logged-on verifier, and would presumably allow further flexibility so that you could filter to look at any given individual verifier.

The tabs approach seems like a good way to open up the possibility of additional info such as stats without making the basic verification grid page seem any more complicated.

Matt's other request was to be able to sort Queried records by date of query and/or by date of most recent response to query - presumably the 'log' tab would be able to be used in this way if a suitable filter was applied to display the Queried records?

**Comment by kitenetter** [comment]
While we're on the subject of the verification page, can I flag up a few other wishlist items, just in case they are easy to implement at the same time:

- Can the "Edit" button be made to allow you to right-click and open in a new tab? At the moment, if I edit a record I then have to reload the verification grid and re-apply any filters that I was working with, which can slow things down significantly

- For the choice between the two-option or five-option versions of the verification buttons, at the moment the verification page always defaults to the two-option version, and the ability to switch to five isn't very obvious. Can we make the five-option one the initial default, and also allow verifiers to set their own default so that it always goes back to the choice that they want?

- If one has chosen the "Review tick list" option, it would be good to be able to use Shift+Click to tick a whole set of boxes in one go, rather than having to tick each one individually.

**Comment by DavidRoy** [comment]
Ok, over to you I think John

**Comment by johnvanbreda** [comment]
I've committed the following updates to the warehouse to provide a comments log report:
https://github.com/Indicia-Team/warehouse/commit/2732a1c356c612a47344459f0a0fcc24c0678afe
https://github.com/Indicia-Team/warehouse/commit/550a4684cc021542b64fece585dfa560ab4132be

Plus the following commits for the client code:
https://github.com/Indicia-Team/client_helpers/commit/f314c7d3228ee3fbe1e25c4204cb721163e9b19d
https://github.com/Indicia-Team/client_helpers/commit/589a74d9a6eda14a060b28d04052fd29e3ffcd8d
https://github.com/Indicia-Team/media/commit/5f34614e0faf406bbb147efeb9d3a1828493633e

Because the develop branch is currently different from the live master branch due to the cache restructure, it makes more sense to wait for this update to feed through rather than write a second, temporary version of the log report to work against the current code. So this issue is currently pending the release of the new cache structure code.

**Comment by kitenetter** [comment]
See example of "verification log" tab in issue #60 - that looks like it goes a long way towards providing the ability to review decisions made by other verifiers, but it's not clear how you can filter for decisions made by "all verifiers other than me".

**Comment by johnvanbreda** [comment]
Suggestion is to add a filter radio option to the the top of the Log tab on the verification 5 page, with options "My entries", "Other verifiers' entries", "All entries".
Whilst at it the default sort of the log should be log date descending I think.

**Comment by kitenetter** [comment]
Is it possible to have that radio choice available for both the "Records" tab and the "Log" tab? I can imagine that if I did want to have a quick check of the decisions made by another verifier it would be useful to see them in the standard "Records" display, for instance so that I could see the photos where they exist.

Within the "Log" view, will it be possible to filter things so that only verification decisions are shown (i.e. excluding all other types of Comment)?

The main purpose of adding the 'other verifiers' filter is to give verifiers an easy way to quickly review the decisions made by other verifiers within their taxon group, so it does ideally need to display just the verified records, and with the usual record details plus photos.

**Comment by Gary-van-Breda** [comment]
Quick questions re the Log view

- Is this a blanket filter? i.e. do you want the user to be able to choose to filter by verification decisions vs. all types of comments?
- When the comment is related to a change of status of the record, it has a field filled in. Can I confirm that the filter is to check for record status of V "verified", R "rejected", and not I "in progress", C "completed", T "Test", or D "dubious/queried" (deprecated)

**Comment by kitenetter** [comment]
@Gary-van-Breda I think the user should be able to choose between looking at verification decisions only vs all comments.

For the purpose of seeing what decisions other verifiers have made I think we need to display all records that been given one of these statuses:
- Accepted
- Accepted: Correct
- Accepted: Considered correct
- Not accepted
- Not accepted: unable to verify
- Not accepted: incorrect
- Plausible
- Queried

I believe the first six of those categories will be picked up by the "V" and "R" codes, but I can't remember how we code plausible records, and queried records are handled in a different way aren't they?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda 
I've had a look at this, and whilst on the surface I was able to get the functionality in place quite easily, there were significant performance issues.
The verified_by_id is not present in the occurrence cache tables.
Putting a field to flag a comment record as a verification record and then filtering against it also had performance issues.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda Ok, focusing back on the core requirement and ignoring the "scope creep" then since we don't want performance problems, can we:
1) Add a radio to the top of the log tab, with 3 options. All (as now), My changes (filter on occurrence_comment.created_by_id=<user_id>), other changes (filter on occurrence_comment.created_by_id=<user_id>).
2) Add a checkbox to the top of the log tab, "verification decisions only". This would filter on query=true or record_status is not null which I don't think should significantly affect performance and can be done without schema changes.

**Comment by Gary-van-Breda** [comment]
Code lodged in both client_helpers (branch hotfix-verification-5-log-filtering) and warehouse (branch hotfix-occurrence-comments-report-extensions).

**Comment by kitenetter** [comment]
Not sure where we are with this, is the code complete, and do we have a plan for release?

**Comment by johnvanbreda** [comment]
This should be fixed in the next release.
