### ISSUE TITLE
UKSI anomaly - Ragwort

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#900]
In the current UKSI, the plant name "Common Ragwort" is a synonym for preferred name "Jacobaea vulgaris". The old name "Senecio jacobaea" is also shown as a synonym for preferred name "Jacobaea vulgaris". However, we seem to be using both scientific names inconsistently within iRecord.

When using the website data entry forms, both "Jacobaea vulgaris" and "Senecio jacobaea" are available for use, and both are displayed with the vernacular "Common Ragwort" alongside.

If you enter a record with name "Common Ragwort" it gets displayed with the old name "Senecio jacobaea" alongside.

A user has reported that when doing a csv import, the name "Senecio jacobaea" is rejected.

In cache_taxa_taxon_lists we have some names linked to a preferred name of "Jacobaea vulgaris" and some to a preferred name of "Senecio jacobaea". See file of names:
[iRecord Ragwort.xlsx](https://github.com/BiologicalRecordsCentre/iRecord/files/5061812/iRecord.Ragwort.xlsx)

Questions:
1. Why has the UKSI update not linked "Senecio jacobaea" to "Jacobaea vulgaris" - was "Senecio jacobaea" shown as a non-preferred synonym for "Jacobaea vulgaris" in the version of UKSI used to do the recent import, or is there a glitch in our scripts??
2. How does the English name "Common Ragwort" get displayed against both "Senecio jacobaea" and "Jacobaea vulgaris" - in the database it appears to be linked to the former but not the latter?
3. Both "Senecio jacobaea" and "Jacobaea vulgaris" are set to TRUE in cache_taxa_taxon_lists.preferred - should they be?
4. Why is "Senecio jacobaea" not being accepted as a valid name for csv import?

Suggested actions:
1. I think all of these ragwort names, including "Senecio jacobaea", should be set to point to the preferred taxon name of "Jacobaea vulgaris".

That action may be all that is required, although it still leaves the question of why "Senecio jacobaea" isn't accepted from a csv file.

**Comment by johnvanbreda** [comment]
I suspect the issue here is that both names are marked as accepted, well-formed and scientific (See http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NHMSYS0021241522). It's only when you click on Senecio jacobea that you see it is not recommended. So I wonder if our scripts are not respecting this correctly?

**Comment by johnvanbreda** [comment]
I've also had a report of other problems with taxon names going missing for CSV import, e.g. Ranunculus ficaria and I think I've found a problem in the UKSI import scripts which I'll document here.

The problem occurs when there is a child list containing a subset of the UKSI taxa.

Script 23 - prepare taxa taxon lists.sql creates a table in the UKSI schema called `prepared_taxa_taxon_lists` which is going to hold a copy of all the expected taxa_taxon_lists records that should be in the system, build from the imported Access CSV data. Later it will be compared with the actual data in the warehouse in order to decide what to update, insert or delete. This is initially populated with all the list entries from UKSI (given taxon_list_id=15) then additional copies are created for any taxa on child lists, but are given the child list's taxon list ID. At this point though, the prepared_taxa_taxon_lists table has null in the id column, this will be filled in later.

Script 24 matches these prepared_taxa_taxon_lists entries to the correct existing taxa_taxon_lists records to fill in the id column if the record already exists. Crucially, on line 22 it forces this to be the copy on the main UKSI list, taxon_list_id=15. That means you will get 2 or more entries in prepared_taxa_taxon_lists, one for the UKSI list, one for each child list that holds the same taxon, but ALL will have the same id (as it's a mapping not a primary key this is OK). 

Script 31 then updates taxa_taxon_lists by linking to prepared_taxa_taxon_lists to get the correct data using the id. Therefore there are competing updates because there are several records with the same ID but different taxon list IDs. The result is that the copy of the taxa_taxon_list record in UKSI will sometimes get moved to the wrong list.

To fix this I propose that line 22 of script 24 is changed to match against the existing taxon_list_id in prepared_taxa_taxon_lists:
```sql
AND ttl.taxon_list_id=(SELECT uksi_taxon_list_id FROM uksi.uksi_settings)
```
changes to
```sql
AND ttl.taxon_list_id=pttl.taxon_list_id
```

I've run the following script as a temporary fix:
```sql
select ttl.id, ttl.taxon_list_id, cttl.taxon_list_id as new_taxon_list_id, ttl.updated_on, cttl.cache_updated_on, cttl.taxon, cttl.parent_id
into temporary to_fix
from taxa_taxon_lists ttl
join cache_taxa_taxon_lists cttl on cttl.id=ttl.id and cttl.taxon_list_id<>ttl.taxon_list_id
where ttl.updated_on>'2020-08-03' 

update taxa_taxon_lists ttl
set taxon_list_id=tf.new_taxon_list_id, parent_id=tf.parent_id, updated_on=now()
from to_fix tf
where tf.id=ttl.id
```

@burkmarr can you work through this when you get a chance please and see if you agree with my proposed fix?

**Comment by burkmarr** [comment]
@johnvanbreda - I've been through this and it makes sense to me, though I can't pretend to have my completely around it. Nevertheless I understand your analysis of the root of the problem and the fix and it seems okay to me.

One this which puzzles me is that you could apply a temporary fix by updating the taxa_taxon_lists table from the cache_taxa_taxon_lists table. I had assumed that the problem would be propogated to the latter from the former. Why is that not the case?

**Comment by johnvanbreda** [comment]
@burkmarr I agree, I'm slightly confused as to why this change did not propagate into cache_taxa_taxon_lists. I think I'd have to try and recreate the entire process to work out why so I doubt it's worth the effort though.

**Comment by burkmarr** [comment]
@kitenetter - @johnvanbreda has made the proposed change to the import scripts which will hopefully avoid these problems in the future. If the remedial script he ran has sorted out the problem with Ragwort to your satisfaction, this issue could be closed?

**Comment by kitenetter** [comment]
Data entry on iRecord is working (albeit still somewhat confusingly due to UKSI not updating its subspecies when a genus name changes), and I'm able to import the old name Senecio jacobaea from a csv file, so this should be resolved now - thanks. Closing.
