### ISSUE TITLE
UKSI edits

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#908]
A user has contacted us to strongly recommend that we stop using the vernacular name "Negro Ant" on the grounds that it is offensive. I have now marked it as not for data entry which I think will solve the immediate issue. The warehouse entry is:
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/235876

This raises some other points:
1. UKSI shows that "Negro Ant" is now flagged as both "Not recommended" and "Deprecated", and instead offers "Dusky Ant": http://nbn-sd-dev.nhm.ac.uk/taxon.php?linkKey=NBNSYS0000169053 - our import process appears to have used "Negro Ant" despite it being Deprecated, and has not included "Dusky Ant" (possibly because UKSI incorrectly has this labelled as a scientific name)
2. The name in the warehouse (http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/235876) was flagged incorrectly as "freshwater" - not sure why that happened, and I have removed the flag.
2. It would be good to add "Dusky Ant" as a vernacular name in iRecord, but when I've tried to add or edit vernacular names in the past it has caused problems (e.g. #799). @burkmarr please can you add this vernacular (and ideally let me know the procedure so I can do so if a similar situation arises in future)
3. The name "Negro Bug" is still in use in UKSI and on iRecord - I intend to mark that as not for data entry as well, and will query it with Chris at UKSI (some sources now call this the Scarab Shieldbug). This vernacular was also incorrectly flagged as a freshwater taxon.
4. These vernaculars are also in use on NatureSpot - @kitenetter to contact Dave N about this

**Comment by johnvanbreda** [comment]
These names were modified on 25th/26th July but the version I received of UKSI was from the 13th July. I presume @burkmarr used the same copy rather than a newer one as that's the copy that went through testing.

Please note that any name updates that are applied need to be applied to the lookup tables used by Logstash for Elasticsearch names. Some automation of this update process might be a nice idea in future.

Looking at the scripts which create the interim preferred_names table, it creates the marine, freshwater and terrestrial fields in that order:
https://github.com/Indicia-Team/support_files/blob/master/UKSI/scripts/6%20-%20create%20tables%20in%20uksi%20schema.sql

But the extraction query for preferred names has terrestrial before marine:
https://indicia-docs.readthedocs.io/en/latest/administrating/warehouse/importing-uksi.html#starting-with-the-microsoft-access-database

As the CSV import relies on the fields being in the correct order I think there has been a simple swap of the freshwater and marine flags. @burkmar do you agree with the following:
1. Fix the extraction query from MS Access to put freshwater before terrestrial.
2. Run a query in the database to swap the flags (list 15 only).
3. Regenerate the Elasticsearch taxa lookup tables, so new records going forward are correct.
4. I think at this point it would be a good idea to write a new PostgreSQL -> Logstash -> Elasticsearch extraction which just updates the taxonomy, so we can run that across the entire dataset in the background without affecting the main extraction.

**Comment by burkmarr** [comment]
@BirenRathod - when I try to look at this via the warehouse website - http://warehouse1.indicia.org.uk/index.php/taxon_list - I'm currently getting this error:
```
cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:http://warehouse1.indicia.org.uk/index.php/services/data/taxon_list
Server response
{"error":"pg_connect(): Unable to connect to PostgreSQL server: FATAL: remaining connection slots are reserved for non-replication superuser connections","code":2,"file":"D:\\websites\\warehouse\\system\\libraries\\drivers\\Database\\Pgsql.php","line":48,"trace":[]}
```

**Comment by BirenRathod** [comment]
@burkmarr What is your username?

**Comment by burkmarr** [comment]
Richard.Burkmar

**Comment by BirenRathod** [comment]
@burkmarr Although if you have logged in using this Richard.Burkmar username then there is no porblem accessing taxon page from browser. It has got same rights as mine one. Check your wi-fi works fine.

**Comment by burkmarr** [comment]
@BirenRathod - it's working now.

**Comment by johnvanbreda** [comment]
@BirenRathod sounds like there was a limit reached in PostgreSQL connections temporarily - one to watch out for I think.

**Comment by burkmarr** [comment]
@johnvanbreda - I see what you mean (https://github.com/BiologicalRecordsCentre/iRecord/issues/908#issuecomment-674508124) and agree with the steps you've outlined. Do you want me to take any of this on?

**Comment by johnvanbreda** [comment]
Hi @burkmarr can you take on as much as you feel comfortable with then let me know please? E.g. you may want me to do the stuff relating to Elasticsearch?

**Comment by burkmarr** [comment]
@johnvanbreda - referring to your 4 point list above (https://github.com/BiologicalRecordsCentre/iRecord/issues/908#issuecomment-674508124)...

- I've swapped the terrestrial and freshwater flags in taxa table (for UKSI list) yesterday and these have been propogated to cache now (point 2).
- I'm happy to have a go at regenerating the ES lookup data (point 3).
- I'm also happy to look at the Access scripts (point 1) and I will also review the stuff you've suggested in https://github.com/BiologicalRecordsCentre/iRecord/issues/900 at the same time (point 1).
- That leaves point 4 which I'd be happier to leave to you at this stage, though I'd like to understand it too. 

There are a few other less pressing questions that this has thrown up for me around the ad hoc changes that we need to do for the taxa listed in Martin's original post but I will return to those once the above is done.

**Comment by burkmarr** [comment]
Change to indicia-docs UKSI all_names query (flag order) is pushed to master. New versions of the two taxonomy yaml files for ES index generation pushed to support_files master.

**Comment by johnvanbreda** [comment]
@burkmarr when you regenerated the YAML files did you spot the bit in the README.md file about the replacements that are required? Line 590.

**Comment by burkmarr** [comment]
I did @johnvanbreda. Did you find a problem?

**Comment by burkmarr** [comment]
@johnvanbreda - I've seen a problem. The replacements preceeded by ```\``` in the readme, render incorrectly in GitHub, so, for example, I replaced "" with " instead of \". (I spotted it for \\ but not the rest.) I will do again.

**Comment by burkmarr** [comment]
@johnvanbreda - I'm a bit confused by this now. Is this unrendered stuff in the README.md - shown below - the literal replacements I should make? I'm unlcear about the back-slashes.
```
    * "," with ": "
    * \ with \\
    * """ with "\"
    * "" with \"
    * Regexp \u0082 with ,
    * Regexp \u0084 with ,,
    * Regexp \u0086 with †
    * Regexp \u0090 with empty string
    * Regexp \u0092 with '
    * Regexp \u0093 with \"
    * Regexp \u0094 with \"
    * Regexp \u0096 with -
    * Regexp \u008A with Š
    * Regexp \u009A with š
    * Regexp \u009c with œ
    * Regexp u\u009Ei with ůži
    * Regexp \u009E with ž
```

**Comment by johnvanbreda** [comment]
Yes, those are the literal replacements that I normally perform in Visual Studio code. E.g. you want backslashes in the strings to be escaped. The triple quote replacement is to catch a case where there is a double quote inside a string (which gets doubled) against the string boundary, also a double quote.

You might find with the regex replacements that not all get hits, as Chris has cleaned a few things up.

**Comment by burkmarr** [comment]
Thanks John. I noticed that a few didn't hit anything. Okay I will repeat this now with the correct replacements and update the README.md so that the replacements are rendered literally in GitHub.

**Comment by burkmarr** [comment]
Redone taxa.yml is pushed to master.

**Comment by johnvanbreda** [comment]
@burkmarr thanks for updating taxa.yml. It was deployed before the weekend and seems to be fine.

**Comment by burkmarr** [comment]
@kitenetter - further to our discussion yesterday

> It would be good to add "Dusky Ant" as a vernacular name in iRecord, but when I've tried to add or edit vernacular names in the past it has caused problems (e.g. #799). @burkmarr please can you add this vernacular (and ideally let me know the procedure so I can do so if a similar situation arises in future).

This what I've don so far.

1. I got the preferred taxa_taxon_list id for Formica fusca for list 15 - 235874
2. I edited this on the Warehouse: http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/235874
3. I just replaced the old vernacular name with the new one.

After a short whilte, Dusky Ant became available for use in iRecord. However, if I start typing Formica fusca, the common name associated with that is still Negro Ant. The root of that problem seems to be that the taxa_taxon_list record for Formica fusca (235847) in the database still has the ID for Negro Ant in the common_taxon_id column. 

@johnvanbreda - is there a way of fixing that through the warehouse website or will I need to the update table in pgAdmin?

**Comment by johnvanbreda** [comment]
@burkmarr I would have expected the code in the taxa_taxon_list model to reset the common_taxon_id field, but without time spent debugging I can't be sure why it didn't. In which case nulling the field (or pointing to Dusky Ant) via pgAdmin seems a good approach.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda. I will do this asap - we're having VPN problems at Lancaster at the moment, so I can't do it yet, but should be fixed soon. I will also take a look at the code to see if I can see what happened.

**Comment by burkmarr** [comment]
@kitenetter - I used pgadmin to point `taxa_taxon_lists.common_taxon_id` for the uksi record for _Formica fusca_ to the new record for Duksy Ant created from the Warehouse interface.
```sql
update taxa_taxon_lists 
set common_taxon_id = 423578, updated_on=now(), updated_by_id=198219
where id = 235874
```
Dusky Ant is now appearring when I type 'Formica fusca' on live iRecord.

**Comment by burkmarr** [comment]
@johnvanbreda - I've had a long look at https://github.com/Indicia-Team/warehouse/blob/master/application/models/taxa_taxon_list.php this morning to try and work out why `common_taxon_id` was not updated in the case above. 

I had a breakthrough when I realised that this update fails when the taxa_taxon_list item associated with the common name has first been marked as _not for data entry_ via the warehouse inerface - which is what happened in the case above. I can consistently reproduce this behaviour on my local instance.

The update of the field should occur in the section of code shown below (line 283). I established that the update was not occurring because ```$this->common_taxon_id == NULL``` was not true.

```php
if ($this->common_taxon_id == NULL && $syn['taxon:language_id'] != 2) {
  $this->common_taxon_id = $sm->taxon->id;
}
```
`$this->common_taxon_id` should be nulled on line 211:

```php
if ($this->common_taxon_id == $syn->taxon->id) {
   $this->common_taxon_id = NULL;
}
```
It turns out that where the common name has been marked as not for data entry, `$this->common_taxon_id == $syn->taxon->id` fails because, for some reason, when you mark a common name as _not for data entry_ via the warehouse interface, a duplicate record of the common name is created and the code above ends up comparing the ID to that of its duplicate.

So I think that's the root of the problem but I couldn't work out why the warehouse interface is duplicating taxon record when the 'Allow data entry' flag is turned off.

**Comment by johnvanbreda** [comment]
@burkmarr I don't understand the statement "this update fails when the taxa_taxon_list item associated with the common name has first been marked as not for data entry via the warehouse interface" - the warehouse interface doesn't allow you to control the allow_data_entry flag on synonyms or common names separately to the accepted name does it? 

I do think the way the UI works is an oversimplification though. In my separate tests on a local instance, replacing a common name with a new one leaves the taxa_taxon_list.deleted flag set to true for the old common name, even if there are records associated with it. The UI ought to behave like the UKSI importer and, rather than delete the old common name, mark it as not for data entry. Or better still, explain what's happening to the user and allow them to decide the best approach, with one option being to delete the old name and change existing records to the new name and another option to leave the name in place but marked as not for data entry. Also note then that the UI would need a way of showing which common names and synonyms are not for data entry.

If I create a local taxa with a common name, then change the common name and resave using the warehouse UI, I end up with 3 taxa_taxon_list records - an accepted name, a deleted common name and a new non-deleted common name. The accepted record points correctly via common_taxon_id to the newly added name. None are marked as not for data entry. If I then use pgAdmin to mark the new non-deleted common name as allow_data_entry=false then use the warehouse UI to change it again and resave, then it still seems to work as expected - the new name is added, the accepted name's common_taxon_id is updated to point to the new name, and there are now 2 deleted common names. So I think I'm missing something from my understanding of this.

**Comment by burkmarr** [comment]
@johnvanbreda - we were doing it by finding the taxa_taxon_list associated with the common name (using pgadmin) and then just editing by going to the URL, e.g. http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/235876.

**Comment by johnvanbreda** [comment]
@burkmarr OK, I guess that's unsupported though as it's not an official link - generally you edit via the page for the accepted name. I appreciate though that this doesn't give you enough control as described in my 2nd paragraph above. When I try this myself, I find that the common name gets saved with the preferred flag set to true, so it's promoted to a top-level name.

**Comment by burkmarr** [comment]
@kitenetter the original problem with those specific names is resolved. The answer to your question about the correct procedure for updating common names seems to be: use the warehouse to change the common name on the form for the _taxa_taxon_list item of the accepted name assocated with it_. **We should avoid doing what we did before to edit the common name taxa_taxon_list item directly through the warehouse**.

However note @johnvanbreda's comment:

> I do think the way the UI works is an oversimplification though. In my separate tests on a local instance, replacing a common name with a new one leaves the taxa_taxon_list.deleted flag set to true for the old common name, even if there are records associated with it. The UI ought to behave like the UKSI importer and, rather than delete the old common name, mark it as not for data entry. Or better still, explain what's happening to the user and allow them to decide the best approach, with one option being to delete the old name and change existing records to the new name and another option to leave the name in place but marked as not for data entry. Also note then that the UI would need a way of showing which common names and synonyms are not for data entry.

I suggest closing this issue and opening a new one for the above so that it can be separately reviewed and priortised at our next meeting.

**Comment by kitenetter** [comment]
Agreed - closing this one.
