### ISSUE TITLE
Confusing Species maps button

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#91]
For the page [http://www.brc.ac.uk/irecord/species-maps]

Current 'Filter' button implies that one would type in a species and then click filter, but the 'Filter' button is required _first_ to retrieve the species list. It seems strange to me to click ‘Filter’ in order to get a list that then needs filtering… Wouldn’t a ‘Retrieve species list’ button be better? (Or some explanatory text).

This page has confused me several times (and the response time doesn't help one to work it out).

**Comment by kitenetter** [comment]
@sacrevert I agree that this is confusing. There is actually no need to click on the blue "Filter" button at all unless you have made a change to either of the two tick boxes above the Filter button:

![image](https://cloud.githubusercontent.com/assets/16039111/19813503/efe4b73a-9d31-11e6-896e-67a7283a9d75.png)

The species list in the grid will populate anyway (although it can be slow if you are using species-rich taxon groups), and you can then filter the species list by typing in to the empty boxes at the head of the grid columns - if you type in to these boxes there is no need to use the blue "Filter" button at all:

![image](https://cloud.githubusercontent.com/assets/16039111/19813565/33596fb0-9d32-11e6-872e-2c6e42e5c4cd.png)

If time allows in future it would be good to rethink how these species maps are displayed and controlled, but perhaps a good short-term improvement would be simply to rename the blue button from "Filter" to "Apply the above tick boxes"?

**Comment by JimBacon** [comment]
Am I the source of some misinformation? When I go to http://www.brc.ac.uk/irecord/species-maps it does nothing...even if I wait a very long time.

**Comment by kitenetter** [comment]
@JimBacon do you have any species groups ticked under "What you record" in your profile? 

If you don't have anything ticked, then when you first go to the species maps they will not list any species. In that case you have to untick "My species groups only?" and then click on "Filter" to get the full species list to show (which takes another minute or so to load).

**Comment by JimBacon** [comment]
No, I don't have anything ticked in my profile. 
Just a few instructions on the page would be a helpful starting point.

**Comment by kitenetter** [comment]
Agreed, and presumably I can add some explanatory notes to the "Body" text box if I edit the page. Will get that done.

**Comment by johnvanbreda** [comment]
3 things:

- I don't think the option to filter for your own groups makes any sense if you haven't selected some in your profile. I have just committed some code which will be applied on the next update that removes the option in this case, so the full report would load straight away.
- If the filter button and tickboxes were all in a single row, would it be clearer that the filter button only relates to these tickboxes?
- The report is indeed very slow. This is because of the need to count ALL the records in order to work out the sort order, even for the species that are not on the first page. I would question whether the count is actually worth keeping in this case - surely you know which species you want anyway?

**Comment by kitenetter** [comment]
@johnvanbreda re your three things, no. 1 is good, for no. 2 I agree that a single row would be clearer, and for no. 3 I agree that sorting by number of records is unnecessary - thanks.

**Comment by johnvanbreda** [comment]
These points have been fixed/implemented a while back now.
