### ISSUE TITLE
Error message on BWARS input forms

### ISSUE THREAD

**Issue by MNSmith** [BiologicalRecordsCentre/iRecord#910]
We have a number of "standalone" Data Entry forms on the BWARS website.  I was advised by a user that entering the Grid Reference in the required "Grid Reference" field of the Colletes hederae form generates the message "The GeoPlanet place search service is no longer supported", which prompted the user to abandon the form.

I have looked at another of the forms on the website (Bombus hypnorum) and get the same message.   Despite this, when I put in a grid reference the form did work and the map zoomed to the right spot.  I have entered a test record via the Colletes hederae form and am waiting to see if it appears correctly on the Aculeate verification grid.

If the form works ok, can we have this error message removed please.

**Comment by burkmarr** [comment]
@MNSmith - I had a look at those two forms and can see the 'The GeoPlanet place search service is no longer supported' on the page before even interacting with them. As John said this is because a now unsupported Georeference driver is selected in the form's configuration and changing this to 'Nominatim' should get rid of this message and display the actual georeference lookup control which is currently not being displayed. Whoever administers your site can log in and edit this form - find the 'Georeferencer' section and change the selection.
![image](https://user-images.githubusercontent.com/9275178/91022667-7455a080-e5ed-11ea-9420-d18966b70024.png)
Or to remove the text without displaying the lookup, remove the [place search] element, and associated parameters underneath it, from the 'User interface > Form Structure' section of the form.

**Comment by MNSmith** [comment]
Thanks.  I have forwarded on the information to the BWARS Website Admin.
