### ISSUE TITLE
Refresh statistics on iRecord home page?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#916]
The statistics on the iRecord home page never seem to change.  Is this a local caching issue?  Would be good to see this updated on a weekly? basis at least

[Approx. 7513236 records of 90125 species, with 1087375 photos.]

**Comment by kitenetter** [comment]
The species total is also misleadingly high, due to complexities of synonyms, multiple taxon dictionaries etc. Personally I would prefer not to have the species total unless we can restrict it to a count of recommended UKSI scientific names (and even then subspecies etc. make it hard to interpret).

**Comment by johnvanbreda** [comment]
Yes, this is old code which is still counting against PostgreSQL and I think timing out. It only refreshes occasionally but the timeout means it never updates. 

It should be replaced by an Elasticsearch query, which could also use the distinct species_taxon_id field count to get a much better indicator of species count. This will still double count species on the European mammal and ABLE lists but will otherwise be accurate as higher taxa are skipped and sub-species mapped to the species.

Please assign to a milestone if a priority.

**Comment by kitenetter** [comment]
Inaccurate stats now removed from the home page (thanks @johnvanbreda), to be replaced with ES queries when possible, or maybe wrapped up into a wider review of user feedback/visualisations.

Adding to a "Visualisations" project and closing for now.
