### ISSUE TITLE
Discrepancies in totals for top 100 records/species league tables

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#917]
A few users have commented that the numbers on the Recorder league tables do not match the totals they get from their My records view. Although the league table is intended as a 'fun' piece of feedback, the discrepancies are being seen by one or two at least as an indication that iRecord is unreliable in general.

Example 1: user ID 105051 has 7879 records showing in the top 100 species recorders league table, but 8128 records in their My records view.

Example 2: user ID 128368 has 8596 records showing in the top 100 species recorders league table, but 10116 records in their My records view, and 1041 species in the league table but 1265 species in My records.

**Comment by johnvanbreda** [comment]
I think the main issue here is that the league table is aggregated on the event.recorded_by field, which sometimes has discrepancies in how it's set (firstname surname or surname, first_name being an example). Also it would include records input by someone else with recorded by set to the user's name.

I think this should be altered to aggregate on the created_by_id field. At the same time the structure should be updated to the newer Elasticsearch code style with auto-generated aggregations.

**Comment by burkmarr** [comment]
@johnvanbreda - I had a look at this today (https://www.brc.ac.uk/irecord/node/8166/edit), but I don't see how it is possible to produced a table with recorder names from the created_by_id field - wouldn't we need a new field in the index, e.g. created_by_name?

**Comment by johnvanbreda** [comment]
If you use @uniqueFieldName=metadata.created_by_id and @fields=["metadata.recorded_by"] it should aggregate on created_by_id, then use a top hits aggregation to pull back the most frequent version of the recorded by field for that created_by_id.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - that helped. @kitenetter - I've implemented a test using the method described above, but I'm not sure it helps much: https://www.brc.ac.uk/irecord/node/8166. (I've displayed the created_by_id to help you evaluate it.)

Because this query aggregates by created_by_id, admin (user 1) had big score because of imports so I put in a filter to remove that ID from the reporting.

Likewise the user with ID 118418 has, I presume, carried out a lot of imports of other peoples records (it's a user associated with Societe Jersiaise). It's not the user corresponding to the name there - from what John said that is just the recorder name most frequently used within those imports). I could also add a filter to remove this ID from the reporting.

If you compare the figures for the big recorders with the corresponding figures on the current report (https://www.brc.ac.uk/irecord/recorder-league-sp) there are obviously some significant differences (some resulting in ranking changes) because of the different way of calculating the figures. There's clearly no perfect way of doing this.

**Comment by kitenetter** [comment]
Explanatory text now added.

@johnvanbreda is it easy to remove the controls on these pages that do not have a function:
- grid column settings
- full screen mode
- Previous and Next buttons
- rows per page

Let me know if I can change those settings from the page itself.

**Comment by johnvanbreda** [comment]
Hi @kitenetter yes, this can be done by adding options to the [dataGrid] control in the interface definitions. The documentation should explain it at https://indicia-docs.readthedocs.io/en/latest/site-building/iform/helpers/elasticsearch-report-helper.html?highlight=elasticsearchreporthelper#elasticsearchreporthelper-datagrid but let me know if it's not clear. E.g. ```@includePager=false``` would remove the previous and next buttons.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda I think that is done. Closing.
