### ISSUE TITLE
Question - bringing in a new website to the ES dataset

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#923]
We recently adding a "reporting" agreement to several data warehouse websites for the Welsh records centres. Their data now appears on the standard Explore pages, but is not visible on the ES explore pages.

Is this just a matter of waiting for the indexes to get updated and takes time? Or is there something else that needs to be done to push the data through?

**Comment by johnvanbreda** [comment]
In the current code, we rely on a pre-configured Elasticsearch alias to ensure the correct records are returned for each task. So, I've just updated the alias to include the additional websites.

I think it would be a good idea to explore dynamically adding the appropriate filter in the Warehouse API, rather than relying on the alias, so this change would happen automatically.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda - just to confirm, the three websites involved were:
- ID 41: SEWBReCord
- ID 47: B.I.S.
- ID 72: WWBIC

If you can confirm that these three were all added then we can close this issue, and I'll open a new one for the potential move to dynamic updating.

**Comment by johnvanbreda** [comment]
Yes, they were added. Closing.
