### ISSUE TITLE
Activity summary for iRecord butterflies duplicating species rows

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#929]
The species summary tab of the activity summary for the iRecord Butterflies app
https://www.brc.ac.uk/irecord/butterfly-app-summary-2020

Shows duplication of some species (e.g. Brown argus).
![iR dash](https://user-images.githubusercontent.com/2699478/93661477-08c9ec00-fa50-11ea-923f-31954930d30c.png)

**Comment by kitenetter** [comment]
@johnvanbreda The above is an example of the type of duplication that I was also seeing. However, the place where I was seeing it was in the Species tab of this Activity summary:
https://www.brc.ac.uk/irecord/activities/summary?group_id=1726&implicit=

For that summary the complete duplication of taxa seems to have stopped, and the only remaining problems are the result of people recording subspecies:

![image](https://user-images.githubusercontent.com/16039111/104924864-f330e880-5995-11eb-98d8-00ef947ce3be.png)

For insects at least I am not a fan of recording subspecies unless there is good justification for doing so, and I wish we could make it harder for people to record subspecies on iRecord, and then in displays such as the above subspecies should be included within the relevant species. But I think that for plant recording subspecies are seen as useful and they are likely to prefer to split them out. Can't think of a good, non-complex solution to that.

Subspecies aside, it looks like this problem may have gone away. However, there are still some inconsistencies:
- The above species table lists 28 rows, which is slightly annoying because there are only 23 species (but it is the subspecies that cause this discrepancy)
- The initial "Summary" tab lists "31 species", which is misleading because there must be some additional duplication going on to reach 31, and they aren't all separate species - it is really saying "31 taxa some of which may be duplicates"
- The Activity includes records of Large Skipper but these are not included in the above Species tab, for reasons I don't understand

**Comment by johnvanbreda** [comment]
@kitenetter I think these issues are solved now? I have a link to the species taxon in Elasticsearch so use that for aggregation - therefore higher taxa are omitted and sub-species are skipped.

**Comment by kitenetter** [comment]
That looks much better, but in the KWACS activity I'm now seeing "Orange Tip Butterfly" as a scientific name, which is picked up in #991. Would be good to resolve that when we can but I'll close this issue.
