### ISSUE TITLE
Activity summary - rebuild using Elastic Search

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/iRecord#930]
Larger activity summaries time-out.  
Examples are the iRecord butterflies, which still does load but often times out
https://www.brc.ac.uk/irecord/butterfly-app-summary-2020

 and iRecord app summaries which I can not longer get to load and always times out
https://www.brc.ac.uk/irecord/irecord-app-summary

Rebuild using Elastic Search?  Are there quick options to get the pages to load even if a full rebuild is more effort?

**Comment by kitenetter** [comment]
We've had a complaint today from the Bringsty Common group that their activity is timing out.

**Comment by johnvanbreda** [comment]
@kitenetter I have a few of the more time-consuming queries ready converted to Elasticsearch. 
For the recorders league, the current query works on the person who typed the data in, rather than the name of the recorder. Would it be OK to switch to counting records and species by the name of the recorder?

**Comment by johnvanbreda** [comment]
- confirmed during Zoom - OK for recorder leagues to use the recorder name.
 - also check why the species tables on activities sometimes have duplicate species names and other taxonomy issues. Switch to ES might fix this?

**Comment by kitenetter** [comment]
For taxon duplication issues see #929

**Comment by johnvanbreda** [comment]
The activity summary and simple activity summary reports are now both converted to Elasticsearch and much faster.

The app summary pages (iRecord app, iRecord butterflies) are custom pages, I'll do a demo of a rough equivalent in Elasticsearch code.

**Comment by kitenetter** [comment]
The summary page loads much more quickly - brilliant! And I think the way that the species and recorder league tables works is better. Some issues:

1. The default map display gets ruined by the 100km and 10km grid refs (example shown is for [Bringsty Common](https://www.brc.ac.uk/irecord/activities/summary?group_id=374&implicit=)):

![image](https://user-images.githubusercontent.com/16039111/105362614-0096de80-5bf3-11eb-94f0-dd0198e9b461.png)

2. The behaviour of the dots on the map seems a bit erratic when zooming in and out of the map.
3. For some reason Orange-tip has "Orange Tip Butterfly" as its scientific name - is this a species dictionary issue? (Probably not, since the scientific name is displaying correctly on the main Explore pages.)
4. The "Trending" species and recorders seem unlikely - that is I'm surprised to see them being put forward as the most active in recent time periods, which is what I thought this display did
5. I can foresee requests to be able to sort by species name or recorder name in the species and recorder league tables.

Finally I think we discussed that the "Explore records" pages also need updating to be ES explore pages - not suggesting this is urgent but just didn't want it forgotten (does it need to be a new issue?).

**Comment by kitenetter** [comment]
Activity summaries have stopped working for two of my activities:
- Berks moths for the last two weeks https://www.brc.ac.uk/irecord/activities/summary?group_id=618&implicit=
- Berks moths for 2021 https://www.brc.ac.uk/irecord/activities/summary?group_id=619&implicit=

The explore pages for both are working fine, but the summaries are not displaying any records.

**Comment by johnvanbreda** [comment]
@kitenetter some activities were not displaying due to an error in filter code for county boundaries. Now fixed. The Explore pages are now converted to ES.
I've now used time available on this part of the project so can any remaining problems be split out to separate issues please?

**Comment by kitenetter** [comment]
Will do.

The two Berkshire moth activities listed above are now working, but the soldierflies one isn't. If it is still unavailable after a day or two I'll add it as a new issue.

**Comment by johnvanbreda** [comment]
I've fixed the soldierfly issue, since it was bound to crop up with other activities.
