### ISSUE TITLE
Show output grid ref in verification grid for records coming from all apps

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#94]
This arose in connection with records originating from the Mammal app. Although an output grid reference is included when downloading such records, the verification page only shows the lat/long coords. A verifier has requested that the output grid ref is displayed here as well (as already happens for data arriving from the main iRecord app), and it seems logical to display output grid ref for all records that arrive with lat/long coordinates.

**Comment by kazlauskis** [comment]
I am planning on updating the iRecord App to submit Grid Reference (GR) by default in UK and Lat/Lon outside of it. It is clearly a problem for many users at the moment.

This is @johnvanbreda call, but I feel that until Indicia is using two dedicated system fields (eg. entered_sref_coord, entered_sref_gridref) for storing the location, then it is up to the apps to submit the data that is following the recommendations set by Indicia; not patching the things around to meet the few app cases. But that is my guess only, if the lat/long locations within the UK are accepted as first class citizens in Indicia then yes the reports should take this into account and display the GRs.

**Comment by JimBacon** [comment]
I didn't entirely follow!
I would say that the Indicia warehouse regards all spatial reference systems as equal.
It stores the spatial reference that is submitted by the recorder.
It can convert that to any desired (valid) system for output.
I can't think of any recommendations set by Indicia.

The warehouse provides a [spatial service](https://github.com/Indicia-Team/warehouse/blob/master/modules/indicia_svc_spatial/controllers/services/spatial.php) for coordinate transformations which employs the [spatial helper class](https://github.com/Indicia-Team/warehouse/blob/master/application/helpers/spatial_ref.php). This relies on functions in the postgres database which will make it tricky to extract. There are then modules for different grid reference systems (e.g. [OSGB](https://github.com/Indicia-Team/warehouse/blob/master/modules/sref_osgb/helpers/osgb.php)) which convert eastings and northings from a false origin into a grid reference.

I can see that if a data entry system is going to consistently submit spatial references in one form and that a reporting system is going to consistently want an output in a different form there will be a lot of wasted and repeated effort making lots of coordinate transformations. That might suggest some sort of cache is worth having.

**Comment by kazlauskis** [comment]
Sorry, that was confusing, I was talking of it from the perspective of the verifiers as looks like the first class citizens here are the GRs as this is what the verifiers expect. I understand the system treats all the location types the same. As @kitenetter suggests LLs should be on a par with GRs, when it comes to record verification easiness.

Thanks, I will look into how to best align the Indicia GRs and the internal App ones.

**Comment by johnvanbreda** [comment]
Just in case anything is still unclear, here's a summary of spatial ref handling in Indicia:
1) The spatial ref can be input in any supported format (grid refs, lat long, x+y coordinates etc). The input string is stored in the sample.entered_sref so that we always have the original data the recorder provided, plus the entered_sref_system field tells us what format/projection they used.
2) No matter what format they enter, we convert this to a geometry object (normally a point or a square) and store this in the geom field, using the Web Mercator projection. This minimises the projection calculations required as we normally output onto Google or similar web map services that use Web Mercator.
3) The tables called cache_* are calculated tables used to optimise outputs. These include a field called output_sref. The output_sref field attempts to generate a map reference for all samples using whatever the best notation for that part of the earth is. So, it will pick British or Irish grids, or revert to lat long for parts of the Earth it does not have a mapping to a known notation for. Therefore you can choose to include the output_sref field in reports if you'd prefer a "standardised" format rather than the format as entered by the user.

We do indeed generally use PostgreSQL/PostGIS transformations, which I believe are internally based on Proj4. We also use a JS version of Proj4 for some transformations on the client, for example when calculating the "ghost" grid square shown as you hover over the map. What we don't yet have is code in JS that performs the conversions from the input notation for a grid square to and from the easting/northing coordinates for that square. It ought to be easy enough to port this code from PHP, e.g. https://github.com/Indicia-Team/warehouse/blob/master/modules/sref_osgb/helpers/osgb.php#L56.

If this code is ported to JS, please can we coordinate so we share the code with the existing Indicia client?

**Comment by JimBacon** [comment]
Thanks for the extra information John. I wasn't aware of the output_sref field in the cache_occurrences_nonfunctional table. I also don't know how the privacy and sensitivity fields are used to blur information. For example, can this output_sref be used for public display and then, conversely, is it suitable for verifiers if it is blurred? Likewise for geom fields: I believe the sample:geom is at full precision and not suitable for displaying publicly on a map. Perhaps that is where the map_sq_xkm_id fields come in.

This thread is not necessarily the best place for the answers to these questions. Some comments on the database fields and some documentation, perhaps in the report writing section, about the cache tables in general and how to extract appropriate spatial information in particular would be helpful.

**Comment by johnvanbreda** [comment]
@kitenetter Back to the original requirement - there is limited space in the verification grid. Options are:
1) Add the output grid ref and accept the "squash"
2) Add it, but configure the grid so it only appears on very wide screens, or when you click a + button in the leftmost column (if you shrink your browser window you can see this effect on the normal Explore pages). 
3) Change the existing grid ref column to show the output grid ref instead (perhaps show the original entered map reference as a tooltip if you hover over it?)

**Comment by kitenetter** [comment]
@johnvanbreda I wasn't clear: I was envisaging that the output grid ref would be shown in the record details pane on the right hand side, rather than appear in the verification grid. This is what currently happens with the main iRecord app:

![image](https://cloud.githubusercontent.com/assets/16039111/19688384/6327764c-9ac1-11e6-8a6f-038fd9987941.png)

Having said that, an alternative would be to remove the "Grid ref" column from the verification grid, and to replace it with the "Output grid ref" column, and then to show the original grid ref/lat long details in the right-hand-side record details pane. But I think having output grid ref in the record details pane will be sufficient.

I certainly don't think we need to have BOTH grid ref AND output grid ref in the verification grid.

**Comment by johnvanbreda** [comment]
@kitenetter Agreed, I'll add output_sref to the data included in the details pane.

@JimBacon I've put some docs up at http://indicia-docs.readthedocs.io/en/latest/developing/reporting/reporting-spatial-fields.html as a starting point.

**Comment by JimBacon** [comment]
Very helpful. Thanks.

**Comment by johnvanbreda** [comment]
I've added the output sref to the key facts for the next feature release of the warehouse.

**Comment by kazlauskis** [comment]
In the next app updates I will drop sending the **gridref_calculated** (app internal grid reference that the users see) altogether - no need for it since the users can see the **output_sref**. The app will also submit lat/longs OR grid references depending on how the location was picked; not just the lat/longs as entered_sref anymore.

**Comment by JimBacon** [comment]
@kitenetter As John's documentation helpfully explains, this grid reference is blurred by privacy/sensitivity. I'm not sure if there is anything in the record details that will highlight to the verifier a. that the record is to be treated with care and b. that the grid ref has been blurred. These may be additional requests that you would like to consider!

**Comment by johnvanbreda** [comment]
@JimBacon @kitenetter Just to be aware - the normal grid refs shown to verifiers are NOT blurred - only the output sref would be. Verifiers get shown full precision where possible.
