### ISSUE TITLE
Home page fails to load properly when in Training mode

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#943]
The home page uses an ES report when accessed by a 'standard' user, but if the user's account is in Training mode it appears to go back to the old report, which times out.

![image](https://user-images.githubusercontent.com/16039111/97235897-d001fd00-17db-11eb-929d-735b50005c27.png)

**Comment by johnvanbreda** [comment]
@kitenetter the home page uses a normal PostgreSQL report in both circumstances. It's slower in training mode because searching for some recent records to show is going to require searching through far more records in training mode than normal mode. 

I agree the home page needs converting to Elasticsearch though.

**Comment by kitenetter** [comment]
Thanks @johnvanbreda. I guess the workaround is to try to avoid the home page when in training mode. Will close this one and add an issue for updating the home page report to ES.
