### ISSUE TITLE
ES Explore: add Previous and Next buttons for lists of species, families, groups

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#952]
There is currently no way of advancing beyond the first page of records when using the species, family or group tabs on the ES Explore page.

**Comment by kitenetter** [comment]
@johnvanbreda I experimented with adding "@pager=true" to the species, family and group tabs. I see that the ES Explore page is now displaying code and saying it has encountered an unexpected error.

Apologies if I have messed things up - are you able to reinstate it?

**Comment by johnvanbreda** [comment]
@kitenetter the page should be sorted now - I think this was actually a brief moment when the code was wrong during an upgrade I just applied. Not your fault!

Regarding the pager, we support 2 types of Elasticsearch aggregations in our data grids, either term or composite. If you look at the docs (https://indicia-docs.readthedocs.io/en/latest/site-building/iform/helpers/elasticsearch-report-helper.html#options) for the mode option, you'll see that each aggregation type has a different set of limitations. The compositeAggregation mode does support basic pagination, but does NOT support sorting the results set by an aggregated data value (such as records count). The termAggregation does support sorting the results set by aggregated data but does not support paging. So we are sacrificing paging for the ability to list the results by record count. 

I suspect a possible solution might be to use termAggregation mode, then if the user clicks "Next page" we would go to Elasticsearch and load approx the first 10 pages of data. They can then freely page through the first few pages since these would be held in memory. Then if they try to page past page 10 they get a helpful message that rather than page through all the data, they should refine their filters instead. This would be a medium size task.

**Comment by kitenetter** [comment]
The immediate workaround is to remind users that they can download the species list to get a complete view of it following completion of #951 

Longer-term we should implement the second of John's two suggestions in the previous comment, using termAggregation mode and enabling a ten-page view.
