### ISSUE TITLE
Question: is it permissible to redetermine a taxon to the same taxon?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#954]
A verifier has received records from a recorder. The verifier was actually the determiner (having seen photos outside iRecord), but the recorder has given themselves as the determiner, The verifier wishes to rectify this.

Editing the record is one option.

Would there be any negative consequences from the verifier redetermining the taxon, to the same taxon, simply as a way of reassigning the verifer to be the determiner?

**Comment by johnvanbreda** [comment]
There shouldn't be any negative consequences technically - adding a second opinion which confirms the existing one is perfectly valid. However from what you've described, I think a more accurate representation of the record's history would be achieved by changing the record's identified by field value to replace the determiner, rather than by adding a new determination.
