### ISSUE TITLE
Ensure that the Explore all records map shows the grid records by default

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#955]
On the new Explore page, if you change the map layer controls to show records for the current species, next time you go to the Explore the map appears to be blank, which could cause alarm.

Can we set it so that when first opened, the map display defaults to showing the view of "All records in current filter (grid map)"?

**Comment by burkmarr** [comment]
@kitenetter the map selection is 'remembered' in a cookie. There is an option on the `[leafletMap]` control to turn off this cookie, but that would also mean that other things, e.g. base layer selection and map position,  are not remembered when the map is revisited. @johnvanbreda - I could add another option on `[leafletMap]` that allows the remembering of map selection to be left out of the cookie. What do you think?

**Comment by johnvanbreda** [comment]
I think it's useful for the cookie to remember the layers chosen in most cases though. The layerConfig already has an enabled property for each layer, which defines the default state before any cookie settings are applied. Perhaps a "forceEnabled" option would allow overriding the cookie on individual layers?

**Comment by burkmarr** [comment]
Sounds good to me. I know that this is not in the November milestone, but it shouldn't take me long to do so I will ahve a look tomorrow.

**Comment by kitenetter** [comment]
I agree that in most cases it is helpful to have the layers remembered, it is just that it looks odd when you go to the "Explore all records" page and get shown an empty map - the reason for the map being empty is not immediately obvious.

Don't think we should spend too much time on this, but if there is a fairly easy solution that would be great, thanks @burkmarr

**Comment by burkmarr** [comment]
@kitenetter - this is fixed in the develop branch now so will be available on the live site when John next merges the develop branch into master and pulls to iRecord. I've already added `"forceEnabled": true,` for the main map - 'All records in current filter (grid map)' - on the two ES pages. So the result will be that when a user visits either of the two ES explore pages, that map layer will be initially switched on even if they had turned it off when they last visited the page.
