### ISSUE TITLE
Activities: summaries have an odd species name display for one species

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#991]
In the summary species tables, for some reason Orange-tip has "Orange Tip Butterfly" as its scientific name. Can only see a problem with this one species, and cannot see any obvious reason for it.

**Comment by johnvanbreda** [comment]
Which activities?
There might be a problem with old records connected to a now-redundant name, but I think new records should be OK.

**Comment by kitenetter** [comment]
Still an issue for summary lists, e.g. from the [KWACS activity](https://www.brc.ac.uk/irecord/activities/summary?group_id=1726&implicit=).

![image](https://user-images.githubusercontent.com/16039111/112378871-5c5b1200-8cdf-11eb-9a71-66b2cbaf7850.png)

Will this need some database updates in the species dictionary? If so I'll check where the name seems to be coming from.

**Comment by johnvanbreda** [comment]
Hi @kitenetter - I've tidied a couple of things that could cause this in the UKSI data (probably due to edits rather than the UKSI script I think). I've also added work queue tasks to tidy all Orange Tip records up, but set them at low priority so please let me know if this hasn't fixed itself in a few days.

**Comment by kitenetter** [comment]
This problem appears to have gone away. Closing.
